[workspace]
allow_dirty = false
dependencies_update = false
repo_url = "https://github.com/ScriptedAlchemy/tracedecay"
release_always = false
pr_branch_prefix = "release-plz-"
pr_labels = ["release"]
release = false
publish = false
semver_check = false

[[package]]
name = "tracedecay"
release = true
git_only = true
publish = false
git_release_enable = true
git_release_name = "v{{ version }}"
git_release_body = "{{ changelog }}"
git_release_type = "prod"
git_release_draft = false
git_release_latest = true
git_tag_enable = true
git_tag_name = "v{{ version }}"

[[package]]
name = "tracedecay-domain"
release = false

[[package]]
name = "tracedecay-code-extraction"
release = false

[[package]]
name = "tracedecay-jsonrpc"
release = false
