use tracedecay_tool_catalog::{EffectClass, ScopeDimension};

use super::{RetainedSurfaceOperation, RetainedSurfaceSpec};

const SESSION_SCOPE: &[ScopeDimension] = &[ScopeDimension::Session, ScopeDimension::Resource];
const PROJECT_SCOPE: &[ScopeDimension] = &[ScopeDimension::Project];
const PROJECT_SESSION_SCOPE: &[ScopeDimension] =
    &[ScopeDimension::Project, ScopeDimension::Session];

pub(super) const SPECS: [RetainedSurfaceSpec; 15] = [
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::SessionRefresh,
        summary: "Control session refresh",
        description: "Start, inspect, resume, or cancel the exact daemon-owned session refresh.",
        example: "Inspect this session refresh",
        effect: EffectClass::Administrative,
        scope: SESSION_SCOPE,
        paginated: false,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::MessageSearch,
        summary: "Search retained session messages",
        description: "Read authorized temporal message evidence without opening another store.",
        example: "Search retained session messages",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::SessionsFor,
        summary: "Find sessions for a Git reference",
        description: "Read project sessions correlated with one admitted Git reference.",
        example: "Find sessions for this branch",
        effect: EffectClass::Read,
        scope: PROJECT_SCOPE,
        paginated: true,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmStatus,
        summary: "Inspect retained LCM status",
        description: "Read temporal-store status through the mounted session authority.",
        example: "Show retained LCM status",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: false,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmDoctor,
        summary: "Diagnose retained LCM state",
        description: "Inspect temporal-store integrity without opening another session store.",
        example: "Diagnose retained LCM state",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: false,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmLoadSession,
        summary: "Load a retained session",
        description: "Load one authorized session from the mounted temporal authority.",
        example: "Load this retained session",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmGrep,
        summary: "Search retained LCM content",
        description: "Search authorized temporal content through the mounted session authority.",
        example: "Search retained LCM content",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmDescribe,
        summary: "Describe retained temporal context",
        description: "Describe one authorized temporal target through the mounted authority.",
        example: "Describe this retained session target",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmExpand,
        summary: "Expand retained temporal context",
        description: "Expand one authorized temporal target through the mounted authority.",
        example: "Expand this retained session target",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmExpandQuery,
        summary: "Expand a retained temporal query",
        description: "Assemble authorized temporal evidence for one bounded query.",
        example: "Expand this query over retained sessions",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmPreflight,
        summary: "Preflight retained temporal context",
        description: "Measure one bounded temporal assembly against the mounted authority.",
        example: "Preflight this retained context request",
        effect: EffectClass::Administrative,
        scope: SESSION_SCOPE,
        paginated: false,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmCompress,
        summary: "Compress retained temporal context",
        description: "Commit bounded temporal compression through the mounted authority.",
        example: "Compress this retained session context",
        effect: EffectClass::Administrative,
        scope: SESSION_SCOPE,
        paginated: false,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmSessionBoundary,
        summary: "Record a retained session boundary",
        description: "Commit an exact temporal boundary through the mounted authority.",
        example: "Record this retained session boundary",
        effect: EffectClass::Administrative,
        scope: SESSION_SCOPE,
        paginated: false,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::SessionStart,
        summary: "Start retained session accounting",
        description: "Record a project-scoped session start through the retained owner.",
        example: "Start accounting for this session",
        effect: EffectClass::Administrative,
        scope: PROJECT_SESSION_SCOPE,
        paginated: false,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::SessionEnd,
        summary: "End retained session accounting",
        description: "Record a project-scoped session end through the retained owner.",
        example: "End accounting for this session",
        effect: EffectClass::Administrative,
        scope: PROJECT_SESSION_SCOPE,
        paginated: false,
    },
];
