use tracedecay_tool_catalog::{EffectClass, ScopeDimension};

use super::{CURRENT_SURFACES, RetainedSurfaceOperation, RetainedSurfaceSpec};

const SESSION_SCOPE: &[ScopeDimension] = &[ScopeDimension::Session, ScopeDimension::Resource];
const PROJECT_SCOPE: &[ScopeDimension] = &[ScopeDimension::Project];

pub(super) const SPECS: [RetainedSurfaceSpec; 12] = [
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::SessionRefreshStatus,
        summary: "Inspect session refresh status",
        description: "Inspect the exact daemon-owned session refresh.",
        example: "Inspect this session refresh",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: false,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::SessionRefreshCancel,
        summary: "Cancel a session refresh",
        description: "Cancel the exact daemon-owned session refresh.",
        example: "Cancel this session refresh",
        effect: EffectClass::Administrative,
        scope: SESSION_SCOPE,
        paginated: false,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::SessionRefreshBegin,
        summary: "Begin a session refresh",
        description: "Begin or resume the exact daemon-owned session refresh.",
        example: "Begin this session refresh",
        effect: EffectClass::Administrative,
        scope: SESSION_SCOPE,
        paginated: false,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::MessageSearch,
        summary: "Search retained session messages",
        description: "Read authorized temporal message evidence without opening another store.",
        example: "Search retained session messages",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::SessionsFor,
        summary: "Find sessions for a Git reference",
        description: "Read project sessions correlated with one admitted Git reference.",
        example: "Find sessions for this branch",
        effect: EffectClass::Read,
        scope: PROJECT_SCOPE,
        paginated: true,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmStatus,
        summary: "Inspect retained LCM status",
        description: "Read temporal-store status through the mounted session authority.",
        example: "Show retained LCM status",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: false,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmDoctor,
        summary: "Diagnose retained LCM state",
        description: "Read bounded temporal-store health through the mounted session authority.",
        example: "Diagnose retained LCM state",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: false,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmLoadSession,
        summary: "Load a retained session",
        description: "Load one authorized session from the mounted temporal authority.",
        example: "Load this retained session",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmGrep,
        summary: "Search retained LCM content",
        description: "Search authorized temporal content through the mounted session authority.",
        example: "Search retained LCM content",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmDescribe,
        summary: "Describe retained temporal context",
        description: "Describe one authorized temporal target through the mounted authority.",
        example: "Describe this retained session target",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmExpand,
        summary: "Expand retained temporal context",
        description: "Expand one authorized temporal target through the mounted authority.",
        example: "Expand this retained session target",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
        surfaces: CURRENT_SURFACES,
    },
    RetainedSurfaceSpec {
        operation: RetainedSurfaceOperation::LcmExpandQuery,
        summary: "Expand a retained temporal query",
        description: "Assemble authorized temporal evidence for one bounded query.",
        example: "Expand this query over retained sessions",
        effect: EffectClass::Read,
        scope: SESSION_SCOPE,
        paginated: true,
        surfaces: CURRENT_SURFACES,
    },
];
