/**
 * Contracts codegen. Deterministic TypeScript + Zod generation from the
 * JSON Schema exported directly from Rust `JsonSchema` derives.
 *
 * Design goals (binding, per docs/plans/tracedecay-v2/11-dashboard-frontend.md
 * §"Typed presentation contracts"):
 *   - The emitted file exposes an `assertNever` helper so the closed unions
 *     (e.g. the 17-value domain-state enum) stay exhaustively switchable.
 *   - Internally-tagged `oneOf` variants remain exact discriminated unions;
 *     codegen never invents variants absent from Rust.
 *   - Generation is deterministic: stable (alphabetical) ordering, no
 *     timestamps, no host/env state, so diffs are reviewable.
 *
 * The generator implements the focused subset of JSON Schema that the exported
 * dashboard schemas use (objects, refs, string/number/bool/null scalars,
 * nullable scalars via `["t","null"]`, string enums, arrays, `anyOf` unions,
 * and internally-tagged `oneOf` unions), plus two internal `x-generic*`
 * extension keys used to recover `DashboardEnvelope<T>` after schemars
 * monomorphizes it for the export catalog.
 */

import { isDeepStrictEqual } from "node:util";

export interface JsonSchema {
  $id?: string;
  $ref?: string;
  title?: string;
  description?: string;
  schemaRevision?: string | number;
  type?: string | string[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  additionalProperties?: JsonSchema | boolean;
  enum?: unknown[];
  const?: unknown;
  format?: string;
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number;
  exclusiveMaximum?: number;
  oneOf?: JsonSchema[];
  anyOf?: JsonSchema[];
  $defs?: Record<string, JsonSchema>;
  definitions?: Record<string, JsonSchema>;
  ["x-generic"]?: string;
  ["x-generic-ref"]?: string;
}

export interface GeneratedContracts {
  /** Map of relative output path -> file content. */
  files: Record<string, string>;
}

const TYPES_FILE = "src/contracts/types.ts";
const DECODERS_FILE = "src/contracts/decoders.ts";
const GENERATED_FILE = "src/contracts/generated.ts";

const HEADER = [
  "// GENERATED by dashboard/codegen from Rust schemars output. DO NOT EDIT.",
  "// Source: the Serialize contract of dashboard/read_model.rs and every Rust",
  "// payload DTO included by dashboard::contract_schema.",
  "// Deterministic output (stable ordering, no timestamps).",
].join("\n");

const TYPES_HEADER = [
  HEADER,
  "//",
  "// These aliases are the consumer contract and are part of every dashboard",
  "// `tsc`. A wrong alias fails that check.",
].join("\n");

const DECODERS_HEADER = [
  "// @ts-nocheck",
  HEADER,
  "//",
  "// Checking these expressions instantiates the whole zod graph and dominates",
  "// a cold dashboard `tsc`. Aliases live in types.ts, which stays checked.",
  "// contracts:generate compiles this file with the directive removed, so a",
  "// decoder that does not match its annotation fails before it is written.",
].join("\n");

/** Return the `$defs`/`definitions` map from a bundle, sorted by key. */
function collectDefs(bundle: JsonSchema): Array<[string, JsonSchema]> {
  const defs = bundle.$defs ?? bundle.definitions ?? {};
  return Object.keys(defs)
    .sort()
    .map((name) => [name, defs[name] as JsonSchema]);
}

function refName(ref: string): string {
  const parts = ref.split("/");
  return parts[parts.length - 1] as string;
}

function isMonomorphizedEnvelope(
  candidate: JsonSchema,
  canonical: JsonSchema,
): boolean {
  if (!candidate.properties || !canonical.properties) return false;
  const { payload: candidatePayload, ...candidateProperties } = candidate.properties;
  const { payload: canonicalPayload, ...canonicalProperties } = canonical.properties;
  if (
    candidatePayload === undefined ||
    canonicalPayload === undefined ||
    isDeepStrictEqual(candidatePayload, canonicalPayload)
  ) {
    return false;
  }
  return isDeepStrictEqual(
    { ...candidate, properties: candidateProperties },
    { ...canonical, properties: canonicalProperties },
  );
}

function localDefinitionRefs(schema: JsonSchema, refs = new Set<string>()): Set<string> {
  if (
    schema.$ref?.startsWith("#/$defs/") ||
    schema.$ref?.startsWith("#/definitions/")
  ) {
    refs.add(refName(schema.$ref));
  }
  for (const value of Object.values(schema)) {
    if (Array.isArray(value)) {
      for (const item of value) {
        if (item && typeof item === "object") {
          localDefinitionRefs(item as JsonSchema, refs);
        }
      }
    } else if (value && typeof value === "object") {
      localDefinitionRefs(value as JsonSchema, refs);
    }
  }
  return refs;
}

function literal(value: unknown): string {
  return JSON.stringify(value);
}

/** Discriminant detection for tagged `oneOf` unions. */
function discriminantOf(variant: JsonSchema): { key: string; value: string } | null {
  const props = variant.properties ?? {};
  for (const key of Object.keys(props).sort()) {
    const prop = props[key] as JsonSchema;
    if (Array.isArray(prop.enum) && prop.enum.length === 1 && typeof prop.enum[0] === "string") {
      return { key, value: prop.enum[0] };
    }
    if (typeof prop.const === "string") {
      return { key, value: prop.const };
    }
  }
  return null;
}

function isTaggedUnion(schema: JsonSchema): boolean {
  if (!Array.isArray(schema.oneOf) || schema.oneOf.length === 0) return false;
  return schema.oneOf.every((v) => discriminantOf(v) !== null);
}

// Type/decoder resolution for a single (possibly nested) schema.
// Returns the structural type, the decoder expression, and a shallow
// annotation so checkers do not infer the expression.
// `generic` supplies the payload param name + schema identifier when inside a
// generic type (DashboardEnvelope<TPayload>).

interface ResolveCtx {
  genericParam?: string;
  genericSchemaVar?: string;
}

interface Resolved {
  ts: string;
  zod: string;
  /**
   * Shallow type of `zod`. Objects, enums, and literal unions keep the methods
   * callers use (`.extend`, `.shape`, `.options`); everything else is
   * `z.ZodType<…>` so the checker never infers the expression.
   */
  ann: string;
}

function typeAnn(ts: string): string {
  // Wire decoders accept unknown input, including catch defaults and lazy refs.
  return `z.ZodType<${ts}, unknown>`;
}

function resolveType(schema: JsonSchema, ctx: ResolveCtx): Resolved {
  if (schema["x-generic-ref"]) {
    const ts = ctx.genericParam ?? schema["x-generic-ref"];
    return {
      ts,
      zod: ctx.genericSchemaVar ?? "z.unknown()",
      ann: typeAnn(ts),
    };
  }

  if (schema.$ref) {
    const name = refName(schema.$ref);
    return { ts: name, zod: `z.lazy(() => ${name}Schema)`, ann: typeAnn(name) };
  }

  if (schema.const !== undefined) {
    const value = literal(schema.const);
    return { ts: value, zod: `z.literal(${value})`, ann: `z.ZodLiteral<${value}>` };
  }

  if (Array.isArray(schema.enum)) {
    const strings = schema.enum.filter((v): v is string => typeof v === "string");
    if (strings.length === schema.enum.length && strings.length > 0) {
      const sorted = [...strings].sort();
      const tsUnion = sorted.map(literal).join(" | ");
      if (sorted.length === 1) {
        const value = literal(sorted[0] as string);
        return { ts: value, zod: `z.literal(${value})`, ann: `z.ZodLiteral<${value}>` };
      }
      const zodList = sorted.map(literal).join(", ");
      return { ts: tsUnion, zod: `z.enum([${zodList}])`, ann: `z.ZodEnum<{ ${sorted.map((value) => `${literal(value)}: ${literal(value)}`).join("; ")} }>` };
    }
  }

  if (isTaggedUnion(schema)) {
    return resolveTaggedUnion(schema, ctx);
  }

  if (Array.isArray(schema.oneOf)) {
    const parts = schema.oneOf.map((s) => resolveType(s, ctx));
    if (parts.length === 1) return parts[0] as Resolved;
    return unionResolved(parts);
  }

  if (Array.isArray(schema.anyOf)) {
    const parts = schema.anyOf.map((s) => resolveType(s, ctx));
    return unionResolved(parts);
  }

  const types = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
  const nullable = types.includes("null");
  const primary = types.find((t) => t !== "null");

  if (primary === "object" || (!primary && schema.properties)) {
    const obj = resolveObject(schema, ctx);
    return applyNullable(obj, nullable);
  }
  if (primary === "array") {
    const inner = resolveType(schema.items ?? {}, ctx);
    const ts = `Array<${inner.ts}>`;
    return applyNullable({ ts, zod: `z.array(${inner.zod})`, ann: typeAnn(ts) }, nullable);
  }
  if (primary === "string") {
    return applyNullable({ ts: "string", zod: "z.string()", ann: typeAnn("string") }, nullable);
  }
  if (primary === "integer") {
    return applyNullable(
      {
        ts: "number",
        zod: applyNumericBounds(integerDecoder(schema), schema),
        ann: typeAnn("number"),
      },
      nullable,
    );
  }
  if (primary === "number") {
    return applyNullable(
      {
        ts: "number",
        zod: applyNumericBounds("z.number()", schema),
        ann: typeAnn("number"),
      },
      nullable,
    );
  }
  if (primary === "boolean") {
    return applyNullable({ ts: "boolean", zod: "z.boolean()", ann: typeAnn("boolean") }, nullable);
  }
  if (nullable && !primary) {
    // A null-only schema (e.g. the `{ "type": "null" }` arm of a nullable ref).
    return { ts: "null", zod: "z.null()", ann: typeAnn("null") };
  }

  return { ts: "unknown", zod: "z.unknown()", ann: typeAnn("unknown") };
}

function unionResolved(parts: Resolved[]): Resolved {
  const ts = parts.map((part) => part.ts).join(" | ");
  const zod = `z.union([${parts.map((part) => part.zod).join(", ")}])`;
  if (parts.length > 0 && parts.every((part) => part.ann.startsWith("z.ZodLiteral<"))) {
    return { ts, zod, ann: `z.ZodUnion<[${parts.map((part) => part.ann).join(", ")}]>` };
  }
  return { ts, zod, ann: typeAnn(ts) };
}

function integerDecoder(schema: JsonSchema): string {
  switch (schema.format) {
    case "int64":
    case "uint64":
    case "uint":
      return "z.number().int()";
    default:
      // Unformatted JSON Schema integers retain their full numeric domain.
      return "z.number().refine(Number.isInteger)";
  }
}

function applyNumericBounds(zod: string, schema: JsonSchema): string {
  const minimum = schema.minimum === undefined ? "" : `.min(${literal(schema.minimum)})`;
  const maximum = schema.maximum === undefined ? "" : `.max(${literal(schema.maximum)})`;
  const exclusiveMinimum =
    schema.exclusiveMinimum === undefined ? "" : `.gt(${literal(schema.exclusiveMinimum)})`;
  const exclusiveMaximum =
    schema.exclusiveMaximum === undefined ? "" : `.lt(${literal(schema.exclusiveMaximum)})`;
  return `${zod}${minimum}${maximum}${exclusiveMinimum}${exclusiveMaximum}`;
}

function applyNullable(resolved: Resolved, nullable: boolean): Resolved {
  if (!nullable) return resolved;
  const ts = `${resolved.ts} | null`;
  return { ts, zod: `${resolved.zod}.nullable()`, ann: typeAnn(ts) };
}

function resolveObject(schema: JsonSchema, ctx: ResolveCtx): Resolved {
  const props = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const keys = Object.keys(props).sort();

  // A Rust map (`BTreeMap`/`HashMap`) reaches us as an object with no declared
  // properties and an `additionalProperties` value schema. It must become a
  // `z.record`, never a `z.object({})`: zod strips unknown keys, so an empty
  // object schema parses every entry of the map away and hands the surface an
  // empty map that is indistinguishable from one the daemon really sent empty.
  const extra = schema.additionalProperties;
  if (keys.length === 0 && extra !== undefined && extra !== false) {
    const value = extra === true ? { ts: "unknown", zod: "z.unknown()", ann: typeAnn("unknown") } : resolveType(extra, ctx);
    const ts = `Record<string, ${value.ts}>`;
    return { ts, zod: `z.record(z.string(), ${value.zod})`, ann: typeAnn(ts) };
  }

  const tsFields: string[] = [];
  const zodFields: string[] = [];
  const annFields: string[] = [];
  for (const key of keys) {
    const resolved = resolveType(props[key] as JsonSchema, ctx);
    const optional = !required.has(key);
    const unknownOutput = resolved.ts === "unknown" || resolved.ts === "any";
    const optionalKey = optional;
    // Optional decoder output includes `undefined`, which is what `z.infer`
    // of `.optional()` produces. `unknown` already contains it.
    const value = optional && !unknownOutput ? `${resolved.ts} | undefined` : resolved.ts;
    tsFields.push(`  ${key}${optionalKey ? "?" : ""}: ${value};`);
    zodFields.push(`  ${key}: ${optional ? `${resolved.zod}.optional()` : resolved.zod},`);
    const field = typeAnn(resolved.ts);
    annFields.push(`  ${key}: ${optional ? `z.ZodOptional<${field}>` : field};`);
  }

  // An empty object infers as `{}`. `Record<string, never>` would reject
  // assignments the decoder accepts.
  const ts = tsFields.length ? `{\n${tsFields.join("\n")}\n}` : "{}";
  const object = zodFields.length ? `z.object({\n${zodFields.join("\n")}\n})` : "z.object({})";
  const zod = extra === false ? `${object}.strict()` : object;
  const shape = annFields.length ? `{\n${annFields.join("\n")}\n}` : "{}";
  const ann = extra === false ? `z.ZodObject<${shape}, z.core.$strict>` : `z.ZodObject<${shape}>`;
  return { ts, zod, ann };
}

// Tagged union: discriminated + exhaustive.

function resolveTaggedUnion(schema: JsonSchema, ctx: ResolveCtx): Resolved {
  const variants = (schema.oneOf ?? [])
    .flatMap((variant) => {
      const disc = discriminantOf(variant);
      return disc === null ? [] : [{ disc, resolved: resolveObject(variant, ctx) }];
    })
    .sort((a, b) => a.disc.value.localeCompare(b.disc.value));

  const discKey = variants[0]?.disc.key ?? "kind";
  const ts = variants
    .map((variant) => `\n  | ${variant.resolved.ts.replace(/\n/g, "\n  ")}`)
    .join("");
  const zod = `z.discriminatedUnion(${literal(discKey)}, [${variants
    .map((variant) => variant.resolved.zod)
    .join(", ")}])`;

  // The named alias is the checker contract. Inlining the union here would
  // duplicate it, and callers parse through `z.ZodType<Name>`.
  return { ts, zod, ann: "" };
}

// Named def emission.

interface EmittedDef {
  typeName: string;
  types: string;
  decoders: string;
}

function emitNamedDef(name: string, schema: JsonSchema): EmittedDef {
  const genericParam = schema["x-generic"];
  const desc = schema.description ? `/** ${schema.description} */\n` : "";

  if (genericParam) {
    // Generic type + decoder factory (DashboardEnvelope<TPayload>).
    const schemaVar = "payloadSchema";
    const ctx: ResolveCtx = { genericParam, genericSchemaVar: schemaVar };
    const obj = resolveObject(schema, ctx);
    return {
      typeName: name,
      types: `${desc}export interface ${name}<${genericParam}> ${obj.ts}`,
      decoders: [
        `export function ${name}Schema<${genericParam}>(`,
        `  ${schemaVar}: ${typeAnn(genericParam)},`,
        `): ${typeAnn(`${name}<${genericParam}>`)} {`,
        `  return ${obj.zod.replace(/\n/g, "\n  ")} as unknown as ${typeAnn(`${name}<${genericParam}>`)};`,
        "}",
      ].join("\n"),
    };
  }

  const ctx: ResolveCtx = {};

  if (isTaggedUnion(schema)) {
    const union = resolveTaggedUnion(schema, ctx);
    return emitAlias(desc, name, typeAnn(name), union.zod, union.ts);
  }

  const resolved = resolveType(schema, ctx);
  if (name === "DashboardDomainStateV1") {
    resolved.zod = `${resolved.zod}.catch("unsupported_schema")`;
    // `.catch` wraps the enum, so the value is no longer a `ZodEnum`.
    resolved.ann = typeAnn(name);
  }
  return emitAlias(desc, name, resolved.ann, resolved.zod, resolved.ts);
}

function emitAlias(desc: string, name: string, ann: string, zod: string, ts: string): EmittedDef {
  return {
    typeName: name,
    types: `export type ${name} = ${ts};`,
    decoders: `${desc}export const ${name}Schema: ${ann} = ${zod};`,
  };
}

// Bundle -> files.

export function generateContracts(bundles: JsonSchema[]): GeneratedContracts {
  const defs: Array<[string, JsonSchema]> = [];
  const revisions: Array<string | number> = [];
  for (const bundle of bundles) {
    if (bundle.schemaRevision !== undefined) revisions.push(bundle.schemaRevision);
    defs.push(...collectDefs(bundle));
  }
  defs.sort((a, b) => a[0].localeCompare(b[0]));

  const uniqueRevisions = [...new Set(revisions.map(String))];
  if (uniqueRevisions.length !== 1) {
    throw new Error(`expected exactly one Rust schema revision, got: ${uniqueRevisions.join(", ")}`);
  }
  const schemaRevision = revisions[0] as string | number;

  const omittedNames = new Set(["DashboardPayloadMarkerV1"]);
  const envelopeIndex = defs.findIndex(([name]) => name === "DashboardEnvelopeV1");
  const envelope = defs[envelopeIndex]?.[1];
  if (envelope?.properties) {
    for (const [name, schema] of defs) {
      if (name !== "DashboardEnvelopeV1" && isMonomorphizedEnvelope(schema, envelope)) {
        omittedNames.add(name);
      }
    }
    defs[envelopeIndex] = [
      "DashboardEnvelopeV1",
      {
        ...envelope,
        "x-generic": "TPayload",
        properties: {
          ...envelope.properties,
          payload: { "x-generic-ref": "TPayload" },
          schema_revision: { const: schemaRevision },
        },
      },
    ];
  }

  const emitted: EmittedDef[] = [];
  for (const [name, schema] of defs) {
    if (omittedNames.has(name)) continue;
    const omittedRef = [...localDefinitionRefs(schema)].find((ref) => omittedNames.has(ref));
    if (omittedRef) {
      throw new Error(
        `${name} references omitted generated definition ${omittedRef}`,
      );
    }
    emitted.push(emitNamedDef(name, schema));
  }

  const types = [
    TYPES_HEADER,
    [
      "/**",
      " * Exhaustiveness helper for discriminated-union switches. A `default`",
      " * branch that calls `assertNever(value)` fails to compile if a union",
      " * member is left unhandled.",
      " */",
      "export function assertNever(value: never): never {",
      "  throw new Error(`Unhandled discriminated union member: ${JSON.stringify(value)}`);",
      "}",
    ].join("\n"),
    `export const WIRE_SCHEMA_REVISION = ${literal(schemaRevision)} as const;`,
    ...emitted.map((item) => item.types),
  ].join("\n\n") + "\n";

  const typeImport = emitted.length === 0
    ? ""
    : `import type {\n${emitted.map((item) => `  ${item.typeName},`).join("\n")}\n} from "./types.ts";`;
  const decoders = [
    DECODERS_HEADER,
    typeImport,
    `import { z } from "zod";`,
    ...emitted.map((item) => item.decoders),
  ].filter((block) => block.length > 0).join("\n\n") + "\n";

  // The one module dashboard code imports contracts from. The split into a
  // checked alias half and an unchecked decoder half is a tsc cost boundary,
  // not a consumer-facing distinction.
  const generated = [
    HEADER,
    `export * from "./types.ts";`,
    `export * from "./decoders.ts";`,
    "",
  ].join("\n");

  return {
    files: {
      [TYPES_FILE]: types,
      [DECODERS_FILE]: decoders,
      [GENERATED_FILE]: generated,
    },
  };
}

export const OUTPUT_FILES = { TYPES_FILE, DECODERS_FILE, GENERATED_FILE };
