/**
 * Contracts codegen — deterministic TypeScript + Zod generation from the
 * JSON Schema exported directly from Rust `JsonSchema` derives.
 *
 * Design goals (binding, per docs/plans/tracedecay-v2/11-dashboard-frontend.md
 * §"Typed presentation contracts"):
 *   - The emitted file exposes an `assertNever` helper so the closed unions
 *     (e.g. the 17-value domain-state enum) stay exhaustively switchable.
 *   - Internally-tagged `oneOf` variants remain exact discriminated unions;
 *     codegen never invents variants absent from Rust.
 *   - Generation is deterministic: stable (alphabetical) ordering, no
 *     timestamps, no host/env state — so diffs are reviewable.
 *
 * The generator implements the focused subset of JSON Schema that the exported
 * dashboard schemas use (objects, refs, string/number/bool/null scalars,
 * nullable scalars via `["t","null"]`, string enums, arrays, `anyOf` unions,
 * and internally-tagged `oneOf` unions), plus two internal `x-generic*`
 * extension keys used to recover `DashboardEnvelope<T>` after schemars
 * monomorphizes it for the export catalog.
 */

import { isDeepStrictEqual } from "node:util";

export interface JsonSchema {
  $id?: string;
  $ref?: string;
  title?: string;
  description?: string;
  schemaRevision?: string | number;
  type?: string | string[];
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema;
  additionalProperties?: JsonSchema | boolean;
  enum?: unknown[];
  const?: unknown;
  oneOf?: JsonSchema[];
  anyOf?: JsonSchema[];
  $defs?: Record<string, JsonSchema>;
  definitions?: Record<string, JsonSchema>;
  ["x-generic"]?: string;
  ["x-generic-ref"]?: string;
}

export interface GeneratedContracts {
  /** Map of relative output path -> file content. */
  files: Record<string, string>;
}

const GENERATED_FILE = "src/contracts/generated.ts";
const INDEX_FILE = "src/contracts/index.ts";

const HEADER = [
  "// GENERATED by dashboard/codegen from Rust schemars output. DO NOT EDIT.",
  "// Source: the Serialize contract of dashboard/read_model.rs and every Rust",
  "// payload DTO included by dashboard::contract_schema.",
  "// Deterministic output (stable ordering, no timestamps).",
].join("\n");

/** Return the `$defs`/`definitions` map from a bundle, sorted by key. */
function collectDefs(bundle: JsonSchema): Array<[string, JsonSchema]> {
  const defs = bundle.$defs ?? bundle.definitions ?? {};
  return Object.keys(defs)
    .sort()
    .map((name) => [name, defs[name] as JsonSchema]);
}

function refName(ref: string): string {
  const parts = ref.split("/");
  return parts[parts.length - 1] as string;
}

function isMonomorphizedEnvelope(
  candidate: JsonSchema,
  canonical: JsonSchema,
): boolean {
  if (!candidate.properties || !canonical.properties) return false;
  const { payload: candidatePayload, ...candidateProperties } = candidate.properties;
  const { payload: canonicalPayload, ...canonicalProperties } = canonical.properties;
  if (
    candidatePayload === undefined ||
    canonicalPayload === undefined ||
    isDeepStrictEqual(candidatePayload, canonicalPayload)
  ) {
    return false;
  }
  return isDeepStrictEqual(
    { ...candidate, properties: candidateProperties },
    { ...canonical, properties: canonicalProperties },
  );
}

function localDefinitionRefs(schema: JsonSchema, refs = new Set<string>()): Set<string> {
  if (
    schema.$ref?.startsWith("#/$defs/") ||
    schema.$ref?.startsWith("#/definitions/")
  ) {
    refs.add(refName(schema.$ref));
  }
  for (const value of Object.values(schema)) {
    if (Array.isArray(value)) {
      for (const item of value) {
        if (item && typeof item === "object") {
          localDefinitionRefs(item as JsonSchema, refs);
        }
      }
    } else if (value && typeof value === "object") {
      localDefinitionRefs(value as JsonSchema, refs);
    }
  }
  return refs;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function literal(value: unknown): string {
  return JSON.stringify(value);
}

/** Discriminant detection for tagged `oneOf` unions. */
function discriminantOf(variant: JsonSchema): { key: string; value: string } | null {
  const props = variant.properties ?? {};
  for (const key of Object.keys(props).sort()) {
    const prop = props[key] as JsonSchema;
    if (Array.isArray(prop.enum) && prop.enum.length === 1 && typeof prop.enum[0] === "string") {
      return { key, value: prop.enum[0] };
    }
    if (typeof prop.const === "string") {
      return { key, value: prop.const };
    }
  }
  return null;
}

function isTaggedUnion(schema: JsonSchema): boolean {
  if (!Array.isArray(schema.oneOf) || schema.oneOf.length === 0) return false;
  return schema.oneOf.every((v) => discriminantOf(v) !== null);
}

// ---------------------------------------------------------------------------
// Type/decoder resolution for a single (possibly nested) schema.
// Returns TS type text and Zod expression text.
// `generic` supplies the payload param name + schema identifier when inside a
// generic type (DashboardEnvelope<TPayload>).
// ---------------------------------------------------------------------------

interface ResolveCtx {
  genericParam?: string;
  genericSchemaVar?: string;
}

function resolveType(schema: JsonSchema, ctx: ResolveCtx): { ts: string; zod: string } {
  if (schema["x-generic-ref"]) {
    return {
      ts: ctx.genericParam ?? schema["x-generic-ref"],
      zod: ctx.genericSchemaVar ?? "z.unknown()",
    };
  }

  if (schema.$ref) {
    const name = refName(schema.$ref);
    return { ts: name, zod: `z.lazy(() => ${name}Schema)` };
  }

  if (schema.const !== undefined) {
    return { ts: literal(schema.const), zod: `z.literal(${literal(schema.const)})` };
  }

  if (Array.isArray(schema.enum)) {
    const strings = schema.enum.filter((v): v is string => typeof v === "string");
    if (strings.length === schema.enum.length && strings.length > 0) {
      const sorted = [...strings].sort();
      const tsUnion = sorted.map(quote).join(" | ");
      if (sorted.length === 1) {
        return { ts: quote(sorted[0] as string), zod: `z.literal(${quote(sorted[0] as string)})` };
      }
      const zodList = sorted.map(quote).join(", ");
      return { ts: tsUnion, zod: `z.enum([${zodList}])` };
    }
  }

  if (isTaggedUnion(schema)) {
    return resolveTaggedUnion(schema, ctx);
  }

  if (Array.isArray(schema.oneOf)) {
    const parts = schema.oneOf.map((s) => resolveType(s, ctx));
    if (parts.length === 1) return parts[0] as { ts: string; zod: string };
    return {
      ts: parts.map((p) => p.ts).join(" | "),
      zod: `z.union([${parts.map((p) => p.zod).join(", ")}])`,
    };
  }

  if (Array.isArray(schema.anyOf)) {
    const parts = schema.anyOf.map((s) => resolveType(s, ctx));
    return {
      ts: parts.map((p) => p.ts).join(" | "),
      zod: `z.union([${parts.map((p) => p.zod).join(", ")}])`,
    };
  }

  const types = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
  const nullable = types.includes("null");
  const primary = types.find((t) => t !== "null");

  if (primary === "object" || (!primary && schema.properties)) {
    const obj = resolveObject(schema, ctx);
    return applyNullable(obj, nullable);
  }
  if (primary === "array") {
    const inner = resolveType(schema.items ?? {}, ctx);
    return applyNullable({ ts: `Array<${inner.ts}>`, zod: `z.array(${inner.zod})` }, nullable);
  }
  if (primary === "string") {
    return applyNullable({ ts: "string", zod: "z.string()" }, nullable);
  }
  if (primary === "integer") {
    return applyNullable({ ts: "number", zod: "z.number().int()" }, nullable);
  }
  if (primary === "number") {
    return applyNullable({ ts: "number", zod: "z.number()" }, nullable);
  }
  if (primary === "boolean") {
    return applyNullable({ ts: "boolean", zod: "z.boolean()" }, nullable);
  }
  if (nullable && !primary) {
    // A null-only schema (e.g. the `{ "type": "null" }` arm of a nullable ref).
    return { ts: "null", zod: "z.null()" };
  }

  return { ts: "unknown", zod: "z.unknown()" };
}

function applyNullable(t: { ts: string; zod: string }, nullable: boolean): { ts: string; zod: string } {
  if (!nullable) return t;
  return { ts: `${t.ts} | null`, zod: `${t.zod}.nullable()` };
}

function resolveObject(schema: JsonSchema, ctx: ResolveCtx): { ts: string; zod: string } {
  const props = schema.properties ?? {};
  const required = new Set(schema.required ?? []);
  const keys = Object.keys(props).sort();

  // A Rust map (`BTreeMap`/`HashMap`) reaches us as an object with no declared
  // properties and an `additionalProperties` value schema. It must become a
  // `z.record`, never a `z.object({})`: zod strips unknown keys, so an empty
  // object schema parses every entry of the map away and hands the surface an
  // empty map that is indistinguishable from one the daemon really sent empty.
  const extra = schema.additionalProperties;
  if (keys.length === 0 && extra !== undefined && extra !== false) {
    const value = extra === true ? { ts: "unknown", zod: "z.unknown()" } : resolveType(extra, ctx);
    return { ts: `Record<string, ${value.ts}>`, zod: `z.record(${value.zod})` };
  }

  const tsFields: string[] = [];
  const zodFields: string[] = [];
  for (const key of keys) {
    const resolved = resolveType(props[key] as JsonSchema, ctx);
    const optional = !required.has(key);
    tsFields.push(`  ${key}${optional ? "?" : ""}: ${resolved.ts};`);
    zodFields.push(`  ${key}: ${optional ? `${resolved.zod}.optional()` : resolved.zod},`);
  }

  const ts = tsFields.length ? `{\n${tsFields.join("\n")}\n}` : "Record<string, never>";
  const zod = zodFields.length ? `z.object({\n${zodFields.join("\n")}\n})` : "z.object({})";
  return { ts, zod };
}

// ---------------------------------------------------------------------------
// Tagged union: discriminated + exhaustive.
// ---------------------------------------------------------------------------

function resolveTaggedUnion(schema: JsonSchema, ctx: ResolveCtx): { ts: string; zod: string } {
  const variants = (schema.oneOf ?? [])
    .map((v) => ({ disc: discriminantOf(v) as { key: string; value: string }, schema: v }))
    .sort((a, b) => a.disc.value.localeCompare(b.disc.value));

  const discKey = variants[0]?.disc.key ?? "kind";

  const tsVariants = variants.map((v) => resolveObject(v.schema, ctx).ts);
  const ts = tsVariants.map((t) => `\n  | ${t.replace(/\n/g, "\n  ")}`).join("");

  const zod = `z.discriminatedUnion(${quote(discKey)}, [${variants
    .map((variant) => resolveObject(variant.schema, ctx).zod)
    .join(", ")}])`;

  return { ts, zod };
}

// ---------------------------------------------------------------------------
// Named def emission.
// ---------------------------------------------------------------------------

function emitNamedDef(name: string, schema: JsonSchema): string {
  const genericParam = schema["x-generic"];

  if (genericParam) {
    // Generic type + decoder factory (DashboardEnvelope<TPayload>).
    const schemaVar = "payloadSchema";
    const ctx: ResolveCtx = { genericParam, genericSchemaVar: schemaVar };
    const obj = resolveObject(schema, ctx);
    const desc = schema.description ? `/** ${schema.description} */\n` : "";
    return [
      `${desc}export interface ${name}<${genericParam}> ${obj.ts.replace(/^\{/, "{").replace(/: /g, ": ")}`,
      "",
      `export function ${name}Schema<${genericParam}>(`,
      `  ${schemaVar}: z.ZodType<${genericParam}>,`,
      `): z.ZodType<${name}<${genericParam}>> {`,
      `  return ${obj.zod.replace(/\n/g, "\n  ")} as unknown as z.ZodType<${name}<${genericParam}>>;`,
      "}",
    ].join("\n");
  }

  const ctx: ResolveCtx = {};

  if (isTaggedUnion(schema)) {
    const union = resolveTaggedUnion(schema, ctx);
    const desc = schema.description ? `/** ${schema.description} */\n` : "";
    return [
      `${desc}export const ${name}Schema = ${union.zod};`,
      `export type ${name} = z.infer<typeof ${name}Schema>;`,
    ].join("\n");
  }

  const resolved = resolveType(schema, ctx);
  if (name === "DashboardDomainStateV1") {
    resolved.zod = `${resolved.zod}.catch("unsupported_schema")`;
  }
  const desc = schema.description ? `/** ${schema.description} */\n` : "";
  const isObject =
    schema.type === "object" || (!schema.type && schema.properties !== undefined);
  if (isObject) {
    return [
      `${desc}export const ${name}Schema = ${resolved.zod};`,
      `export type ${name} = z.infer<typeof ${name}Schema>;`,
    ].join("\n");
  }
  return [
    `${desc}export const ${name}Schema = ${resolved.zod};`,
    `export type ${name} = z.infer<typeof ${name}Schema>;`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Bundle -> files.
// ---------------------------------------------------------------------------

export function generateContracts(bundles: JsonSchema[]): GeneratedContracts {
  const defs: Array<[string, JsonSchema]> = [];
  const revisions: Array<string | number> = [];
  for (const bundle of bundles) {
    if (bundle.schemaRevision !== undefined) revisions.push(bundle.schemaRevision);
    defs.push(...collectDefs(bundle));
  }
  defs.sort((a, b) => a[0].localeCompare(b[0]));

  const uniqueRevisions = [...new Set(revisions.map(String))];
  if (uniqueRevisions.length !== 1) {
    throw new Error(`expected exactly one Rust schema revision, got: ${uniqueRevisions.join(", ")}`);
  }
  const schemaRevision = revisions[0] as string | number;

  const omittedNames = new Set(["DashboardPayloadMarkerV1"]);
  const envelopeIndex = defs.findIndex(([name]) => name === "DashboardEnvelopeV1");
  const envelope = defs[envelopeIndex]?.[1];
  if (envelope?.properties) {
    for (const [name, schema] of defs) {
      if (name !== "DashboardEnvelopeV1" && isMonomorphizedEnvelope(schema, envelope)) {
        omittedNames.add(name);
      }
    }
    defs[envelopeIndex] = [
      "DashboardEnvelopeV1",
      {
        ...envelope,
        "x-generic": "TPayload",
        properties: {
          ...envelope.properties,
          payload: { "x-generic-ref": "TPayload" },
          schema_revision: { const: schemaRevision },
        },
      },
    ];
  }

  const blocks: string[] = [];
  blocks.push(HEADER);
  blocks.push(`import { z } from "zod";`);
  blocks.push(
    [
      "/**",
      " * Exhaustiveness helper for discriminated-union switches. A `default`",
      " * branch that calls `assertNever(value)` fails to compile if a union",
      " * member is left unhandled.",
      " */",
      "export function assertNever(value: never): never {",
      "  throw new Error(`Unhandled discriminated union member: ${JSON.stringify(value)}`);",
      "}",
    ].join("\n"),
  );
  blocks.push(`export const WIRE_SCHEMA_REVISION = ${literal(schemaRevision)} as const;`);

  for (const [name, schema] of defs) {
    if (omittedNames.has(name)) continue;
    const omittedRef = [...localDefinitionRefs(schema)].find((ref) => omittedNames.has(ref));
    if (omittedRef) {
      throw new Error(
        `${name} references omitted generated definition ${omittedRef}`,
      );
    }
    blocks.push(emitNamedDef(name, schema));
  }

  const generated = blocks.join("\n\n") + "\n";

  const index = [
    HEADER,
    "",
    `export * from "./generated";`,
    "",
  ].join("\n");

  return {
    files: {
      [GENERATED_FILE]: generated,
      [INDEX_FILE]: index,
    },
  };
}

export const OUTPUT_FILES = { GENERATED_FILE, INDEX_FILE };
