//! Embedded static assets for the dashboard.
//!
//! The dist files are produced by `dashboard/build.mjs` (run `npm install &&
//! npm run build` in `dashboard/`) and embedded at compile time, so the
//! installed binary serves the UI with no filesystem dependency.

use axum::extract::Path;
use axum::http::{HeaderMap, StatusCode, header};
use axum::response::{Html, IntoResponse, Response};

const INDEX_HTML: &str = r#"<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>tracedecay dashboard</title>
    <link rel="stylesheet" href="/shell/shell.css" />
  </head>
  <body>
    <div id="root"></div>
    <script src="/shell/shell.js"></script>
  </body>
</html>
"#;

const SHELL_JS: &[u8] = include_bytes!("../../dashboard/shell/dist/shell.js");
const SHELL_CSS: &[u8] = include_bytes!("../../dashboard/shell/dist/shell.css");
// Plugin bundles are embedded as &str (they are UTF-8 JavaScript output) so the
// Hermes installer (src/agents/hermes/dashboard_wrapper.rs) can reuse the exact same
// embedded data when writing the wrapper plugin's dist files to disk.
pub(crate) const HOLOGRAPHIC_JS: &str = include_str!("../../dashboard/holographic/dist/index.js");
pub(crate) const HOLOGRAPHIC_CSS: &str = include_str!("../../dashboard/holographic/dist/style.css");
pub(crate) const LCM_JS: &str = include_str!("../../dashboard/lcm/dist/index.js");
pub(crate) const LCM_CSS: &str = include_str!("../../dashboard/lcm/dist/style.css");
pub(crate) const GRAPH_JS: &str = include_str!("../../dashboard/graph/dist/index.js");
pub(crate) const GRAPH_CSS: &str = include_str!("../../dashboard/graph/dist/style.css");
pub(crate) const CODE_DIAGNOSTICS_JS: &str =
    include_str!("../../dashboard/code-diagnostics/dist/index.js");
pub(crate) const CODE_DIAGNOSTICS_CSS: &str =
    include_str!("../../dashboard/code-diagnostics/dist/style.css");
pub(crate) const SAVINGS_JS: &str = include_str!("../../dashboard/savings/dist/index.js");
pub(crate) const SAVINGS_CSS: &str = include_str!("../../dashboard/savings/dist/style.css");
pub(crate) const SETTINGS_JS: &str = include_str!("../../dashboard/settings/dist/index.js");
pub(crate) const SETTINGS_CSS: &str = include_str!("../../dashboard/settings/dist/style.css");
const ASSET_STAMP: &str = env!("TRACEDECAY_DASHBOARD_ASSET_STAMP");

// The single-app dashboard (dashboard/app-dist) embedded via the manifest
// generated by build.rs. `APP_ASSETS` carries every dist file with its
// content type; `APP_ASSET_STAMP` hashes the dist for ETag validation.
mod app_manifest {
    include!(concat!(env!("OUT_DIR"), "/dashboard_app_assets.rs"));
}
use app_manifest::{APP_ASSET_STAMP, APP_ASSETS};

pub(crate) struct DashboardPlugin {
    pub(crate) name: &'static str,
    pub(crate) label: &'static str,
    pub(crate) description: &'static str,
    pub(crate) icon: &'static str,
}

pub(crate) const DASHBOARD_PLUGINS: &[DashboardPlugin] = &[
    DashboardPlugin {
        name: "holographic",
        label: "Holographic Memory",
        description: "Holographic memory explorer + curation",
        icon: "BrainCircuit",
    },
    DashboardPlugin {
        name: "hermes-lcm",
        label: "LCM",
        description: "Lossless Context Management dashboard tab.",
        icon: "Database",
    },
    DashboardPlugin {
        name: "graph",
        label: "Code Graph",
        description: "Search and explore the indexed code graph.",
        icon: "Network",
    },
    DashboardPlugin {
        name: "savings",
        label: "Savings & Cost",
        description: "Token savings ledger and session cost accounting.",
        icon: "PiggyBank",
    },
    DashboardPlugin {
        name: "code-diagnostics",
        label: "Code Diagnostics",
        description: "LSP-backed compiler and type diagnostics.",
        icon: "Bug",
    },
    DashboardPlugin {
        name: "settings",
        label: "Settings",
        description: "Project, user, and environment configuration.",
        icon: "Settings",
    },
];

struct PluginAsset {
    plugin: &'static str,
    js: &'static str,
    css: &'static str,
}

const PLUGIN_ASSETS: &[PluginAsset] = &[
    PluginAsset {
        plugin: "holographic",
        js: HOLOGRAPHIC_JS,
        css: HOLOGRAPHIC_CSS,
    },
    PluginAsset {
        plugin: "hermes-lcm",
        js: LCM_JS,
        css: LCM_CSS,
    },
    PluginAsset {
        plugin: "graph",
        js: GRAPH_JS,
        css: GRAPH_CSS,
    },
    PluginAsset {
        plugin: "code-diagnostics",
        js: CODE_DIAGNOSTICS_JS,
        css: CODE_DIAGNOSTICS_CSS,
    },
    PluginAsset {
        plugin: "savings",
        js: SAVINGS_JS,
        css: SAVINGS_CSS,
    },
    PluginAsset {
        plugin: "settings",
        js: SETTINGS_JS,
        css: SETTINGS_CSS,
    },
];

/// `ETag` value for every embedded asset: the compile-time bundle stamp,
/// quoted per RFC 9110.
fn asset_etag() -> String {
    format!("\"{ASSET_STAMP}\"")
}

/// True when the request's `If-None-Match` matches the embedded-asset
/// `ETag`, so the (up to ~600 KB) bundle body can be skipped with a 304.
fn if_none_match_hits(headers: &HeaderMap) -> bool {
    let etag = asset_etag();
    headers
        .get(header::IF_NONE_MATCH)
        .and_then(|value| value.to_str().ok())
        .is_some_and(|value| {
            value == "*"
                || value
                    .split(',')
                    .any(|tag| tag.trim().trim_start_matches("W/") == etag)
        })
}

fn asset_headers(response: &mut Response, content_type: &'static str) {
    let headers = response.headers_mut();
    headers.insert(
        header::CONTENT_TYPE,
        header::HeaderValue::from_static(content_type),
    );
    // `no-cache` (not `no-store`): the browser revalidates every load, and
    // the build-time stamp answers with a body-less 304 unless the binary —
    // and therefore the embedded bundle — actually changed.
    headers.insert(
        header::CACHE_CONTROL,
        header::HeaderValue::from_static("no-cache"),
    );
    if let Ok(etag) = header::HeaderValue::from_str(&asset_etag()) {
        headers.insert(header::ETAG, etag);
    }
    headers.insert(
        header::HeaderName::from_static("x-tracedecay-asset-stamp"),
        header::HeaderValue::from_static(ASSET_STAMP),
    );
}

fn static_response(
    headers: &HeaderMap,
    body: &'static [u8],
    content_type: &'static str,
) -> Response {
    let mut response = if if_none_match_hits(headers) {
        StatusCode::NOT_MODIFIED.into_response()
    } else {
        body.into_response()
    };
    asset_headers(&mut response, content_type);
    response
}

pub(crate) async fn index_html() -> Html<&'static str> {
    Html(INDEX_HTML)
}

fn app_asset_by_path(path: &str) -> Option<&'static app_manifest::AppAsset> {
    APP_ASSETS.iter().find(|asset| asset.path == path)
}

fn app_etag() -> String {
    format!("\"{APP_ASSET_STAMP}\"")
}

fn app_response(headers: &HeaderMap, asset: &'static app_manifest::AppAsset) -> Response {
    let hit = headers
        .get(header::IF_NONE_MATCH)
        .and_then(|value| value.to_str().ok())
        .is_some_and(|value| {
            value == "*"
                || value
                    .split(',')
                    .any(|tag| tag.trim().trim_start_matches("W/") == app_etag())
        });
    let mut response = if hit {
        StatusCode::NOT_MODIFIED.into_response()
    } else {
        asset.contents.into_response()
    };
    let response_headers = response.headers_mut();
    if let Ok(value) = header::HeaderValue::from_str(asset.content_type) {
        response_headers.insert(header::CONTENT_TYPE, value);
    }
    response_headers.insert(
        header::CACHE_CONTROL,
        header::HeaderValue::from_static("no-cache"),
    );
    if let Ok(etag) = header::HeaderValue::from_str(&app_etag()) {
        response_headers.insert(header::ETAG, etag);
    }
    response
}

/// Serves the single-app dashboard index (embedded dashboard/app-dist).
pub(crate) async fn app_index(headers: HeaderMap) -> Response {
    match app_asset_by_path("index.html") {
        Some(asset) => app_response(&headers, asset),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

/// Serves hashed static assets under `/static/**` from the embedded dist.
pub(crate) async fn app_static(headers: HeaderMap, Path(tail): Path<String>) -> Response {
    match app_asset_by_path(&format!("static/{tail}")) {
        Some(asset) => app_response(&headers, asset),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

/// SPA fallback: client-routed paths (never `/api/**`) receive the app index
/// so React Router owns deep links like `/brain?scope=…`.
pub(crate) async fn app_spa_fallback(headers: HeaderMap) -> Response {
    app_index(headers).await
}

pub(crate) async fn shell_asset(headers: HeaderMap, Path(file): Path<String>) -> Response {
    match file.as_str() {
        "shell.js" => static_response(&headers, SHELL_JS, "application/javascript"),
        "shell.css" => static_response(&headers, SHELL_CSS, "text/css"),
        _ => StatusCode::NOT_FOUND.into_response(),
    }
}

pub(crate) async fn plugin_asset(
    headers: HeaderMap,
    Path((plugin, file)): Path<(String, String)>,
) -> Response {
    let serve =
        |body: &'static str, content_type| static_response(&headers, body.as_bytes(), content_type);
    let Some(asset) = PLUGIN_ASSETS
        .iter()
        .find(|asset| asset.plugin == plugin.as_str())
    else {
        return StatusCode::NOT_FOUND.into_response();
    };
    match file.as_str() {
        "index.js" => serve(asset.js, "application/javascript"),
        "style.css" => serve(asset.css, "text/css"),
        _ => StatusCode::NOT_FOUND.into_response(),
    }
}
