//! Embedded static assets for the dashboard.
//!
//! The canonical single-app dist is produced by Rsbuild (`npm install &&
//! npm run build` in `dashboard/`) and embedded at compile time, so the
//! installed binary serves the UI with no filesystem dependency.

use axum::extract::Path;
use axum::http::{HeaderMap, StatusCode, header};
use axum::response::{IntoResponse, Response};

// The single-app dashboard (dashboard/app-dist) embedded via the manifest
// generated by build.rs. `APP_ASSETS` carries every dist file with its
// content type; `APP_ASSET_STAMP` hashes the dist for ETag validation.
mod app_manifest {
    include!(concat!(env!("OUT_DIR"), "/dashboard_app_assets.rs"));
}
use app_manifest::{APP_ASSET_STAMP, APP_ASSETS};

fn app_asset_by_path(path: &str) -> Option<&'static app_manifest::AppAsset> {
    APP_ASSETS.iter().find(|asset| asset.path == path)
}

fn app_etag() -> String {
    format!("\"{APP_ASSET_STAMP}\"")
}

fn app_response(headers: &HeaderMap, asset: &'static app_manifest::AppAsset) -> Response {
    let hit = headers
        .get(header::IF_NONE_MATCH)
        .and_then(|value| value.to_str().ok())
        .is_some_and(|value| {
            value == "*"
                || value
                    .split(',')
                    .any(|tag| tag.trim().trim_start_matches("W/") == app_etag())
        });
    let mut response = if hit {
        StatusCode::NOT_MODIFIED.into_response()
    } else {
        asset.contents.into_response()
    };
    let response_headers = response.headers_mut();
    if let Ok(value) = header::HeaderValue::from_str(asset.content_type) {
        response_headers.insert(header::CONTENT_TYPE, value);
    }
    response_headers.insert(
        header::CACHE_CONTROL,
        header::HeaderValue::from_static("no-cache"),
    );
    if let Ok(etag) = header::HeaderValue::from_str(&app_etag()) {
        response_headers.insert(header::ETAG, etag);
    }
    response
}

/// Serves the single-app dashboard index (embedded dashboard/app-dist).
pub(crate) async fn app_index(headers: HeaderMap) -> Response {
    match app_asset_by_path("index.html") {
        Some(asset) => app_response(&headers, asset),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

/// Serves hashed static assets under `/static/**` from the embedded dist.
pub(crate) async fn app_static(headers: HeaderMap, Path(tail): Path<String>) -> Response {
    match app_asset_by_path(&format!("static/{tail}")) {
        Some(asset) => app_response(&headers, asset),
        None => StatusCode::NOT_FOUND.into_response(),
    }
}

/// SPA fallback: client-routed paths (never `/api/**`) receive the app index
/// so React Router owns deep links like `/brain?scope=…`.
pub(crate) async fn app_spa_fallback(headers: HeaderMap) -> Response {
    app_index(headers).await
}
