//! Root build-script bridge for the embedded dashboard bundle.
//!
//! The root binary owns `OUT_DIR`, so it supplies generated bytes to the
//! canonical HTTP asset adapter in `tracedecay-api`. Routing, ETag matching,
//! cache policy, and API fallback protection live in that adapter.

use std::sync::Arc;

use axum::Router;
use tracedecay_api::{DashboardAssetSource, StaticDashboardAsset, static_dashboard_router};

// The single-app dashboard (dashboard/app-dist) embedded via the manifest
// generated by build.rs. `APP_ASSETS` carries every dist file with its
// content type; `APP_ASSET_STAMP` hashes the dist for ETag validation.
mod app_manifest {
    include!(concat!(env!("OUT_DIR"), "/dashboard_app_assets.rs"));
}
use app_manifest::{APP_ASSET_STAMP, APP_ASSETS};

fn app_asset_by_path(path: &str) -> Option<&'static app_manifest::AppAsset> {
    APP_ASSETS.iter().find(|asset| asset.path == path)
}

struct EmbeddedDashboardAssetSource;

impl DashboardAssetSource for EmbeddedDashboardAssetSource {
    fn asset_by_path(&self, path: &str) -> Option<StaticDashboardAsset> {
        app_asset_by_path(path).map(|asset| StaticDashboardAsset {
            path: asset.path,
            contents: asset.contents,
            content_type: asset.content_type,
        })
    }

    fn cache_tag(&self) -> &str {
        APP_ASSET_STAMP
    }
}

/// The root build owns the manifest; `tracedecay-api` owns this router's
/// complete HTTP behavior.
pub(crate) fn spa_router() -> Router {
    static_dashboard_router(Arc::new(EmbeddedDashboardAssetSource))
}
