//! Typed payload variants stored by the canonical observability envelope.

use serde::{Deserialize, Serialize};

use super::{
    ActivityObservedV1, AdoptionEligibilityObservedV1, AdoptionOutcomeLinkedV1,
    AnalyticsConsentChangedV1, AppropriateRelianceObservedV1, AutomationFunnelObservedV1,
    ContextOutcomeObservedV1, DeadlineObservedV1, ExecutionTopologySampledV1,
    GitHubStackCapabilityObservedV1, HealthSnapshotObservedV1, IndexObservedV1, LatencyObservedV1,
    McpDispatchObservedV1, NoProgressObservedV1, OperationResourceObservedV1,
    ProviderReliabilityObservedV1, RejectedArgumentObservedV1, RemoteCoverageObservedV1,
    RetrievalAblationObservedV1, RetrievalPlannerObservedV1, RetrievalQueryObservedV1,
    RetrievalSourceObservedV1, RetrievalSynthesisObservedV1, RetrieverObservedV1,
    StorageObservedV1,
    TaskIntelligenceDecisionObservedV1, TaskIntelligenceOutcomeObservedV1, TelemetryDropObservedV1,
    WorkBlockedIntervalObservedV1, WorkConflictOutcomeLinkedV1, WorkConflictPredictionObservedV1,
    WorkDeliveryFanoutObservedV1, WorkDuplicateEffortObservedV1, WorkExecutionLeakObservedV1,
    WorkIntegrationTransitionObservedV1, WorkRerunObservedV1, WorkStackDriftObservedV1,
    WorkflowLifecycleObservedV1, WorkflowOutcomeObservedV1, WorkflowResourceObservedV1,
};

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "snake_case", tag = "kind", content = "value")]
pub enum ObservabilityPayloadV1 {
    RetrievalQuery(RetrievalQueryObservedV1),
    RetrievalPlanner(RetrievalPlannerObservedV1),
    Retriever(RetrieverObservedV1),
    RetrievalSynthesis(RetrievalSynthesisObservedV1),
    RetrievalSource(RetrievalSourceObservedV1),
    ContextOutcome(ContextOutcomeObservedV1),
    RetrievalAblation(RetrievalAblationObservedV1),
    AdoptionEligibility(AdoptionEligibilityObservedV1),
    AdoptionOutcome(AdoptionOutcomeLinkedV1),
    AnalyticsConsent(AnalyticsConsentChangedV1),
    OperationResource(Box<OperationResourceObservedV1>),
    NoProgress(NoProgressObservedV1),
    Latency(LatencyObservedV1),
    Deadline(DeadlineObservedV1),
    Storage(StorageObservedV1),
    Index(IndexObservedV1),
    ExecutionTopology(ExecutionTopologySampledV1),
    WorkConflictPrediction(WorkConflictPredictionObservedV1),
    WorkConflictOutcome(WorkConflictOutcomeLinkedV1),
    WorkIntegrationTransition(WorkIntegrationTransitionObservedV1),
    WorkStackDrift(WorkStackDriftObservedV1),
    GitHubStackCapability(GitHubStackCapabilityObservedV1),
    WorkDuplicateEffort(WorkDuplicateEffortObservedV1),
    WorkBlockedInterval(WorkBlockedIntervalObservedV1),
    WorkRerun(WorkRerunObservedV1),
    WorkExecutionLeak(WorkExecutionLeakObservedV1),
    WorkDeliveryFanout(WorkDeliveryFanoutObservedV1),
    TelemetryDrop(TelemetryDropObservedV1),
    HealthSnapshot(HealthSnapshotObservedV1),
    Activity(ActivityObservedV1),
    McpDispatch(McpDispatchObservedV1),
    AppropriateReliance(AppropriateRelianceObservedV1),
    AutomationFunnel(AutomationFunnelObservedV1),
    TaskIntelligenceDecision(TaskIntelligenceDecisionObservedV1),
    TaskIntelligenceOutcome(TaskIntelligenceOutcomeObservedV1),
    ProviderReliability(ProviderReliabilityObservedV1),
    RemoteCoverage(RemoteCoverageObservedV1),
    WorkflowLifecycle(WorkflowLifecycleObservedV1),
    WorkflowOutcome(WorkflowOutcomeObservedV1),
    WorkflowResource(WorkflowResourceObservedV1),
    RejectedArgument(RejectedArgumentObservedV1),
}
impl ObservabilityPayloadV1 {
    pub const fn event_kind(&self) -> &'static str {
        match self {
            Self::RetrievalQuery(_) => "retrieval.query.completed.v1",
            Self::RetrievalPlanner(_) => "retrieval.planner.decided.v1",
            Self::Retriever(_) => "retrieval.retriever.completed.v1",
            Self::RetrievalSynthesis(_) => "retrieval.synthesis.completed.v1",
            Self::RetrievalSource(_) => "retrieval.source.observed.v1",
            Self::ContextOutcome(_) => "retrieval.context.outcome_linked.v1",
            Self::RetrievalAblation(_) => "retrieval.ablation.measured.v1",
            Self::AdoptionEligibility(_) => "adoption.eligibility_observed.v1",
            Self::AdoptionOutcome(_) => "adoption.outcome.linked.v1",
            Self::AnalyticsConsent(_) => "analytics.consent.changed.v1",
            Self::OperationResource(_) => "operation.resource.completed.v1",
            Self::NoProgress(_) => "operation.no_progress.terminal.v1",
            Self::Latency(_) => "operation.latency.observed.v1",
            Self::Deadline(_) => "operation.deadline.observed.v1",
            Self::Storage(_) => "storage.measurement.observed.v1",
            Self::Index(_) => "index.measurement.observed.v1",
            Self::ExecutionTopology(_) => "work.execution_topology.sampled.v1",
            Self::WorkConflictPrediction(_) => "work.conflict_prediction.observed.v1",
            Self::WorkConflictOutcome(_) => "work.conflict_outcome.linked.v1",
            Self::WorkIntegrationTransition(_) => "work.integration.transition.observed.v1",
            Self::WorkStackDrift(_) => "work.stack_drift.observed.v1",
            Self::GitHubStackCapability(_) => "work.github_stack_capability.observed.v1",
            Self::WorkDuplicateEffort(_) => "work.duplicate_effort.observed.v1",
            Self::WorkBlockedInterval(_) => "work.blocked_interval.observed.v1",
            Self::WorkRerun(_) => "work.rerun.observed.v1",
            Self::WorkExecutionLeak(_) => "work.execution_leak.observed.v1",
            Self::WorkDeliveryFanout(_) => "work.delivery_fanout.observed.v1",
            Self::TelemetryDrop(_) => "telemetry.drop.observed.v1",
            Self::HealthSnapshot(_) => "health.snapshot.observed.v1",
            Self::Activity(_) => "activity.observed.v1",
            Self::McpDispatch(_) => "mcp.dispatch.observed.v1",
            Self::AppropriateReliance(_) => "reliance.decision.observed.v1",
            Self::AutomationFunnel(_) => "automation.funnel.observed.v1",
            Self::TaskIntelligenceDecision(_) => "work.task_intelligence.decision.observed.v1",
            Self::TaskIntelligenceOutcome(_) => "work.task_intelligence.outcome.observed.v1",
            Self::ProviderReliability(_) => "work.provider_reliability.observed.v1",
            Self::RemoteCoverage(_) => "remote.coverage.observed.v1",
            Self::WorkflowLifecycle(_) => "workflow.lifecycle.observed.v1",
            Self::WorkflowOutcome(_) => "workflow.outcome.observed.v1",
            Self::WorkflowResource(_) => "workflow.resource.observed.v1",
            Self::RejectedArgument(_) => "feedback.argument.rejected.v1",
        }
    }

    /// Validates payload-specific bounds and semantic relationships before a
    /// record reaches the registered observation authority.
    pub fn validate(&self) -> Result<(), &'static str> {
        match self {
            Self::RetrievalQuery(value) => value.validate(),
            Self::RetrievalPlanner(value) => value.validate(),
            Self::Retriever(value) => value.validate(),
            Self::RetrievalSynthesis(value) => value.validate(),
            Self::RetrievalSource(value) => value.validate(),
            Self::ContextOutcome(value) => value.validate(),
            Self::RetrievalAblation(value) => value.validate(),
            Self::AdoptionEligibility(value) => value.validate(),
            Self::AdoptionOutcome(value) => value.validate(),
            Self::AnalyticsConsent(_) => Ok(()),
            Self::OperationResource(_) => Ok(()),
            Self::NoProgress(value) => value.validate(),
            Self::Latency(value) => value.validate(),
            Self::Deadline(value) => value.validate(),
            Self::Storage(value) => value.validate(),
            Self::Index(value) => value.validate(),
            Self::ExecutionTopology(value) => value.validate(),
            Self::WorkConflictPrediction(value) => value.validate(),
            Self::WorkConflictOutcome(value) => value.validate(),
            Self::WorkIntegrationTransition(value) => value.validate(),
            Self::WorkStackDrift(value) => value.validate(),
            Self::GitHubStackCapability(value) => value.validate(),
            Self::WorkDuplicateEffort(value) => value.validate(),
            Self::WorkBlockedInterval(value) => value.validate(),
            Self::WorkRerun(value) => value.validate(),
            Self::WorkExecutionLeak(value) => value.validate(),
            Self::WorkDeliveryFanout(value) => value.validate(),
            Self::TelemetryDrop(value) => value.validate(),
            Self::HealthSnapshot(_) | Self::Activity(_) | Self::McpDispatch(_) => Ok(()),
            Self::AppropriateReliance(value) => value.validate(),
            Self::AutomationFunnel(value) => value.validate(),
            Self::TaskIntelligenceDecision(value) => value.validate(),
            Self::TaskIntelligenceOutcome(value) => value.validate(),
            Self::ProviderReliability(value) => value.validate(),
            Self::RemoteCoverage(value) => value.validate(),
            Self::WorkflowLifecycle(value) => value.validate(),
            Self::WorkflowOutcome(value) => value.validate(),
            Self::WorkflowResource(value) => value.validate(),
            Self::RejectedArgument(value) => value.validate(),
        }
    }
}
