//! Hermes dashboard wrapper deployment.
//!
//! Deploys the canonical `dashboard/hermes-wrapper/` plugin (manifest,
//! `plugin_api.py` reverse proxy, and the UI bundles) into a generated Hermes
//! plugin's `dashboard/` subdirectory, where the Hermes web server's
//! dashboard-plugin discovery picks it up
//! (`<hermes_home>/plugins/<name>/dashboard/manifest.json` — both stock and
//! forked Hermes scan user plugins this way).
//!
//! Everything is embedded at build time so installs need no source checkout:
//! the wrapper entry/manifest/api come straight from `dashboard/hermes-wrapper/`;
//! the build script resolves the product dashboard dist assets from the
//! repository root and embeds the same source files used by the standalone
//! dashboard server.
//!
//! On hosts whose Hermes predates dashboard-plugin discovery the deployed
//! directory is inert: the agent-plugin loader only reads `plugin.yaml` and
//! never imports `dashboard/`, so the deploy degrades gracefully.

use std::path::Path;

use crate::errors::{Result, TraceDecayError};

mod assets {
    include!(concat!(env!("OUT_DIR"), "/hermes_dashboard_assets_generated.rs"));
}

/// Manifest for the wrapper plugin (canonical source: `dashboard/hermes-wrapper/`).
const MANIFEST_JSON: &str = include_str!("../../../../../dashboard/hermes-wrapper/manifest.json");
/// `FastAPI` reverse proxy mounted by Hermes at `/api/plugins/tracedecay/`.
const PLUGIN_API_PY: &str = include_str!("../../../../../dashboard/hermes-wrapper/plugin_api.py");
/// Wrapper entry bundle (deployed as `dist/index.js`; plain JS, no build step).
const WRAPPER_ENTRY_JS: &str = include_str!("../../../../../dashboard/hermes-wrapper/src/entry.js");
/// Wrapper-chrome stylesheet (concatenated ahead of the child stylesheets).
const WRAPPER_CSS: &str = include_str!("../../../../../dashboard/hermes-wrapper/src/wrapper.css");

/// Placeholder line in `plugin_api.py` rewritten with the installed binary.
const BIN_PLACEHOLDER: &str = "DEPLOYED_TRACEDECAY_BIN = None";

/// Returns true when `plugin_dir` contains a generated dashboard wrapper.
pub(super) fn is_deployed(plugin_dir: &Path) -> bool {
    plugin_dir.join("dashboard/manifest.json").is_file()
}

/// Applies the install-time dashboard wrapper policy for a generated Hermes plugin.
///
/// Dashboard-enabled installs create or update the wrapper. Dashboard-disabled
/// installs remove only files generated by tracedecay, leaving user files in place.
pub(super) fn apply_install_policy(
    plugin_dir: &Path,
    tracedecay_bin: &str,
    deploy_dashboard: bool,
) -> Result<()> {
    if deploy_dashboard {
        deploy(plugin_dir, tracedecay_bin)
    } else {
        uninstall(plugin_dir)
    }
}

/// Refreshes a dashboard wrapper only when the previous install had one.
///
/// `tracedecay update-plugin` must preserve a `--no-dashboard` install as
/// dashboard-free while still rebaking wrapper assets and the binary path
/// for installs where the dashboard page already exists.
pub(super) fn refresh_if_previously_deployed(
    plugin_dir: &Path,
    tracedecay_bin: &str,
    previously_deployed: bool,
) -> Result<()> {
    if previously_deployed {
        deploy(plugin_dir, tracedecay_bin)?;
    }
    Ok(())
}

/// Deploys the dashboard wrapper into `<plugin_dir>/dashboard/`.
///
/// The binary path is baked into `plugin_api.py`; the dashboard resolves its
/// real project from the Hermes process cwd or an explicit `TraceDecay` env var.
fn deploy(plugin_dir: &Path, tracedecay_bin: &str) -> Result<()> {
    let dashboard_dir = plugin_dir.join("dashboard");
    let dist_dir = dashboard_dir.join("dist");
    std::fs::create_dir_all(&dist_dir).map_err(|e| TraceDecayError::Config {
        message: format!("failed to create {}: {e}", dist_dir.display()),
    })?;

    super::write_text_file(&dashboard_dir.join("manifest.json"), &manifest_json()?)?;
    super::write_text_file(
        &dashboard_dir.join("plugin_api.py"),
        &plugin_api(tracedecay_bin)?,
    )?;
    super::write_text_file(&dist_dir.join("index.js"), WRAPPER_ENTRY_JS)?;
    super::write_text_file(
        &dist_dir.join("holographic.js"),
        assets::HOLOGRAPHIC_JS,
    )?;
    super::write_text_file(&dist_dir.join("lcm.js"), assets::LCM_JS)?;
    super::write_text_file(
        &dist_dir.join("graph.js"),
        assets::GRAPH_JS,
    )?;
    super::write_text_file(
        &dist_dir.join("savings.js"),
        assets::SAVINGS_JS,
    )?;
    super::write_text_file(&dist_dir.join("style.css"), &wrapper_style_css())?;

    eprintln!(
        "\x1b[32m✔\x1b[0m Wrote Hermes dashboard plugin page to {}",
        dashboard_dir.display()
    );
    Ok(())
}

/// Removes a previously deployed dashboard wrapper (uninstall and the
/// `--no-dashboard` opt-out both route here). Only generated files are
/// removed; a directory containing anything else is left in place.
pub(super) fn uninstall(plugin_dir: &Path) -> Result<()> {
    let dashboard_dir = plugin_dir.join("dashboard");
    if !dashboard_dir.exists() {
        return Ok(());
    }
    let dist_dir = dashboard_dir.join("dist");
    for file in [
        "index.js",
        "holographic.js",
        "lcm.js",
        "graph.js",
        "savings.js",
        "style.css",
    ] {
        super::remove_generated_file(&dist_dir.join(file))?;
    }
    super::remove_empty_dir(&dist_dir)?;
    super::remove_generated_file(&dashboard_dir.join("manifest.json"))?;
    super::remove_generated_file(&dashboard_dir.join("plugin_api.py"))?;
    if super::remove_empty_dir(&dashboard_dir)? {
        eprintln!(
            "\x1b[32m✔\x1b[0m Removed Hermes dashboard plugin page from {}",
            dashboard_dir.display()
        );
    } else {
        eprintln!(
            "  Left {} in place because it contains files not generated by tracedecay",
            dashboard_dir.display()
        );
    }
    Ok(())
}

/// The embedded manifest with `version` stamped to the generating binary, so
/// stale deploys are detectable the same way as the agent plugin manifest.
fn manifest_json() -> Result<String> {
    let mut manifest: serde_json::Value =
        serde_json::from_str(MANIFEST_JSON).map_err(|e| TraceDecayError::Config {
            message: format!("embedded hermes-wrapper manifest.json is invalid: {e}"),
        })?;
    manifest["version"] = serde_json::Value::String(env!("TRACEDECAY_PRODUCT_VERSION").to_string());
    serde_json::to_string_pretty(&manifest)
        .map(|json| format!("{json}\n"))
        .map_err(|e| TraceDecayError::Config {
            message: format!("failed to serialize hermes-wrapper manifest.json: {e}"),
        })
}

/// The embedded `plugin_api.py` with the deploy-time binary path rewritten.
///
/// The placeholder is an exact module-level line in the canonical wrapper;
/// substitution always starts from the embedded template, so reinstalls are
/// idempotent.
fn plugin_api(tracedecay_bin: &str) -> Result<String> {
    let encode = |value: &str| {
        // JSON string literals are valid Python string literals.
        serde_json::to_string(value).map_err(|e| TraceDecayError::Config {
            message: format!("unencodable deploy value for plugin_api.py: {e}"),
        })
    };
    if !PLUGIN_API_PY.contains(BIN_PLACEHOLDER) {
        return Err(TraceDecayError::Config {
            message: "embedded plugin_api.py is missing its binary placeholder — \
                      this is a tracedecay build bug"
                .to_string(),
        });
    }
    Ok(PLUGIN_API_PY.replace(
        BIN_PLACEHOLDER,
        &format!("DEPLOYED_TRACEDECAY_BIN = {}", encode(tracedecay_bin)?),
    ))
}

/// Wrapper stylesheet: wrapper chrome + the child stylesheets, concatenated
/// exactly like `dashboard/build.mjs` builds `hermes-wrapper/dist/style.css`.
fn wrapper_style_css() -> String {
    [
        WRAPPER_CSS,
        assets::HOLOGRAPHIC_CSS,
        assets::LCM_CSS,
        assets::GRAPH_CSS,
        assets::SAVINGS_CSS,
    ]
    .join("\n")
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use std::collections::BTreeMap;
    use std::path::{Path, PathBuf};

    use tempfile::TempDir;

    use super::*;

    fn text(path: &Path) -> String {
        std::fs::read_to_string(path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()))
    }

    fn file_contents(root: &Path) -> BTreeMap<PathBuf, String> {
        fn walk(dir: &Path, root: &Path, out: &mut BTreeMap<PathBuf, String>) {
            let Ok(entries) = std::fs::read_dir(dir) else {
                return;
            };
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    walk(&path, root, out);
                } else {
                    let relative = path.strip_prefix(root).unwrap().to_path_buf();
                    out.insert(relative, text(&path));
                }
            }
        }

        let mut out = BTreeMap::new();
        walk(root, root, &mut out);
        out
    }

    #[test]
    fn manifest_is_stamped_with_crate_version() {
        let manifest = manifest_json().unwrap();
        let parsed: serde_json::Value = serde_json::from_str(&manifest).unwrap();
        assert_eq!(parsed["version"], env!("TRACEDECAY_PRODUCT_VERSION"));
        assert_eq!(parsed["name"], "tracedecay");
        assert_eq!(parsed["label"], "TraceDecay");
        assert_eq!(parsed["api"], "plugin_api.py");
        // The provider link must match the memory provider name the installer
        // writes into config.yaml (`memory.provider: tracedecay`).
        assert_eq!(parsed["provider"]["name"], "tracedecay");
    }

    #[test]
    fn plugin_api_bakes_binary_but_no_project() {
        let api = plugin_api("/usr/local/bin/tracedecay").unwrap();
        assert!(api.contains(r#"DEPLOYED_TRACEDECAY_BIN = "/usr/local/bin/tracedecay""#));
        assert!(!api.contains("DEPLOYED_PROJECT_ROOT"));
        assert!(!api.contains(BIN_PLACEHOLDER));
    }

    #[test]
    fn plugin_api_never_uses_plugin_profile_dir_as_project() {
        let temp = TempDir::new().unwrap();
        let plugin_dir = temp.path().join(".hermes/plugins/tracedecay");
        deploy(&plugin_dir, "/usr/local/bin/tracedecay").unwrap();

        let api = text(&plugin_dir.join("dashboard/plugin_api.py"));
        assert!(!api.contains("DEPLOYED_PROJECT_ROOT"));
        assert!(!api.contains(temp.path().to_string_lossy().as_ref()));
        assert!(!api.contains(BIN_PLACEHOLDER));
    }

    #[test]
    fn plugin_api_escapes_quotes_in_paths() {
        let api = plugin_api("/tmp/we\"ird/tracedecay").unwrap();
        assert!(api.contains(r#"DEPLOYED_TRACEDECAY_BIN = "/tmp/we\"ird/tracedecay""#));
    }

    #[test]
    fn wrapper_css_concatenates_all_child_sheets() {
        let css = wrapper_style_css();
        assert!(css.starts_with(WRAPPER_CSS));
        for child in [
            assets::HOLOGRAPHIC_CSS,
            assets::LCM_CSS,
            assets::GRAPH_CSS,
            assets::SAVINGS_CSS,
        ] {
            assert!(css.contains(child));
        }
    }

    #[test]
    fn first_install_deploys_wrapper_files() {
        let temp = TempDir::new().unwrap();
        let plugin_dir = temp.path().join(".hermes/plugins/tracedecay");

        apply_install_policy(&plugin_dir, "/bin/tracedecay", true).unwrap();

        assert!(is_deployed(&plugin_dir));
        assert!(plugin_dir.join("dashboard/dist/index.js").is_file());
        assert!(plugin_dir.join("dashboard/dist/holographic.js").is_file());
        assert!(plugin_dir.join("dashboard/dist/lcm.js").is_file());
        assert!(plugin_dir.join("dashboard/dist/graph.js").is_file());
        assert!(plugin_dir.join("dashboard/dist/savings.js").is_file());
        let api = text(&plugin_dir.join("dashboard/plugin_api.py"));
        assert!(api.contains(r#"DEPLOYED_TRACEDECAY_BIN = "/bin/tracedecay""#));
        assert!(!api.contains("DEPLOYED_PROJECT_ROOT"));
    }

    #[test]
    fn install_creates_missing_parent_directories() {
        let temp = TempDir::new().unwrap();
        let plugin_dir = temp.path().join("missing/profile/plugins/tracedecay");

        apply_install_policy(&plugin_dir, "/bin/tracedecay", true).unwrap();

        assert!(plugin_dir.join("dashboard/manifest.json").is_file());
        assert!(plugin_dir.join("dashboard/dist/style.css").is_file());
    }

    #[test]
    fn update_over_existing_wrapper_replaces_generated_content() {
        let temp = TempDir::new().unwrap();
        let plugin_dir = temp.path().join(".hermes/plugins/tracedecay");
        apply_install_policy(&plugin_dir, "/old/bin/tracedecay", true).unwrap();

        apply_install_policy(&plugin_dir, "/new/bin/tracedecay", true).unwrap();

        let api = text(&plugin_dir.join("dashboard/plugin_api.py"));
        assert!(api.contains("/new/bin/tracedecay"));
        assert!(!api.contains("/old/bin/tracedecay"));
        assert!(!api.contains("DEPLOYED_PROJECT_ROOT"));
    }

    #[test]
    fn no_dashboard_policy_removes_generated_wrapper() {
        let temp = TempDir::new().unwrap();
        let plugin_dir = temp.path().join(".hermes/plugins/tracedecay");
        apply_install_policy(&plugin_dir, "/bin/tracedecay", true).unwrap();

        apply_install_policy(&plugin_dir, "/bin/tracedecay", false).unwrap();

        assert!(!plugin_dir.join("dashboard").exists());
    }

    #[test]
    fn no_dashboard_policy_preserves_non_generated_files() {
        let temp = TempDir::new().unwrap();
        let plugin_dir = temp.path().join(".hermes/plugins/tracedecay");
        apply_install_policy(&plugin_dir, "/bin/tracedecay", true).unwrap();
        std::fs::write(plugin_dir.join("dashboard/notes.txt"), "user file").unwrap();

        apply_install_policy(&plugin_dir, "/bin/tracedecay", false).unwrap();

        assert_eq!(text(&plugin_dir.join("dashboard/notes.txt")), "user file");
        assert!(!plugin_dir.join("dashboard/manifest.json").exists());
        assert!(!plugin_dir.join("dashboard/plugin_api.py").exists());
        assert!(!plugin_dir.join("dashboard/dist").exists());
    }

    #[test]
    fn repeated_deploy_is_idempotent() {
        let temp = TempDir::new().unwrap();
        let plugin_dir = temp.path().join(".hermes/plugins/tracedecay");
        apply_install_policy(&plugin_dir, "/bin/tracedecay", true).unwrap();
        let before = file_contents(&plugin_dir.join("dashboard"));

        apply_install_policy(&plugin_dir, "/bin/tracedecay", true).unwrap();
        let after = file_contents(&plugin_dir.join("dashboard"));

        assert_eq!(after, before);
    }

    #[test]
    fn refresh_preserves_no_dashboard_installs() {
        let temp = TempDir::new().unwrap();
        let plugin_dir = temp.path().join(".hermes/plugins/tracedecay");

        refresh_if_previously_deployed(&plugin_dir, "/bin/tracedecay", false).unwrap();

        assert!(!plugin_dir.join("dashboard").exists());
    }

    #[test]
    fn refresh_updates_previously_deployed_wrapper() {
        let temp = TempDir::new().unwrap();
        let plugin_dir = temp.path().join(".hermes/plugins/tracedecay");
        apply_install_policy(&plugin_dir, "/old/bin/tracedecay", true).unwrap();

        refresh_if_previously_deployed(&plugin_dir, "/new/bin/tracedecay", true).unwrap();

        let api = text(&plugin_dir.join("dashboard/plugin_api.py"));
        assert!(api.contains("/new/bin/tracedecay"));
        assert!(!api.contains("DEPLOYED_PROJECT_ROOT"));
    }
}
