//! Generated Hermes plugin template rendering.
//!
//! This module owns the generated Python/YAML/Markdown source strings emitted by
//! `tracedecay install --agent hermes`, keeping the installer flow in
//! `super::write_plugin_files` focused on filesystem orchestration.

use crate::errors::{Result, TraceDecayError};

pub(super) fn plugin_manifest() -> Result<String> {
    let tools = crate::ports::tool_definitions()?
        .into_iter()
        .map(|tool| format!("  - {}", tool.name))
        .collect::<Vec<_>>()
        .join("\n");
    // `version` tracks the generating binary so `hermes plugins list` and
    // `tracedecay doctor` can detect stale generated plugins after upgrades.
    Ok(format!(
        "name: tracedecay\n\
         kind: standalone\n\
         version: {version}\n\
         generator_commit: {commit}\n\
         description: TraceDecay code-graph tools, memory provider, and LCM context engine for Hermes\n\
         author: tracedecay (generated by `tracedecay install --agent hermes`)\n\
         provides_tools:\n{tools}\n\
         provides_hooks:\n\
           - pre_llm_call\n\
           - post_tool_call\n\
         provides_commands:\n\
           - /tracedecay_status\n",
        version = env!("TRACEDECAY_PRODUCT_VERSION"),
        commit = env!("TRACEDECAY_GIT_SHA"),
    ))
}

pub(super) fn plugin_schemas() -> String {
    r#""""Generated tracedecay tool schemas for Hermes."""
import json
from pathlib import Path

with Path(__file__).with_name("schemas.json").open("r", encoding="utf-8") as schema_file:
    TOOL_SCHEMAS = json.load(schema_file)
"#
    .to_string()
}

pub(super) fn plugin_schemas_json() -> Result<String> {
    let defs = crate::ports::tool_definitions()?
        .into_iter()
        .map(|tool| {
            serde_json::json!({
                "name": tool.name,
                "description": tool.description,
                "parameters": tool.input_schema,
            })
        })
        .collect::<Vec<_>>();
    serde_json::to_string_pretty(&defs)
        .map(|json| format!("{json}\n"))
        .map_err(|e| TraceDecayError::Config {
            message: format!("failed to serialize Hermes schemas.json: {e}"),
        })
}

pub(super) fn plugin_tools(tracedecay_bin: &str) -> Result<String> {
    let bin =
        serde_json::to_string(tracedecay_bin).unwrap_or_else(|_| "\"tracedecay\"".to_string());
    let format_tools = crate::ports::format_capable_tool_names()?
        .iter()
        .map(|name| format!("    {name:?},"))
        .collect::<Vec<_>>()
        .join("\n");
    Ok(format!(
        r#""""Generated tracedecay tool handlers for Hermes."""
import json
import os
import subprocess
import tempfile

TRACEDECAY_BIN = {bin}
# Default per-call ceiling. Long-running verbs (LCM ingest/compression over
# long transcripts, doctor/diagnose repair passes) keep a higher ceiling.
TRACEDECAY_TIMEOUT_SECONDS = 120
TRACEDECAY_LONG_TIMEOUT_SECONDS = 600
LONG_RUNNING_TOOLS = frozenset((
    "tracedecay_lcm_compress",
    "tracedecay_lcm_preflight",
    "tracedecay_lcm_doctor",
    "tracedecay_diagnose",
    # First hermes search runs the state.db catch-up sweep, which can
    # exceed the default ceiling on large profile histories.
    "tracedecay_message_search",
))
MAX_CAPTURE_CHARS = 4000
# Linux caps a single argv string at MAX_ARG_STRLEN (128 KiB). Payloads at or
# above this threshold spill to a tempfile passed as `--args @<path>` so
# compression of exactly the long sessions it exists for cannot fail with
# E2BIG/EFAULT at exec time.
ARGS_FILE_THRESHOLD_BYTES = 100000

JSON_FORMAT_TOOLS = frozenset((
{format_tools}
))

_PLUGIN_CONFIG_CACHE = {{}}

def hermes_home_dir(hermes_home=None):
    return str(
        hermes_home
        or os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    )

def plugin_config_block(hermes_home=None):
    """Return the `plugins.tracedecay` mapping from the profile config.yaml.

    This is the conventional Hermes home for plugin settings (the same
    `plugins.<name>` block bundled plugins use). Cached per config file
    mtime so the hot tool-dispatch path stays cheap.
    """
    home = hermes_home_dir(hermes_home)
    path = os.path.join(home, "config.yaml")
    try:
        stat = os.stat(path)
        cache_key = (stat.st_mtime_ns, stat.st_size)
    except OSError:
        return {{}}
    cached = _PLUGIN_CONFIG_CACHE.get(path)
    if cached is not None and cached[0] == cache_key:
        return cached[1]
    block = {{}}
    try:
        import yaml
        with open(path, encoding="utf-8-sig") as config_file:
            config = yaml.safe_load(config_file) or {{}}
        plugins = config.get("plugins")
        candidate = plugins.get("tracedecay") if isinstance(plugins, dict) else None
        if isinstance(candidate, dict):
            block = candidate
    except Exception:
        block = {{}}
    _PLUGIN_CONFIG_CACHE[path] = (cache_key, block)
    return block

def code_project_root(explicit=None, cwd=None, hermes_home=None):
    candidate = explicit or cwd or os.getcwd()
    if isinstance(candidate, str) and candidate.strip() and os.path.isabs(candidate):
        candidate = candidate.strip()
        try:
            candidate_real = os.path.realpath(candidate)
            hermes_real = os.path.realpath(hermes_home_dir(hermes_home))
            if os.path.commonpath((hermes_real, candidate_real)) == hermes_real:
                return None
        except (OSError, TypeError, ValueError):
            return None
        return candidate
    return None

def normalize_output(value) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    return str(value)

def truncate_output(value, limit: int = MAX_CAPTURE_CHARS) -> str:
    output = normalize_output(value)
    if len(output) <= limit:
        return output
    return output[:limit] + "...<truncated>"

def error_payload(message: str, result=None) -> str:
    payload = {{"error": message}}
    if result is not None:
        stdout = truncate_output(getattr(result, "stdout", ""))
        stderr = truncate_output(getattr(result, "stderr", ""))
        if stdout:
            payload["stdout"] = stdout
        if stderr:
            payload["stderr"] = stderr
    return json.dumps(payload)

def call_tracedecay_tool(name: str, args: dict, **kwargs) -> str:
    args_file = None
    try:
        tool_args = dict(args or {{}})
        if name in JSON_FORMAT_TOOLS and "format" not in tool_args:
            tool_args = dict(tool_args)
            tool_args["format"] = "json"
        if "messages" in kwargs and "messages" not in tool_args:
            tool_args = dict(tool_args)
            tool_args["messages"] = kwargs["messages"]
        registry_argv = None
        if name == "tracedecay_project_list":
            registry_argv = [TRACEDECAY_BIN, "projects", "list"]
            if tool_args.get("limit") is not None:
                registry_argv.extend(["--limit", str(tool_args["limit"])])
        elif name == "tracedecay_project_search":
            query = str(tool_args.get("query") or "").strip()
            if not query:
                return error_payload("tracedecay_project_search requires query")
            registry_argv = [TRACEDECAY_BIN, "projects", "search", query]
            if tool_args.get("limit") is not None:
                registry_argv.extend(["--limit", str(tool_args["limit"])])
        elif name == "tracedecay_project_context":
            project_selector = tool_args.get("project_selector")
            nested_selector = project_selector if isinstance(project_selector, dict) else {{}}
            selector = str(
                tool_args.get("project_id")
                or tool_args.get("project_path")
                or tool_args.get("path")
                or nested_selector.get("project_id")
                or nested_selector.get("project_path")
                or nested_selector.get("path")
                or ""
            ).strip()
            if selector:
                registry_argv = [TRACEDECAY_BIN, "projects", "context", selector]
        if registry_argv is not None:
            registry_argv.append("--json")
        # `project_root` is transport routing, never part of the MCP argument
        # object. Resolve it only from an explicit call or the real process /
        # session cwd; Hermes homes and profiles never select TraceDecay data.
        project_root = kwargs.get("project_root")
        user_scoped = (
            tool_args.get("memory_scope") == "user"
            or tool_args.get("storage_scope") == "user"
        )
        if user_scoped:
            project_root = None
        elif not project_root:
            project_root = code_project_root(
                cwd=kwargs.get("cwd") or tool_args.get("cwd"),
                hermes_home=kwargs.get("hermes_home"),
            )
        else:
            project_root = code_project_root(
                explicit=project_root,
                hermes_home=kwargs.get("hermes_home"),
            )
        payload = json.dumps(tool_args)
        if registry_argv is not None:
            argv = registry_argv
        else:
            argv = [TRACEDECAY_BIN, "tool"]
            if project_root:
                argv.extend(["--project", str(project_root)])
            argv.extend([name, "--json", "--args"])
            if len(payload.encode("utf-8")) >= ARGS_FILE_THRESHOLD_BYTES:
                fd, args_file = tempfile.mkstemp(prefix="tracedecay-args-", suffix=".json")
                with os.fdopen(fd, "w", encoding="utf-8") as args_handle:
                    args_handle.write(payload)
                argv.append("@" + args_file)
            else:
                argv.append(payload)
        timeout_seconds = (
            TRACEDECAY_LONG_TIMEOUT_SECONDS
            if name in LONG_RUNNING_TOOLS
            else TRACEDECAY_TIMEOUT_SECONDS
        )
        run_kwargs = {{
            "check": False,
            "capture_output": True,
            "text": True,
            "timeout": timeout_seconds,
            "shell": False,
        }}
        if registry_argv is not None:
            run_kwargs["cwd"] = str(project_root) if project_root else os.path.abspath(os.sep)
        elif not project_root:
            run_kwargs["cwd"] = os.path.abspath(os.sep)
        result = subprocess.run(argv, **run_kwargs)
        if result.returncode != 0:
            return error_payload(f"tracedecay tool exited with status {{result.returncode}}", result)
        output = result.stdout.strip()
        if not output:
            return "{{}}"
        try:
            json.loads(output)
            if registry_argv is not None:
                return json.dumps({{"content": [{{"type": "text", "text": output}}]}})
            return output
        except json.JSONDecodeError:
            return error_payload("tracedecay tool returned invalid JSON", result)
    except subprocess.TimeoutExpired as exc:
        return error_payload("tracedecay tool timed out", exc)
    except Exception as exc:
        return json.dumps({{"error": f"tracedecay tool failed: {{exc}}"}})
    finally:
        if args_file is not None:
            try:
                os.unlink(args_file)
            except OSError:
                pass

def make_handler(name: str, hermes_home=None):
    def handler(args: dict, **kwargs) -> str:
        if hermes_home and not kwargs.get("hermes_home"):
            kwargs["hermes_home"] = hermes_home
        return call_tracedecay_tool(name, args, **kwargs)
    return handler
"#
    ))
}

/// Generated `__init__.py` body, embedded from `templates/plugin_init.py` so
/// the Python payload lives as an editable asset instead of a giant Rust
/// string literal. Copied verbatim (no interpolation) below the provenance
/// header.
const PLUGIN_INIT_BODY_PY: &str = include_str!("templates/plugin_init.py");

pub(super) fn plugin_init() -> String {
    // Provenance header: lets `tracedecay doctor` and humans detect a live
    // install that was clobbered by an older/newer generator build.
    format!(
        "# Generated by tracedecay {} (commit {}). Do not edit; refresh with `tracedecay update-plugin`.\n{body}",
        env!("TRACEDECAY_PRODUCT_VERSION"),
        env!("TRACEDECAY_GIT_SHA"),
        body = PLUGIN_INIT_BODY_PY,
    )
}

/// `hermes tracedecay ...` CLI passthrough. Hermes' memory-plugin CLI
/// discovery (`plugins/memory/__init__.py::discover_plugin_cli_commands`)
/// loads `cli.py` from the ACTIVE provider's directory and wires
/// `register_cli(subparser)` + `tracedecay_command(args)` into argparse, so
/// the verbs work without any core change (honcho pattern).
pub(super) const PLUGIN_CLI_PY: &str = include_str!("templates/cli.py");

pub(super) const HERMES_SKILL: &str = include_str!("templates/skill.md");
