// GENERATED by dashboard/codegen from Rust schemars output. DO NOT EDIT.
// Source: the Serialize contract of dashboard/read_model.rs and every Rust
// payload DTO included by dashboard::contract_schema.
// Deterministic output (stable ordering, no timestamps).

import { z } from "zod";

/**
 * Exhaustiveness helper for discriminated-union switches. A `default`
 * branch that calls `assertNever(value)` fails to compile if a union
 * member is left unhandled.
 */
export function assertNever(value: never): never {
  throw new Error(`Unhandled discriminated union member: ${JSON.stringify(value)}`);
}

export const WIRE_SCHEMA_REVISION = 1 as const;

/** Strongly typed canonical identity: `ActorId`. */
export const ActorIdSchema = z.string();
export type ActorId = z.infer<typeof ActorIdSchema>;

export const CancellationObservationSchema = z.object({
  observed_at: z.lazy(() => UtcMicrosSchema),
  stage: z.lazy(() => CancellationStageSchema),
});
export type CancellationObservation = z.infer<typeof CancellationObservationSchema>;

/** Exact stage at which cancellation or deadline state was observed. */
export const CancellationStageSchema = z.enum(["after_commit", "before_admission", "before_effect", "before_read", "during_read", "effect_in_flight", "reconciling"]);
export type CancellationStage = z.infer<typeof CancellationStageSchema>;

/** Authorization outcome for the read. On the loopback single-user dashboard a
legal local read is [`Self::Authorized`]; the other variants are retained so
the contract can express `unauthorized` (identity absent/expired), `denied`
(known identity lacks permission), and `redacted` reads without a schema
change. */
export const DashboardAuthorizationV1Schema = z.discriminatedUnion("outcome", [z.object({
  outcome: z.literal("authorized"),
}), z.object({
  outcome: z.literal("denied"),
}), z.object({
  outcome: z.literal("redacted"),
}), z.object({
  outcome: z.literal("unauthorized"),
})]);
export type DashboardAuthorizationV1 = z.infer<typeof DashboardAuthorizationV1Schema>;

/** Coverage completeness axis. `Unsupported` distinguishes "the source that
would establish coverage is not wired" from `Unknown` ("coverage could not
be determined"). */
export const DashboardCoverageCompletenessV1Schema = z.enum(["complete", "partial", "unknown", "unsupported"]);
export type DashboardCoverageCompletenessV1 = z.infer<typeof DashboardCoverageCompletenessV1Schema>;

/** Coverage statement. Counts are optional; an unknown denominator is `None`,
never a fabricated `0`/`100%`. The completeness axis is authoritative — the
frontend never derives `complete` from a `matched == eligible` coincidence. */
export const DashboardCoverageV1Schema = z.object({
  completeness: z.lazy(() => DashboardCoverageCompletenessV1Schema),
  denominator: z.number().int().nullable(),
  eligible: z.number().int().nullable(),
  examined: z.number().int().nullable(),
  excluded: z.number().int().nullable(),
  matched: z.number().int().nullable(),
  omission_reasons: z.array(z.string()),
  omitted: z.number().int().nullable(),
  unit: z.string().nullable(),
  unknown: z.number().int().nullable(),
});
export type DashboardCoverageV1 = z.infer<typeof DashboardCoverageV1Schema>;

/** The normative dashboard domain-state union.

The first sixteen variants are the plan's exact `DashboardDomainState`
discriminated union. [`Self::Unsupported`] is the PR14 backend-gap binding
state: the read model's HTTP surface exists, but its live producer/source is
not yet wired server-side. It is never healthy or empty — the frontend
renders a distinct "not yet available" state — and it is deliberately
separate from [`Self::UnsupportedSchema`] (an undecodable schema/variant). */
export const DashboardDomainStateV1Schema = z.union([z.enum(["cancelled", "complete_zero_findings", "conflicting", "denied", "error", "loading", "locked", "offline", "partial", "ready", "redacted", "stale", "timed_out", "unauthorized", "unknown", "unsupported_schema"]), z.literal("unsupported")]).catch("unsupported_schema");
export type DashboardDomainStateV1 = z.infer<typeof DashboardDomainStateV1Schema>;

/** The normative read-model envelope. Every V2 read-model route returns exactly
this shape; only `payload` varies by route. */
export interface DashboardEnvelopeV1<TPayload> {
  authorization: DashboardAuthorizationV1;
  coverage: DashboardCoverageV1;
  domain_state: DashboardDomainStateV1;
  freshness: DashboardFreshnessV1;
  legal_actions: Array<DashboardLegalActionRefV1>;
  payload: TPayload;
  schema_revision: 1;
  scope: DashboardScopeV1;
  source_watermark: DashboardWatermarkV1 | null;
  time: DashboardTimeV1;
  version: DashboardVersionV1;
}

export function DashboardEnvelopeV1Schema<TPayload>(
  payloadSchema: z.ZodType<TPayload>,
): z.ZodType<DashboardEnvelopeV1<TPayload>> {
  return z.object({
    authorization: z.lazy(() => DashboardAuthorizationV1Schema),
    coverage: z.lazy(() => DashboardCoverageV1Schema),
    domain_state: z.lazy(() => DashboardDomainStateV1Schema),
    freshness: z.lazy(() => DashboardFreshnessV1Schema),
    legal_actions: z.array(z.lazy(() => DashboardLegalActionRefV1Schema)),
    payload: payloadSchema,
    schema_revision: z.literal(1),
    scope: z.lazy(() => DashboardScopeV1Schema),
    source_watermark: z.union([z.lazy(() => DashboardWatermarkV1Schema), z.null()]),
    time: z.lazy(() => DashboardTimeV1Schema),
    version: z.lazy(() => DashboardVersionV1Schema),
  }) as unknown as z.ZodType<DashboardEnvelopeV1<TPayload>>;
}

/** Freshness of the observed state relative to its live source watermark.
`Absent` (no source produced anything) and `Unsupported` (no source wired)
are distinct from `Stale` (behind the watermark) and `Unknown`. */
export const DashboardFreshnessStateV1Schema = z.enum(["absent", "fresh", "stale", "unknown", "unsupported"]);
export type DashboardFreshnessStateV1 = z.infer<typeof DashboardFreshnessStateV1Schema>;

/** Freshness statement plus the optional observation stamp/watermark it was
judged against. */
export const DashboardFreshnessV1Schema = z.object({
  observed_at_micros: z.number().int().nullable(),
  state: z.lazy(() => DashboardFreshnessStateV1Schema),
  watermark: z.string().nullable(),
});
export type DashboardFreshnessV1 = z.infer<typeof DashboardFreshnessV1Schema>;

/** The legal-action reference kinds a read model may attach. This mirrors the
plan's action vocabulary reduced to the read surface: the dashboard only
renders these references and submits them through the owning application
operation; it never constructs an effect inline. */
export const DashboardLegalActionKindV1Schema = z.enum(["expand_evidence", "inspect", "refresh", "request_apply", "request_cancel", "request_dry_run"]);
export type DashboardLegalActionKindV1 = z.infer<typeof DashboardLegalActionKindV1Schema>;

/** A reference to one owner-supplied legal action. `operation` names the owning
application operation; the dashboard never embeds argv, a path, or an inline
effect. */
export const DashboardLegalActionRefV1Schema = z.object({
  kind: z.lazy(() => DashboardLegalActionKindV1Schema),
  operation: z.string(),
});
export type DashboardLegalActionRefV1 = z.infer<typeof DashboardLegalActionRefV1Schema>;

/** Exact scope the envelope was resolved for. A deep link/query never falls
back to a title, path, or latest version to recover scope. */
export const DashboardScopeV1Schema = z.object({
  project_id: z.string().nullable(),
  storage_mode: z.string(),
  store_root: z.string(),
});
export type DashboardScopeV1 = z.infer<typeof DashboardScopeV1Schema>;

/** Valid time and observation time, kept separate. `observation_time` is when
the daemon observed the state; `valid_time` is when the state was true in the
modelled domain (absent when a read model has no distinct valid time). */
export const DashboardTimeV1Schema = z.object({
  observation_time_micros: z.number().int(),
  valid_time_micros: z.number().int().nullable(),
});
export type DashboardTimeV1 = z.infer<typeof DashboardTimeV1Schema>;

/** Entity and graph version identities pinned by the envelope. Both are
optional: a read model with no versioned graph state leaves them absent
rather than inventing `0`/`latest`. */
export const DashboardVersionV1Schema = z.object({
  entity_version: z.string().nullable(),
  graph_version: z.string().nullable(),
});
export type DashboardVersionV1 = z.infer<typeof DashboardVersionV1Schema>;

/** Opaque monotone source watermark. The frontend compares watermarks for
staleness but never parses their internal structure. */
export const DashboardWatermarkV1Schema = z.object({
  source: z.string(),
  watermark: z.string(),
});
export type DashboardWatermarkV1 = z.infer<typeof DashboardWatermarkV1Schema>;

/** One immutable deadline supplied by the caller or upstream admission layer. */
export const DeadlineSchema = z.object({
  expires_at: z.lazy(() => UtcMicrosSchema),
});
export type Deadline = z.infer<typeof DeadlineSchema>;

/** Whether an owning operation requires an explicit human confirmation before it
may perform its admitted mutating effect. */
export const DoctorConfirmationRequirementV1Schema = z.union([z.literal("required"), z.literal("not_required")]);
export type DoctorConfirmationRequirementV1 = z.infer<typeof DoctorConfirmationRequirementV1Schema>;

/** Whether Doctor observed all of a family's evidence sources. */
export const DoctorCoverageCompletenessV1Schema = z.union([z.literal("complete"), z.literal("partial"), z.literal("unknown")]);
export type DoctorCoverageCompletenessV1 = z.infer<typeof DoctorCoverageCompletenessV1Schema>;

/** A bounded, human-readable coverage statement plus its completeness. */
export const DoctorCoverageStatementV1Schema = z.object({
  completeness: z.lazy(() => DoctorCoverageCompletenessV1Schema),
  statement: z.string(),
});
export type DoctorCoverageStatementV1 = z.infer<typeof DoctorCoverageStatementV1Schema>;

/** Durable, non-disclosing reference to one owning-authority evidence
record (for example a `FeedbackFindingId`, configuration revision, or
runtime read coverage anchor). Doctor stores the reference only; the
owning authority remains the single source of the record. */
export const DoctorEvidenceReferenceV1Schema = z.string();
export type DoctorEvidenceReferenceV1 = z.infer<typeof DoctorEvidenceReferenceV1Schema>;

/** A typed reference to one piece of evidence Doctor composed into a finding.

The `family` records which audited input surface produced the evidence, so
a finding may cross-cite evidence from more than one family without losing
provenance. */
export const DoctorEvidenceRefV1Schema = z.object({
  family: z.lazy(() => DoctorFindingFamilyV1Schema),
  reference: z.lazy(() => DoctorEvidenceReferenceV1Schema),
});
export type DoctorEvidenceRefV1 = z.infer<typeof DoctorEvidenceRefV1Schema>;

/** Exact Doctor evidence states from Plan 09 §PR14.

Missing, partial, or unknown truth never becomes healthy or clean. Only
[`DoctorEvidenceStateV1::HealthyCompleteCoverage`] asserts a healthy result,
and only when its finding carries complete coverage (see
[`DoctorFindingV1::new`]). */
export const DoctorEvidenceStateV1Schema = z.union([z.literal("unsupported"), z.literal("absent"), z.literal("stale"), z.literal("degraded"), z.literal("partial"), z.literal("unknown"), z.literal("denied"), z.literal("healthy_complete_coverage")]);
export type DoctorEvidenceStateV1 = z.infer<typeof DoctorEvidenceStateV1Schema>;

/** Whether a family was consulted from an observed source or is unavailable. */
export const DoctorFamilyConsultationV1Schema = z.discriminatedUnion("status", [z.object({
  status: z.literal("consulted"),
}), z.object({
  reason: z.lazy(() => DoctorFamilyUnavailableReasonV1Schema),
  status: z.literal("unavailable"),
})]);
export type DoctorFamilyConsultationV1 = z.infer<typeof DoctorFamilyConsultationV1Schema>;

/** The consultation status of one finding family within a report. */
export const DoctorFamilyCoverageV1Schema = z.object({
  consultation: z.lazy(() => DoctorFamilyConsultationV1Schema),
  family: z.lazy(() => DoctorFindingFamilyV1Schema),
});
export type DoctorFamilyCoverageV1 = z.infer<typeof DoctorFamilyCoverageV1Schema>;

/** Why a finding family could not be consulted from an observed source. */
export const DoctorFamilyUnavailableReasonV1Schema = z.union([z.literal("unwired"), z.literal("unsupported"), z.literal("absent"), z.literal("denied"), z.literal("unknown")]);
export type DoctorFamilyUnavailableReasonV1 = z.infer<typeof DoctorFamilyUnavailableReasonV1Schema>;

/** Stable Doctor finding families.

The initial list is derived from Plan 14's observable classes (advisory
findings from Brain/Explorer/Loom/Code/Observatory) and the legacy
`core_doctor` checks (graph quick-check, temporal/migration health,
configuration compatibility drift, semantic runtime, session ingest).
Each family maps to one audited typed input surface. The set is kept small
and honest; new families are added through a future versioned enum rather
than by widening the meaning of an existing variant. */
export const DoctorFindingFamilyV1Schema = z.union([z.literal("advisory"), z.literal("configuration"), z.literal("storage_runtime"), z.literal("storage"), z.literal("language_server"), z.literal("semantic_index"), z.literal("observability")]);
export type DoctorFindingFamilyV1 = z.infer<typeof DoctorFindingFamilyV1Schema>;

/** The canonical Doctor report projection. `entries` retains the storage
subclass attached by the kernel; remediation descriptors are emitted only
after the kernel registry resolves the finding's owner-supplied reference. */
export const DoctorFindingsPayloadV1Schema = z.object({
  entries: z.array(z.lazy(() => DoctorReportEntryV1Schema)),
  family_filter: z.union([z.lazy(() => DoctorFindingFamilyV1Schema), z.null()]),
  kind_statuses: z.array(z.lazy(() => StorageFindingKindStatusV1Schema)).nullable().optional(),
  known_families: z.array(z.lazy(() => DoctorFindingFamilyV1Schema)),
  note: z.string(),
  remediations: z.array(z.lazy(() => DoctorRemediationDescriptorV1Schema)),
  report_coverage: z.union([z.lazy(() => DoctorReportCoverageV1Schema), z.null()]),
});
export type DoctorFindingsPayloadV1 = z.infer<typeof DoctorFindingsPayloadV1Schema>;

/** One canonical Doctor finding.

A finding pins its diagnosis `family`, its evidence `state`, the typed
evidence it composed, a coverage statement, and an optional reference to an
owner-supplied remediation. Construction enforces the Plan 09 §PR14
invariants that keep unknown/partial evidence from collapsing into a healthy
or clean result. */
export const DoctorFindingV1Schema = z.object({
  coverage: z.lazy(() => DoctorCoverageStatementV1Schema),
  evidence: z.array(z.lazy(() => DoctorEvidenceRefV1Schema)),
  family: z.lazy(() => DoctorFindingFamilyV1Schema),
  remediation: z.union([z.lazy(() => DoctorRemediationRefV1Schema), z.null()]),
  state: z.lazy(() => DoctorEvidenceStateV1Schema),
});
export type DoctorFindingV1 = z.infer<typeof DoctorFindingV1Schema>;

/** Reference to the owning application operation that would perform a
remediation (its capability or use-case identity). Doctor names the
operation; it never embeds argv, a path, or an inline effect. */
export const DoctorOwningOperationRefV1Schema = z.string();
export type DoctorOwningOperationRefV1 = z.infer<typeof DoctorOwningOperationRefV1Schema>;

/** The application surface that owns dispatch of a remediation operation.

The kernel names the owner so a transport can route confirmation and dispatch
to the correct surface; it never dispatches itself. */
export const DoctorOwningSurfaceV1Schema = z.union([z.literal("configuration_control_plane"), z.literal("storage_runtime"), z.literal("daemon_runtime"), z.literal("host_integration"), z.literal("semantic_index_runtime"), z.literal("feedback_read")]);
export type DoctorOwningSurfaceV1 = z.infer<typeof DoctorOwningSurfaceV1Schema>;

export const DoctorRemediationApplyRequestV1Schema = z.object({
  confirmed: z.boolean(),
  idempotency_key: z.string(),
  operation: z.lazy(() => DoctorOwningOperationRefV1Schema),
  preview_id: z.string().nullable(),
});
export type DoctorRemediationApplyRequestV1 = z.infer<typeof DoctorRemediationApplyRequestV1Schema>;

/** A typed description of what an owner-supplied remediation operation would do.

This is a *description*, not an effect. It never carries argv, a path, or an
inline action, and resolving it performs no work. */
export const DoctorRemediationDescriptorV1Schema = z.object({
  action_confirmation: z.lazy(() => DoctorConfirmationRequirementV1Schema),
  operation: z.lazy(() => DoctorOwningOperationRefV1Schema),
  preview_available: z.boolean(),
  summary: z.string(),
  surface: z.lazy(() => DoctorOwningSurfaceV1Schema),
});
export type DoctorRemediationDescriptorV1 = z.infer<typeof DoctorRemediationDescriptorV1Schema>;

export const DoctorRemediationDispatchErrorV1Schema = z.enum(["confirmation_required", "denied", "invalid_reference", "owner_unavailable", "unsupported"]);
export type DoctorRemediationDispatchErrorV1 = z.infer<typeof DoctorRemediationDispatchErrorV1Schema>;

/** Preview-versus-action distinction for an owner-supplied remediation.

Doctor never repairs; it references an owning application operation. A
preview pins expected state without mutating; an action is the owning
operation's admitted effect. Both are invoked through the owning operation,
never inline. */
export const DoctorRemediationKindV1Schema = z.union([z.literal("preview"), z.literal("action")]);
export type DoctorRemediationKindV1 = z.infer<typeof DoctorRemediationKindV1Schema>;

export const DoctorRemediationOperationPhaseV1Schema = z.enum(["cancelled", "completed", "effect_unknown", "failed", "partial", "previewed", "running", "timed_out"]);
export type DoctorRemediationOperationPhaseV1 = z.infer<typeof DoctorRemediationOperationPhaseV1Schema>;

export const DoctorRemediationOperationV1Schema = z.object({
  effect_receipt: z.union([z.lazy(() => EffectReceiptSchema), z.null()]),
  execution: z.union([z.lazy(() => OperationReceiptSchema), z.null()]),
  operation_id: z.lazy(() => OperationIdSchema),
  owning_operation: z.lazy(() => DoctorOwningOperationRefV1Schema),
  phase: z.lazy(() => DoctorRemediationOperationPhaseV1Schema),
  preview_id: z.string().nullable(),
});
export type DoctorRemediationOperationV1 = z.infer<typeof DoctorRemediationOperationV1Schema>;

export const DoctorRemediationPayloadV1Schema = z.discriminatedUnion("status", [z.object({
  operation: z.lazy(() => DoctorRemediationOperationV1Schema),
  status: z.literal("operation"),
}), z.object({
  reason: z.lazy(() => DoctorRemediationDispatchErrorV1Schema),
  status: z.literal("unavailable"),
})]);
export type DoctorRemediationPayloadV1 = z.infer<typeof DoctorRemediationPayloadV1Schema>;

export const DoctorRemediationPreviewRequestV1Schema = z.object({
  operation: z.lazy(() => DoctorOwningOperationRefV1Schema),
});
export type DoctorRemediationPreviewRequestV1 = z.infer<typeof DoctorRemediationPreviewRequestV1Schema>;

/** A reference to an owner-supplied remediation.

Doctor never repairs directly; it names the owning application operation
and whether a preview or action is offered. The caller invokes that owning
operation through its normal admitted path. */
export const DoctorRemediationRefV1Schema = z.object({
  kind: z.lazy(() => DoctorRemediationKindV1Schema),
  owning_operation: z.lazy(() => DoctorOwningOperationRefV1Schema),
});
export type DoctorRemediationRefV1 = z.infer<typeof DoctorRemediationRefV1Schema>;

/** The report-wide coverage statement: which families were consulted versus
unavailable, plus an overall completeness and a bounded human statement. */
export const DoctorReportCoverageV1Schema = z.object({
  completeness: z.lazy(() => DoctorCoverageCompletenessV1Schema),
  families: z.array(z.lazy(() => DoctorFamilyCoverageV1Schema)),
  statement: z.lazy(() => DoctorCoverageStatementV1Schema),
});
export type DoctorReportCoverageV1 = z.infer<typeof DoctorReportCoverageV1Schema>;

/** One entry in a Doctor report: a canonical finding plus, for the storage
family, its typed subclass. The subclass is present only for storage findings
(a non-storage entry never carries one). */
export const DoctorReportEntryV1Schema = z.object({
  finding: z.lazy(() => DoctorFindingV1Schema),
  storage_kind: z.union([z.lazy(() => DoctorStorageFindingKindV1Schema), z.null()]),
});
export type DoctorReportEntryV1 = z.infer<typeof DoctorReportEntryV1Schema>;

/** Typed subclasses of the [`DoctorFindingFamilyV1::Storage`] finding family
(Plan 38 §7).

The storage family never reports a silent overage: each subclass names one
observable retention/size condition Doctor surfaces over the Plan 26 size
observability read models. The set is closed and grows only through a future
versioned enum, never by widening an existing subclass. */
export const DoctorStorageFindingKindV1Schema = z.union([z.literal("over_budget_store"), z.literal("orphan_store"), z.literal("stale_branch_dbs"), z.literal("incident_debris_present"), z.literal("retention_backlog")]);
export type DoctorStorageFindingKindV1 = z.infer<typeof DoctorStorageFindingKindV1Schema>;

/** The stable effect classification of one application operation.

Git index writes remain separate classes so policy cannot accidentally
substitute one index mutation for another. */
export const EffectClassSchema = z.enum(["administrative", "configuration_write", "git_index_commit", "git_index_stage", "git_index_unstage", "preview", "read", "source_edit"]);
export type EffectClass = z.infer<typeof EffectClassSchema>;

/** Durable effect proof. It records identities and receipts, never credentials
or arbitrary command text. */
export const EffectReceiptSchema = z.object({
  actor: z.lazy(() => ActorIdSchema),
  catalog_digest: z.lazy(() => ManifestDigestSchema),
  committed_state: z.union([z.lazy(() => ManifestDigestSchema), z.null()]),
  configuration_digest: z.lazy(() => ManifestDigestSchema),
  effect_class: z.lazy(() => EffectClassSchema),
  expected_state: z.lazy(() => ManifestDigestSchema),
  external_proof: z.union([z.lazy(() => RetrievalAnchorIdSchema), z.null()]),
  idempotency_key: z.string(),
  input_digest: z.lazy(() => ManifestDigestSchema),
  operation: z.lazy(() => UseCaseIdSchema),
  outcome: z.lazy(() => EffectTerminationSchema),
  policy_digest: z.lazy(() => ManifestDigestSchema),
  privacy_digest: z.lazy(() => ManifestDigestSchema),
  request_id: z.string(),
  scope: z.lazy(() => ResolvedScopeSchema),
});
export type EffectReceipt = z.infer<typeof EffectReceiptSchema>;

/** Durable effect receipt terminal state. */
export const EffectTerminationSchema = z.enum(["cancelled", "completed", "effect_unknown", "failed", "partial", "timed_out"]);
export type EffectTermination = z.infer<typeof EffectTerminationSchema>;

/** Strongly typed algorithm-tagged integrity digest: `ManifestDigest`. */
export const ManifestDigestSchema = z.string();
export type ManifestDigest = z.infer<typeof ManifestDigestSchema>;

/** Bounded work accounting supplied by an owning port or transaction. */
export const OperationBudgetUsageSchema = z.object({
  bytes_consumed: z.number().int(),
  elapsed_micros: z.number().int(),
  units_consumed: z.number().int(),
});
export type OperationBudgetUsage = z.infer<typeof OperationBudgetUsageSchema>;

/** Stable operation identity. The originating authorized request owns the
identity; paths, labels, and client-selected payloads never participate. */
export const OperationIdSchema = z.string();
export type OperationId = z.infer<typeof OperationIdSchema>;

/** Canonical operation evidence. An admitted failure remains represented here
rather than being replaced by a transport exception. */
export const OperationReceiptSchema = z.object({
  budget: z.lazy(() => OperationBudgetUsageSchema),
  cancellation: z.union([z.lazy(() => CancellationObservationSchema), z.null()]),
  effective_deadline: z.lazy(() => DeadlineSchema),
  ended_at: z.lazy(() => UtcMicrosSchema),
  started_at: z.lazy(() => UtcMicrosSchema),
  termination: z.lazy(() => OperationTerminationSchema),
});
export type OperationReceipt = z.infer<typeof OperationReceiptSchema>;

/** Terminal state after an operation has been admitted. */
export const OperationTerminationSchema = z.enum(["cancelled", "completed", "effect_unknown", "failed", "partial", "timed_out"]);
export type OperationTermination = z.infer<typeof OperationTerminationSchema>;

/** Strongly typed canonical identity: `ProjectId`. */
export const ProjectIdSchema = z.string();
export type ProjectId = z.infer<typeof ProjectIdSchema>;

/** Strongly typed canonical identity: `RefId`. */
export const RefIdSchema = z.string();
export type RefId = z.infer<typeof RefIdSchema>;

/** Strongly typed canonical identity: `RepositoryId`. */
export const RepositoryIdSchema = z.string();
export type RepositoryId = z.infer<typeof RepositoryIdSchema>;

/** The resolved PR11 scope is one exact project/repository/worktree root.

Paths, CWDs, labels, and mutable branch spellings are deliberately absent. */
export const ResolvedScopeSchema = z.object({
  project_id: z.lazy(() => ProjectIdSchema),
  reference: z.union([z.lazy(() => RefIdSchema), z.null()]),
  repository_id: z.lazy(() => RepositoryIdSchema),
  scope_digest: z.lazy(() => ManifestDigestSchema),
  worktree_id: z.lazy(() => WorktreeIdSchema),
});
export type ResolvedScope = z.infer<typeof ResolvedScopeSchema>;

/** Strongly typed canonical identity: `RetrievalAnchorId`. */
export const RetrievalAnchorIdSchema = z.string();
export type RetrievalAnchorId = z.infer<typeof RetrievalAnchorIdSchema>;

/** A byte size measurement. A newtype keeps sizes from being confused with
counts, ratios, or timestamps in the read models and producers. */
export const StorageByteSizeV1Schema = z.number().int();
export type StorageByteSizeV1 = z.infer<typeof StorageByteSizeV1Schema>;

/** Source-coverage status for one typed storage finding producer. */
export const StorageFindingKindStatusV1Schema = z.object({
  kind: z.lazy(() => DoctorStorageFindingKindV1Schema),
  observed_entries: z.number().int(),
  reason: z.string(),
  state: z.lazy(() => StorageFindingSourceStateV1Schema),
});
export type StorageFindingKindStatusV1 = z.infer<typeof StorageFindingKindStatusV1Schema>;

/** Whether one Plan 38 producer had enough source evidence to report a real
result. This is source coverage, not a health grade: `Real` can describe a
clean observation or a problem finding. */
export const StorageFindingSourceStateV1Schema = z.enum(["partial", "real", "unset", "unsupported"]);
export type StorageFindingSourceStateV1 = z.infer<typeof StorageFindingSourceStateV1Schema>;

/** Telemetry payload: one entry per distinct store the dashboard holds a
connection to. */
export const StorageTelemetryPayloadV1Schema = z.object({
  budget_note: z.string(),
  growth_note: z.string(),
  stores: z.array(z.lazy(() => StoreTelemetryEntryV1Schema)),
});
export type StorageTelemetryPayloadV1 = z.infer<typeof StorageTelemetryPayloadV1Schema>;

/** The typed result of one telemetry read attempt.

The port is *total*: it never fails silently into a healthy or empty result.
A platform that cannot query `dbstat`/pragmas reports [`Self::Unsupported`];
a denied read reports [`Self::Denied`]; an undetermined read reports
[`Self::Unknown`]. Each maps to a distinct, honest Doctor evidence state. */
export const StorageTelemetryReadV1Schema = z.discriminatedUnion("kind", [z.object({
  kind: z.literal("denied"),
  store: z.lazy(() => StoreKeyV1Schema),
}), z.object({
  kind: z.literal("observed"),
  sample: z.lazy(() => StoreSizeSampleV1Schema),
}), z.object({
  kind: z.literal("unknown"),
  store: z.lazy(() => StoreKeyV1Schema),
}), z.object({
  kind: z.literal("unsupported"),
  store: z.lazy(() => StoreKeyV1Schema),
})]);
export type StorageTelemetryReadV1 = z.infer<typeof StorageTelemetryReadV1Schema>;

/** The budget-evaluation dimension, sourced from owner configuration. */
export const StoreBudgetDimensionV1Schema = z.discriminatedUnion("state", [z.object({
  evaluation: z.lazy(() => StoreBudgetEvaluationV1Schema),
  reason: z.string(),
  setting_key: z.string(),
  state: z.literal("evaluated"),
}), z.object({
  reason: z.string(),
  state: z.literal("unknown"),
}), z.object({
  reason: z.string(),
  setting_key: z.string(),
  state: z.literal("unset"),
})]);
export type StoreBudgetDimensionV1 = z.infer<typeof StoreBudgetDimensionV1Schema>;

/** The outcome of evaluating a store size against its soft budget. */
export const StoreBudgetEvaluationV1Schema = z.discriminatedUnion("state", [z.object({
  observed: z.lazy(() => StorageByteSizeV1Schema),
  overage: z.lazy(() => StorageByteSizeV1Schema),
  soft_limit: z.lazy(() => StorageByteSizeV1Schema),
  state: z.literal("over_budget"),
}), z.object({
  observed: z.lazy(() => StorageByteSizeV1Schema),
  soft_limit: z.lazy(() => StorageByteSizeV1Schema),
  state: z.literal("within_budget"),
})]);
export type StoreBudgetEvaluationV1 = z.infer<typeof StoreBudgetEvaluationV1Schema>;

/** The per-store growth dimension. Growth is only ever reported over the window
the server actually observed, and that window is named in `coverage`. */
export const StoreGrowthDimensionV1Schema = z.discriminatedUnion("state", [z.object({
  coverage: z.string(),
  measured_at: z.number().int(),
  reason: z.string(),
  state: z.literal("baseline"),
  total_bytes: z.number().int(),
}), z.object({
  coverage: z.string(),
  current_total_bytes: z.number().int(),
  first_measured_at: z.number().int(),
  first_total_bytes: z.number().int(),
  growth_bytes: z.number().int(),
  last_measured_at: z.number().int(),
  sample_count: z.number().int(),
  samples: z.array(z.lazy(() => StoreSizeWatermarkV1Schema)),
  state: z.literal("observed"),
}), z.object({
  reason: z.string(),
  state: z.literal("unknown"),
})]);
export type StoreGrowthDimensionV1 = z.infer<typeof StoreGrowthDimensionV1Schema>;

/** Logical name of one owner-profile store (for example `sessions.db`,
`graph.db`, or `branches/feature-x`). Never an absolute on-disk path. */
export const StoreKeyV1Schema = z.string();
export type StoreKeyV1 = z.infer<typeof StoreKeyV1Schema>;

/** One cheap size sample for a single store, derived from page-count pragmas.

`total_bytes` is `page_count * page_size`; `free_bytes` is
`freelist_pages * page_size`. Both are recorded so the free-page ratio and
the reclaimable-bytes estimate (Plan 38 §6 compaction) can be computed
without re-reading the store. */
export const StoreSizeSampleV1Schema = z.object({
  freelist_pages: z.number().int(),
  observed_at: z.lazy(() => UtcMicrosSchema),
  page_count: z.number().int(),
  page_size_bytes: z.number().int(),
  store: z.lazy(() => StoreKeyV1Schema),
});
export type StoreSizeSampleV1 = z.infer<typeof StoreSizeSampleV1Schema>;

/** One recorded store-size watermark. */
export const StoreSizeWatermarkV1Schema = z.object({
  free_bytes: z.number().int(),
  measured_at: z.number().int(),
  total_bytes: z.number().int(),
});
export type StoreSizeWatermarkV1 = z.infer<typeof StoreSizeWatermarkV1Schema>;

/** One store's telemetry entry. One entry per distinct store **file**, not per
dashboard role. */
export const StoreTelemetryEntryV1Schema = z.object({
  budget: z.lazy(() => StoreBudgetDimensionV1Schema),
  free_bytes: z.number().int().nullable(),
  free_page_ratio: z.number().nullable(),
  growth: z.lazy(() => StoreGrowthDimensionV1Schema),
  path: z.string(),
  read: z.lazy(() => StorageTelemetryReadV1Schema),
  role: z.string(),
  roles: z.array(z.string()),
  store: z.string(),
  total_bytes: z.number().int().nullable(),
});
export type StoreTelemetryEntryV1 = z.infer<typeof StoreTelemetryEntryV1Schema>;

/** Stable, canonical catalog identity for `UseCaseId`. */
export const UseCaseIdSchema = z.string();
export type UseCaseId = z.infer<typeof UseCaseIdSchema>;

/** UTC timestamp represented as microseconds from the Unix epoch. */
export const UtcMicrosSchema = z.number().int();
export type UtcMicros = z.infer<typeof UtcMicrosSchema>;

/** Strongly typed canonical identity: `WorktreeId`. */
export const WorktreeIdSchema = z.string();
export type WorktreeId = z.infer<typeof WorktreeIdSchema>;

export const DomainStateSchema = DashboardDomainStateV1Schema;
export type WireDomainState = DashboardDomainStateV1;
export const ScopeSchema = DashboardScopeV1Schema;
export type WireScope = DashboardScopeV1;
export const VersionSchema = DashboardVersionV1Schema;
export type WireVersion = DashboardVersionV1;
export const TimeSchema = DashboardTimeV1Schema;
export type WireTime = DashboardTimeV1;
export const WatermarkSchema = DashboardWatermarkV1Schema;
export type WireWatermark = DashboardWatermarkV1;
export const AuthorizationSchema = DashboardAuthorizationV1Schema;
export type WireAuthorization = DashboardAuthorizationV1;
export const CoverageSchema = DashboardCoverageV1Schema;
export type WireCoverage = DashboardCoverageV1;
export const FreshnessSchema = DashboardFreshnessV1Schema;
export type WireFreshness = DashboardFreshnessV1;
export const LegalActionKindSchema = DashboardLegalActionKindV1Schema;
export type WireLegalActionKind = DashboardLegalActionKindV1;
export const LegalActionRefSchema = DashboardLegalActionRefV1Schema;
export type WireLegalActionRef = DashboardLegalActionRefV1;
export const EnvelopeSchema = DashboardEnvelopeV1Schema;
export type WireEnvelope<TPayload> = DashboardEnvelopeV1<TPayload>;
export const DoctorConfirmationRequirementSchema = DoctorConfirmationRequirementV1Schema;
export type DoctorConfirmationRequirement = DoctorConfirmationRequirementV1;
export const DoctorCoverageCompletenessSchema = DoctorCoverageCompletenessV1Schema;
export type DoctorCoverageCompleteness = DoctorCoverageCompletenessV1;
export const DoctorCoverageStatementSchema = DoctorCoverageStatementV1Schema;
export type DoctorCoverageStatement = DoctorCoverageStatementV1;
export const DoctorEvidenceRefSchema = DoctorEvidenceRefV1Schema;
export type DoctorEvidenceRef = DoctorEvidenceRefV1;
export const DoctorEvidenceReferenceSchema = DoctorEvidenceReferenceV1Schema;
export type DoctorEvidenceReference = DoctorEvidenceReferenceV1;
export const DoctorEvidenceStateSchema = DoctorEvidenceStateV1Schema;
export type DoctorEvidenceState = DoctorEvidenceStateV1;
export const DoctorFamilyConsultationSchema = DoctorFamilyConsultationV1Schema;
export type DoctorFamilyConsultation = DoctorFamilyConsultationV1;
export const DoctorFamilyCoverageSchema = DoctorFamilyCoverageV1Schema;
export type DoctorFamilyCoverage = DoctorFamilyCoverageV1;
export const DoctorFamilyUnavailableReasonSchema = DoctorFamilyUnavailableReasonV1Schema;
export type DoctorFamilyUnavailableReason = DoctorFamilyUnavailableReasonV1;
export const DoctorFindingFamilySchema = DoctorFindingFamilyV1Schema;
export type DoctorFindingFamily = DoctorFindingFamilyV1;
export const DoctorFindingSchema = DoctorFindingV1Schema;
export type DoctorFinding = DoctorFindingV1;
export const DoctorFindingsPayloadSchema = DoctorFindingsPayloadV1Schema;
export type DoctorFindingsPayload = DoctorFindingsPayloadV1;
export const DoctorOwningOperationRefSchema = DoctorOwningOperationRefV1Schema;
export type DoctorOwningOperationRef = DoctorOwningOperationRefV1;
export const DoctorOwningSurfaceSchema = DoctorOwningSurfaceV1Schema;
export type DoctorOwningSurface = DoctorOwningSurfaceV1;
export const DoctorRemediationApplyRequestSchema = DoctorRemediationApplyRequestV1Schema;
export type DoctorRemediationApplyRequest = DoctorRemediationApplyRequestV1;
export const DoctorRemediationDescriptorSchema = DoctorRemediationDescriptorV1Schema;
export type DoctorRemediationDescriptor = DoctorRemediationDescriptorV1;
export const DoctorRemediationDispatchErrorSchema = DoctorRemediationDispatchErrorV1Schema;
export type DoctorRemediationDispatchError = DoctorRemediationDispatchErrorV1;
export const DoctorRemediationKindSchema = DoctorRemediationKindV1Schema;
export type DoctorRemediationKind = DoctorRemediationKindV1;
export const DoctorRemediationOperationPhaseSchema = DoctorRemediationOperationPhaseV1Schema;
export type DoctorRemediationOperationPhase = DoctorRemediationOperationPhaseV1;
export const DoctorRemediationOperationSchema = DoctorRemediationOperationV1Schema;
export type DoctorRemediationOperation = DoctorRemediationOperationV1;
export const DoctorRemediationPayloadSchema = DoctorRemediationPayloadV1Schema;
export type DoctorRemediationPayload = DoctorRemediationPayloadV1;
export const DoctorRemediationPreviewRequestSchema = DoctorRemediationPreviewRequestV1Schema;
export type DoctorRemediationPreviewRequest = DoctorRemediationPreviewRequestV1;
export const DoctorRemediationRefSchema = DoctorRemediationRefV1Schema;
export type DoctorRemediationRef = DoctorRemediationRefV1;
export const DoctorReportCoverageSchema = DoctorReportCoverageV1Schema;
export type DoctorReportCoverage = DoctorReportCoverageV1;
export const DoctorReportEntrySchema = DoctorReportEntryV1Schema;
export type DoctorReportEntry = DoctorReportEntryV1;
export const DoctorStorageFindingKindSchema = DoctorStorageFindingKindV1Schema;
export type DoctorStorageFindingKind = DoctorStorageFindingKindV1;
export const StorageByteSizeSchema = StorageByteSizeV1Schema;
export type StorageByteSize = StorageByteSizeV1;
export const StorageFindingKindStatusSchema = StorageFindingKindStatusV1Schema;
export type StorageFindingKindStatus = StorageFindingKindStatusV1;
export const StorageFindingSourceStateSchema = StorageFindingSourceStateV1Schema;
export type StorageFindingSourceState = StorageFindingSourceStateV1;
export const StorageTelemetryPayloadSchema = StorageTelemetryPayloadV1Schema;
export type StorageTelemetryPayload = StorageTelemetryPayloadV1;
export const StorageTelemetryReadSchema = StorageTelemetryReadV1Schema;
export type StorageTelemetryRead = StorageTelemetryReadV1;
export const StoreBudgetDimensionSchema = StoreBudgetDimensionV1Schema;
export type StoreBudgetDimension = StoreBudgetDimensionV1;
export const StoreBudgetEvaluationSchema = StoreBudgetEvaluationV1Schema;
export type StoreBudgetEvaluation = StoreBudgetEvaluationV1;
export const StoreGrowthDimensionSchema = StoreGrowthDimensionV1Schema;
export type StoreGrowthDimension = StoreGrowthDimensionV1;
export const StoreKeySchema = StoreKeyV1Schema;
export type StoreKey = StoreKeyV1;
export const StoreSizeSampleSchema = StoreSizeSampleV1Schema;
export type StoreSizeSample = StoreSizeSampleV1;
export const StoreSizeWatermarkSchema = StoreSizeWatermarkV1Schema;
export type StoreSizeWatermark = StoreSizeWatermarkV1;
export const StoreTelemetryEntrySchema = StoreTelemetryEntryV1Schema;
export type StoreTelemetryEntry = StoreTelemetryEntryV1;
export const DoctorCancellationStageSchema = CancellationStageSchema;
export type DoctorCancellationStage = CancellationStage;
export const DoctorOperationTerminationSchema = OperationTerminationSchema;
export type DoctorOperationTermination = OperationTermination;
export const DoctorOperationReceiptSchema = OperationReceiptSchema;
export type DoctorOperationReceipt = OperationReceipt;
export const DoctorEffectReceiptSchema = EffectReceiptSchema;
export type DoctorEffectReceipt = EffectReceipt;
export const StorageFindingsPayloadSchema = DoctorFindingsPayloadV1Schema;
export type StorageFindingsPayload = DoctorFindingsPayloadV1;
