// AUTO-GENERATED by dashboard/codegen — DO NOT EDIT BY HAND.
// Source: dashboard/codegen/schemas/*.schema.json
// Regenerate: `npm run contracts:generate`  Verify: `npm run contracts:check`
// Deterministic output (stable ordering, no timestamps).

import { z } from "zod";

/**
 * Exhaustiveness helper for discriminated-union switches. A `default`
 * branch that calls `assertNever(value)` fails to compile if a union
 * member is left unhandled.
 */
export function assertNever(value: never): never {
  throw new Error(`Unhandled discriminated union member: ${JSON.stringify(value)}`);
}

export const SCHEMA_REVISION = "2026-07-23.1" as const;

export interface Authorization {
  outcome: "authorized" | "denied" | "redacted" | "unauthorized";
}

export const AuthorizationSchema: z.ZodType<Authorization> = z.object({
  outcome: z.enum(["authorized", "denied", "redacted", "unauthorized"]),
});

/** Coverage counts. Unknown denominators never render 0%/100%. */
export interface Coverage {
  denominator: number | null;
  eligible: number;
  examined: number;
  excluded: number;
  matched: number;
  omitted: number;
  unit: string;
  unknown: number;
}

export const CoverageSchema: z.ZodType<Coverage> = z.object({
  denominator: z.number().int().nullable(),
  eligible: z.number().int(),
  examined: z.number().int(),
  excluded: z.number().int(),
  matched: z.number().int(),
  omitted: z.number().int(),
  unit: z.string(),
  unknown: z.number().int(),
});

/** 16-variant discriminated union. The `unsupported_schema` variant is synthesized by the decoder for unknown kinds and is never authored here (15 authored + 1 synthesized = 16). */
export type DashboardDomainState =
  | {
    kind: "cancelled";
  }
  | {
    kind: "complete_zero_findings";
  }
  | {
    kind: "conflicting";
  }
  | {
    kind: "denied";
  }
  | {
    code: string;
    kind: "error";
    message: string;
  }
  | {
    kind: "loading";
  }
  | {
    kind: "locked";
  }
  | {
    kind: "offline";
  }
  | {
    kind: "partial";
  }
  | {
    kind: "ready";
  }
  | {
    display_label: string;
    kind: "redacted";
    locator_class: string;
    reason_code: string;
    source_id: string;
    source_kind: string;
    source_revision: string;
  }
  | {
    kind: "stale";
  }
  | {
    kind: "timed_out";
  }
  | {
    kind: "unauthorized";
  }
  | {
    kind: "unknown";
  }
  | {
    kind: "unsupported_schema";
    raw: unknown;
  };

export const DashboardDomainStateSchema: z.ZodType<DashboardDomainState> = z.custom().transform((rawInput, ctx) => {
    const variants: Record<string, z.ZodTypeAny> = {
    "cancelled": z.object({
  kind: z.literal("cancelled"),
}),
    "complete_zero_findings": z.object({
  kind: z.literal("complete_zero_findings"),
}),
    "conflicting": z.object({
  kind: z.literal("conflicting"),
}),
    "denied": z.object({
  kind: z.literal("denied"),
}),
    "error": z.object({
  code: z.string(),
  kind: z.literal("error"),
  message: z.string(),
}),
    "loading": z.object({
  kind: z.literal("loading"),
}),
    "locked": z.object({
  kind: z.literal("locked"),
}),
    "offline": z.object({
  kind: z.literal("offline"),
}),
    "partial": z.object({
  kind: z.literal("partial"),
}),
    "ready": z.object({
  kind: z.literal("ready"),
}),
    "redacted": z.object({
  display_label: z.string(),
  kind: z.literal("redacted"),
  locator_class: z.string(),
  reason_code: z.string(),
  source_id: z.string(),
  source_kind: z.string(),
  source_revision: z.string(),
}),
    "stale": z.object({
  kind: z.literal("stale"),
}),
    "timed_out": z.object({
  kind: z.literal("timed_out"),
}),
    "unauthorized": z.object({
  kind: z.literal("unauthorized"),
}),
    "unknown": z.object({
  kind: z.literal("unknown"),
}),
    };
    const disc = typeof rawInput === "object" && rawInput !== null
      ? (rawInput as Record<string, unknown>)["kind"]
      : undefined;
    if (typeof disc !== "string" || !(disc in variants)) {
      return { kind: "unsupported_schema" as const, raw: rawInput };
    }
    const parsed = variants[disc]!.safeParse(rawInput);
    if (!parsed.success) {
      for (const issue of parsed.error.issues) ctx.addIssue(issue);
      return z.NEVER;
    }
    return parsed.data;
  }) as unknown as z.ZodType<DashboardDomainState>;

/** DashboardEnvelope<TPayload>. Always carries schema_revision, exact scope, entity/graph version, valid and observation time, source watermark, authorization, coverage, freshness, domain state, legal action references, and payload. */
export interface DashboardEnvelope<TPayload> {
  authorization: Authorization;
  coverage: Coverage;
  domain_state: DashboardDomainState;
  freshness: Freshness;
  legal_actions: Array<LegalActionRef>;
  observation_time: string;
  payload: TPayload;
  schema_revision: string;
  scope: Scope;
  valid_time: string;
  versions: Versions;
  watermark: string;
}

export function DashboardEnvelopeSchema<TPayload>(
  payloadSchema: z.ZodType<TPayload>,
): z.ZodType<DashboardEnvelope<TPayload>> {
  return z.object({
    authorization: z.lazy(() => AuthorizationSchema),
    coverage: z.lazy(() => CoverageSchema),
    domain_state: z.lazy(() => DashboardDomainStateSchema),
    freshness: z.lazy(() => FreshnessSchema),
    legal_actions: z.array(z.lazy(() => LegalActionRefSchema)),
    observation_time: z.string(),
    payload: payloadSchema,
    schema_revision: z.string(),
    scope: z.lazy(() => ScopeSchema),
    valid_time: z.string(),
    versions: z.lazy(() => VersionsSchema),
    watermark: z.string(),
  }) as unknown as z.ZodType<DashboardEnvelope<TPayload>>;
}

/** Sample domain payload. Severity and evidence quality are separate token axes, never one scale. */
export interface FindingPayload {
  evidence_quality: "corroborated" | "unverified" | "verified" | "weak";
  finding_id: string;
  severity: "critical" | "high" | "info" | "low" | "medium";
  summary: string;
  title: string;
}

export const FindingPayloadSchema: z.ZodType<FindingPayload> = z.object({
  evidence_quality: z.enum(["corroborated", "unverified", "verified", "weak"]),
  finding_id: z.string(),
  severity: z.enum(["critical", "high", "info", "low", "medium"]),
  summary: z.string(),
  title: z.string(),
});

export interface Freshness {
  observed_at: string;
  stale: boolean;
  watermark: string;
}

export const FreshnessSchema: z.ZodType<Freshness> = z.object({
  observed_at: z.string(),
  stale: z.boolean(),
  watermark: z.string(),
});

/** Reference to a server-authored legal action. No command payload. */
export interface LegalActionRef {
  action_id: string;
  kind: string;
}

export const LegalActionRefSchema: z.ZodType<LegalActionRef> = z.object({
  action_id: z.string(),
  kind: z.string(),
});

/** Opaque exact scope identity. Never a title, path, or branch label. */
export interface Scope {
  key: string;
  revision: string;
}

export const ScopeSchema: z.ZodType<Scope> = z.object({
  key: z.string(),
  revision: z.string(),
});

/** Entity and graph version identity carried by every envelope. */
export interface Versions {
  entity: string;
  graph: string;
}

export const VersionsSchema: z.ZodType<Versions> = z.object({
  entity: z.string(),
  graph: z.string(),
});
