// GENERATED by dashboard/codegen from Rust schemars output. DO NOT EDIT.
// Source: the Serialize contract of dashboard/read_model.rs and every Rust
// payload DTO included by dashboard::contract_schema.
// Deterministic output (stable ordering, no timestamps).

import { z } from "zod";

/**
 * Exhaustiveness helper for discriminated-union switches. A `default`
 * branch that calls `assertNever(value)` fails to compile if a union
 * member is left unhandled.
 */
export function assertNever(value: never): never {
  throw new Error(`Unhandled discriminated union member: ${JSON.stringify(value)}`);
}

export const WIRE_SCHEMA_REVISION = 1 as const;

/** Strongly typed canonical identity: `ActorId`. */
export const ActorIdSchema = z.string();
export type ActorId = z.infer<typeof ActorIdSchema>;

/** Authoritative scope of a source binding. A mutable path, label, or host
profile cannot be represented as authority. */
export const AuthorityRefSchema = z.discriminatedUnion("kind", [z.object({
  id: z.lazy(() => ProjectIdSchema),
  kind: z.literal("project"),
}), z.object({
  id: z.string(),
  kind: z.literal("projectless_hermes"),
})]);
export type AuthorityRef = z.infer<typeof AuthorityRefSchema>;

export const AutomaticWorktreeGcV1Schema = z.discriminatedUnion("kind", [z.object({
  kind: z.literal("disabled"),
}), z.object({
  kind: z.literal("eligible_only"),
  maximum_per_run: z.number().int(),
  minimum_idle_seconds: z.number().int(),
})]);
export type AutomaticWorktreeGcV1 = z.infer<typeof AutomaticWorktreeGcV1Schema>;

/** One human-review queue: a count, or the reason there is no count.

Kept as a tagged reading rather than a bare number because these two queues
are the entire human-approval step of the automation pipeline. A queue whose
authority is unmounted must not report `0`, which reads as "checked, nothing
waiting" — the precise false zero this shape exists to prevent. */
export const AutomationPendingReviewCountV1Schema = z.discriminatedUnion("state", [z.object({
  count: z.number().int(),
  reason: z.string().nullable(),
  state: z.literal("measured"),
}), z.object({
  count: z.number().int().nullable(),
  reason: z.string(),
  state: z.literal("unreadable"),
})]);
export type AutomationPendingReviewCountV1 = z.infer<typeof AutomationPendingReviewCountV1Schema>;

export const AutomationPendingReviewV1Schema = z.object({
  fact_proposals: z.lazy(() => AutomationPendingReviewCountV1Schema),
  skills: z.lazy(() => AutomationPendingReviewCountV1Schema),
});
export type AutomationPendingReviewV1 = z.infer<typeof AutomationPendingReviewV1Schema>;

/** The scheduler reading served by all three of `status`, `pause`, and
`resume`.

The two control routes return this same payload rather than an
acknowledgement because the pause flag is the thing a caller is actually
asking about, and a bare `{"ok":true}` would leave the dashboard to assume
the new state instead of observing it. Returning the re-read means a client
never has to optimistically flip a control it has not seen take effect.

Typed here, rather than assembled with `json!`, so the shape reaches
`contract_schema.rs` and the dashboard consumes a generated contract. The
field set is deliberately identical to the `json!` literal it replaces: this
is the same wire, described, not a new one. */
export const AutomationSchedulerStatusV1Schema = z.object({
  control_path: z.string(),
  enabled: z.boolean(),
  last_session_activity: z.number().int().nullable(),
  now: z.number().int(),
  paused: z.boolean(),
  pending_fact_proposals: z.number().int().nullable(),
  pending_review: z.lazy(() => AutomationPendingReviewV1Schema),
  pending_skills: z.number().int().nullable(),
  project_config_path: z.string(),
  scheduler_tick_secs: z.number().int(),
  status: z.string(),
  tasks: z.array(z.lazy(() => AutomationTaskStatusV1Schema)),
});
export type AutomationSchedulerStatusV1 = z.infer<typeof AutomationSchedulerStatusV1Schema>;

export const AutomationTaskStatusV1Schema = z.object({
  due: z.boolean(),
  last_scheduler_run: z.unknown(),
  skip_reason: z.string().nullable(),
  task: z.string(),
});
export type AutomationTaskStatusV1 = z.infer<typeof AutomationTaskStatusV1Schema>;

export const BranchCollisionPolicyV1Schema = z.discriminatedUnion("kind", [z.object({
  kind: z.literal("append_monotonic_ordinal"),
  maximum_attempts: z.number().int(),
}), z.object({
  kind: z.literal("reject"),
})]);
export type BranchCollisionPolicyV1 = z.infer<typeof BranchCollisionPolicyV1Schema>;

export const BranchNameComponentV1Schema = z.discriminatedUnion("kind", [z.object({
  kind: z.literal("monotonic_collision_ordinal"),
}), z.object({
  kind: z.literal("repository_slug"),
}), z.object({
  bytes: z.number().int(),
  kind: z.literal("task_id_digest_prefix"),
}), z.object({
  kind: z.literal("work_class"),
})]);
export type BranchNameComponentV1 = z.infer<typeof BranchNameComponentV1Schema>;

export const BranchNameSeparatorV1Schema = z.enum(["hyphen", "slash", "underscore"]);
export type BranchNameSeparatorV1 = z.infer<typeof BranchNameSeparatorV1Schema>;

export const BranchNamingPolicyV1Schema = z.object({
  collision: z.lazy(() => BranchCollisionPolicyV1Schema),
  components: z.array(z.lazy(() => BranchNameComponentV1Schema)),
  maximum_bytes: z.number().int(),
  prefix: z.lazy(() => CanonicalGitRefPrefixSchema),
  separator: z.lazy(() => BranchNameSeparatorV1Schema),
});
export type BranchNamingPolicyV1 = z.infer<typeof BranchNamingPolicyV1Schema>;

export const BranchTopologyKindV1Schema = z.enum(["independent_branches", "local_stack", "no_branches", "unbranched"]);
export type BranchTopologyKindV1 = z.infer<typeof BranchTopologyKindV1Schema>;

export const BranchTopologyPolicyV1Schema = z.object({
  allowed: z.array(z.lazy(() => BranchTopologyKindV1Schema)),
});
export type BranchTopologyPolicyV1 = z.infer<typeof BranchTopologyPolicyV1Schema>;

export const CallChainMeasurementV1Schema = z.object({
  directed: z.boolean(),
  edge_kind: z.string(),
  found: z.boolean(),
  from_node_id: z.string(),
  hop_count: z.number().int().nullable(),
  max_depth: z.number().int(),
  selection: z.string(),
  steps: z.array(z.lazy(() => CallChainStepV1Schema)),
  to_node_id: z.string(),
});
export type CallChainMeasurementV1 = z.infer<typeof CallChainMeasurementV1Schema>;

export const CallChainStepV1Schema = z.object({
  incoming_edge: z.union([z.lazy(() => IncomingCallEdgeV1Schema), z.null()]),
  node: z.lazy(() => NodeRefV1Schema),
});
export type CallChainStepV1 = z.infer<typeof CallChainStepV1Schema>;

export const CancellationObservationSchema = z.object({
  observed_at: z.lazy(() => UtcMicrosSchema),
  stage: z.lazy(() => CancellationStageSchema),
});
export type CancellationObservation = z.infer<typeof CancellationObservationSchema>;

/** Exact stage at which cancellation or deadline state was observed. */
export const CancellationStageSchema = z.enum(["after_commit", "before_admission", "before_effect", "before_read", "during_read", "effect_in_flight", "reconciling"]);
export type CancellationStage = z.infer<typeof CancellationStageSchema>;

/** A validated full native Git ref name, such as `refs/heads/main`. */
export const CanonicalGitRefNameV1Schema = z.string();
export type CanonicalGitRefNameV1 = z.infer<typeof CanonicalGitRefNameV1Schema>;

/** A validated ref/branch prefix. Branch naming accepts a short branch prefix
(for example `tracedecay/`) while protected-ref selectors use full
`refs/.../` prefixes. */
export const CanonicalGitRefPrefixSchema = z.string();
export type CanonicalGitRefPrefix = z.infer<typeof CanonicalGitRefPrefixSchema>;

/** Strongly typed canonical identity: `CapabilityId`. */
export const CapabilityIdSchema = z.string();
export type CapabilityId = z.infer<typeof CapabilityIdSchema>;

export const CodeIndexFreshnessPayloadV1Schema = z.object({
  note: z.string(),
  required_source: z.string(),
  worktrees: z.array(z.lazy(() => CodeIndexWorktreeFreshnessV1Schema)),
});
export type CodeIndexFreshnessPayloadV1 = z.infer<typeof CodeIndexFreshnessPayloadV1Schema>;

/** Freshness/generation state for one mounted worktree. Unpopulated until the
scheduler-registry read port is wired into the dashboard state. */
export const CodeIndexWorktreeFreshnessV1Schema = z.object({
  hook_hint_count: z.number().int().nullable(),
  last_reconcile_micros: z.number().int().nullable(),
  latest_generation_id: z.string().nullable(),
  staleness_state: z.string().nullable(),
  worktree_root: z.string(),
});
export type CodeIndexWorktreeFreshnessV1 = z.infer<typeof CodeIndexWorktreeFreshnessV1Schema>;

export const ConfigurationProtectedApplySurfaceRequestSchema = z.object({
  expected_base_revision_id: z.string(),
  idempotency_key: z.string(),
  operation_digest: z.lazy(() => ManifestDigestSchema),
  plan_id: z.string(),
});
export type ConfigurationProtectedApplySurfaceRequest = z.infer<typeof ConfigurationProtectedApplySurfaceRequestSchema>;

export const ConfigurationProtectedPreviewSurfaceRequestSchema = z.object({
  change: z.lazy(() => ProtectedChangeSchema),
  expected_revision: z.string(),
});
export type ConfigurationProtectedPreviewSurfaceRequest = z.infer<typeof ConfigurationProtectedPreviewSurfaceRequestSchema>;

export const CoveringTestV1Schema = z.object({
  file_path: z.string(),
  id: z.string(),
  name: z.string(),
  qualification: z.string(),
  start_line: z.number().int(),
});
export type CoveringTestV1 = z.infer<typeof CoveringTestV1Schema>;

export const CrossMergeModeV1Schema = z.enum(["cherry_pick_exact_commits", "disabled", "fast_forward_only", "manual_receipt_only", "merge_commit"]);
export type CrossMergeModeV1 = z.infer<typeof CrossMergeModeV1Schema>;

export const CrossMergePolicyV1Schema = z.object({
  allow_cross_repository: z.boolean(),
  allowed_modes: z.array(z.lazy(() => CrossMergeModeV1Schema)),
  default_mode: z.lazy(() => CrossMergeModeV1Schema),
});
export type CrossMergePolicyV1 = z.infer<typeof CrossMergePolicyV1Schema>;

/** Authorization outcome for the read. On the loopback single-user dashboard a
legal local read is [`Self::Authorized`]; the other variants are retained so
the contract can express `unauthorized` (identity absent/expired), `denied`
(known identity lacks permission), and `redacted` reads without a schema
change. */
export const DashboardAuthorizationV1Schema = z.discriminatedUnion("outcome", [z.object({
  outcome: z.literal("authorized"),
}), z.object({
  outcome: z.literal("denied"),
}), z.object({
  outcome: z.literal("redacted"),
}), z.object({
  outcome: z.literal("unauthorized"),
})]);
export type DashboardAuthorizationV1 = z.infer<typeof DashboardAuthorizationV1Schema>;

/** Coverage completeness axis. `Unsupported` distinguishes "the source that
would establish coverage is not wired" from `Unknown` ("coverage could not
be determined"). */
export const DashboardCoverageCompletenessV1Schema = z.enum(["complete", "partial", "unknown", "unsupported"]);
export type DashboardCoverageCompletenessV1 = z.infer<typeof DashboardCoverageCompletenessV1Schema>;

/** Coverage statement. Counts are optional; an unknown denominator is `None`,
never a fabricated `0`/`100%`. The completeness axis is authoritative — the
frontend never derives `complete` from a `matched == eligible` coincidence. */
export const DashboardCoverageV1Schema = z.object({
  completeness: z.lazy(() => DashboardCoverageCompletenessV1Schema),
  denominator: z.number().int().nullable(),
  eligible: z.number().int().nullable(),
  examined: z.number().int().nullable(),
  excluded: z.number().int().nullable(),
  matched: z.number().int().nullable(),
  omission_reasons: z.array(z.string()),
  omitted: z.number().int().nullable(),
  unit: z.string().nullable(),
  unknown: z.number().int().nullable(),
});
export type DashboardCoverageV1 = z.infer<typeof DashboardCoverageV1Schema>;

/** A typed description of what an owner-supplied remediation operation would do.

This is a *description*, not an effect. It never carries argv, a path, or an
inline action, and resolving it performs no work. */
export const DashboardDoctorRemediationDescriptorV1Schema = z.object({
  action_confirmation: z.lazy(() => DoctorConfirmationRequirementV1Schema),
  operation: z.lazy(() => DoctorOwningOperationRefV1Schema),
  preview_available: z.boolean(),
  summary: z.string(),
  surface: z.lazy(() => DoctorOwningSurfaceV1Schema),
  target: z.union([z.lazy(() => DoctorRemediationTargetV1Schema), z.null()]),
});
export type DashboardDoctorRemediationDescriptorV1 = z.infer<typeof DashboardDoctorRemediationDescriptorV1Schema>;

/** The normative dashboard domain-state union.

The first sixteen variants are the plan's exact `DashboardDomainState`
discriminated union. [`Self::Unsupported`] is the PR14 backend-gap binding
state: the read model's HTTP surface exists, but its live producer/source is
not yet wired server-side. It is never healthy or empty — the frontend
renders a distinct "not yet available" state — and it is deliberately
separate from [`Self::UnsupportedSchema`] (an undecodable schema/variant). */
export const DashboardDomainStateV1Schema = z.union([z.enum(["cancelled", "complete_zero_findings", "conflicting", "denied", "error", "loading", "locked", "offline", "partial", "ready", "redacted", "stale", "timed_out", "unauthorized", "unknown", "unsupported_schema"]), z.literal("unsupported")]).catch("unsupported_schema");
export type DashboardDomainStateV1 = z.infer<typeof DashboardDomainStateV1Schema>;

/** The normative read-model envelope. Every V2 read-model route returns exactly
this shape; only `payload` varies by route. */
export interface DashboardEnvelopeV1<TPayload> {
  authorization: DashboardAuthorizationV1;
  coverage: DashboardCoverageV1;
  domain_state: DashboardDomainStateV1;
  freshness: DashboardFreshnessV1;
  legal_actions: Array<DashboardLegalActionRefV1>;
  payload: TPayload;
  schema_revision: 1;
  scope: DashboardScopeV1;
  source_watermark: DashboardWatermarkV1 | null;
  time: DashboardTimeV1;
  version: DashboardVersionV1;
}

export function DashboardEnvelopeV1Schema<TPayload>(
  payloadSchema: z.ZodType<TPayload>,
): z.ZodType<DashboardEnvelopeV1<TPayload>> {
  return z.object({
    authorization: z.lazy(() => DashboardAuthorizationV1Schema),
    coverage: z.lazy(() => DashboardCoverageV1Schema),
    domain_state: z.lazy(() => DashboardDomainStateV1Schema),
    freshness: z.lazy(() => DashboardFreshnessV1Schema),
    legal_actions: z.array(z.lazy(() => DashboardLegalActionRefV1Schema)),
    payload: payloadSchema,
    schema_revision: z.literal(1),
    scope: z.lazy(() => DashboardScopeV1Schema),
    source_watermark: z.union([z.lazy(() => DashboardWatermarkV1Schema), z.null()]),
    time: z.lazy(() => DashboardTimeV1Schema),
    version: z.lazy(() => DashboardVersionV1Schema),
  }) as unknown as z.ZodType<DashboardEnvelopeV1<TPayload>>;
}

/** Freshness of the observed state relative to its live source watermark.
`Absent` (no source produced anything) and `Unsupported` (no source wired)
are distinct from `Stale` (behind the watermark) and `Unknown`. */
export const DashboardFreshnessStateV1Schema = z.enum(["absent", "fresh", "stale", "unknown", "unsupported"]);
export type DashboardFreshnessStateV1 = z.infer<typeof DashboardFreshnessStateV1Schema>;

/** Freshness statement plus the optional observation stamp/watermark it was
judged against. */
export const DashboardFreshnessV1Schema = z.object({
  observed_at_micros: z.number().int().nullable(),
  state: z.lazy(() => DashboardFreshnessStateV1Schema),
  watermark: z.string().nullable(),
});
export type DashboardFreshnessV1 = z.infer<typeof DashboardFreshnessV1Schema>;

/** The legal-action reference kinds a read model may attach. This mirrors the
plan's action vocabulary reduced to the read surface: the dashboard only
renders these references and submits them through the owning application
operation; it never constructs an effect inline. */
export const DashboardLegalActionKindV1Schema = z.enum(["expand_evidence", "inspect", "refresh", "request_apply", "request_cancel", "request_dry_run"]);
export type DashboardLegalActionKindV1 = z.infer<typeof DashboardLegalActionKindV1Schema>;

/** A reference to one owner-supplied legal action. `operation` names the owning
application operation; the dashboard never embeds argv, a path, or an inline
effect. */
export const DashboardLegalActionRefV1Schema = z.object({
  kind: z.lazy(() => DashboardLegalActionKindV1Schema),
  operation: z.string(),
});
export type DashboardLegalActionRefV1 = z.infer<typeof DashboardLegalActionRefV1Schema>;

/** Exact scope the envelope was resolved for. A deep link/query never falls
back to a title, path, or latest version to recover scope. */
export const DashboardScopeV1Schema = z.object({
  project_id: z.string().nullable(),
  storage_mode: z.string(),
  store_root: z.string(),
});
export type DashboardScopeV1 = z.infer<typeof DashboardScopeV1Schema>;

/** Valid time and observation time, kept separate. `observation_time` is when
the daemon observed the state; `valid_time` is when the state was true in the
modelled domain (absent when a read model has no distinct valid time). */
export const DashboardTimeV1Schema = z.object({
  observation_time_micros: z.number().int(),
  valid_time_micros: z.number().int().nullable(),
});
export type DashboardTimeV1 = z.infer<typeof DashboardTimeV1Schema>;

/** Entity and graph version identities pinned by the envelope. Both are
optional: a read model with no versioned graph state leaves them absent
rather than inventing `0`/`latest`. */
export const DashboardVersionV1Schema = z.object({
  entity_version: z.string().nullable(),
  graph_version: z.string().nullable(),
});
export type DashboardVersionV1 = z.infer<typeof DashboardVersionV1Schema>;

/** Opaque monotone source watermark. The frontend compares watermarks for
staleness but never parses their internal structure. */
export const DashboardWatermarkV1Schema = z.object({
  source: z.string(),
  watermark: z.string(),
});
export type DashboardWatermarkV1 = z.infer<typeof DashboardWatermarkV1Schema>;

/** One immutable deadline supplied by the caller or upstream admission layer. */
export const DeadlineSchema = z.object({
  expires_at: z.lazy(() => UtcMicrosSchema),
});
export type Deadline = z.infer<typeof DeadlineSchema>;

/** Whether an owning operation requires an explicit human confirmation before it
may perform its admitted mutating effect. */
export const DoctorConfirmationRequirementV1Schema = z.union([z.literal("required"), z.literal("not_required")]);
export type DoctorConfirmationRequirementV1 = z.infer<typeof DoctorConfirmationRequirementV1Schema>;

/** Whether Doctor observed all of a family's evidence sources. */
export const DoctorCoverageCompletenessV1Schema = z.union([z.literal("complete"), z.literal("partial"), z.literal("unknown")]);
export type DoctorCoverageCompletenessV1 = z.infer<typeof DoctorCoverageCompletenessV1Schema>;

/** A bounded, human-readable coverage statement plus its completeness. */
export const DoctorCoverageStatementV1Schema = z.object({
  completeness: z.lazy(() => DoctorCoverageCompletenessV1Schema),
  statement: z.string(),
});
export type DoctorCoverageStatementV1 = z.infer<typeof DoctorCoverageStatementV1Schema>;

/** Durable, non-disclosing reference to one owning-authority evidence
record (for example a `FeedbackFindingId`, configuration revision, or
runtime read coverage anchor). Doctor stores the reference only; the
owning authority remains the single source of the record. */
export const DoctorEvidenceReferenceV1Schema = z.string();
export type DoctorEvidenceReferenceV1 = z.infer<typeof DoctorEvidenceReferenceV1Schema>;

/** A typed reference to one piece of evidence Doctor composed into a finding.

The `family` records which audited input surface produced the evidence, so
a finding may cross-cite evidence from more than one family without losing
provenance. */
export const DoctorEvidenceRefV1Schema = z.object({
  family: z.lazy(() => DoctorFindingFamilyV1Schema),
  reference: z.lazy(() => DoctorEvidenceReferenceV1Schema),
});
export type DoctorEvidenceRefV1 = z.infer<typeof DoctorEvidenceRefV1Schema>;

/** Exact Doctor evidence states from Plan 09 §PR14.

Missing, partial, or unknown truth never becomes healthy or clean. Only
[`DoctorEvidenceStateV1::HealthyCompleteCoverage`] asserts a healthy result,
and only when its finding carries complete coverage (see
[`DoctorFindingV1::new`]). */
export const DoctorEvidenceStateV1Schema = z.union([z.literal("unsupported"), z.literal("absent"), z.literal("stale"), z.literal("degraded"), z.literal("partial"), z.literal("unknown"), z.literal("denied"), z.literal("healthy_complete_coverage")]);
export type DoctorEvidenceStateV1 = z.infer<typeof DoctorEvidenceStateV1Schema>;

/** Whether a family was consulted from an observed source or is unavailable. */
export const DoctorFamilyConsultationV1Schema = z.discriminatedUnion("status", [z.object({
  status: z.literal("consulted"),
}), z.object({
  reason: z.lazy(() => DoctorFamilyUnavailableReasonV1Schema),
  status: z.literal("unavailable"),
})]);
export type DoctorFamilyConsultationV1 = z.infer<typeof DoctorFamilyConsultationV1Schema>;

/** The consultation status of one finding family within a report. */
export const DoctorFamilyCoverageV1Schema = z.object({
  consultation: z.lazy(() => DoctorFamilyConsultationV1Schema),
  family: z.lazy(() => DoctorFindingFamilyV1Schema),
});
export type DoctorFamilyCoverageV1 = z.infer<typeof DoctorFamilyCoverageV1Schema>;

/** Why a finding family could not be consulted from an observed source. */
export const DoctorFamilyUnavailableReasonV1Schema = z.union([z.literal("unwired"), z.literal("unsupported"), z.literal("absent"), z.literal("denied"), z.literal("unknown")]);
export type DoctorFamilyUnavailableReasonV1 = z.infer<typeof DoctorFamilyUnavailableReasonV1Schema>;

/** Stable Doctor finding families.

The initial list is derived from Plan 14's observable classes (advisory
findings from Brain/Explorer/Loom/Code/Observatory) and the legacy
`core_doctor` checks (graph quick-check, temporal/migration health,
configuration compatibility drift, semantic runtime, session ingest).
Each family maps to one audited typed input surface. The set is kept small
and honest; new families are added through a future versioned enum rather
than by widening the meaning of an existing variant. */
export const DoctorFindingFamilyV1Schema = z.union([z.literal("advisory"), z.literal("configuration"), z.literal("storage_runtime"), z.literal("storage"), z.literal("language_server"), z.literal("semantic_index"), z.literal("observability")]);
export type DoctorFindingFamilyV1 = z.infer<typeof DoctorFindingFamilyV1Schema>;

/** The canonical Doctor report projection. `entries` retains the storage
subclass attached by the kernel; remediation descriptors are emitted only
after the kernel registry resolves the finding's owner-supplied reference. */
export const DoctorFindingsPayloadV1Schema = z.object({
  entries: z.array(z.lazy(() => DoctorReportEntryV1Schema)),
  family_filter: z.union([z.lazy(() => DoctorFindingFamilyV1Schema), z.null()]),
  known_families: z.array(z.lazy(() => DoctorFindingFamilyV1Schema)),
  note: z.string(),
  remediations: z.array(z.lazy(() => DashboardDoctorRemediationDescriptorV1Schema)),
  report_coverage: z.union([z.lazy(() => DoctorReportCoverageV1Schema), z.null()]),
});
export type DoctorFindingsPayloadV1 = z.infer<typeof DoctorFindingsPayloadV1Schema>;

/** One canonical Doctor finding.

A finding pins its diagnosis `family`, its evidence `state`, the typed
evidence it composed, a coverage statement, and an optional reference to an
owner-supplied remediation. Construction enforces the Plan 09 §PR14
invariants that keep unknown/partial evidence from collapsing into a healthy
or clean result. */
export const DoctorFindingV1Schema = z.object({
  coverage: z.lazy(() => DoctorCoverageStatementV1Schema),
  evidence: z.array(z.lazy(() => DoctorEvidenceRefV1Schema)),
  family: z.lazy(() => DoctorFindingFamilyV1Schema),
  remediation: z.union([z.lazy(() => DoctorRemediationRefV1Schema), z.null()]),
  state: z.lazy(() => DoctorEvidenceStateV1Schema),
});
export type DoctorFindingV1 = z.infer<typeof DoctorFindingV1Schema>;

/** Reference to the owning application operation that would perform a
remediation (its capability or use-case identity). Doctor names the
operation; it never embeds argv, a path, or an inline effect. */
export const DoctorOwningOperationRefV1Schema = z.string();
export type DoctorOwningOperationRefV1 = z.infer<typeof DoctorOwningOperationRefV1Schema>;

/** The application surface that owns dispatch of a remediation operation.

The kernel names the owner so a transport can route confirmation and dispatch
to the correct surface; it never dispatches itself. */
export const DoctorOwningSurfaceV1Schema = z.union([z.literal("configuration_control_plane"), z.literal("storage_runtime"), z.literal("daemon_runtime"), z.literal("host_integration"), z.literal("semantic_index_runtime"), z.literal("feedback_read")]);
export type DoctorOwningSurfaceV1 = z.infer<typeof DoctorOwningSurfaceV1Schema>;

export const DoctorRemediationApplyRequestV1Schema = z.object({
  confirmed: z.boolean(),
  idempotency_key: z.string(),
  operation: z.lazy(() => DoctorOwningOperationRefV1Schema),
  preview_id: z.string().nullable(),
  target: z.lazy(() => DoctorRemediationTargetV1Schema),
});
export type DoctorRemediationApplyRequestV1 = z.infer<typeof DoctorRemediationApplyRequestV1Schema>;

export const DoctorRemediationDispatchErrorV1Schema = z.enum(["confirmation_required", "denied", "invalid_reference", "owner_unavailable", "unsupported"]);
export type DoctorRemediationDispatchErrorV1 = z.infer<typeof DoctorRemediationDispatchErrorV1Schema>;

/** Preview-versus-action distinction for an owner-supplied remediation.

Doctor never repairs; it references an owning application operation. A
preview pins expected state without mutating; an action is the owning
operation's admitted effect. Both are invoked through the owning operation,
never inline. */
export const DoctorRemediationKindV1Schema = z.union([z.literal("preview"), z.literal("action")]);
export type DoctorRemediationKindV1 = z.infer<typeof DoctorRemediationKindV1Schema>;

export const DoctorRemediationOperationPhaseV1Schema = z.enum(["cancelled", "completed", "effect_unknown", "failed", "partial", "previewed", "running", "timed_out"]);
export type DoctorRemediationOperationPhaseV1 = z.infer<typeof DoctorRemediationOperationPhaseV1Schema>;

export const DoctorRemediationOperationV1Schema = z.object({
  effect_receipt: z.union([z.lazy(() => EffectReceiptSchema), z.null()]),
  execution: z.union([z.lazy(() => OperationReceiptSchema), z.null()]),
  operation_id: z.lazy(() => OperationIdSchema),
  owner_effect_receipt: z.union([z.lazy(() => EffectReceiptSchema), z.null()]).optional(),
  owner_result_digest: z.union([z.lazy(() => ManifestDigestSchema), z.null()]).optional(),
  owning_operation: z.lazy(() => DoctorOwningOperationRefV1Schema),
  phase: z.lazy(() => DoctorRemediationOperationPhaseV1Schema),
  preview_id: z.string().nullable(),
});
export type DoctorRemediationOperationV1 = z.infer<typeof DoctorRemediationOperationV1Schema>;

export const DoctorRemediationPayloadV1Schema = z.discriminatedUnion("status", [z.object({
  operation: z.lazy(() => DoctorRemediationOperationV1Schema),
  status: z.literal("operation"),
}), z.object({
  reason: z.lazy(() => DoctorRemediationDispatchErrorV1Schema),
  status: z.literal("unavailable"),
})]);
export type DoctorRemediationPayloadV1 = z.infer<typeof DoctorRemediationPayloadV1Schema>;

export const DoctorRemediationPreviewRequestV1Schema = z.object({
  operation: z.lazy(() => DoctorOwningOperationRefV1Schema),
  target: z.lazy(() => DoctorRemediationTargetV1Schema),
});
export type DoctorRemediationPreviewRequestV1 = z.infer<typeof DoctorRemediationPreviewRequestV1Schema>;

/** A reference to an owner-supplied remediation.

Doctor never repairs directly; it names the owning application operation
and whether a preview or action is offered. The caller invokes that owning
operation through its normal admitted path. */
export const DoctorRemediationRefV1Schema = z.object({
  kind: z.lazy(() => DoctorRemediationKindV1Schema),
  owning_operation: z.lazy(() => DoctorOwningOperationRefV1Schema),
});
export type DoctorRemediationRefV1 = z.infer<typeof DoctorRemediationRefV1Schema>;

export const DoctorRemediationTargetV1Schema = z.discriminatedUnion("owner_operation", [z.object({
  owner_operation: z.literal("code_index_remount"),
}), z.object({
  owner_operation: z.literal("configuration_pin_authority"),
}), z.object({
  owner_operation: z.literal("configuration_protected_apply"),
  target: z.lazy(() => ConfigurationProtectedApplySurfaceRequestSchema),
}), z.object({
  owner_operation: z.literal("configuration_protected_preview"),
  target: z.lazy(() => ConfigurationProtectedPreviewSurfaceRequestSchema),
}), z.object({
  owner_operation: z.literal("host_repair_integration"),
  target: z.object({
  components: z.array(z.lazy(() => HostBundleComponentV1Schema)),
  host: z.lazy(() => HostKindV1Schema),
}),
}), z.object({
  owner_operation: z.literal("runtime_recover_daemon"),
}), z.object({
  owner_operation: z.literal("storage_branch_gc"),
}), z.object({
  owner_operation: z.literal("storage_collect_orphan_store"),
}), z.object({
  owner_operation: z.literal("storage_quarantine_and_collect_debris"),
}), z.object({
  owner_operation: z.literal("storage_retention_collect"),
})]);
export type DoctorRemediationTargetV1 = z.infer<typeof DoctorRemediationTargetV1Schema>;

/** The report-wide coverage statement: which families were consulted versus
unavailable, plus an overall completeness and a bounded human statement. */
export const DoctorReportCoverageV1Schema = z.object({
  completeness: z.lazy(() => DoctorCoverageCompletenessV1Schema),
  families: z.array(z.lazy(() => DoctorFamilyCoverageV1Schema)),
  statement: z.lazy(() => DoctorCoverageStatementV1Schema),
});
export type DoctorReportCoverageV1 = z.infer<typeof DoctorReportCoverageV1Schema>;

/** One entry in a Doctor report: a canonical finding plus, for the storage
family, its typed subclass. The subclass is present only for storage findings
(a non-storage entry never carries one). */
export const DoctorReportEntryV1Schema = z.object({
  finding: z.lazy(() => DoctorFindingV1Schema),
  storage_kind: z.union([z.lazy(() => DoctorStorageFindingKindV1Schema), z.null()]),
});
export type DoctorReportEntryV1 = z.infer<typeof DoctorReportEntryV1Schema>;

/** Typed subclasses of the [`DoctorFindingFamilyV1::Storage`] finding family
(Plan 38 §7).

The storage family never reports a silent overage: each subclass names one
observable retention/size condition Doctor surfaces over the Plan 26 size
observability read models. The set is closed and grows only through a future
versioned enum, never by widening an existing subclass. */
export const DoctorStorageFindingKindV1Schema = z.union([z.literal("over_budget_store"), z.literal("orphan_store"), z.literal("stale_branch_dbs"), z.literal("incident_debris_present"), z.literal("retention_backlog")]);
export type DoctorStorageFindingKindV1 = z.infer<typeof DoctorStorageFindingKindV1Schema>;

/** The stable effect classification of one application operation.

Git index writes remain separate classes so policy cannot accidentally
substitute one index mutation for another. */
export const EffectClassSchema = z.enum(["administrative", "configuration_write", "git_index_commit", "git_index_stage", "git_index_unstage", "preview", "read", "source_edit"]);
export type EffectClass = z.infer<typeof EffectClassSchema>;

/** Durable effect proof. It records identities and receipts, never credentials
or arbitrary command text. */
export const EffectReceiptSchema = z.object({
  actor: z.lazy(() => ActorIdSchema),
  catalog_digest: z.lazy(() => ManifestDigestSchema),
  committed_state: z.union([z.lazy(() => ManifestDigestSchema), z.null()]),
  configuration_digest: z.lazy(() => ManifestDigestSchema),
  effect_class: z.lazy(() => EffectClassSchema),
  expected_state: z.lazy(() => ManifestDigestSchema),
  external_proof: z.union([z.lazy(() => RetrievalAnchorIdSchema), z.null()]),
  idempotency_key: z.string(),
  input_digest: z.lazy(() => ManifestDigestSchema),
  operation: z.lazy(() => UseCaseIdSchema),
  outcome: z.lazy(() => EffectTerminationSchema),
  policy_digest: z.lazy(() => ManifestDigestSchema),
  privacy_digest: z.lazy(() => ManifestDigestSchema),
  request_id: z.string(),
  scope: z.lazy(() => ResolvedScopeSchema),
});
export type EffectReceipt = z.infer<typeof EffectReceiptSchema>;

/** Durable effect receipt terminal state. */
export const EffectTerminationSchema = z.enum(["cancelled", "completed", "effect_unknown", "failed", "partial", "timed_out"]);
export type EffectTermination = z.infer<typeof EffectTerminationSchema>;

export const ExplorerFinalityV1Schema = z.enum(["cancelled", "complete", "error", "partial", "pending"]);
export type ExplorerFinalityV1 = z.infer<typeof ExplorerFinalityV1Schema>;

export const ExplorerQueryRequestV1Schema = z.object({
  limit: z.number().int(),
  offset: z.number().int(),
  query: z.string(),
});
export type ExplorerQueryRequestV1 = z.infer<typeof ExplorerQueryRequestV1Schema>;

export const ExplorerQueryRunV1Schema = z.object({
  completed_at_micros: z.number().int().nullable(),
  elapsed_micros: z.number().int(),
  explanation: z.string(),
  finality: z.lazy(() => ExplorerFinalityV1Schema),
  merge_revision: z.string(),
  ordering_policy: z.string(),
  plan_revision: z.string(),
  request: z.lazy(() => ExplorerQueryRequestV1Schema),
  request_revision: z.string(),
  required_source_ids: z.array(z.lazy(() => ExplorerSourceIdV1Schema)),
  run_id: z.string(),
  sources: z.array(z.lazy(() => ExplorerSourceProgressV1Schema)),
  state: z.lazy(() => ExplorerRunStateV1Schema),
  submitted_at_micros: z.number().int(),
});
export type ExplorerQueryRunV1 = z.infer<typeof ExplorerQueryRunV1Schema>;

export const ExplorerResultPageV1Schema = z.object({
  limit: z.number().int(),
  metadata: z.unknown(),
  next_offset: z.number().int().nullable(),
  offset: z.number().int(),
  rows: z.array(z.unknown()),
  total: z.number().int().nullable(),
});
export type ExplorerResultPageV1 = z.infer<typeof ExplorerResultPageV1Schema>;

export const ExplorerRunStateV1Schema = z.enum(["cancelled", "completed", "error", "partial", "pending"]);
export type ExplorerRunStateV1 = z.infer<typeof ExplorerRunStateV1Schema>;

export const ExplorerSourceIdV1Schema = z.enum(["code_graph", "knowledge", "sessions"]);
export type ExplorerSourceIdV1 = z.infer<typeof ExplorerSourceIdV1Schema>;

export const ExplorerSourceOutcomeV1Schema = z.enum(["cancelled", "error", "pending", "ready", "unavailable"]);
export type ExplorerSourceOutcomeV1 = z.infer<typeof ExplorerSourceOutcomeV1Schema>;

export const ExplorerSourcePhaseV1Schema = z.enum(["cancelled", "completed", "queued", "reading"]);
export type ExplorerSourcePhaseV1 = z.infer<typeof ExplorerSourcePhaseV1Schema>;

export const ExplorerSourceProgressV1Schema = z.object({
  completed_units: z.number().int().nullable(),
  coverage: z.lazy(() => DashboardCoverageV1Schema),
  error_code: z.string().nullable(),
  freshness: z.string(),
  message: z.string().nullable(),
  outcome: z.lazy(() => ExplorerSourceOutcomeV1Schema),
  page: z.union([z.lazy(() => ExplorerResultPageV1Schema), z.null()]),
  phase: z.lazy(() => ExplorerSourcePhaseV1Schema),
  source_id: z.lazy(() => ExplorerSourceIdV1Schema),
  source_label: z.string(),
  total_units: z.number().int().nullable(),
  watermark: z.string().nullable(),
});
export type ExplorerSourceProgressV1 = z.infer<typeof ExplorerSourceProgressV1Schema>;

export const FactArmCoverageV1Schema = z.object({
  completeness: z.string(),
  limit: z.number().int(),
  returned: z.number().int(),
  truncated: z.boolean(),
});
export type FactArmCoverageV1 = z.infer<typeof FactArmCoverageV1Schema>;

export const FactMatchArmV1Schema = z.object({
  collision_warning: z.string(),
  coverage: z.lazy(() => FactArmCoverageV1Schema),
  facts: z.array(z.unknown()),
  match_basis: z.string(),
  strength: z.string(),
});
export type FactMatchArmV1 = z.infer<typeof FactMatchArmV1Schema>;

export const FactMatchesMeasurementV1Schema = z.object({
  arms: z.array(z.lazy(() => FactMatchArmV1Schema)),
  caption: z.string(),
  entity_matches: z.array(z.unknown()),
  granularity: z.string(),
  identity_semantics: z.string(),
  name: z.string(),
  node: z.lazy(() => NodeRefV1Schema),
  normalized_name: z.string(),
  payload_fts_matches: z.array(z.unknown()),
  same_name_collision_possible: z.boolean(),
});
export type FactMatchesMeasurementV1 = z.infer<typeof FactMatchesMeasurementV1Schema>;

export const GitHubStackedPullRequestPolicyV1Schema = z.enum(["disabled", "probe_private_preview"]);
export type GitHubStackedPullRequestPolicyV1 = z.infer<typeof GitHubStackedPullRequestPolicyV1Schema>;

export const HistoryRewritePolicyV1Schema = z.literal("forbid_force_and_rebase");
export type HistoryRewritePolicyV1 = z.infer<typeof HistoryRewritePolicyV1Schema>;

export const HostBundleComponentV1Schema = z.enum(["agent", "context_mcp", "core", "operator_mcp"]);
export type HostBundleComponentV1 = z.infer<typeof HostBundleComponentV1Schema>;

/** Canonical stock host surfaces shared by catalog, packaging, delivery, and
conformance consumers. A host surface is not itself evidence that the PR6
observation-capture capability is fixture-backed. */
export const HostKindV1Schema = z.enum(["claude_code", "cline", "cline_family", "codex", "cursor_cloud", "cursor_desktop", "hermes", "kilo", "kimi_code", "kiro", "open_code", "roo_code"]);
export type HostKindV1 = z.infer<typeof HostKindV1Schema>;

export const IncomingCallEdgeV1Schema = z.object({
  kind: z.string(),
  line: z.number().int().nullable(),
  source: z.string(),
  target: z.string(),
});
export type IncomingCallEdgeV1 = z.infer<typeof IncomingCallEdgeV1Schema>;

/** Strongly typed algorithm-tagged integrity digest: `LocatorDigest`. */
export const LocatorDigestSchema = z.string();
export type LocatorDigest = z.infer<typeof LocatorDigestSchema>;

export const LoomFileSessionProjectionV1Schema = z.object({
  authority: z.string(),
  eligible_sessions: z.number().int(),
  granularity: z.string(),
  matched_sessions: z.number().int(),
  providers: z.array(z.string()),
  sessions: z.array(z.unknown()),
});
export type LoomFileSessionProjectionV1 = z.infer<typeof LoomFileSessionProjectionV1Schema>;

/** Strongly typed algorithm-tagged integrity digest: `ManifestDigest`. */
export const ManifestDigestSchema = z.string();
export type ManifestDigest = z.infer<typeof ManifestDigestSchema>;

export const NodeRefV1Schema = z.object({
  file_path: z.string(),
  id: z.string(),
  kind: z.string(),
  name: z.string(),
  qualified_name: z.string(),
  start_line: z.number().int(),
});
export type NodeRefV1 = z.infer<typeof NodeRefV1Schema>;

export const NodeSessionsMeasurementV1Schema = z.object({
  available_granularities: z.array(z.string()),
  linkage: z.lazy(() => LoomFileSessionProjectionV1Schema),
  node: z.lazy(() => NodeRefV1Schema),
  symbol_granularity_available: z.boolean(),
  symbol_granularity_reason: z.string(),
});
export type NodeSessionsMeasurementV1 = z.infer<typeof NodeSessionsMeasurementV1Schema>;

/** Bounded work accounting supplied by an owning port or transaction. */
export const OperationBudgetUsageSchema = z.object({
  bytes_consumed: z.number().int(),
  elapsed_micros: z.number().int(),
  units_consumed: z.number().int(),
});
export type OperationBudgetUsage = z.infer<typeof OperationBudgetUsageSchema>;

/** Stable operation identity. The originating authorized request owns the
identity; paths, labels, and client-selected payloads never participate. */
export const OperationIdSchema = z.string();
export type OperationId = z.infer<typeof OperationIdSchema>;

/** Canonical operation evidence. An admitted failure remains represented here
rather than being replaced by a transport exception. */
export const OperationReceiptSchema = z.object({
  budget: z.lazy(() => OperationBudgetUsageSchema),
  cancellation: z.union([z.lazy(() => CancellationObservationSchema), z.null()]),
  effective_deadline: z.lazy(() => DeadlineSchema),
  ended_at: z.lazy(() => UtcMicrosSchema),
  started_at: z.lazy(() => UtcMicrosSchema),
  termination: z.lazy(() => OperationTerminationSchema),
});
export type OperationReceipt = z.infer<typeof OperationReceiptSchema>;

/** Terminal state after an operation has been admitted. */
export const OperationTerminationSchema = z.enum(["cancelled", "completed", "effect_unknown", "failed", "partial", "timed_out"]);
export type OperationTermination = z.infer<typeof OperationTerminationSchema>;

/** Strongly typed canonical identity: `ProjectId`. */
export const ProjectIdSchema = z.string();
export type ProjectId = z.infer<typeof ProjectIdSchema>;

/** The protected configuration operation set. Ordinary scalar mutations are
intentionally absent; they activate directly after validation. */
export const ProtectedChangeSchema = z.discriminatedUnion("kind", [z.object({
  kind: z.literal("bind_source"),
  value: z.lazy(() => ScopeSourceBindingSchema),
}), z.object({
  kind: z.literal("rebind_source"),
  value: z.lazy(() => ScopeSourceBindingSchema),
}), z.object({
  kind: z.literal("remove_access_rule"),
  value: z.object({
  rule_id: z.string(),
}),
}), z.object({
  kind: z.literal("replace_work_topology_policy"),
  value: z.lazy(() => WorkTopologyPolicyV1Schema),
}), z.object({
  kind: z.literal("unbind_source"),
  value: z.object({
  binding_id: z.string(),
}),
}), z.object({
  kind: z.literal("upsert_access_rule"),
  value: z.lazy(() => ScopeAccessRuleSchema),
})]);
export type ProtectedChange = z.infer<typeof ProtectedChangeSchema>;

export const ProtectedRefDispositionV1Schema = z.enum(["reject", "require_human_approval_and_independent_review"]);
export type ProtectedRefDispositionV1 = z.infer<typeof ProtectedRefDispositionV1Schema>;

export const ProtectedRefRuleV1Schema = z.object({
  disposition: z.lazy(() => ProtectedRefDispositionV1Schema),
  selector: z.lazy(() => ProtectedRefSelectorV1Schema),
});
export type ProtectedRefRuleV1 = z.infer<typeof ProtectedRefRuleV1Schema>;

export const ProtectedRefSelectorV1Schema = z.discriminatedUnion("kind", [z.object({
  kind: z.literal("exact"),
  value: z.lazy(() => CanonicalGitRefNameV1Schema),
}), z.object({
  kind: z.literal("native_default_branch"),
}), z.object({
  kind: z.literal("prefix"),
  value: z.lazy(() => CanonicalGitRefPrefixSchema),
})]);
export type ProtectedRefSelectorV1 = z.infer<typeof ProtectedRefSelectorV1Schema>;

/** Strongly typed canonical identity: `RefId`. */
export const RefIdSchema = z.string();
export type RefId = z.infer<typeof RefIdSchema>;

/** Strongly typed canonical identity: `RepositoryId`. */
export const RepositoryIdSchema = z.string();
export type RepositoryId = z.infer<typeof RepositoryIdSchema>;

export const RepositoryPlacementScopeV1Schema = z.discriminatedUnion("kind", [z.object({
  kind: z.literal("all_authorized"),
}), z.object({
  kind: z.literal("allowlist"),
  repositories: z.array(z.lazy(() => RepositoryIdSchema)),
})]);
export type RepositoryPlacementScopeV1 = z.infer<typeof RepositoryPlacementScopeV1Schema>;

export const RequiredCheckExpectationV1Schema = z.literal("successful_terminal");
export type RequiredCheckExpectationV1 = z.infer<typeof RequiredCheckExpectationV1Schema>;

export const RequiredCheckV1Schema = z.object({
  capability_id: z.lazy(() => CapabilityIdSchema),
  expectation: z.lazy(() => RequiredCheckExpectationV1Schema),
  maximum_age_seconds: z.number().int(),
});
export type RequiredCheckV1 = z.infer<typeof RequiredCheckV1Schema>;

/** The resolved PR11 scope is one exact project/repository/worktree root.

Paths, CWDs, labels, and mutable branch spellings are deliberately absent. */
export const ResolvedScopeSchema = z.object({
  project_id: z.lazy(() => ProjectIdSchema),
  reference: z.union([z.lazy(() => RefIdSchema), z.null()]),
  repository_id: z.lazy(() => RepositoryIdSchema),
  scope_digest: z.lazy(() => ManifestDigestSchema),
  worktree_id: z.lazy(() => WorktreeIdSchema),
});
export type ResolvedScope = z.infer<typeof ResolvedScopeSchema>;

/** Strongly typed canonical identity: `RetrievalAnchorId`. */
export const RetrievalAnchorIdSchema = z.string();
export type RetrievalAnchorId = z.infer<typeof RetrievalAnchorIdSchema>;

export const ReviewRequirementV1Schema = z.discriminatedUnion("kind", [z.object({
  kind: z.literal("code_owner_and_independent_review"),
}), z.object({
  count: z.number().int(),
  kind: z.literal("independent_review_count"),
}), z.object({
  kind: z.literal("none"),
})]);
export type ReviewRequirementV1 = z.infer<typeof ReviewRequirementV1Schema>;

export const ReviewTopologyKindV1Schema = z.enum(["git_hub_stacked_pull_requests", "independent_review", "no_review", "standard_pull_requests"]);
export type ReviewTopologyKindV1 = z.infer<typeof ReviewTopologyKindV1Schema>;

export const ReviewTopologyPolicyV1Schema = z.object({
  allowed: z.array(z.lazy(() => ReviewTopologyKindV1Schema)),
  github_stacked_prs: z.lazy(() => GitHubStackedPullRequestPolicyV1Schema),
});
export type ReviewTopologyPolicyV1 = z.infer<typeof ReviewTopologyPolicyV1Schema>;

export const RuleEffectSchema = z.enum(["allow", "deny"]);
export type RuleEffect = z.infer<typeof RuleEffectSchema>;

/** Restrictive policy input. An allow never grants capabilities absent from
the independently authorized capability set passed to the resolver. */
export const ScopeAccessRuleSchema = z.object({
  authority: z.lazy(() => AuthorityRefSchema),
  capabilities: z.array(z.lazy(() => CapabilityIdSchema)),
  effect: z.lazy(() => RuleEffectSchema),
  expires_at: z.union([z.lazy(() => UtcMicrosSchema), z.null()]),
  rule_id: z.string(),
  subject: z.lazy(() => ScopeAccessSubjectV1Schema),
});
export type ScopeAccessRule = z.infer<typeof ScopeAccessRuleSchema>;

/** Typed rule selectors. Unset dimensions match all values at that dimension,
but at least one dimension must be constrained. Free-form paths, labels,
collection names, and branch names are deliberately absent. */
export const ScopeAccessSubjectV1Schema = z.object({
  actor: z.union([z.lazy(() => ActorIdSchema), z.null()]),
  operation: z.union([z.lazy(() => ScopeControlOperationV1Schema), z.null()]),
  source_kind: z.union([z.lazy(() => SourceKindV1Schema), z.null()]),
});
export type ScopeAccessSubjectV1 = z.infer<typeof ScopeAccessSubjectV1Schema>;

export const ScopeControlOperationV1Schema = z.enum(["access_rule_remove", "access_rule_upsert", "read", "replace_topology_policy", "rollback", "set_default_collection", "source_bind", "source_rebind", "source_unbind"]);
export type ScopeControlOperationV1 = z.infer<typeof ScopeControlOperationV1Schema>;

/** A source-to-authority binding. It stores only the source kind, a redacted
locator digest, and the pre-resolved authority reference. */
export const ScopeSourceBindingSchema = z.object({
  authority: z.lazy(() => AuthorityRefSchema),
  binding_id: z.string(),
  source_kind: z.lazy(() => SourceKindV1Schema),
  source_locator_digest: z.lazy(() => LocatorDigestSchema),
});
export type ScopeSourceBinding = z.infer<typeof ScopeSourceBindingSchema>;

/** Reference-only filesystem locator. The raw path is sealed outside this
contract; only the privacy-bound locator digest and sealed-value digest are
representable here. */
export const SensitiveFilesystemLocatorV1Schema = z.object({
  locator_digest: z.lazy(() => LocatorDigestSchema),
  sealed_value_digest: z.lazy(() => ManifestDigestSchema),
});
export type SensitiveFilesystemLocatorV1 = z.infer<typeof SensitiveFilesystemLocatorV1Schema>;

export const SourceKindV1Schema = z.enum(["claude", "codex", "cursor", "git_hub", "hermes", "kiro"]);
export type SourceKindV1 = z.infer<typeof SourceKindV1Schema>;

/** A byte size measurement. A newtype keeps sizes from being confused with
counts, ratios, or timestamps in the read models and producers. */
export const StorageByteSizeV1Schema = z.number().int();
export type StorageByteSizeV1 = z.infer<typeof StorageByteSizeV1Schema>;

/** Source-coverage status for one typed storage finding producer. */
export const StorageFindingKindStatusV1Schema = z.object({
  kind: z.lazy(() => DoctorStorageFindingKindV1Schema),
  observed_entries: z.number().int(),
  reason: z.string(),
  state: z.lazy(() => StorageFindingSourceStateV1Schema),
});
export type StorageFindingKindStatusV1 = z.infer<typeof StorageFindingKindStatusV1Schema>;

/** Whether one Plan 38 producer had enough source evidence to report a real
result. This is source coverage, not a health grade: `Real` can describe a
clean observation or a problem finding. */
export const StorageFindingSourceStateV1Schema = z.enum(["partial", "real", "unset", "unsupported"]);
export type StorageFindingSourceStateV1 = z.infer<typeof StorageFindingSourceStateV1Schema>;

/** Route-specific payload for `/api/storage/findings`.

Storage producer coverage is required here rather than an optional field on
the general Doctor payload, so generated consumers cannot mistake one route
for the other. */
export const StorageFindingsPayloadV1Schema = z.object({
  entries: z.array(z.lazy(() => DoctorReportEntryV1Schema)),
  family_filter: z.union([z.lazy(() => DoctorFindingFamilyV1Schema), z.null()]),
  kind_statuses: z.array(z.lazy(() => StorageFindingKindStatusV1Schema)),
  known_families: z.array(z.lazy(() => DoctorFindingFamilyV1Schema)),
  note: z.string(),
  remediations: z.array(z.lazy(() => DashboardDoctorRemediationDescriptorV1Schema)),
  report_coverage: z.union([z.lazy(() => DoctorReportCoverageV1Schema), z.null()]),
});
export type StorageFindingsPayloadV1 = z.infer<typeof StorageFindingsPayloadV1Schema>;

/** Telemetry payload: one entry per distinct store the dashboard holds a
connection to. */
export const StorageTelemetryPayloadV1Schema = z.object({
  budget_note: z.string(),
  growth_note: z.string(),
  stores: z.array(z.lazy(() => StoreTelemetryEntryV1Schema)),
});
export type StorageTelemetryPayloadV1 = z.infer<typeof StorageTelemetryPayloadV1Schema>;

/** The typed result of one telemetry read attempt.

The port is *total*: it never fails silently into a healthy or empty result.
A platform that cannot query `dbstat`/pragmas reports [`Self::Unsupported`];
a denied read reports [`Self::Denied`]; an undetermined read reports
[`Self::Unknown`]. Each maps to a distinct, honest Doctor evidence state. */
export const StorageTelemetryReadV1Schema = z.discriminatedUnion("kind", [z.object({
  kind: z.literal("denied"),
  store: z.lazy(() => StoreKeyV1Schema),
}), z.object({
  kind: z.literal("observed"),
  sample: z.lazy(() => StoreSizeSampleV1Schema),
}), z.object({
  kind: z.literal("unknown"),
  store: z.lazy(() => StoreKeyV1Schema),
}), z.object({
  kind: z.literal("unsupported"),
  store: z.lazy(() => StoreKeyV1Schema),
})]);
export type StorageTelemetryReadV1 = z.infer<typeof StorageTelemetryReadV1Schema>;

/** The budget-evaluation dimension, sourced from owner configuration. */
export const StoreBudgetDimensionV1Schema = z.discriminatedUnion("state", [z.object({
  evaluation: z.lazy(() => StoreBudgetEvaluationV1Schema),
  reason: z.string(),
  setting_key: z.string(),
  state: z.literal("evaluated"),
}), z.object({
  reason: z.string(),
  state: z.literal("unknown"),
}), z.object({
  reason: z.string(),
  setting_key: z.string(),
  state: z.literal("unset"),
})]);
export type StoreBudgetDimensionV1 = z.infer<typeof StoreBudgetDimensionV1Schema>;

/** The outcome of evaluating a store size against its soft budget. */
export const StoreBudgetEvaluationV1Schema = z.discriminatedUnion("state", [z.object({
  observed: z.lazy(() => StorageByteSizeV1Schema),
  overage: z.lazy(() => StorageByteSizeV1Schema),
  soft_limit: z.lazy(() => StorageByteSizeV1Schema),
  state: z.literal("over_budget"),
}), z.object({
  observed: z.lazy(() => StorageByteSizeV1Schema),
  soft_limit: z.lazy(() => StorageByteSizeV1Schema),
  state: z.literal("within_budget"),
})]);
export type StoreBudgetEvaluationV1 = z.infer<typeof StoreBudgetEvaluationV1Schema>;

/** The per-store growth dimension. Growth is only ever reported over the window
the server actually observed, and that window is named in `coverage`. */
export const StoreGrowthDimensionV1Schema = z.discriminatedUnion("state", [z.object({
  coverage: z.string(),
  measured_at: z.number().int(),
  reason: z.string(),
  state: z.literal("baseline"),
  total_bytes: z.number().int(),
}), z.object({
  coverage: z.string(),
  current_total_bytes: z.number().int(),
  first_measured_at: z.number().int(),
  first_total_bytes: z.number().int(),
  growth_bytes: z.number().int(),
  last_measured_at: z.number().int(),
  sample_count: z.number().int(),
  samples: z.array(z.lazy(() => StoreSizeWatermarkV1Schema)),
  state: z.literal("observed"),
}), z.object({
  reason: z.string(),
  state: z.literal("unknown"),
})]);
export type StoreGrowthDimensionV1 = z.infer<typeof StoreGrowthDimensionV1Schema>;

/** Logical name of one owner-profile store (for example `sessions.db`,
`graph.db`, or `branches/feature-x`). Never an absolute on-disk path. */
export const StoreKeyV1Schema = z.string();
export type StoreKeyV1 = z.infer<typeof StoreKeyV1Schema>;

/** One cheap size sample for a single store, derived from page-count pragmas.

`total_bytes` is `page_count * page_size`; `free_bytes` is
`freelist_pages * page_size`. Both are recorded so the free-page ratio and
the reclaimable-bytes estimate (Plan 38 §6 compaction) can be computed
without re-reading the store. */
export const StoreSizeSampleV1Schema = z.object({
  freelist_pages: z.number().int(),
  observed_at: z.lazy(() => UtcMicrosSchema),
  page_count: z.number().int(),
  page_size_bytes: z.number().int(),
  store: z.lazy(() => StoreKeyV1Schema),
});
export type StoreSizeSampleV1 = z.infer<typeof StoreSizeSampleV1Schema>;

/** One recorded store-size watermark. */
export const StoreSizeWatermarkV1Schema = z.object({
  free_bytes: z.number().int(),
  measured_at: z.number().int(),
  total_bytes: z.number().int(),
});
export type StoreSizeWatermarkV1 = z.infer<typeof StoreSizeWatermarkV1Schema>;

/** One store's telemetry entry. One entry per distinct store **file**, not per
dashboard role. */
export const StoreTelemetryEntryV1Schema = z.object({
  budget: z.lazy(() => StoreBudgetDimensionV1Schema),
  free_bytes: z.number().int().nullable(),
  free_page_ratio: z.number().nullable(),
  growth: z.lazy(() => StoreGrowthDimensionV1Schema),
  path: z.string(),
  read: z.lazy(() => StorageTelemetryReadV1Schema),
  role: z.string(),
  roles: z.array(z.string()),
  store: z.string(),
  total_bytes: z.number().int().nullable(),
});
export type StoreTelemetryEntryV1 = z.infer<typeof StoreTelemetryEntryV1Schema>;

export const StrataClusterV1Schema = z.object({
  boundary_edges: z.number().int(),
  directory: z.string(),
  file_count: z.number().int(),
  incoming_edges: z.number().int(),
  internal_edges: z.number().int(),
  order: z.number().int(),
  outgoing_edges: z.number().int(),
});
export type StrataClusterV1 = z.infer<typeof StrataClusterV1Schema>;

export const StrataFileV1Schema = z.object({
  chain: z.array(z.string()),
  depth: z.number().int(),
  path: z.string(),
  scc_size: z.number().int(),
});
export type StrataFileV1 = z.infer<typeof StrataFileV1Schema>;

export const StrataMeasurementV1Schema = z.object({
  algorithm: z.string(),
  cluster_ordering: z.string(),
  clusters: z.array(z.lazy(() => StrataClusterV1Schema)),
  dependency_edge_kinds: z.array(z.string()),
  files: z.array(z.lazy(() => StrataFileV1Schema)),
  granularity: z.string(),
  graph_generation: z.string(),
  ideal_depth: z.number().int(),
  max_depth: z.number().int(),
  scan: z.lazy(() => StrataScanV1Schema),
});
export type StrataMeasurementV1 = z.infer<typeof StrataMeasurementV1Schema>;

export const StrataScanV1Schema = z.object({
  budget_ms: z.number().int(),
  cache_scope: z.string(),
  cache_state: z.string(),
  dependency_edges_examined: z.number().int(),
  files_examined: z.number().int(),
  max_dependency_edges: z.number().int(),
  max_files: z.number().int(),
});
export type StrataScanV1 = z.infer<typeof StrataScanV1Schema>;

export const StructureReadV1Schema = z.discriminatedUnion("status", [z.object({
  code: z.string(),
  detail: z.string(),
  retryable: z.boolean(),
  status: z.literal("failed"),
}), z.object({
  measurement: z.lazy(() => CallChainMeasurementV1Schema),
  status: z.literal("measured"),
}), z.object({
  detail: z.string(),
  reason: z.string(),
  status: z.literal("unmeasured"),
})]);
export type StructureReadV1 = z.infer<typeof StructureReadV1Schema>;

export const StructureReadV12Schema = z.discriminatedUnion("status", [z.object({
  code: z.string(),
  detail: z.string(),
  retryable: z.boolean(),
  status: z.literal("failed"),
}), z.object({
  measurement: z.lazy(() => StrataMeasurementV1Schema),
  status: z.literal("measured"),
}), z.object({
  detail: z.string(),
  reason: z.string(),
  status: z.literal("unmeasured"),
})]);
export type StructureReadV12 = z.infer<typeof StructureReadV12Schema>;

export const StructureReadV13Schema = z.discriminatedUnion("status", [z.object({
  code: z.string(),
  detail: z.string(),
  retryable: z.boolean(),
  status: z.literal("failed"),
}), z.object({
  measurement: z.lazy(() => FactMatchesMeasurementV1Schema),
  status: z.literal("measured"),
}), z.object({
  detail: z.string(),
  reason: z.string(),
  status: z.literal("unmeasured"),
})]);
export type StructureReadV13 = z.infer<typeof StructureReadV13Schema>;

export const StructureReadV14Schema = z.discriminatedUnion("status", [z.object({
  code: z.string(),
  detail: z.string(),
  retryable: z.boolean(),
  status: z.literal("failed"),
}), z.object({
  measurement: z.lazy(() => TestMapMeasurementV1Schema),
  status: z.literal("measured"),
}), z.object({
  detail: z.string(),
  reason: z.string(),
  status: z.literal("unmeasured"),
})]);
export type StructureReadV14 = z.infer<typeof StructureReadV14Schema>;

export const StructureReadV15Schema = z.discriminatedUnion("status", [z.object({
  code: z.string(),
  detail: z.string(),
  retryable: z.boolean(),
  status: z.literal("failed"),
}), z.object({
  measurement: z.lazy(() => NodeSessionsMeasurementV1Schema),
  status: z.literal("measured"),
}), z.object({
  detail: z.string(),
  reason: z.string(),
  status: z.literal("unmeasured"),
})]);
export type StructureReadV15 = z.infer<typeof StructureReadV15Schema>;

export const TestMapMeasurementV1Schema = z.object({
  algorithm: z.string(),
  applicable: z.boolean(),
  caller_depth: z.number().int(),
  granularity: z.string(),
  node: z.lazy(() => NodeRefV1Schema),
  reason: z.string().nullable(),
  test_files: z.array(z.string()),
  tests: z.array(z.lazy(() => CoveringTestV1Schema)),
});
export type TestMapMeasurementV1 = z.infer<typeof TestMapMeasurementV1Schema>;

export const TopologyConcurrencyPolicyV1Schema = z.object({
  maximum_active_per_repository: z.number().int(),
  maximum_global_active: z.number().int(),
  maximum_parallel_per_task: z.number().int(),
  maximum_stack_depth: z.number().int(),
});
export type TopologyConcurrencyPolicyV1 = z.infer<typeof TopologyConcurrencyPolicyV1Schema>;

export const TopologyEscalationPolicyV1Schema = z.enum(["reject", "require_explicit_human_approval", "require_human_approval_and_independent_review"]);
export type TopologyEscalationPolicyV1 = z.infer<typeof TopologyEscalationPolicyV1Schema>;

export const TopologyGatePolicyV1Schema = z.object({
  cleanliness: z.lazy(() => WorktreeCleanlinessRequirementV1Schema),
  maximum_preflight_age_seconds: z.number().int(),
  require_fresh_preflight: z.boolean(),
  review: z.lazy(() => ReviewRequirementV1Schema),
  tests: z.array(z.lazy(() => RequiredCheckV1Schema)),
});
export type TopologyGatePolicyV1 = z.infer<typeof TopologyGatePolicyV1Schema>;

export const TopologyNotificationLevelV1Schema = z.enum(["critical_only", "lifecycle", "verbose"]);
export type TopologyNotificationLevelV1 = z.infer<typeof TopologyNotificationLevelV1Schema>;

/** Stable, canonical catalog identity for `UseCaseId`. */
export const UseCaseIdSchema = z.string();
export type UseCaseId = z.infer<typeof UseCaseIdSchema>;

/** UTC timestamp represented as microseconds from the Unix epoch. */
export const UtcMicrosSchema = z.number().int();
export type UtcMicros = z.infer<typeof UtcMicrosSchema>;

/** Complete V1 policy. Partial values are intentionally impossible: callers
must provide the entire policy and validation rejects adapter-local defaults. */
export const WorkTopologyPolicyV1Schema = z.object({
  branch_naming: z.lazy(() => BranchNamingPolicyV1Schema),
  branch_topology: z.lazy(() => BranchTopologyPolicyV1Schema),
  concurrency: z.lazy(() => TopologyConcurrencyPolicyV1Schema),
  cross_merge: z.lazy(() => CrossMergePolicyV1Schema),
  escalation: z.lazy(() => TopologyEscalationPolicyV1Schema),
  gates: z.lazy(() => TopologyGatePolicyV1Schema),
  history_rewrite: z.lazy(() => HistoryRewritePolicyV1Schema),
  notifications: z.lazy(() => TopologyNotificationLevelV1Schema),
  placement: z.lazy(() => WorktreePlacementModeV1Schema),
  protected_refs: z.array(z.lazy(() => ProtectedRefRuleV1Schema)),
  retention: z.lazy(() => WorktreeRetentionPolicyV1Schema),
  review_topology: z.lazy(() => ReviewTopologyPolicyV1Schema),
  roots: z.array(z.lazy(() => WorktreeRootPolicyV1Schema)),
  schema_version: z.number().int(),
});
export type WorkTopologyPolicyV1 = z.infer<typeof WorkTopologyPolicyV1Schema>;

export const WorktreeCleanlinessRequirementV1Schema = z.enum(["allow_untracked_only_for_preflight", "read_only_preflight_only", "require_clean"]);
export type WorktreeCleanlinessRequirementV1 = z.infer<typeof WorktreeCleanlinessRequirementV1Schema>;

/** Strongly typed canonical identity: `WorktreeId`. */
export const WorktreeIdSchema = z.string();
export type WorktreeId = z.infer<typeof WorktreeIdSchema>;

export const WorktreePlacementModeV1Schema = z.discriminatedUnion("kind", [z.object({
  kind: z.literal("configured_root"),
  root_id: z.string(),
}), z.object({
  kind: z.literal("existing_worktree_only"),
}), z.object({
  kind: z.literal("repository_local_root"),
}), z.object({
  kind: z.literal("sibling_of_primary_checkout"),
})]);
export type WorktreePlacementModeV1 = z.infer<typeof WorktreePlacementModeV1Schema>;

export const WorktreeRetentionPolicyV1Schema = z.object({
  abandoned_retention_seconds: z.number().int().nullable(),
  automatic_gc: z.lazy(() => AutomaticWorktreeGcV1Schema),
  maximum_retained_per_repository: z.number().int().nullable(),
  terminal_retention_seconds: z.number().int().nullable(),
});
export type WorktreeRetentionPolicyV1 = z.infer<typeof WorktreeRetentionPolicyV1Schema>;

export const WorktreeRootPolicyV1Schema = z.object({
  locator: z.lazy(() => SensitiveFilesystemLocatorV1Schema),
  maximum_active_worktrees: z.number().int(),
  repository_scope: z.lazy(() => RepositoryPlacementScopeV1Schema),
  root_id: z.string(),
});
export type WorktreeRootPolicyV1 = z.infer<typeof WorktreeRootPolicyV1Schema>;

export const DomainStateSchema = DashboardDomainStateV1Schema;
export type WireDomainState = DashboardDomainStateV1;
export const ScopeSchema = DashboardScopeV1Schema;
export type WireScope = DashboardScopeV1;
export const VersionSchema = DashboardVersionV1Schema;
export type WireVersion = DashboardVersionV1;
export const TimeSchema = DashboardTimeV1Schema;
export type WireTime = DashboardTimeV1;
export const WatermarkSchema = DashboardWatermarkV1Schema;
export type WireWatermark = DashboardWatermarkV1;
export const AuthorizationSchema = DashboardAuthorizationV1Schema;
export type WireAuthorization = DashboardAuthorizationV1;
export const CoverageSchema = DashboardCoverageV1Schema;
export type WireCoverage = DashboardCoverageV1;
export const FreshnessSchema = DashboardFreshnessV1Schema;
export type WireFreshness = DashboardFreshnessV1;
export const LegalActionKindSchema = DashboardLegalActionKindV1Schema;
export type WireLegalActionKind = DashboardLegalActionKindV1;
export const LegalActionRefSchema = DashboardLegalActionRefV1Schema;
export type WireLegalActionRef = DashboardLegalActionRefV1;
export const EnvelopeSchema = DashboardEnvelopeV1Schema;
export type WireEnvelope<TPayload> = DashboardEnvelopeV1<TPayload>;
export const AutomaticWorktreeGcSchema = AutomaticWorktreeGcV1Schema;
export type AutomaticWorktreeGc = AutomaticWorktreeGcV1;
export const AutomationPendingReviewCountSchema = AutomationPendingReviewCountV1Schema;
export type AutomationPendingReviewCount = AutomationPendingReviewCountV1;
export const AutomationPendingReviewSchema = AutomationPendingReviewV1Schema;
export type AutomationPendingReview = AutomationPendingReviewV1;
export const AutomationSchedulerStatusSchema = AutomationSchedulerStatusV1Schema;
export type AutomationSchedulerStatus = AutomationSchedulerStatusV1;
export const AutomationTaskStatusSchema = AutomationTaskStatusV1Schema;
export type AutomationTaskStatus = AutomationTaskStatusV1;
export const BranchCollisionPolicySchema = BranchCollisionPolicyV1Schema;
export type BranchCollisionPolicy = BranchCollisionPolicyV1;
export const BranchNameComponentSchema = BranchNameComponentV1Schema;
export type BranchNameComponent = BranchNameComponentV1;
export const BranchNameSeparatorSchema = BranchNameSeparatorV1Schema;
export type BranchNameSeparator = BranchNameSeparatorV1;
export const BranchNamingPolicySchema = BranchNamingPolicyV1Schema;
export type BranchNamingPolicy = BranchNamingPolicyV1;
export const BranchTopologyKindSchema = BranchTopologyKindV1Schema;
export type BranchTopologyKind = BranchTopologyKindV1;
export const BranchTopologyPolicySchema = BranchTopologyPolicyV1Schema;
export type BranchTopologyPolicy = BranchTopologyPolicyV1;
export const CallChainMeasurementSchema = CallChainMeasurementV1Schema;
export type CallChainMeasurement = CallChainMeasurementV1;
export const CallChainStepSchema = CallChainStepV1Schema;
export type CallChainStep = CallChainStepV1;
export const CanonicalGitRefNameSchema = CanonicalGitRefNameV1Schema;
export type CanonicalGitRefName = CanonicalGitRefNameV1;
export const CodeIndexFreshnessPayloadSchema = CodeIndexFreshnessPayloadV1Schema;
export type CodeIndexFreshnessPayload = CodeIndexFreshnessPayloadV1;
export const CodeIndexWorktreeFreshnessSchema = CodeIndexWorktreeFreshnessV1Schema;
export type CodeIndexWorktreeFreshness = CodeIndexWorktreeFreshnessV1;
export const CoveringTestSchema = CoveringTestV1Schema;
export type CoveringTest = CoveringTestV1;
export const CrossMergeModeSchema = CrossMergeModeV1Schema;
export type CrossMergeMode = CrossMergeModeV1;
export const CrossMergePolicySchema = CrossMergePolicyV1Schema;
export type CrossMergePolicy = CrossMergePolicyV1;
export const DoctorConfirmationRequirementSchema = DoctorConfirmationRequirementV1Schema;
export type DoctorConfirmationRequirement = DoctorConfirmationRequirementV1;
export const DoctorCoverageCompletenessSchema = DoctorCoverageCompletenessV1Schema;
export type DoctorCoverageCompleteness = DoctorCoverageCompletenessV1;
export const DoctorCoverageStatementSchema = DoctorCoverageStatementV1Schema;
export type DoctorCoverageStatement = DoctorCoverageStatementV1;
export const DoctorEvidenceRefSchema = DoctorEvidenceRefV1Schema;
export type DoctorEvidenceRef = DoctorEvidenceRefV1;
export const DoctorEvidenceReferenceSchema = DoctorEvidenceReferenceV1Schema;
export type DoctorEvidenceReference = DoctorEvidenceReferenceV1;
export const DoctorEvidenceStateSchema = DoctorEvidenceStateV1Schema;
export type DoctorEvidenceState = DoctorEvidenceStateV1;
export const DoctorFamilyConsultationSchema = DoctorFamilyConsultationV1Schema;
export type DoctorFamilyConsultation = DoctorFamilyConsultationV1;
export const DoctorFamilyCoverageSchema = DoctorFamilyCoverageV1Schema;
export type DoctorFamilyCoverage = DoctorFamilyCoverageV1;
export const DoctorFamilyUnavailableReasonSchema = DoctorFamilyUnavailableReasonV1Schema;
export type DoctorFamilyUnavailableReason = DoctorFamilyUnavailableReasonV1;
export const DoctorFindingFamilySchema = DoctorFindingFamilyV1Schema;
export type DoctorFindingFamily = DoctorFindingFamilyV1;
export const DoctorFindingSchema = DoctorFindingV1Schema;
export type DoctorFinding = DoctorFindingV1;
export const DoctorFindingsPayloadSchema = DoctorFindingsPayloadV1Schema;
export type DoctorFindingsPayload = DoctorFindingsPayloadV1;
export const DoctorOwningOperationRefSchema = DoctorOwningOperationRefV1Schema;
export type DoctorOwningOperationRef = DoctorOwningOperationRefV1;
export const DoctorOwningSurfaceSchema = DoctorOwningSurfaceV1Schema;
export type DoctorOwningSurface = DoctorOwningSurfaceV1;
export const DoctorRemediationApplyRequestSchema = DoctorRemediationApplyRequestV1Schema;
export type DoctorRemediationApplyRequest = DoctorRemediationApplyRequestV1;
export const DoctorRemediationDispatchErrorSchema = DoctorRemediationDispatchErrorV1Schema;
export type DoctorRemediationDispatchError = DoctorRemediationDispatchErrorV1;
export const DoctorRemediationKindSchema = DoctorRemediationKindV1Schema;
export type DoctorRemediationKind = DoctorRemediationKindV1;
export const DoctorRemediationOperationPhaseSchema = DoctorRemediationOperationPhaseV1Schema;
export type DoctorRemediationOperationPhase = DoctorRemediationOperationPhaseV1;
export const DoctorRemediationOperationSchema = DoctorRemediationOperationV1Schema;
export type DoctorRemediationOperation = DoctorRemediationOperationV1;
export const DoctorRemediationPayloadSchema = DoctorRemediationPayloadV1Schema;
export type DoctorRemediationPayload = DoctorRemediationPayloadV1;
export const DoctorRemediationPreviewRequestSchema = DoctorRemediationPreviewRequestV1Schema;
export type DoctorRemediationPreviewRequest = DoctorRemediationPreviewRequestV1;
export const DoctorRemediationRefSchema = DoctorRemediationRefV1Schema;
export type DoctorRemediationRef = DoctorRemediationRefV1;
export const DoctorRemediationTargetSchema = DoctorRemediationTargetV1Schema;
export type DoctorRemediationTarget = DoctorRemediationTargetV1;
export const DoctorReportCoverageSchema = DoctorReportCoverageV1Schema;
export type DoctorReportCoverage = DoctorReportCoverageV1;
export const DoctorReportEntrySchema = DoctorReportEntryV1Schema;
export type DoctorReportEntry = DoctorReportEntryV1;
export const DoctorStorageFindingKindSchema = DoctorStorageFindingKindV1Schema;
export type DoctorStorageFindingKind = DoctorStorageFindingKindV1;
export const ExplorerFinalitySchema = ExplorerFinalityV1Schema;
export type ExplorerFinality = ExplorerFinalityV1;
export const ExplorerQueryRequestSchema = ExplorerQueryRequestV1Schema;
export type ExplorerQueryRequest = ExplorerQueryRequestV1;
export const ExplorerQueryRunSchema = ExplorerQueryRunV1Schema;
export type ExplorerQueryRun = ExplorerQueryRunV1;
export const ExplorerResultPageSchema = ExplorerResultPageV1Schema;
export type ExplorerResultPage = ExplorerResultPageV1;
export const ExplorerRunStateSchema = ExplorerRunStateV1Schema;
export type ExplorerRunState = ExplorerRunStateV1;
export const ExplorerSourceIdSchema = ExplorerSourceIdV1Schema;
export type ExplorerSourceId = ExplorerSourceIdV1;
export const ExplorerSourceOutcomeSchema = ExplorerSourceOutcomeV1Schema;
export type ExplorerSourceOutcome = ExplorerSourceOutcomeV1;
export const ExplorerSourcePhaseSchema = ExplorerSourcePhaseV1Schema;
export type ExplorerSourcePhase = ExplorerSourcePhaseV1;
export const ExplorerSourceProgressSchema = ExplorerSourceProgressV1Schema;
export type ExplorerSourceProgress = ExplorerSourceProgressV1;
export const FactArmCoverageSchema = FactArmCoverageV1Schema;
export type FactArmCoverage = FactArmCoverageV1;
export const FactMatchArmSchema = FactMatchArmV1Schema;
export type FactMatchArm = FactMatchArmV1;
export const FactMatchesMeasurementSchema = FactMatchesMeasurementV1Schema;
export type FactMatchesMeasurement = FactMatchesMeasurementV1;
export const GitHubStackedPullRequestPolicySchema = GitHubStackedPullRequestPolicyV1Schema;
export type GitHubStackedPullRequestPolicy = GitHubStackedPullRequestPolicyV1;
export const HistoryRewritePolicySchema = HistoryRewritePolicyV1Schema;
export type HistoryRewritePolicy = HistoryRewritePolicyV1;
export const HostBundleComponentSchema = HostBundleComponentV1Schema;
export type HostBundleComponent = HostBundleComponentV1;
export const HostKindSchema = HostKindV1Schema;
export type HostKind = HostKindV1;
export const IncomingCallEdgeSchema = IncomingCallEdgeV1Schema;
export type IncomingCallEdge = IncomingCallEdgeV1;
export const LoomFileSessionProjectionSchema = LoomFileSessionProjectionV1Schema;
export type LoomFileSessionProjection = LoomFileSessionProjectionV1;
export const NodeRefSchema = NodeRefV1Schema;
export type NodeRef = NodeRefV1;
export const NodeSessionsMeasurementSchema = NodeSessionsMeasurementV1Schema;
export type NodeSessionsMeasurement = NodeSessionsMeasurementV1;
export const ProtectedRefDispositionSchema = ProtectedRefDispositionV1Schema;
export type ProtectedRefDisposition = ProtectedRefDispositionV1;
export const ProtectedRefRuleSchema = ProtectedRefRuleV1Schema;
export type ProtectedRefRule = ProtectedRefRuleV1;
export const ProtectedRefSelectorSchema = ProtectedRefSelectorV1Schema;
export type ProtectedRefSelector = ProtectedRefSelectorV1;
export const RepositoryPlacementScopeSchema = RepositoryPlacementScopeV1Schema;
export type RepositoryPlacementScope = RepositoryPlacementScopeV1;
export const RequiredCheckExpectationSchema = RequiredCheckExpectationV1Schema;
export type RequiredCheckExpectation = RequiredCheckExpectationV1;
export const RequiredCheckSchema = RequiredCheckV1Schema;
export type RequiredCheck = RequiredCheckV1;
export const ReviewRequirementSchema = ReviewRequirementV1Schema;
export type ReviewRequirement = ReviewRequirementV1;
export const ReviewTopologyKindSchema = ReviewTopologyKindV1Schema;
export type ReviewTopologyKind = ReviewTopologyKindV1;
export const ReviewTopologyPolicySchema = ReviewTopologyPolicyV1Schema;
export type ReviewTopologyPolicy = ReviewTopologyPolicyV1;
export const ScopeAccessSubjectSchema = ScopeAccessSubjectV1Schema;
export type ScopeAccessSubject = ScopeAccessSubjectV1;
export const ScopeControlOperationSchema = ScopeControlOperationV1Schema;
export type ScopeControlOperation = ScopeControlOperationV1;
export const SensitiveFilesystemLocatorSchema = SensitiveFilesystemLocatorV1Schema;
export type SensitiveFilesystemLocator = SensitiveFilesystemLocatorV1;
export const SourceKindSchema = SourceKindV1Schema;
export type SourceKind = SourceKindV1;
export const StorageByteSizeSchema = StorageByteSizeV1Schema;
export type StorageByteSize = StorageByteSizeV1;
export const StorageFindingKindStatusSchema = StorageFindingKindStatusV1Schema;
export type StorageFindingKindStatus = StorageFindingKindStatusV1;
export const StorageFindingSourceStateSchema = StorageFindingSourceStateV1Schema;
export type StorageFindingSourceState = StorageFindingSourceStateV1;
export const StorageFindingsPayloadSchema = StorageFindingsPayloadV1Schema;
export type StorageFindingsPayload = StorageFindingsPayloadV1;
export const StorageTelemetryPayloadSchema = StorageTelemetryPayloadV1Schema;
export type StorageTelemetryPayload = StorageTelemetryPayloadV1;
export const StorageTelemetryReadSchema = StorageTelemetryReadV1Schema;
export type StorageTelemetryRead = StorageTelemetryReadV1;
export const StoreBudgetDimensionSchema = StoreBudgetDimensionV1Schema;
export type StoreBudgetDimension = StoreBudgetDimensionV1;
export const StoreBudgetEvaluationSchema = StoreBudgetEvaluationV1Schema;
export type StoreBudgetEvaluation = StoreBudgetEvaluationV1;
export const StoreGrowthDimensionSchema = StoreGrowthDimensionV1Schema;
export type StoreGrowthDimension = StoreGrowthDimensionV1;
export const StoreKeySchema = StoreKeyV1Schema;
export type StoreKey = StoreKeyV1;
export const StoreSizeSampleSchema = StoreSizeSampleV1Schema;
export type StoreSizeSample = StoreSizeSampleV1;
export const StoreSizeWatermarkSchema = StoreSizeWatermarkV1Schema;
export type StoreSizeWatermark = StoreSizeWatermarkV1;
export const StoreTelemetryEntrySchema = StoreTelemetryEntryV1Schema;
export type StoreTelemetryEntry = StoreTelemetryEntryV1;
export const StrataClusterSchema = StrataClusterV1Schema;
export type StrataCluster = StrataClusterV1;
export const StrataFileSchema = StrataFileV1Schema;
export type StrataFile = StrataFileV1;
export const StrataMeasurementSchema = StrataMeasurementV1Schema;
export type StrataMeasurement = StrataMeasurementV1;
export const StrataScanSchema = StrataScanV1Schema;
export type StrataScan = StrataScanV1;
export const StructureReadSchema = StructureReadV1Schema;
export type StructureRead = StructureReadV1;
export const TestMapMeasurementSchema = TestMapMeasurementV1Schema;
export type TestMapMeasurement = TestMapMeasurementV1;
export const TopologyConcurrencyPolicySchema = TopologyConcurrencyPolicyV1Schema;
export type TopologyConcurrencyPolicy = TopologyConcurrencyPolicyV1;
export const TopologyEscalationPolicySchema = TopologyEscalationPolicyV1Schema;
export type TopologyEscalationPolicy = TopologyEscalationPolicyV1;
export const TopologyGatePolicySchema = TopologyGatePolicyV1Schema;
export type TopologyGatePolicy = TopologyGatePolicyV1;
export const TopologyNotificationLevelSchema = TopologyNotificationLevelV1Schema;
export type TopologyNotificationLevel = TopologyNotificationLevelV1;
export const WorkTopologyPolicySchema = WorkTopologyPolicyV1Schema;
export type WorkTopologyPolicy = WorkTopologyPolicyV1;
export const WorktreeCleanlinessRequirementSchema = WorktreeCleanlinessRequirementV1Schema;
export type WorktreeCleanlinessRequirement = WorktreeCleanlinessRequirementV1;
export const WorktreePlacementModeSchema = WorktreePlacementModeV1Schema;
export type WorktreePlacementMode = WorktreePlacementModeV1;
export const WorktreeRetentionPolicySchema = WorktreeRetentionPolicyV1Schema;
export type WorktreeRetentionPolicy = WorktreeRetentionPolicyV1;
export const WorktreeRootPolicySchema = WorktreeRootPolicyV1Schema;
export type WorktreeRootPolicy = WorktreeRootPolicyV1;
export const DoctorCancellationStageSchema = CancellationStageSchema;
export type DoctorCancellationStage = CancellationStage;
export const DoctorOperationTerminationSchema = OperationTerminationSchema;
export type DoctorOperationTermination = OperationTermination;
export const DoctorOperationReceiptSchema = OperationReceiptSchema;
export type DoctorOperationReceipt = OperationReceipt;
export const DoctorEffectReceiptSchema = EffectReceiptSchema;
export type DoctorEffectReceipt = EffectReceipt;
