// GENERATED by dashboard/codegen from Rust schemars output. DO NOT EDIT.
// Source: the Serialize contract of dashboard/read_model.rs and every Rust
// payload DTO included by dashboard::contract_schema.
// Deterministic output (stable ordering, no timestamps).

export * from "./generated";
