// AUTO-GENERATED by dashboard/codegen — DO NOT EDIT BY HAND.
// Source: dashboard/codegen/schemas/*.schema.json
// Regenerate: `npm run contracts:generate`  Verify: `npm run contracts:check`
// Deterministic output (stable ordering, no timestamps).

export * from "./generated";
