import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const browser = await chromium.launch();
const base = process.env.BASE_URL ?? 'http://127.0.0.1:5195';
try {
  const page = await browser.newPage({ viewport: { width:1586, height:992 }, reducedMotion:'reduce' });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  const start = performance.now();
  await page.goto(`${base}/?surface=loom&state=04&loom_source=ubuntu`);
  await page.locator('.journey-group').filter({ hasText: /^codex/ }).click();
  assert.equal(new URL(page.url()).searchParams.get('loom_provider'), 'codex');
  assert.equal(await page.locator('.journey-nav-entry').count(), 2);
  await page.getByRole('button', { name:'ALL WORKSTREAMS', exact:true }).click();
  await page.getByRole('button', { name:'AGENT', exact:true }).click();
  await page.locator('.journey-nav-entry').first().waitFor();
  const rows = await page.locator('.journey-nav-entry').count();
  assert.ok(rows < 30 && rows > 0, '808 identities must not become 808 DOM navigation rows');
  assert.match(await page.locator('.loom-head').innerText(), /693 UNIQUE CAPTURED AGENT IDS.*808 SESSIONS/s);
  assert.ok(await page.locator('.journey-group').count() < 30, 'Agent zoom must preserve aggregation until a neighborhood is selected');
  await page.locator('.journey-nav-entry .loom-nav-row').first().focus();
  await page.keyboard.press('End');
  await page.waitForFunction(() => document.activeElement?.getAttribute('data-row') === '807');
  assert.match(await page.locator(':focus').getAttribute('aria-label'), /session 808 of 808/);
  await page.screenshot({ path:'/tmp/loom-dense-ubuntu.png', fullPage:true });
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => Boolean(new URL(location.href).searchParams.get('loom_session')));
  assert.ok(await page.locator('.journey-group').count() < 30);
  assert.match(await page.locator('.journey-group').first().innerText(), /count unavailable/);
  const focusId = new URL(page.url()).searchParams.get('loom_session');
  await page.reload();
  assert.equal(new URL(page.url()).searchParams.get('loom_session'), focusId);
  assert.equal(await page.getByLabel('Loom data source', { exact:true }).inputValue(), 'ubuntu');
  await page.getByRole('button', { name:'EVIDENCE GAPS ↗', exact:true }).click();
  assert.doesNotMatch(await page.locator('.loom-gap-workspace').innerText(), /Code index not sealed/);
  await page.getByLabel('Loom data source', { exact:true }).selectOption('mac');
  await page.waitForURL(url => url.searchParams.get('loom_source') === 'mac');
  await page.locator('.journey-event').first().waitFor();
  assert.equal(new URL(page.url()).searchParams.get('loom_session'), '');
  await page.setViewportSize({ width:640, height:800 });
  await page.getByLabel('Loom data source', { exact:true }).selectOption('ubuntu');
  await page.locator('.journey-navigator').waitFor();
  const reflow = await page.evaluate(() => ({ width:innerWidth, document:document.documentElement.scrollWidth, stage:document.querySelector('.journey-stage').getBoundingClientRect().bottom, legend:document.querySelector('.journey-legend').getBoundingClientRect().top }));
  assert.equal(reflow.document, reflow.width, 'Narrow layout must not clip the footer horizontally');
  assert.ok(reflow.stage <= reflow.legend, 'Navigator and legend must not overlap on reflow');
  await page.screenshot({ path:'/tmp/loom-dense-narrow.png', fullPage:true });
  assert.deepEqual(errors, []);
  console.log(`PASS: 808 real sessions, bounded ${rows}-row navigator, keyboard traversal to row808, focused identity persistence, unknown counts, source-isolated gaps and source switching (${Math.round(performance.now()-start)}ms full flow).`);
} finally { await browser.close(); }
