import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const browser = await chromium.launch();
try {
  const page = await browser.newPage({viewport:{width:1280,height:853},reducedMotion:'reduce'});
  const base = process.env.BASE_URL ?? 'http://127.0.0.1:5195';
  const errors=[];page.on('pageerror', error=>errors.push(error.message));
  const initialTail = `${base}/?surface=loom&loom_source=design&state=01`;
  await page.goto(initialTail);
  await page.getByRole('button',{name:'Load remaining example events →',exact:true}).waitFor();
  assert.equal(new URL(page.url()).searchParams.get('loom_page'),'tail');
  const oldEnd = Number(await page.getByRole('slider',{name:'Seek loaded snapshot',exact:true}).getAttribute('max'));
  assert.equal(oldEnd,Date.parse('2025-05-12T10:08:00Z')/1000,'The tail page ends at its last authored event');
  assert.equal(new URL(page.url()).searchParams.get('loom_follow'),'1');
  assert.equal(new URL(page.url()).searchParams.get('loom_replay'),'0');
  assert.equal(await page.locator('.journey-moment').count(),0,'Follow tail is distinct from paused moment inspection');
  assert.match(await page.locator('.journey-coverage').innerText(),/TAIL EXAMPLE PAGE/);
  const windowControl=page.getByRole('button',{name:'Move visible time window; use left and right arrows',exact:true});
  await windowControl.press('ArrowLeft');
  assert.equal(new URL(page.url()).searchParams.get('loom_follow'),'0','Panning pauses follow');
  assert.equal(Number(await page.getByRole('slider',{name:'Seek loaded snapshot',exact:true}).getAttribute('max')),oldEnd,'Panning cannot move the loaded page boundary');
  await page.getByRole('button',{name:'RETURN TO LOADED TAIL',exact:true}).click();
  assert.equal(new URL(page.url()).searchParams.get('loom_follow'),'1');
  assert.equal(Number(new URL(page.url()).searchParams.get('loom_time')),oldEnd);

  const rows = await page.locator('.loom-fallback').first().locator('tbody tr td:first-child').allTextContents();
  assert.ok(rows.length > 0 && rows.every(time => time <= '05-12 10:08:00'), 'unloaded afternoon records must not enter the exact table');
  await page.locator('.journey-event').first().click();
  const selected = new URL(page.url()).searchParams.get('loom_event');
  const originalRecord = await page.locator('.loom-design-source .loom-pre').textContent();
  await page.getByRole('button',{name:'BACK TO WEAVE',exact:true}).click();
  const paused = new URL(page.url()).searchParams;
  assert.equal(paused.get('loom_follow'),'0','Selecting exact evidence pauses follow');
  await page.getByRole('button',{name:'Load remaining example events →',exact:true}).click();
  await page.waitForURL(/loom_page=full/);
  await page.locator('.journey-field canvas').waitFor();
  const loaded = new URL(page.url()).searchParams;
  for(const key of ['loom_event','loom_time','loom_from','loom_to','loom_session']) assert.equal(loaded.get(key),paused.get(key),`paused ${key} must survive loading`);
  assert.equal(loaded.get('loom_event'),selected);
  assert.ok(Number(await page.getByRole('slider',{name:'Seek loaded snapshot',exact:true}).getAttribute('max')) > oldEnd);
  await page.locator('.journey-event.selected').click();
  assert.equal(await page.locator('.loom-design-source .loom-pre').textContent(), originalRecord, 'loading more records must preserve the exact previously loaded event');
  await page.reload();
  assert.equal(new URL(page.url()).searchParams.get('loom_page'),'full');
  assert.equal(new URL(page.url()).searchParams.get('loom_event'),selected);
  await page.goto(initialTail);
  await page.getByRole('button',{name:'Load remaining example events →',exact:true}).click();
  await page.waitForURL(/loom_page=full/);
  await page.locator('.journey-field canvas').waitFor();
  const following = new URL(page.url()).searchParams;
  assert.equal(following.get('loom_follow'),'1');
  assert.equal(following.get('loom_time'),following.get('loom_to'));
  assert.ok(Number(following.get('loom_to')) > oldEnd, 'following view must advance to newly loaded tail');

  await page.goto(`${base}/?surface=loom&loom_source=design&state=02`);
  await page.waitForURL(url=>url.searchParams.get('loom_replay')==='1');
  const replay=new URL(page.url()).searchParams;
  assert.equal(replay.get('loom_page'),'tail');
  assert.equal(replay.get('loom_follow'),'0');
  assert.equal(replay.get('loom_replay'),'1');
  assert.ok(Number(replay.get('loom_time'))<oldEnd);
  assert.ok(await page.locator('.journey-map-event').evaluateAll((marks,cursor)=>marks.every(mark=>Number(mark.dataset.time)<=cursor),Number(replay.get('loom_time'))));
  await page.goto(`${base}/?surface=loom&loom_source=design&state=03`);
  await page.waitForURL(url=>url.searchParams.get('loom_session')==='design:session:agent-091');
  assert.equal(new URL(page.url()).searchParams.get('loom_page'),'morning');
  assert.equal(new URL(page.url()).searchParams.get('loom_session'),'design:session:agent-091');
  await page.goto(`${base}/?surface=loom&loom_source=design&state=04`);
  await page.waitForURL(url=>url.searchParams.has('loom_from'));
  assert.equal(new URL(page.url()).searchParams.get('loom_page'),'full');
  assert.equal(Number(new URL(page.url()).searchParams.get('loom_from')),Date.parse('2025-05-12T14:06:00Z')/1000);
  await page.goto(`${base}/?surface=loom&loom_source=design&state=01&loom_page=full`);
  assert.equal(new URL(page.url()).searchParams.get('loom_page'),'full','An explicitly requested full page is not replaced by the demonstration default');
  assert.match(await page.locator('.loom-head').innerText(),/EXECUTION INSPECTION/);
  assert.equal(new URL(page.url()).searchParams.get('loom_follow'),'0');
  assert.deepEqual(errors,[]);
  console.log('PASS: loaded-page isolation, immutable selected identity, paused viewport retention, append while following and reload persistence.');
} finally {await browser.close();}
