import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1586, height: 992 }, reducedMotion: 'reduce' });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const base = process.env.BASE_URL ?? 'http://127.0.0.1:5195';
try {
  await page.goto(`${base}/?surface=loom&state=01`);
  await page.locator('.journey-event').first().waitFor();
  const initialFocus = new URL(page.url()).searchParams.get('loom_session');
  const initialWindow = new URL(page.url()).searchParams.get('loom_from');
  await page.locator('.journey-event').nth(1).click();
  if (await page.locator('#loom-event-cluster').isVisible()) await page.locator('#loom-event-cluster button').first().click();
  await page.getByRole('heading', { name: 'EVENT & SOURCE', exact: true }).waitFor();
  const selected = new URL(page.url()).searchParams.get('loom_event');
  assert.ok(selected);
  assert.ok(await page.locator('.loom-pre').innerText().then(text => text.includes(selected)));
  const selectedTime = Number(new URL(page.url()).searchParams.get('loom_time'));
  const evidenceUrl = page.url();
  await page.getByRole('navigation',{name:'Workspaces'}).getByRole('button',{name:/Loom/}).click();
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  assert.equal(page.url(), evidenceUrl, 'Clicking the active workspace must preserve its evidence and replay context');
  assert(await page.getByRole('heading',{name:'EVENT & SOURCE',exact:true}).isVisible());

  await page.getByRole('button', { name: 'BACK TO WEAVE', exact: true }).click();
  assert.equal(new URL(page.url()).searchParams.get('loom_from'), initialWindow);
  assert.equal(new URL(page.url()).searchParams.get('loom_session'), initialFocus, 'opening evidence must not replace the weave focus');
  assert.equal(new URL(page.url()).searchParams.get('loom_event'), selected);
  await page.getByRole('button', { name: 'WORKSTREAM', exact: true }).click();
  assert.equal(new URL(page.url()).searchParams.get('loom_zoom'), 'workstream');
  assert.equal(Number(new URL(page.url()).searchParams.get('loom_time')), selectedTime);
  await page.reload();
  await page.locator('.journey-field[data-level=workstream]').waitFor();
  assert.equal(new URL(page.url()).searchParams.get('loom_event'), selected);
  await page.getByRole('button', { name: 'EPISODE', exact: true }).click();
  await page.getByRole('button', { name: '⛶ FIT', exact: true }).click();
  const loadedRows = await page.locator('.loom-fallback').first().locator('tbody tr').count();
  await page.getByLabel('Scrub loaded page', { exact: true }).press('Home');
  await page.locator('.loom-fallback summary').first().click();
  const revealed = await page.locator('.loom-fallback').first().locator('tbody tr td:first-child').allTextContents();
  const cutoff = new Date(Number(new URL(page.url()).searchParams.get('loom_time')) * 1000).toISOString().slice(5,19).replace('T',' ');
  assert.ok(revealed.length < loadedRows && revealed.every(time => time <= cutoff), 'future events cannot leak through exact table; records exactly at the cursor remain visible');
  await page.getByRole('button', { name: 'RETURN TO LOADED TAIL', exact: true }).click();
  assert.equal(new URL(page.url()).searchParams.get('loom_follow'), '1');
  assert.equal(new URL(page.url()).searchParams.get('loom_to'), new URL(page.url()).searchParams.get('loom_time'), 'return-to-tail moves the visible window to the loaded end');
  await page.getByRole('button', { name: '▽ EVENT FILTERS', exact: true }).click();
  await page.getByLabel('PR MARKER', { exact: true }).check();
  const kinds = await page.locator('.loom-fallback').first().locator('tbody tr td:nth-child(2)').allTextContents();
  assert.ok(kinds.length > 0);
  assert.ok(kinds.every(kind => kind === 'PR MARKER'));
  await page.getByRole('button', { name: 'CLEAR FILTERS', exact: true }).click();
  await page.getByRole('button', { name: '▽ EVENT FILTERS', exact: true }).click();
  await page.getByRole('button', { name: 'AGENT', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Search branches' }).fill('not-an-agent');
  assert.equal(await page.locator('.journey-nav-entry').count(), 0);
  await page.getByRole('searchbox', { name: 'Search branches' }).fill('');
  await page.locator('.journey-pin').first().click();
  await page.getByRole('button', { name: 'PINNED', exact: true }).click();
  assert.equal(await page.locator('.journey-nav-entry').count(), 1);
  await page.screenshot({ path: '/tmp/loom-journey-progress.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('PASS: shared event identity, back-to-weave viewport, semantic zoom, reload, replay cutoff, filters, branch search and pins; no runtime errors.');
} finally { await browser.close(); }
