import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const browser = await chromium.launch();
try {
  const page = await browser.newPage({viewport:{width:1586,height:992}, reducedMotion:'reduce'});
  const errors=[]; page.on('pageerror', e=>errors.push(e.message));
  const base=process.env.BASE_URL ?? 'http://127.0.0.1:5195';
  await page.goto(`${base}/?surface=loom&loom_source=design&state=04`);
  await page.locator('.journey-group').first().waitFor();
  assert.match(await page.locator('.loom-head').innerText(), /CONCEPT \/ SYNTHETIC DATA/);
  assert.equal(await page.locator('.journey-group').count(), 6);
  const evidenceKey = await page.locator('.journey-legend span').evaluateAll(rows => rows.map(row => ({label:row.textContent.trim(), stroke:row.querySelector('path').getAttribute('stroke'), dash:row.querySelector('path').getAttribute('stroke-dasharray')})));
  assert.deepEqual(evidenceKey.map(row => row.label), ['EXACT','EXPLICIT','INFERRED','AMBIGUOUS','STALE','UNAVAILABLE']);
  assert.equal(new Set(evidenceKey.map(row => `${row.stroke}/${row.dash}`)).size, 6, 'Each evidence class has a distinct visual key');

  assert.match(await page.locator('.loom-head').innerText(), /103 UNIQUE AGENTS.*123 WORKSTREAM PARTICIPATIONS/);
  assert.equal((await page.locator('.journey-group small').allTextContents()).reduce((sum,text)=>sum+Number(text.split(' ')[0]),0),123,'group participations may exceed unique agents');
  assert.match(await page.locator('.journey-nav-list').innerText(), /[1-9]\d* high-risk records/);
  assert.match(await page.locator('.journey-nav-list').innerText(), /Relations:.*exact/);
  assert.equal(await page.locator('.journey-density').count(),1,'Dense view exposes a time-density strip');
  assert.equal(await page.locator('.journey-bottom .journey-minimap').count(),1,'Loaded-page minimap remains separate from the time strip');
  await page.getByRole('slider',{name:'Seek visible event density',exact:true}).fill(String(Date.parse('2025-05-12T14:06:03.452Z')/1000));
  assert.equal(new URL(page.url()).searchParams.get('loom_replay'),'1','Seeking the time-density strip enters replay');
  assert.match(await page.locator('.journey-density').getAttribute('aria-label'),/103 revealed records/,'Density counts unique revealed event records, not overlapping participations');
  const replayOverview = new URL(page.url());
  replayOverview.searchParams.set('loom_replay', '1'); replayOverview.searchParams.set('loom_follow', '0');
  replayOverview.searchParams.set('loom_time', String(Date.parse('2025-05-12T14:06:03.452Z') / 1000));
  await page.goto(replayOverview.href); await page.locator('.journey-group').first().waitFor();
  assert.doesNotMatch(await page.locator('.journey-nav-list').innerText(), /[1-9]\d* high-risk records/, 'Navigator counts must withhold future risk');
  await page.goto(`${base}/?surface=loom&loom_source=design&state=04`); await page.locator('.journey-group').first().waitFor();
  await page.getByRole('searchbox', {name:'Search branches'}).fill('TimelineCanvas.tsx');
  await page.waitForFunction(() => new URLSearchParams(location.search).get('loom_query') === 'TimelineCanvas.tsx');
  assert.match(await page.locator('.loom-head').innerText(), /2 UNIQUE AGENTS.*4 WORKSTREAM PARTICIPATIONS/);
  assert.equal(await page.locator('.journey-group').count(), 2, 'two matching identities retain their overlapping workstream participation');
  const filteredDensity = await page.locator('.journey-density').getAttribute('aria-label');
  assert.ok(Number(filteredDensity.match(/(\d+) revealed/)[1])<100,'Density respects the active source search');
  await page.reload();
  assert.equal(await page.getByRole('searchbox', {name:'Search branches'}).inputValue(), 'TimelineCanvas.tsx');
  assert.equal(await page.locator('.journey-group').count(), 2);
  await page.getByRole('searchbox', {name:'Search branches'}).fill('');
  assert.match(await page.locator('.status').innerText(), /DESIGN FIXTURES \/ LOCAL ONLY/);
  await page.screenshot({path:'/tmp/loom-design-dense.png', fullPage:true});
  await page.getByRole('button', {name:'OUTCOME', exact:true}).click();
  assert.equal(await page.locator('.journey-outcome').count(), 6);
  assert.match(await page.locator('.journey-outcomes').innerText(), /exact/);
  await page.getByRole('button', {name:'HIGH RISK', exact:true}).click();
  assert.ok(await page.locator('.journey-outcome').count() < 6);
  await page.reload();
  assert.equal(await page.getByRole('button', {name:'HIGH RISK', exact:true}).getAttribute('aria-pressed'), 'true');
  await page.getByRole('button', {name:'HIGH RISK', exact:true}).click();
  await page.screenshot({path:'/tmp/loom-design-outcome.png', fullPage:true});
  await page.getByRole('button', {name:'WORKSTREAM', exact:true}).click();
  await page.getByRole('button', {name:'▽ EVENT FILTERS',exact:true}).click();
  await page.getByLabel('INFERRED',{exact:true}).check();
  assert.match(await page.locator('.loom-head').innerText(), /1 UNIQUE AGENTS.*2 WORKSTREAM PARTICIPATIONS/);
  assert.ok(await page.locator('.loom-fallback').first().locator('tbody tr').count() > 0, 'inferred relations retain source endpoints');
  assert.ok((await page.locator('.loom-fallback').first().locator('tbody tr td:last-child').allTextContents()).every(grade => grade === 'EXACT'), 'recording an event does not upgrade its inferred relationship');
  await page.getByRole('button',{name:'CLEAR FILTERS',exact:true}).click();
  await page.getByRole('button', {name:'▽ EVENT FILTERS',exact:true}).click();
  assert.ok(await page.locator('.journey-event').count() > 20, 'dense glyphs resolve to actual illustrative events');
  await page.locator('.journey-group').filter({hasText:'Dashboard review'}).click();
  assert.equal(new URL(page.url()).searchParams.get('loom_project'), 'Dashboard review');
  assert.match(await page.locator('.journey-nav-entry .loom-nav-row').first().getAttribute('aria-label'), /of 27/);
  await page.reload();
  assert.equal(new URL(page.url()).searchParams.get('loom_source'), 'design');
  await page.goto(`${base}/?surface=loom&loom_source=design&state=01`);
  await page.locator('.journey-event').first().waitFor();
  await page.getByRole('button', {name:'Zoom in',exact:true}).click();
  const beforePan = new URL(page.url()).searchParams;
  const cursor = beforePan.get('loom_time');
  await page.getByRole('button', {name:'Move visible time window; use left and right arrows'}).focus();
  await page.keyboard.press('ArrowLeft');
  await page.waitForFunction(previous => new URLSearchParams(location.search).get('loom_from') !== previous, beforePan.get('loom_from'));
  assert.equal(new URL(page.url()).searchParams.get('loom_time'), cursor, 'minimap pans independently of replay time');
  const windowBeforeZoom = new URL(page.url()).searchParams;
  await page.getByRole('button', {name:'WORKSTREAM', exact:true}).click();
  assert.equal(new URL(page.url()).searchParams.get('loom_from'), windowBeforeZoom.get('loom_from'), 'semantic zoom preserves visible time');
  await page.getByRole('button', {name:'EPISODE', exact:true}).click();
  assert.ok(await page.locator('.journey-event').count() > 8);
  assert.match(await page.locator('.journey-field').innerText(), /HANDOFF/);
  await page.screenshot({path:'/tmp/loom-design-tail.png',fullPage:true});
  await page.setViewportSize({width:1280,height:853});
  await page.goto(`${base}/?surface=loom&loom_source=design&state=03`);
  await page.locator('.journey-group').first().waitFor();
  assert.match(await page.locator('.journey-field').innerText(), /streaming-ingest/);
  const represented = await page.locator('.journey-event').evaluateAll(glyphs => glyphs.reduce((count,glyph)=>count+Number(glyph.querySelector('sup')?.textContent ?? 1),0));
  assert.equal(represented, await page.locator('.loom-fallback').first().locator('tbody tr').count(), 'exact temporal neighbors remain available as individual source records');
  for (const glyph of await page.locator('.journey-event[popovertarget]').all()) {
    const count=Number(await glyph.locator('sup').innerText());
    await glyph.click();
    assert.equal(await page.locator('#loom-event-cluster').getByRole('button').count(),count,'time-collision inspector exposes every represented source');
    await page.keyboard.press('Escape');
  }
  assert.ok(await page.locator('.journey-minimap path').count() > 0, 'loaded provenance remains connected in the minimap');
  assert.ok(await page.locator('.journey-field').evaluate(field => {
    const bounds=field.getBoundingClientRect();
    return [...field.querySelectorAll('.journey-event span')].every(label => label.getBoundingClientRect().bottom <= bounds.bottom);
  }), 'lowest branch labels fit inside the field at plate size');
  await page.getByRole('button',{name:'COLLAPSE CHILDREN',exact:true}).click();
  const children = page.locator('.journey-collapsed').filter({hasText:'Collapsed children'});
  assert.match(await children.innerText(), /3 sessions · 20 revealed events/);
  assert.match(await children.innerText(), /unavailable/, 'collapsing preserves the missing-return evidence class');
  await children.click();
  assert.equal(await page.locator('.journey-event').evaluateAll(glyphs=>glyphs.reduce((sum,glyph)=>sum+Number(glyph.querySelector('sup')?.textContent ?? 1),0)), await page.locator('.loom-fallback').first().locator('tbody tr').count(), 'expanding restores every source, including close temporal neighbors');
  await page.getByRole('button', {name:'↓ PATH TO OUTCOME', exact:true}).click();
  assert.match(new URL(page.url()).searchParams.get('loom_event'), /rejoin/);
  await page.getByRole('button', {name:'BACK TO WEAVE', exact:true}).click();
  await page.locator('.journey-field').click({position:{x:8,y:8}});
  await page.keyboard.press('Home');
  assert.equal(await page.locator('.journey-event').count(), 0, 'replay start hides all future glyphs');
  await page.getByRole('slider',{name:'Seek loaded snapshot',exact:true}).press('Home');
  assert.equal(await page.locator('.journey-minimap path').count(), 0, 'loaded-page start withholds future provenance, including earlier episode context');
  await page.getByRole('combobox',{name:'Loom data source'}).selectOption('mac');
  await page.waitForURL(/loom_source=mac/);
  assert.doesNotMatch(await page.locator('.loom-head').innerText(), /SYNTHETIC DATA/);
  await page.setViewportSize({width:1280,height:853});
  await page.goto(`${base}/?surface=loom&loom_source=design&state=01`);
  await page.locator('.journey-event').first().waitFor();
  assert.equal(await page.locator('.journey-event').evaluateAll(glyphs=>glyphs.reduce((sum,glyph)=>sum+Number(glyph.querySelector('sup')?.textContent ?? 1),0)), await page.locator('.loom-fallback').first().locator('tbody tr').count(), 'Tail preserves every source through exact anchors and nearby-event inspectors');
  assert.equal(await page.locator('.journey-event > span').count(), await page.locator('.journey-event').count(), 'Every close-view event has a caption');
  assert.match(await page.getByRole('list',{name:'Event symbols'}).innerText(), /TOOL CALL/);
  await page.goto(`${base}/?surface=loom&loom_source=design&state=02`);
  const readButton = page.locator('.journey-event').filter({hasText:'/tests/loom.test.ts'});
  await readButton.waitFor();
  const beforeSeek = await readButton.boundingBox();
  const fieldBounds = await page.locator('.journey-field').boundingBox();
  await page.mouse.click(beforeSeek.x + beforeSeek.width/2, fieldBounds.y + fieldBounds.height - 38);
  await page.waitForFunction(() => Math.abs(Number(new URLSearchParams(location.search).get('loom_time')) - Date.parse('2025-05-12T09:52:00Z')/1000) < 1);
  await page.getByRole('slider', {name:'Scrub loaded page',exact:true}).fill(String(Date.parse('2025-05-12T09:52:00Z')/1000));
  await readButton.waitFor();
  const afterSeek = await readButton.boundingBox();
  assert(Math.abs(beforeSeek.x - afterSeek.x) < .1, 'Revealing or withholding future work must not move past events');
  await page.reload(); await readButton.waitFor();
  assert(Math.abs((await readButton.boundingBox()).x - beforeSeek.x) < .1, 'Recorded time geometry survives URL restoration');
  await page.getByRole('button',{name:'Zoom in',exact:true}).click();
  const panStart = new URL(page.url()).searchParams;
  const panField = await page.locator('.journey-field').boundingBox();
  await page.mouse.move(panField.x + panField.width/2, panField.y + panField.height - 38);
  await page.mouse.down(); await page.mouse.move(panField.x + panField.width/2 + 20, panField.y + panField.height - 38, {steps:2}); await page.mouse.up();
  await page.waitForFunction(from => new URLSearchParams(location.search).get('loom_from') !== from, panStart.get('loom_from'));
  const panEnd = new URL(page.url()).searchParams;
  assert.equal(panEnd.get('loom_time'), panStart.get('loom_time'), 'Dragging the temporal field preserves replay time');
  assert(Math.abs((Number(panEnd.get('loom_to'))-Number(panEnd.get('loom_from'))) - (Number(panStart.get('loom_to'))-Number(panStart.get('loom_from')))) < .001, 'Pan preserves the loaded-window duration');
  await page.setViewportSize({width:793,height:700});
  await page.goto(`${base}/?surface=loom&data=fixture&loom_source=design&state=01`);
  const narrowGlyph=page.locator('.journey-event').first();
  await narrowGlyph.waitFor();
  const anchor=await narrowGlyph.boundingBox();
  await narrowGlyph.focus();
  await page.locator('.journey-point-preview').waitFor();
  const focusedAnchor=await narrowGlyph.boundingBox();
  assert.deepEqual(focusedAnchor,anchor,'Narrow source inspection does not move the exact event anchor');
  assert.match(await page.locator('.journey-point-preview').innerText(),/UTC/);
  assert(await page.locator('.journey-event>span').evaluateAll(labels=>labels.every(label=>getComputedStyle(label).display==='none')),'Crowded captions use the native-focus readout at narrow width');
  await page.screenshot({path:'/tmp/tracedecay-concept-01-narrow.png'});
  assert.deepEqual(errors,[]);
  console.log('PASS: labeled design source, six groups, overlapping group scope, dense event picking, tail branches, replay cutoff and profile isolation.');
} finally {await browser.close();}
