import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const base = process.env.BASE_URL ?? 'http://127.0.0.1:5195';
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1600, height: 1000 }, reducedMotion: 'reduce' });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));

  await page.goto(`${base}/?surface=work&data=snapshot&work_task=T-203`);
  await page.locator('.wk-root.is-snapshot').waitFor();
  assert.equal(await page.locator('.wk-task').count(), 0, 'missing Work authority must render no task cards');
  assert.match(await page.locator('.wk-absence-copy').innerText(), /NO CANONICAL WORK GRAPH/, 'a TaskId query must not synthesize fixture work into an authority-free snapshot');
  assert.equal(await page.locator('.wk-chip:disabled').count(), 5, 'missing Work authority must disable every task projection');
  assert.equal(await page.locator('.wk-thread-glyph[aria-pressed=true]').count(), 1, 'delegation preview keeps an exact selected session');
  assert.match(await page.locator('.wk-inspect').innerText(), /commands\s+not prepared/i, 'snapshot commands must be unavailable');
  const sessionId = await page.locator('.wk-thread-glyph[aria-pressed=true]').getAttribute('title');
  await page.getByRole('button', { name: /Open exact source in Agents|Open represented family in Agents/ }).click();
  await page.waitForURL(/surface=agents/);
  assert.equal(new URL(page.url()).searchParams.get('loom_target_session'), sessionId, 'Agents pivot must retain exact session identity');
  assert.equal(await page.locator('.loom-destination-native').count(), 1, 'exact Mac session should mount the native Agents view');

  await page.goto(`${base}/?surface=work&data=fixture`);
  await page.locator('[data-task-id="T-103"]').waitFor();
  assert.equal(await page.locator('.wk-task').count(), 4, 'default outcome path must focus the selected task and reachable gating neighborhood');
  assert.equal(await page.locator('.wk-plan-context').count(), 2, 'other plans must remain visible as counted stable context');
  assert.match(await page.locator('.wk-inspect').innerText(), /GRAPH REVISION.*revision 7.*OUTCOME EVIDENCE.*No delivery outcome has been recorded/s, 'selected task inspector must distinguish immutable graph revision from absent delivery evidence');
  const selectedBox = await page.locator('[data-task-id="T-102"]').boundingBox();
  const childBox = await page.locator('[data-task-id="T-103"]').boundingBox();
  assert(selectedBox && childBox && selectedBox.y < childBox.y, 'selected outcome root must sit above its real gating descendants');
  const overlaps = (a, b) => a && b && a.left < b.right && a.right > b.left && a.top < b.bottom && a.bottom > b.top;
  const taskBoxes = await page.locator('.wk-task').evaluateAll((elements) => elements.map((element) => {
    const box = element.getBoundingClientRect();
    return { left: box.left, right: box.right, top: box.top, bottom: box.bottom };
  }));
  const obstructorBoxes = await page.locator('.wk-minimap, .wk-plan-context, [role="dialog"], [popover]:popover-open').evaluateAll((elements) => elements.map((element) => {
    const box = element.getBoundingClientRect();
    return { left: box.left, right: box.right, top: box.top, bottom: box.bottom };
  }));
  assert(taskBoxes.every((task) => obstructorBoxes.every((obstructor) => !overlaps(task, obstructor))), 'task cards must not be occluded by minimap, stable plan lanes, or open evidence popovers');
  assert.equal(await page.locator('.wk-mini-relations path').count(), 4, 'minimap must retain every visible typed relation');
  assert.equal(await page.locator('.wk-minimap rect.is-selected').getAttribute('width'), '300', 'minimap selected bounds must match the readable selected task plate');
  const filterCamera = await page.locator('.wk-world').getAttribute('style');
  const filterPosition = await page.locator('[data-task-id="T-103"]').boundingBox();
  await page.getByRole('searchbox', { name: 'Find TaskId or title' }).fill('failure');
  assert.equal(await page.locator('.wk-filter-results [role=option]').count(), 1, 'task search must expose the one exact title match');
  assert.match(await page.locator('.wk-filter-results [role=option]').innerText(), /T-203.*Preserve failure provenance/s, 'matching list must name the canonical TaskId and title');
  assert(await page.locator('[data-task-id="T-103"]').evaluate(element => element.classList.contains('is-muted')), 'nonmatching visible tasks must dim without disappearing');
  assert.equal(await page.locator('.wk-world').getAttribute('style'), filterCamera, 'filtering must not move the camera');
  assert.deepEqual(await page.locator('[data-task-id="T-103"]').boundingBox(), filterPosition, 'filtering must not change task coordinates');
  await page.getByRole('searchbox', { name: 'Find TaskId or title' }).fill('not-a-task');
  assert.match(await page.locator('.wk-filter-results').innerText(), /0 OF 15 TASKS.*NO MATCHING TASKS/s, 'zero matches must remain explicit while graph context stays mounted');
  await page.getByRole('button', { name: 'Clear task filters' }).click();
  assert.equal(await page.locator('.wk-task.is-muted').count(), 0, 'clearing filters must restore the unchanged graph context');
  await page.locator('.wk-field').focus();
  await page.keyboard.press('ArrowLeft');
  assert(Number(await page.locator('.wk-mini-camera').getAttribute('x')) < 0, 'minimap viewport must preserve the true negative inverse camera bound');
  await page.getByRole('button', { name: 'Fit graph' }).click();
  const siblingBefore = await page.locator('[data-task-id="T-104"]').boundingBox();
  await page.locator('[data-task-id="T-103"]').click();
  assert.deepEqual(await page.locator('[data-task-id="T-104"]').boundingBox(), siblingBefore, 'selecting a sibling must preserve the path anchor and screen position');
  await page.locator('[data-task-id="T-103"]').focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.locator(':focus').getAttribute('data-task-id'), 'T-104', 'Right must traverse to the adjacent sibling in the same gating rank');
  await page.keyboard.press('ArrowUp');
  assert.equal(await page.locator(':focus').getAttribute('data-task-id'), 'T-102', 'Up must traverse an actual gating predecessor');
  await page.getByRole('button', { name: 'ROOT PATH' }).click();
  assert.equal(await page.locator('.wk-task').count(), 3, 'root path must show the selected task and its gating ancestors');
  assert.equal(await page.locator('[data-task-id="T-103"]').getAttribute('aria-pressed'), 'true', 'path recomputation must keep the selected TaskId visible');
  await page.getByRole('button', { name: 'OVERVIEW · 15' }).click();
  assert.equal(await page.locator('.wk-task').count(), 15, 'explicit overview must expose the full authored task population');
  assert.equal(await page.locator('.wk-plan-landmark').count(), 3, 'overview must retain all three counted plans as portfolio landmarks');
  assert.equal(await page.locator('.wk-beacon').count(), 5, 'failed, waiting and blocked tasks must remain visible as beacons');
  await page.getByRole('button', { name: 'EXACT TASK TABLE · 15' }).click();
  assert.equal(await page.locator('.wk-task-table [role=row]').count(), 15, 'exact fallback must retain every task identity');
  await page.getByRole('tab', { name: 'TIMELINE' }).click();
  assert.equal(await page.locator('[data-task-id="T-103"]').getAttribute('aria-pressed'), 'true', 'Timeline must preserve the canonical TaskId selection');
  assert.equal(await page.locator('.wk-timeline-axis').count(), 1, 'Timeline must expose its authored event-time axis');
  assert.equal(await page.locator('.wk-unavailable-band').count(), 1, 'Timeline must preserve absent event times in an explicit band');
  assert((await page.locator('[data-task-id="T-101"]').boundingBox()).y > (await page.locator('[data-task-id="T-102"]').boundingBox()).y, 'untimed work must not receive fabricated event coordinates');
  await page.getByRole('tab', { name: 'WORKLOAD' }).click();
  assert.equal(await page.locator('[data-task-id="T-103"]').getAttribute('aria-pressed'), 'true', 'Workload must preserve the canonical TaskId selection');
  assert.equal(await page.locator('.wk-owner-region').count(), 6, 'Workload must group the portfolio by real executor regions');
  assert.notEqual((await page.locator('[data-task-id="T-103"]').boundingBox()).width, (await page.locator('[data-task-id="T-104"]').boundingBox()).width, 'Workload card area must encode authored estimate mass');
  await page.getByRole('tab', { name: 'TOPOLOGY' }).click();
  assert.equal(await page.locator('[data-task-id="T-103"]').getAttribute('aria-pressed'), 'true', 'Topology must preserve the canonical TaskId selection');
  assert(await page.locator('.wk-attempt').count() > 0, 'Topology must expose authored execution attempts');
  await page.getByRole('tab', { name: 'DAG' }).click();
  await page.getByRole('button', { name: 'OUTCOMES' }).click();
  await page.locator('[data-task-id="T-103"]').click();
  assert.match(await page.locator('.wk-inspect').innerText(), /No incomplete gating predecessor/, 'failed informational evidence must not gate readiness');
  assert.match(await page.locator('.wk-inspect').innerText(), /informational/i, 'the non-gating failure relation must remain inspectable');

  await page.getByRole('tab', { name: 'CAUSAL' }).click();
  assert.equal(await page.locator('[data-task-id="T-103"]').getAttribute('aria-pressed'), 'true', 'TaskId selection must survive projection changes');
  await page.getByRole('tab', { name: 'DAG' }).click();
  await page.locator('[data-task-id="T-105"]').click();
  const blockedRank = await page.locator('[data-task-id="T-105"]').boundingBox();
  assert.match(await page.locator('.wk-inspect').innerText(), /1 gating blocker/);
  await page.getByRole('button', { name: 'Replan blocking edge' }).click();
  assert.match(await page.locator('.wk-inspect').innerText(), /READY/, 'replanning the gating edge must recompute readiness');
  const replannedRank = await page.locator('[data-task-id="T-105"]').boundingBox();
  assert(replannedRank.y < blockedRank.y, 'DAG rank must recompute from the surviving gating relations after replan');
  await page.locator('[data-task-id="T-104"]').click();
  await page.getByRole('button', { name: 'Record fixture success' }).click();
  assert.match(await page.locator('.wk-inspect').innerText(), /DONE/, 'legal completion must update local fixture state');

  await page.setViewportSize({ width: 1263, height: 992 });
  const toolbarBox = await page.locator('.wk-controls').boundingBox();
  const cameraControls = await page.locator('.wk-tools button').evaluateAll(elements => elements.map(element => { const box = element.getBoundingClientRect(); return { left: box.left, right: box.right, top: box.top, bottom: box.bottom }; }));
  assert(toolbarBox && cameraControls.length === 4 && cameraControls.every(box => box.left >= toolbarBox.x && box.right <= toolbarBox.x + toolbarBox.width && box.top >= toolbarBox.y && box.bottom <= toolbarBox.y + toolbarBox.height), 'Fit, zoom and Back controls must remain fully inside the Work toolbar at 1263px');
  await page.getByRole('button', { name: 'Fit graph' }).click();
  const fittedAt1263 = await page.locator('.wk-world').getAttribute('style');
  await page.getByRole('button', { name: 'Zoom in' }).click();
  await page.getByRole('button', { name: 'Previous camera' }).click();
  assert.equal(await page.locator('.wk-world').getAttribute('style'), fittedAt1263, 'Fit and Back must be operable at 1263px');
  const cameraBefore = await page.locator('.wk-world').getAttribute('style');
  await page.getByRole('button', { name: 'Zoom in' }).click();
  assert.notEqual(await page.locator('.wk-world').getAttribute('style'), cameraBefore, 'zoom control must change the continuous camera');
  await page.setViewportSize({ width: 760, height: 900 });
  await page.getByRole('button', { name: 'Fit graph' }).click();
  const fittedStyle = await page.locator('.wk-world').getAttribute('style');
  const fieldBox = await page.locator('.wk-field').boundingBox();
  const fittedTasks = await page.locator('.wk-task').evaluateAll(elements => elements.map(element => { const box = element.getBoundingClientRect(); return { left: box.left, top: box.top, right: box.right, bottom: box.bottom }; }));
  assert(fieldBox && fittedTasks.every(box => box.left >= fieldBox.x && box.right <= fieldBox.x + fieldBox.width && box.top >= fieldBox.y && box.bottom <= fieldBox.y + fieldBox.height), 'Fit must use the current narrow viewport and visible task bounds');
  await page.getByRole('button', { name: 'Zoom in' }).click();
  await page.locator('.wk-field').focus();
  await page.keyboard.press('0');
  assert.equal(await page.locator('.wk-world').getAttribute('style'), fittedStyle, '0 must use the same measured fit as the visible control and minimap');
  const bounds = await page.locator('.wk-root').evaluate(element => ({ scrollWidth: element.scrollWidth, clientWidth: element.clientWidth, scrollHeight: element.scrollHeight, clientHeight: element.clientHeight }));
  assert(bounds.scrollWidth <= bounds.clientWidth, 'narrow Work must not overflow horizontally');
  assert(bounds.scrollHeight > bounds.clientHeight, 'narrow Work should expose its expanded inspector through surface scrolling');
  await page.locator('.wk-root').evaluate(element => { element.scrollTop = element.scrollHeight; });
  await page.getByRole('button', { name: 'Delivery', exact: true }).scrollIntoViewIfNeeded();
  assert(await page.getByRole('button', { name: 'Delivery', exact: true }).isVisible(), 'narrow task pivots must remain reachable');

  await page.setViewportSize({ width: 1600, height: 1000 });
  await page.goto(`${base}/?surface=work&data=fixture&work_task=T-204`);
  await page.locator('[data-task-id="T-204"][aria-pressed=true]').waitFor();
  assert.equal(await page.locator('.wk-task').count(), 5, 'an exact Work arrival must reveal its plan neighborhood once');
  await page.goto(`${base}/?surface=work&data=fixture&work_task=T-999`);
  assert.match(await page.getByRole('alert').innerText(), /not present/, 'an unknown Work arrival must remain explicit and preserve local selection');

  await page.evaluate(() => sessionStorage.setItem('td:view:fixture:work.fixture.graph', JSON.stringify({ revision: 99, tasks: [], relations: [], events: [] })));
  await page.reload();
  await page.locator('[data-task-id="T-204"]').waitFor();
  assert.match(await page.locator('.wk-fixture-board .wk-panel-head').innerText(), /revision 7/, 'invalid optional fixture memory must recover to the complete authored graph');

  await page.evaluate(() => {
    sessionStorage.setItem('td:view:fixture:work.fixture.camera.v2', JSON.stringify({ x: 0, y: 0, zoom: 0 }));
    sessionStorage.setItem('td:view:fixture:work.fixture.camera-history.v2', JSON.stringify([{}]));
  });
  await page.reload();
  await page.locator('[data-task-id="T-204"]').waitFor();
  const recoveredCamera = await page.locator('.wk-world').getAttribute('style');
  assert.match(recoveredCamera, /translate\(0px, 8px\) scale\(1\)/, 'invalid direct camera memory must render through the canonical focus camera');
  assert(await page.getByRole('button', { name: 'Previous camera' }).isDisabled(), 'invalid history entries must be discarded before Back can consume them');
  await page.getByRole('button', { name: 'Zoom in' }).click();
  await page.getByRole('button', { name: 'Previous camera' }).click();
  assert.equal(await page.locator('.wk-world').getAttribute('style'), recoveredCamera, 'Back must remain usable after malformed history recovery');
  await page.getByRole('combobox', { name: 'Filter tasks by status' }).selectOption('failed');
  assert.equal(await page.locator('.wk-filter-results [role=option]').count(), 1, 'failed status filter must find the authored failed task without scanning the canvas');
  await page.locator('.wk-filter-results [role=option]').click();
  assert.equal(await page.locator('[data-task-id="T-203"]').getAttribute('aria-pressed'), 'true', 'choosing a matching result must update the canonical TaskId selection');
  await page.getByRole('tab', { name: 'TIMELINE' }).click();
  assert.equal(await page.locator('[data-task-id="T-203"]').getAttribute('aria-pressed'), 'true', 'filtered TaskId selection must survive projection changes');
  await page.getByRole('combobox', { name: 'Filter tasks by status' }).selectOption('blocked');
  assert.equal(await page.locator('.wk-filter-results [role=option]').count(), 3, 'blocked filter must expose every authored blocked task');
  await page.getByRole('button', { name: 'Clear task filters' }).click();
  assert.deepEqual(errors, []);
  console.log('PASS Work authority refusal, ranked gating traversal/replan, truthful projections, typed actions, exact arrivals, storage recovery, camera and narrow reachability');
} finally {
  await browser.close();
}
