#!/usr/bin/env python3
"""Reproducible TraceDecay efficiency scorecard.

One command produces a machine-readable JSON scorecard plus a human summary
for the product journeys every efficiency lane touches, so a win or a
regression can be proven by running the same command on two commits and
diffing two files.

    scripts/efficiency-scorecard.py                       # build + run (3 runs)
    scripts/efficiency-scorecard.py --binary target/release/tracedecay
    scripts/efficiency-scorecard.py --quick               # 1 run smoke (~1 min)
    scripts/efficiency-scorecard.py --label b9181367ba \
        --binary /path/to/old/tracedecay --output target/effscore-base

Outputs (under --output, default target/efficiency-scorecard):
    scorecard.json   tracedecay.efficiency-scorecard/v1 (schema below)
    summary.md       the human table, also printed to stdout

What is measured
----------------
Every run builds a fresh SANDBOX under the OS temp dir — isolated HOME/XDG,
isolated TRACEDECAY_DATA_DIR/GLOBAL_DB, private daemon socket — and drives
the pinned fixture repo through the production journeys with the real
binary. The operator's daemon, profile, and stores are never touched.

    phase                metric
    -------------------- ----------------------------------------------------
    daemon_start_empty   spawn -> socket bind, on an empty profile
    cold_index           `tracedecay init` -> code_index_freshness "current"
                         (wall), plus the daemon's own generation build
                         elapsed and the seal->activation span
    tool_calls           p50/p95/max of `tool` CLI round-trips: search, grep,
                         context, status, fact_store_search (memory recall);
                         N samples per tool after fixed warm-up
    incremental_sync     one-file edit + commit, `tracedecay sync` -> the NEW
                         generation is "current" (wall + seal->activation)
    daemon_restart       SIGTERM -> exit, respawn -> freshness "current"
                         again over the populated store (activation/replay
                         cost on startup)
    store size           tracedecay.db/-wal/-shm bytes and per-generation
                         artifact sizes after cold index and after sync
    peak RSS             per-phase max daemon VmRSS (50 ms sampling) plus
                         whole-process VmHWM

Determinism policy
------------------
- Fixture: benchmark_data/index-bench/corpus (committed, generated by a pure
  function of the file ordinal). The tree digest is recorded; two scorecards
  are comparable only when their fixture digests match.
- The fixture copy is committed in the sandbox with pinned git author,
  committer, and timestamps, so the fixture commit SHA is a constant.
- Fixed query set, fixed warm-up (2 untimed calls per tool), fixed sample
  counts, fixed observer cadence (50 ms). Repetition: the whole scenario runs
  --runs times (default 3); the scorecard reports per-run values and the
  cross-run median for every scalar.
- Each measured wait uses one long-lived MCP observer process/connection
  on the healthy path. If that observer becomes unusable (proxy exit or
  handshake failure), it is closed and a new observer is opened; reconnects
  increment the recorded process/connection counts. Wall times that end on
  an observation quantize at the observer cadence plus one protocol
  round-trip; the identical policy applies to every commit being compared,
  and the medians absorb scheduler noise.
- Load averages before/after are recorded; compare scorecards captured
  under comparable load.

Readiness is the product's own signal: the `status` tool reports
code_index_freshness.status == "current" only when the latest generation is
sealed, complete, and fresh. "seal->activation" is the span from the
generation's sealed_at_micros (daemon clock) to the poll that first observed
"current" (host clock, same machine).

The daemon binary is driven purely from outside (CLI + daemon socket); the
harness never links daemon code, reads private store schemas, or queries
SQLite directly. Store sizes come from the filesystem.

Failure policy: any phase that misses its deadline fails the run; the
scorecard records the typed reason and the process exits 1. Exit 2 is a
harness/usage error and never a performance verdict.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import select
import shutil
import signal
import statistics
import subprocess
import sys
import tempfile
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path

SCHEMA = "tracedecay.efficiency-scorecard/v1"
REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_FIXTURE = REPO_ROOT / "benchmark_data" / "index-bench" / "corpus"

# Pinned edit target for the incremental-sync phase (must exist in the fixture).
TOUCH_FILE = Path("rust") / "watermark_010.rs"
TOUCH_APPEND = (
    "\n/// Scorecard incremental-sync probe appended by efficiency-scorecard.py.\n"
    "pub fn scorecard_incremental_probe(seed: u64) -> u64 {\n"
    "    seed.wrapping_mul(2654435761).wrapping_add(40503)\n"
    "}\n"
)

# Pinned tool-call battery. Sample i of a tool uses queries[i % len(queries)].
SEARCH_QUERIES = ("BeaconState010", "capsule_0", "WatermarkState021", "aperture_1")
CONTEXT_TASKS = (
    "Explain BeaconState010 and its callers",
    "How does capsule_0 assemble its window",
    "Trace WatermarkState021 through related symbols",
    "What calls aperture_1 and what does it call",
)
GREP_PATTERNS = ("saturating_add", "Bounded accumulator over an ordered keyspace")
RECALL_QUERIES = ("fixture corpus decision", "daemon socket policy")
SEED_FACTS = (
    "The scorecard fixture corpus is generated deterministically; the decision "
    "was to pin it and record its tree digest in every capture.",
    "The scorecard daemon runs on a private socket inside the sandbox; the "
    "policy is that the operator daemon is never contacted.",
    "Incremental sync is measured after a one-file edit and commit so the "
    "delta plan has exactly one changed source file.",
)

GIT_ENV = {
    "GIT_CONFIG_GLOBAL": "/dev/null",
    "GIT_CONFIG_SYSTEM": "/dev/null",
    "GIT_CONFIG_NOSYSTEM": "1",
    "GIT_AUTHOR_NAME": "TraceDecay Scorecard",
    "GIT_AUTHOR_EMAIL": "scorecard@tracedecay.invalid",
    "GIT_AUTHOR_DATE": "2026-01-01T00:00:00 +0000",
    "GIT_COMMITTER_NAME": "TraceDecay Scorecard",
    "GIT_COMMITTER_EMAIL": "scorecard@tracedecay.invalid",
    "GIT_COMMITTER_DATE": "2026-01-01T00:00:00 +0000",
}

POLL_INTERVAL_SECONDS = 0.05
TOOL_CALL_TIMEOUT = float(os.environ.get("SCORECARD_TOOL_TIMEOUT", "60"))
STARTUP_DEADLINE = float(os.environ.get("SCORECARD_STARTUP_DEADLINE", "120"))
COLD_INDEX_DEADLINE = float(os.environ.get("SCORECARD_COLD_INDEX_DEADLINE", "900"))
SYNC_DEADLINE = float(os.environ.get("SCORECARD_SYNC_DEADLINE", "600"))
RESTART_DEADLINE = float(os.environ.get("SCORECARD_RESTART_DEADLINE", "600"))


class PhaseFailure(RuntimeError):
    """A measured phase missed its deadline or produced an invalid state."""

    def __init__(self, phase: str, reason: str) -> None:
        super().__init__(f"{phase}: {reason}")
        self.phase = phase
        self.reason = reason


class HarnessError(RuntimeError):
    """A usage/environment error that is never a performance verdict."""


def percentile(values: list[float], quantile: float) -> float:
    ordered = sorted(values)
    index = min(len(ordered) - 1, max(0, math.ceil(quantile * len(ordered)) - 1))
    return ordered[index]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_tree(root: Path) -> str:
    digest = hashlib.sha256()
    for entry in sorted(root.rglob("*")):
        if not entry.is_file():
            continue
        digest.update(entry.relative_to(root).as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(bytes.fromhex(sha256_file(entry)))
    return digest.hexdigest()


def tree_size_bytes(root: Path) -> int:
    return sum(entry.stat().st_size for entry in root.rglob("*") if entry.is_file())


class RssSampler:
    """Samples the daemon's VmRSS every 50 ms, tagged with the active phase.

    Peak RSS per phase is the max sampled VmRSS while that phase was active;
    a spike shorter than the cadence can be missed, identically on every
    commit being compared. VmHWM (whole-process high-water mark) is also
    read at each phase boundary as untagged context.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._pid: int | None = None
        self._phase = "idle"
        self._peaks: dict[str, int] = {}
        self._hwm: dict[str, int] = {}
        self._stop = threading.Event()
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def set_pid(self, pid: int | None) -> None:
        with self._lock:
            self._pid = pid

    def set_phase(self, phase: str) -> None:
        with self._lock:
            previous = self._phase
            self._phase = phase
            pid = self._pid
        if pid is not None:
            hwm = self._read_kb(pid, "VmHWM:")
            if hwm is not None:
                with self._lock:
                    self._hwm[previous] = max(self._hwm.get(previous, 0), hwm * 1024)

    @staticmethod
    def _read_kb(pid: int, label: str) -> int | None:
        try:
            for line in (Path("/proc") / str(pid) / "status").read_text().splitlines():
                if line.startswith(label):
                    return int(line.split()[1])
        except (OSError, ValueError, IndexError):
            return None
        return None

    def _run(self) -> None:
        while not self._stop.wait(POLL_INTERVAL_SECONDS):
            with self._lock:
                pid, phase = self._pid, self._phase
            if pid is None:
                continue
            rss = self._read_kb(pid, "VmRSS:")
            if rss is None:
                continue
            with self._lock:
                key = phase
                value = rss * 1024
                if value > self._peaks.get(key, 0):
                    self._peaks[key] = value

    def finish(self) -> tuple[dict[str, int], dict[str, int]]:
        self.set_phase("idle")
        self._stop.set()
        self._thread.join(timeout=2.0)
        with self._lock:
            return dict(self._peaks), dict(self._hwm)


class StatusObserver:
    """One persistent MCP connection for a measured readiness phase."""

    def __init__(self, sandbox: Sandbox) -> None:
        self._sandbox = sandbox
        self.log_path = sandbox.root / f"status-observer-{sandbox.observer_process_count}.log"
        self._stderr = self.log_path.open("wb")
        try:
            self._process = subprocess.Popen(
                (str(sandbox.binary), "serve", "--path", str(sandbox.project)),
                cwd=sandbox.project,
                env=sandbox.env,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=self._stderr,
                start_new_session=True,
                bufsize=0,
            )
        except OSError:
            self._stderr.close()
            raise
        if self._process.stdin is None or self._process.stdout is None:
            self.close()
            raise HarnessError("could not create status observer MCP pipes")
        self._input = self._process.stdin
        self._output = self._process.stdout
        self._next_id = 0
        self._buffer = b""
        self._initialized = False
        self._usable = True

    @property
    def usable(self) -> bool:
        return self._usable

    def __enter__(self) -> StatusObserver:
        return self

    def __exit__(self, *_args: object) -> None:
        self.close()

    def close(self) -> None:
        process = self._process
        input_stream = getattr(self, "_input", None)
        output_stream = getattr(self, "_output", None)
        if input_stream is not None:
            try:
                input_stream.close()
            except OSError:
                pass
        if process.poll() is None:
            try:
                process.wait(timeout=3)
            except subprocess.TimeoutExpired:
                try:
                    os.killpg(process.pid, signal.SIGTERM)
                except ProcessLookupError:
                    pass
                try:
                    process.wait(timeout=2)
                except subprocess.TimeoutExpired:
                    try:
                        os.killpg(process.pid, signal.SIGKILL)
                    except ProcessLookupError:
                        pass
                    process.wait(timeout=2)
        if output_stream is not None:
            try:
                output_stream.close()
            except OSError:
                pass
        if not self._stderr.closed:
            self._stderr.close()

    def status_payload(self) -> dict | None:
        """Read status through this observer; None while the route is unavailable."""
        if not self._usable:
            return None
        try:
            if not self._initialized:
                self._initialize()
            self._sandbox.observer_request_count += 1
            response = self._request(
                "tools/call",
                {
                    "name": "tracedecay_status",
                    "arguments": {
                        "format": "json",
                        "include_branch_diagnostics": False,
                    },
                },
                TOOL_CALL_TIMEOUT,
            )
            if response is None or response.get("error") is not None:
                return None
            result = response["result"]
            if result.get("isError") is True:
                return None
            return json.loads(result["content"][0]["text"])
        except (KeyError, OSError, TypeError, ValueError):
            self._usable = False
            return None

    def _initialize(self) -> None:
        response = self._request(
            "initialize",
            {
                "protocolVersion": "2024-11-05",
                "capabilities": {},
                "clientInfo": {"name": "tracedecay-efficiency-scorecard", "version": "1"},
            },
            TOOL_CALL_TIMEOUT,
        )
        if response is None or response.get("error") is not None:
            raise OSError("status observer MCP initialize failed")
        self._send(
            {
                "jsonrpc": "2.0",
                "method": "notifications/initialized",
                "params": {},
            }
        )
        self._initialized = True

    def _request(self, method: str, params: dict, timeout: float) -> dict | None:
        self._next_id += 1
        request_id = self._next_id
        self._send(
            {
                "jsonrpc": "2.0",
                "id": request_id,
                "method": method,
                "params": params,
            }
        )
        deadline = time.monotonic() + timeout
        while (remaining := deadline - time.monotonic()) > 0:
            message = self._read(remaining)
            if message is None:
                return None
            if message.get("id") == request_id:
                return message
        return None

    def _send(self, value: dict) -> None:
        if self._process.poll() is not None:
            raise OSError(f"status observer exited with {self._process.returncode}")
        self._input.write(json.dumps(value, separators=(",", ":")).encode() + b"\n")
        self._input.flush()

    def _read(self, timeout: float) -> dict | None:
        while True:
            if b"\n" in self._buffer:
                line, _, self._buffer = self._buffer.partition(b"\n")
                if not line.strip():
                    continue
                value = json.loads(line)
                if not isinstance(value, dict):
                    raise ValueError("status observer emitted a non-object response")
                return value
            ready, _, _ = select.select([self._output.fileno()], [], [], timeout)
            if not ready:
                return None
            chunk = os.read(self._output.fileno(), 65_536)
            if not chunk:
                raise OSError("status observer closed stdout before responding")
            self._buffer += chunk


@dataclass
class Sandbox:
    """One disposable, isolated profile + fixture project + daemon."""

    binary: Path
    fixture: Path
    keep: bool
    root: Path = field(init=False)
    project: Path = field(init=False)
    profile: Path = field(init=False)
    socket: Path = field(init=False)
    env: dict[str, str] = field(init=False)
    daemon: subprocess.Popen | None = field(init=False, default=None)
    daemon_log_index: int = field(init=False, default=0)
    observer_process_count: int = field(init=False, default=0)
    observer_connection_count: int = field(init=False, default=0)
    observer_request_count: int = field(init=False, default=0)
    # Called with the daemon pid immediately after spawn, before the socket
    # bind wait, so the RSS sampler covers the startup window too.
    on_spawn: object = field(init=False, default=None)

    def __post_init__(self) -> None:
        base = Path(tempfile.mkdtemp(prefix="tdscore.", dir=os.environ.get("TMPDIR", "/tmp")))
        self.root = base
        self.project = base / "project"
        self.profile = base / "profile"
        self.socket = base / "d.sock"
        if len(str(self.socket)) > 100:
            raise HarnessError(
                f"socket path '{self.socket}' is too long for a Unix socket; set TMPDIR shorter"
            )
        home = base / "home"
        for path in (self.profile, home / ".local" / "share", home / ".config", base / "tmp"):
            path.mkdir(parents=True, exist_ok=True)

        env = {
            key: value
            for key, value in os.environ.items()
            if not key.startswith(("TRACEDECAY_", "GIT_"))
        }
        env.update(
            HOME=str(home),
            XDG_DATA_HOME=str(home / ".local" / "share"),
            XDG_CONFIG_HOME=str(home / ".config"),
            TMPDIR=str(base / "tmp"),
            TRACEDECAY_DATA_DIR=str(self.profile),
            TRACEDECAY_GLOBAL_DB=str(self.profile / "global.db"),
            TRACEDECAY_DAEMON_SOCKET=str(self.socket),
        )
        env.update(GIT_ENV)
        self.env = env
        self._seed_project()

    def _seed_project(self) -> None:
        shutil.copytree(self.fixture, self.project, copy_function=shutil.copy2)
        self.git("init", "-q", "-b", "main")
        self.git("add", "-A")
        self.git("commit", "-q", "-m", "scorecard fixture corpus")

    def git(self, *args: str) -> None:
        completed = subprocess.run(
            ("git", *args),
            cwd=self.project,
            env=self.env,
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )
        if completed.returncode != 0:
            raise HarnessError(f"git {args[0]} failed in sandbox: {completed.stderr.strip()}")

    def head_commit(self) -> str:
        completed = subprocess.run(
            ("git", "rev-parse", "HEAD"),
            cwd=self.project,
            env=self.env,
            capture_output=True,
            text=True,
            timeout=60,
            check=False,
        )
        return completed.stdout.strip()

    # ── daemon lifecycle ─────────────────────────────────────────────────

    def spawn_daemon(self) -> float:
        """Start the daemon; return seconds from spawn to socket bind."""
        self.daemon_log_index += 1
        started = time.monotonic()
        with (self.root / f"daemon-{self.daemon_log_index}.log").open("wb") as log:
            self.daemon = subprocess.Popen(
                (str(self.binary), "daemon", "run", "--socket", str(self.socket)),
                cwd=self.project,
                env=self.env,
                stdout=log,
                stderr=subprocess.STDOUT,
                start_new_session=True,
            )
        if callable(self.on_spawn):
            self.on_spawn(self.daemon.pid)
        deadline = started + STARTUP_DEADLINE
        while not self.socket.exists():
            if self.daemon.poll() is not None:
                raise PhaseFailure("daemon_start", "daemon exited before binding its socket")
            if time.monotonic() > deadline:
                raise PhaseFailure(
                    "daemon_start", f"socket not bound within {STARTUP_DEADLINE}s"
                )
            time.sleep(0.005)
        return time.monotonic() - started

    def stop_daemon(self) -> None:
        daemon = self.daemon
        if daemon is None:
            return
        self.daemon = None
        if daemon.poll() is None:
            try:
                os.killpg(daemon.pid, signal.SIGTERM)
            except ProcessLookupError:
                pass
            try:
                daemon.wait(timeout=15)
            except subprocess.TimeoutExpired:
                try:
                    os.killpg(daemon.pid, signal.SIGKILL)
                except ProcessLookupError:
                    pass
                # SIGKILL cannot be ignored, but tearing down a multi-GB
                # daemon can outlast a short bound and a timeout here would
                # mask the run's own result from the caller's `finally`.
                daemon.wait()
        self.socket.unlink(missing_ok=True)

    def daemon_alive(self) -> bool:
        return self.daemon is not None and self.daemon.poll() is None

    def daemon_log_tail(self) -> str:
        path = self.root / f"daemon-{self.daemon_log_index}.log"
        try:
            return path.read_text(errors="replace")[-4096:]
        except OSError:
            return "(no daemon log)"

    # ── CLI drivers ──────────────────────────────────────────────────────

    def run_cli(self, *args: str, timeout: float) -> subprocess.CompletedProcess:
        return subprocess.run(
            (str(self.binary), *args),
            cwd=self.project,
            env=self.env,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )

    def tool_json(self, name: str, arguments: dict, timeout: float = TOOL_CALL_TIMEOUT) -> dict:
        try:
            completed = self.run_cli(
                "tool",
                name,
                "--project",
                str(self.project),
                "--args",
                json.dumps(arguments, separators=(",", ":"), sort_keys=True),
                "--json",
                timeout=timeout,
            )
        except subprocess.TimeoutExpired as expired:
            raise PhaseFailure(f"tool_{name}", f"timed out after {timeout}s") from expired
        if completed.returncode != 0:
            raise PhaseFailure(
                f"tool_{name}", f"exit {completed.returncode}: {completed.stderr.strip()[:400]}"
            )
        envelope = json.loads(completed.stdout)
        return json.loads(envelope["content"][0]["text"])

    def open_status_observer(self) -> StatusObserver:
        observer = StatusObserver(self)
        self.observer_process_count += 1
        self.observer_connection_count += 1
        return observer

    def cleanup(self) -> None:
        self.stop_daemon()
        if self.keep:
            print(f"scorecard: sandbox kept at {self.root}", file=sys.stderr)
        else:
            shutil.rmtree(self.root, ignore_errors=True)


def freshness(payload: dict) -> dict:
    return payload.get("code_index_freshness") or {}


def freshness_current(payload: dict) -> bool:
    return freshness(payload).get("status") == "current"


def latest_generation(payload: dict) -> str | None:
    worktree = freshness(payload).get("worktree") or {}
    return worktree.get("latest_generation_id")


def source_revision(payload: dict) -> str | None:
    worktree = freshness(payload).get("worktree") or {}
    return worktree.get("source_revision")


def wait_for(
    sandbox: Sandbox,
    phase: str,
    deadline_seconds: float,
    predicate,
) -> tuple[float, dict, float]:
    """Observe `status` until predicate(payload); return (wall, payload, observed_at).

    One observer process/connection is used for the whole wait on the healthy
    path. An unusable observer (proxy death, failed handshake, broken JSON-RPC
    stream) is closed and a new one is opened so readiness polling keeps the
    same retry cadence as the old per-poll CLI, with reconnects visible in
    the observer process/connection counts.
    """
    started = time.monotonic()
    deadline = started + deadline_seconds
    while True:
        with sandbox.open_status_observer() as observer:
            while True:
                payload = observer.status_payload()
                observed_at = time.time()
                if payload is not None and predicate(payload):
                    return time.monotonic() - started, payload, observed_at
                if not sandbox.daemon_alive():
                    raise PhaseFailure(
                        phase, f"daemon exited; log tail: {sandbox.daemon_log_tail()}"
                    )
                if time.monotonic() > deadline:
                    state = (
                        "unanswered"
                        if payload is None
                        else json.dumps(freshness(payload))[:300]
                    )
                    reason = (
                        f"not ready within {deadline_seconds}s (last freshness: {state})"
                    )
                    if not observer.usable:
                        reason = (
                            f"{reason}; last observer unusable, stderr: {observer.log_path}"
                        )
                    raise PhaseFailure(phase, reason)
                time.sleep(POLL_INTERVAL_SECONDS)
                if not observer.usable:
                    break


def seal_to_activation_seconds(payload: dict, observed_at: float) -> float | None:
    worktree = freshness(payload).get("worktree") or {}
    sealed_at_micros = worktree.get("sealed_at_micros")
    if not isinstance(sealed_at_micros, int) or sealed_at_micros <= 0:
        return None
    return round(observed_at - sealed_at_micros / 1_000_000.0, 3)


GENERATION_DIGEST = re.compile(r"([0-9a-f]{64})")


def store_measurements(sandbox: Sandbox) -> dict:
    """Filesystem sizes of the sandbox store, attributed without private schema
    knowledge.

    - `generation_payload_bytes`: files under `**/code-generations-v*/`
      grouped by the 64-hex generation digest embedded in the file name
      (generation-<digest>.json) — the manifest-size-per-generation signal.
    - `generation_segment_bytes`: physical bytes in the shared
      `code-generation-segments-v*/` content-addressed pool.
    - `code_index_children_bytes`: one-level size breakdown under each
      `code-index-v1/<worktree-key>/` (generation payloads vs the
      content-addressed text-artifact pool vs everything else).
    - `top_level_bytes`: one-level breakdown of the whole project store.
    """
    stores = []
    projects_root = sandbox.profile / "projects"
    if projects_root.is_dir():
        for store in sorted(projects_root.iterdir()):
            if not store.is_dir():
                continue
            db = store / "tracedecay.db"
            generations: dict[str, int] = {}
            for generations_root in sorted(store.rglob("code-generations-v*")):
                if not generations_root.is_dir():
                    continue
                for entry in sorted(generations_root.iterdir()):
                    if not entry.is_file():
                        continue
                    match = GENERATION_DIGEST.search(entry.name)
                    key = match.group(1)[:16] if match else "unattributed"
                    generations[key] = generations.get(key, 0) + entry.stat().st_size
            generation_segment_bytes = sum(
                tree_size_bytes(root)
                for root in sorted(store.rglob("code-generation-segments-v*"))
                if root.is_dir()
            )
            code_index_children: dict[str, int] = {}
            for code_index_root in sorted(store.glob("code-index-v*")):
                for worktree_dir in sorted(code_index_root.iterdir()):
                    if not worktree_dir.is_dir():
                        continue
                    for child in sorted(worktree_dir.iterdir()):
                        size = (
                            tree_size_bytes(child) if child.is_dir() else child.stat().st_size
                        )
                        code_index_children[child.name] = (
                            code_index_children.get(child.name, 0) + size
                        )
            stores.append(
                {
                    "store": store.name,
                    "db_bytes": db.stat().st_size if db.exists() else 0,
                    "wal_bytes": (
                        db.with_name(db.name + "-wal").stat().st_size
                        if db.with_name(db.name + "-wal").exists()
                        else 0
                    ),
                    "shm_bytes": (
                        db.with_name(db.name + "-shm").stat().st_size
                        if db.with_name(db.name + "-shm").exists()
                        else 0
                    ),
                    "store_tree_bytes": tree_size_bytes(store),
                    "generation_count": len(
                        [key for key in generations if key != "unattributed"]
                    ),
                    "generation_payload_bytes": generations,
                    "generation_segment_bytes": generation_segment_bytes,
                    "code_index_children_bytes": code_index_children,
                    "top_level_bytes": {
                        child.name: (
                            tree_size_bytes(child) if child.is_dir() else child.stat().st_size
                        )
                        for child in sorted(store.iterdir())
                    },
                }
            )
    return {
        "profile_tree_bytes": tree_size_bytes(sandbox.profile),
        "project_stores": stores,
    }


def graph_statistics(payload: dict) -> dict:
    stats = payload.get("graph_statistics") or {}
    if stats.get("state") == "unavailable":
        return {"state": "unavailable", "reason": stats.get("reason")}
    return stats


def timed_tool_call(sandbox: Sandbox, name: str, arguments: dict) -> float:
    started = time.monotonic()
    sandbox.tool_json(name, arguments)
    return (time.monotonic() - started) * 1000.0


def tool_battery(sandbox: Sandbox, samples: int) -> dict:
    """Fixed warm-up, then interleaved timed rounds; per-tool p50/p95/max ms."""

    def battery_arguments(tool: str, index: int) -> tuple[str, dict]:
        if tool == "search":
            query = SEARCH_QUERIES[index % len(SEARCH_QUERIES)]
            return "search", {"query": query, "limit": 10, "format": "json"}
        if tool == "context":
            task = CONTEXT_TASKS[index % len(CONTEXT_TASKS)]
            return "context", {
                "task": task,
                "max_nodes": 20,
                "include_code": False,
                "format": "json",
            }
        if tool == "grep":
            pattern = GREP_PATTERNS[index % len(GREP_PATTERNS)]
            return "grep", {
                "pattern": pattern,
                "fixed_strings": True,
                "max_results": 20,
                "format": "json",
            }
        if tool == "status":
            return "status", {"format": "json", "include_branch_diagnostics": False}
        query = RECALL_QUERIES[index % len(RECALL_QUERIES)]
        return "fact_store_search", {"query": query, "limit": 5, "format": "json"}

    tools = ("search", "grep", "context", "status", "memory_recall")
    for warmup in range(2):
        for tool in tools:
            name, arguments = battery_arguments(tool, warmup)
            timed_tool_call(sandbox, name, arguments)

    samples_ms: dict[str, list[float]] = {tool: [] for tool in tools}
    for index in range(samples):
        for tool in tools:
            name, arguments = battery_arguments(tool, index)
            samples_ms[tool].append(timed_tool_call(sandbox, name, arguments))

    return {
        tool: {
            "samples": len(values),
            "p50_ms": round(percentile(values, 0.50), 1),
            "p95_ms": round(percentile(values, 0.95), 1),
            "max_ms": round(max(values), 1),
        }
        for tool, values in samples_ms.items()
    }


def run_scenario(
    binary: Path, fixture: Path, tool_samples: int, keep_sandbox: bool, sampler: RssSampler
) -> dict:
    sandbox = Sandbox(binary=binary, fixture=fixture, keep=keep_sandbox)
    sandbox.on_spawn = sampler.set_pid
    run: dict = {"sandbox": str(sandbox.root), "fixture_commit": sandbox.head_commit()}
    try:
        # ── daemon_start_empty ───────────────────────────────────────────
        sampler.set_phase("daemon_start_empty")
        socket_seconds = sandbox.spawn_daemon()
        run["daemon_start_empty"] = {"spawn_to_socket_seconds": round(socket_seconds, 3)}

        # ── cold_index ───────────────────────────────────────────────────
        sampler.set_phase("cold_index")
        init_started = time.monotonic()
        init = sandbox.run_cli("init", timeout=COLD_INDEX_DEADLINE)
        if init.returncode != 0:
            raise PhaseFailure("cold_index", f"init failed: {init.stderr.strip()[:400]}")
        init_returned = time.monotonic() - init_started
        remaining = COLD_INDEX_DEADLINE - init_returned
        wall, payload, observed_at = wait_for(
            sandbox, "cold_index", remaining, freshness_current
        )
        cold_generation = latest_generation(payload)
        worktree = freshness(payload).get("worktree") or {}
        progress = worktree.get("progress") or {}
        run["cold_index"] = {
            "wall_seconds": round(init_returned + wall, 3),
            "init_returned_seconds": round(init_returned, 3),
            "seal_to_activation_seconds": seal_to_activation_seconds(payload, observed_at),
            "daemon_build_elapsed_seconds": (
                round(progress["elapsed_micros"] / 1_000_000.0, 3)
                if isinstance(progress.get("elapsed_micros"), int)
                else None
            ),
            "generation_id": cold_generation,
            "sealed_source_digest": progress.get("sealed_source_digest"),
            "graph_statistics": graph_statistics(payload),
            "store": store_measurements(sandbox),
        }

        # ── memory seed (setup, untimed metric-wise) ─────────────────────
        sampler.set_phase("memory_seed")
        for fact in SEED_FACTS:
            sandbox.tool_json(
                "fact_store_add",
                {"content": fact, "category": "decision", "format": "json"},
            )

        # ── tool_calls ───────────────────────────────────────────────────
        sampler.set_phase("tool_calls")
        run["tool_calls"] = tool_battery(sandbox, tool_samples)

        # ── incremental_sync ─────────────────────────────────────────────
        sampler.set_phase("incremental_sync")
        touch_path = sandbox.project / TOUCH_FILE
        if not touch_path.is_file():
            raise PhaseFailure("incremental_sync", f"pinned touch file missing: {TOUCH_FILE}")
        with touch_path.open("a", encoding="utf-8") as handle:
            handle.write(TOUCH_APPEND)
        sandbox.git("add", "-A")
        sandbox.git("commit", "-q", "-m", "scorecard incremental probe")
        probe_commit = sandbox.head_commit()
        sync_started = time.monotonic()
        sync = sandbox.run_cli("sync", timeout=SYNC_DEADLINE)
        if sync.returncode != 0:
            raise PhaseFailure("incremental_sync", f"sync failed: {sync.stderr.strip()[:400]}")
        sync_returned = time.monotonic() - sync_started

        def new_generation_current(payload: dict) -> bool:
            # The new generation must be serving AND belong to the probe
            # commit, so a spurious same-content reconcile cannot satisfy the
            # wait early.
            return (
                freshness_current(payload)
                and latest_generation(payload) != cold_generation
                and source_revision(payload) == probe_commit
            )

        wall, payload, observed_at = wait_for(
            sandbox, "incremental_sync", SYNC_DEADLINE - sync_returned, new_generation_current
        )
        run["incremental_sync"] = {
            "wall_seconds": round(sync_returned + wall, 3),
            "sync_returned_seconds": round(sync_returned, 3),
            "seal_to_activation_seconds": seal_to_activation_seconds(payload, observed_at),
            "generation_id": latest_generation(payload),
            "store": store_measurements(sandbox),
        }

        # ── daemon_restart (populated store -> serving again) ────────────
        sampler.set_phase("daemon_restart")
        sandbox.stop_daemon()
        sampler.set_pid(None)
        restart_started = time.monotonic()
        socket_seconds = sandbox.spawn_daemon()
        wall, payload, _observed_at = wait_for(
            sandbox, "daemon_restart", RESTART_DEADLINE, freshness_current
        )
        run["daemon_restart"] = {
            "spawn_to_socket_seconds": round(socket_seconds, 3),
            "spawn_to_current_seconds": round(time.monotonic() - restart_started, 3),
            "generation_id": latest_generation(payload),
        }

        sampler.set_phase("idle")
        run["status"] = "ok"
        return run
    except PhaseFailure as failure:
        run["status"] = "failed"
        run["failure"] = {"phase": failure.phase, "reason": failure.reason}
        run["daemon_log_tail"] = sandbox.daemon_log_tail()
        return run
    finally:
        run["observer"] = {
            "process_count": sandbox.observer_process_count,
            "connection_count": sandbox.observer_connection_count,
            "request_count": sandbox.observer_request_count,
        }
        sampler.set_pid(None)
        sandbox.cleanup()


# ── aggregation ──────────────────────────────────────────────────────────


def collect_scalars(run: dict) -> dict[str, float]:
    """Flatten one run's scalar metrics into dotted keys for median-ing."""
    scalars: dict[str, float] = {}

    def visit(prefix: str, value) -> None:
        if isinstance(value, bool) or value is None:
            return
        if isinstance(value, (int, float)):
            scalars[prefix] = float(value)
        elif isinstance(value, dict):
            for key, child in value.items():
                visit(f"{prefix}.{key}" if prefix else key, child)

    for section in (
        "daemon_start_empty",
        "cold_index",
        "tool_calls",
        "incremental_sync",
        "daemon_restart",
        "observer",
        "rss",
    ):
        visit(section, run.get(section))
    return scalars


def median_runs(runs: list[dict]) -> dict[str, float]:
    ok_runs = [run for run in runs if run.get("status") == "ok"]
    if not ok_runs:
        return {}
    per_key: dict[str, list[float]] = {}
    for run in ok_runs:
        for key, value in collect_scalars(run).items():
            per_key.setdefault(key, []).append(value)
    return {
        key: round(statistics.median(values), 3)
        for key, values in sorted(per_key.items())
        if len(values) == len(ok_runs)
    }


def enforce_run_invariants(run: dict) -> None:
    if run.get("status") != "ok":
        return
    graph = (run.get("cold_index") or {}).get("graph_statistics") or {}
    if graph.get("state") == "observed":
        return
    detail = graph.get("reason") or f"state={graph.get('state')!r}"
    run["status"] = "failed"
    run["failure"] = {
        "phase": "cold_index",
        "reason": f"graph statistics were not observed: {detail}",
    }


def finalize_scorecard(scorecard: dict) -> int:
    runs = scorecard["runs"]
    for run in runs:
        enforce_run_invariants(run)
    scorecard["median"] = median_runs(runs)
    failed = [run for run in runs if run.get("status") != "ok"]
    scorecard["verdict"] = "ok" if not failed else "failed"
    return 0 if not failed else 1


def human_summary(scorecard: dict) -> str:
    median = scorecard["median"]
    runs = scorecard["runs"]
    ok = sum(1 for run in runs if run.get("status") == "ok")
    lines = [
        f"## TraceDecay efficiency scorecard — {scorecard.get('label') or 'unlabeled'}",
        "",
        f"binary `{scorecard['binary']['version']}` · fixture "
        f"`{scorecard['fixture']['tree_sha256'][:12]}` ({scorecard['fixture']['files']} files) · "
        f"{ok}/{len(runs)} runs ok · median across runs",
        "",
        "| metric | median |",
        "| --- | ---: |",
    ]

    def row(label: str, key: str, unit: str = "s") -> None:
        value = median.get(key)
        if value is None:
            rendered = "—"
        elif unit == "s":
            rendered = f"{value:,.3f} s"
        else:
            rendered = f"{value:,.0f} {unit}".rstrip()
        lines.append(f"| {label} | {rendered} |")

    row("daemon start (empty profile) → socket", "daemon_start_empty.spawn_to_socket_seconds")
    row("cold index → freshness current", "cold_index.wall_seconds")
    row("cold index seal → activation", "cold_index.seal_to_activation_seconds")
    row("cold index daemon build elapsed", "cold_index.daemon_build_elapsed_seconds")
    row("incremental sync (1-file) → new generation current", "incremental_sync.wall_seconds")
    row("incremental sync seal → activation", "incremental_sync.seal_to_activation_seconds")
    row("daemon restart → serving (populated store)", "daemon_restart.spawn_to_current_seconds")
    row("readiness observer processes", "observer.process_count", "")
    row("readiness observer connections", "observer.connection_count", "")
    row("readiness observer requests", "observer.request_count", "")
    lines.append("| | |")
    for tool in ("search", "grep", "context", "status", "memory_recall"):
        row(f"{tool} p50", f"tool_calls.{tool}.p50_ms", "ms")
        row(f"{tool} p95", f"tool_calls.{tool}.p95_ms", "ms")
    lines.append("| | |")
    row("graph symbols after cold index", "cold_index.graph_statistics.symbol_count", "")
    row("graph edges after cold index", "cold_index.graph_statistics.edge_count", "")
    row("store tree after cold index (1 gen)", "cold_index.store.project_stores_tree_bytes", "B")
    row("store tree after sync (2 gens)", "incremental_sync.store.project_stores_tree_bytes", "B")
    row(
        "generation payload after cold index",
        "cold_index.store.generation_payload_total_bytes",
        "B",
    )
    row(
        "generation payload after sync",
        "incremental_sync.store.generation_payload_total_bytes",
        "B",
    )
    row(
        "shared generation segments after sync",
        "incremental_sync.store.generation_segment_bytes",
        "B",
    )
    row(
        "physical generation growth for 1-file edit",
        "incremental_sync.store.generation_physical_growth_bytes",
        "B",
    )
    row(
        "text-artifact pool after sync",
        "incremental_sync.store.text_artifact_pool_bytes",
        "B",
    )
    row("store WAL after sync", "incremental_sync.store.project_stores_wal_bytes", "B")
    for phase in (
        "daemon_start_empty",
        "cold_index",
        "tool_calls",
        "incremental_sync",
        "daemon_restart",
    ):
        row(f"peak daemon RSS — {phase}", f"rss.peak_bytes.{phase}", "B")
    lines.append("")
    return "\n".join(lines)


def flatten_store_bytes(run: dict) -> None:
    """Promote first-store sizes to stable scalar keys for the summary/median.

    Per-generation digests differ between runs (they carry repository
    identity), so the medians use totals and the largest single generation
    rather than digest-keyed entries.
    """
    for section in ("cold_index", "incremental_sync"):
        stores = ((run.get(section) or {}).get("store") or {}).get("project_stores") or []
        if stores:
            payloads = stores[0]["generation_payload_bytes"]
            run[section]["store"]["project_stores_db_bytes"] = stores[0]["db_bytes"]
            run[section]["store"]["project_stores_wal_bytes"] = stores[0]["wal_bytes"]
            run[section]["store"]["project_stores_tree_bytes"] = stores[0]["store_tree_bytes"]
            run[section]["store"]["generation_count"] = stores[0]["generation_count"]
            run[section]["store"]["generation_payload_total_bytes"] = sum(payloads.values())
            run[section]["store"]["generation_payload_max_bytes"] = (
                max(payloads.values()) if payloads else 0
            )
            run[section]["store"]["generation_segment_bytes"] = stores[0][
                "generation_segment_bytes"
            ]
            run[section]["store"]["generation_physical_bytes"] = (
                run[section]["store"]["generation_payload_total_bytes"]
                + run[section]["store"]["generation_segment_bytes"]
            )
            run[section]["store"]["text_artifact_pool_bytes"] = stores[0][
                "code_index_children_bytes"
            ].get("code-text-artifacts-v1", 0)
    cold = ((run.get("cold_index") or {}).get("store") or {}).get(
        "generation_physical_bytes"
    )
    incremental = ((run.get("incremental_sync") or {}).get("store") or {}).get(
        "generation_physical_bytes"
    )
    if isinstance(cold, int) and isinstance(incremental, int):
        run["incremental_sync"]["store"]["generation_physical_growth_bytes"] = max(
            0, incremental - cold
        )


def build_binary() -> Path:
    jobs = os.environ.get("CARGO_BUILD_JOBS", "8")
    print(f"scorecard: building tracedecay (release, jobs={jobs})", file=sys.stderr)
    env = dict(os.environ, CARGO_BUILD_JOBS=jobs, TRACEDECAY_SKIP_DASHBOARD_BUILD="1")
    completed = subprocess.run(
        (
            "cargo",
            "build",
            "--locked",
            "--release",
            "-p",
            "tracedecay-cli",
            "--bin",
            "tracedecay",
        ),
        cwd=REPO_ROOT,
        env=env,
        check=False,
    )
    if completed.returncode != 0:
        raise HarnessError("the tracedecay release build failed")
    target_dir = Path(os.environ.get("CARGO_TARGET_DIR", REPO_ROOT / "target"))
    binary = target_dir / "release" / "tracedecay"
    if not binary.is_file():
        raise HarnessError(f"expected a binary at {binary} after the build")
    return binary


def git_output(*args: str) -> str:
    completed = subprocess.run(
        ("git", *args), cwd=REPO_ROOT, capture_output=True, text=True, check=False
    )
    return completed.stdout.strip() if completed.returncode == 0 else ""


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__.splitlines()[0], formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--binary", help="prebuilt tracedecay binary (default: cargo build)")
    parser.add_argument(
        "--output",
        default=str(REPO_ROOT / "target" / "efficiency-scorecard"),
        help="output directory (default: target/efficiency-scorecard)",
    )
    parser.add_argument("--runs", type=int, default=3, help="scenario repetitions (default 3)")
    parser.add_argument(
        "--tool-samples", type=int, default=25, help="timed samples per tool per run (default 25)"
    )
    parser.add_argument(
        "--fixture", default=str(DEFAULT_FIXTURE), help="pinned fixture corpus directory"
    )
    parser.add_argument("--label", default="", help="free-form label recorded in the scorecard")
    parser.add_argument("--keep-sandbox", action="store_true", help="do not delete sandboxes")
    parser.add_argument(
        "--quick", action="store_true", help="smoke settings: --runs 1 --tool-samples 8"
    )
    args = parser.parse_args()

    if args.quick:
        args.runs = 1
        args.tool_samples = 8
    if args.runs < 1 or args.tool_samples < 1:
        raise HarnessError("--runs and --tool-samples must be positive")

    fixture = Path(args.fixture).resolve()
    if not fixture.is_dir():
        raise HarnessError(f"fixture directory does not exist: {fixture}")
    if not (fixture / TOUCH_FILE).is_file():
        raise HarnessError(f"fixture is missing the pinned touch file {TOUCH_FILE}")

    binary = Path(args.binary).resolve() if args.binary else build_binary()
    if not (binary.is_file() and os.access(binary, os.X_OK)):
        raise HarnessError(f"binary is not executable: {binary}")
    version = subprocess.run(
        (str(binary), "--version"), capture_output=True, text=True, check=False
    ).stdout.strip()

    fixture_files = sum(1 for entry in fixture.rglob("*") if entry.is_file())
    scorecard: dict = {
        "schema": SCHEMA,
        "captured_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "label": args.label,
        "binary": {"path": str(binary), "sha256": sha256_file(binary), "version": version},
        "source": {
            "git_commit": git_output("rev-parse", "HEAD"),
            "git_branch": git_output("rev-parse", "--abbrev-ref", "HEAD"),
        },
        "host": {
            "cpu_count": os.cpu_count(),
            "load_avg_start": list(os.getloadavg()),
            "kernel": os.uname().release,
        },
        "fixture": {
            "path": str(fixture),
            "files": fixture_files,
            "bytes": tree_size_bytes(fixture),
            "tree_sha256": sha256_tree(fixture),
        },
        "settings": {
            "runs": args.runs,
            "tool_samples_per_run": args.tool_samples,
            "warmup_calls_per_tool": 2,
            "poll_interval_seconds": POLL_INTERVAL_SECONDS,
            "search_queries": list(SEARCH_QUERIES),
            "context_tasks": list(CONTEXT_TASKS),
            "grep_patterns": list(GREP_PATTERNS),
            "recall_queries": list(RECALL_QUERIES),
            "touch_file": str(TOUCH_FILE),
        },
        "runs": [],
    }

    for index in range(args.runs):
        print(f"scorecard: run {index + 1}/{args.runs}", file=sys.stderr)
        sampler = RssSampler()
        run = run_scenario(binary, fixture, args.tool_samples, args.keep_sandbox, sampler)
        peaks, hwm = sampler.finish()
        run["rss"] = {"peak_bytes": peaks, "vmhwm_bytes_at_phase_end": hwm}
        flatten_store_bytes(run)
        enforce_run_invariants(run)
        scorecard["runs"].append(run)
        if run["status"] != "ok":
            print(
                f"scorecard: run {index + 1} FAILED in {run['failure']['phase']}: "
                f"{run['failure']['reason']}",
                file=sys.stderr,
            )

    scorecard["host"]["load_avg_end"] = list(os.getloadavg())
    exit_code = finalize_scorecard(scorecard)

    output = Path(args.output)
    output.mkdir(parents=True, exist_ok=True)
    (output / "scorecard.json").write_text(
        json.dumps(scorecard, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    summary = human_summary(scorecard)
    (output / "summary.md").write_text(summary + "\n", encoding="utf-8")
    print(summary)
    print(f"scorecard: JSON written to {output / 'scorecard.json'}", file=sys.stderr)
    return exit_code


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except HarnessError as error:
        print(f"scorecard: error: {error}", file=sys.stderr)
        raise SystemExit(2)
