#!/usr/bin/env python3
"""Regenerate the committed indexing-benchmark corpus.

The corpus is checked in so that head-vs-base profiling compares two
compilers of the *same* bytes: nothing about the workload may depend on
the machine, the clock, or a random seed. This generator is therefore
purely a function of the file ordinal - no RNG, no timestamps, no
environment reads - and rewriting the tree with an unchanged script is a
no-op.

Usage:
    python3 scripts/generate-index-bench-corpus.py [--out DIR]

The defaults reproduce `benchmark_data/index-bench/corpus` byte for byte.
Changing the per-language counts changes the profiled workload, so treat
the counts as part of the benchmark contract: bump
`WORKLOAD_REVISION` in the same commit and re-baseline.
"""

from __future__ import annotations

import argparse
import hashlib
import pathlib
import shutil

# Bump together with any change to the emitters or the counts below.
WORKLOAD_REVISION = "index-bench-corpus.v1"

# Per-language file counts. The mix is weighted towards the languages whose
# extractors do the most structural work (Rust, TypeScript), because those
# are the parser paths a PR is most likely to regress.
COUNTS = {
    "rust": 90,
    "typescript": 70,
    "python": 50,
    "go": 30,
    "java": 20,
}

WORDS = (
    "ledger", "cursor", "digest", "manifest", "lease", "epoch", "shard",
    "receipt", "envelope", "quorum", "watermark", "lineage", "stratum",
    "beacon", "harness", "outline", "capsule", "gradient", "trellis",
    "aperture",
)


def token(ordinal: int, offset: int) -> str:
    """Deterministic identifier fragment for a file/member position."""
    return WORDS[(ordinal * 7 + offset * 3) % len(WORDS)]


def members(ordinal: int) -> int:
    """Members per file: 6..13, cycling so file sizes vary deterministically."""
    return 6 + (ordinal % 8)


def rust_file(ordinal: int) -> str:
    name = f"{token(ordinal, 0)}_{ordinal:03}"
    peer = (ordinal + 11) % COUNTS["rust"]
    lines = [
        "//! Deterministic indexing-benchmark fixture.",
        "//!",
        "//! Generated by `scripts/generate-index-bench-corpus.py`; do not edit.",
        "",
        "use std::collections::BTreeMap;",
        "use std::fmt;",
        "",
        f"use crate::{token(peer, 0)}_{peer:03}::{token(peer, 1).capitalize()}State{peer:03};",
        "",
        "/// Bounded accumulator over an ordered keyspace.",
        "#[derive(Clone, Debug, Default, PartialEq, Eq)]",
        f"pub struct {token(ordinal, 1).capitalize()}State{ordinal:03} {{",
        "    entries: BTreeMap<String, u64>,",
        "    sealed: bool,",
        "}",
        "",
        f"impl {token(ordinal, 1).capitalize()}State{ordinal:03} {{",
    ]
    for member in range(members(ordinal)):
        verb = token(ordinal, member + 2)
        lines += [
            f"    /// Fold `{verb}` evidence into the accumulator.",
            f"    pub fn {verb}_{member}(&mut self, key: &str, weight: u64) -> u64 {{",
            "        if self.sealed {",
            "            return 0;",
            "        }",
            "        let slot = self.entries.entry(key.to_owned()).or_default();",
            f"        *slot = slot.saturating_add(weight).saturating_add({member});",
            "        *slot",
            "    }",
            "",
        ]
    lines += [
        "    /// Freeze the accumulator so later folds abstain.",
        "    pub fn seal(&mut self) -> usize {",
        "        self.sealed = true;",
        "        self.entries.len()",
        "    }",
        "}",
        "",
        f"impl fmt::Display for {token(ordinal, 1).capitalize()}State{ordinal:03} {{",
        "    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {",
        f'        write!(formatter, "{name}({{}})", self.entries.len())',
        "    }",
        "}",
        "",
        "/// Join two accumulators, preferring the larger weight per key.",
        f"pub fn join_{name}(",
        f"    left: &{token(ordinal, 1).capitalize()}State{ordinal:03},",
        f"    right: &{token(peer, 1).capitalize()}State{peer:03},",
        ") -> usize {",
        "    let _ = right;",
        "    left.entries.len()",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    #[test]",
        f"    fn {name}_folds_then_seals() {{",
        f"        let mut state = {token(ordinal, 1).capitalize()}State{ordinal:03}::default();",
        f'        assert!(state.{token(ordinal, 2)}_0("alpha", 3) > 0);',
        "        assert_eq!(state.seal(), 1);",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def typescript_file(ordinal: int) -> str:
    name = f"{token(ordinal, 0)}{ordinal:03}"
    peer = (ordinal + 7) % COUNTS["typescript"]
    lines = [
        "// Deterministic indexing-benchmark fixture.",
        "// Generated by `scripts/generate-index-bench-corpus.py`; do not edit.",
        "",
        f'import {{ type {token(peer, 1).capitalize()}Record{peer:03} }} from "./{token(peer, 0)}{peer:03}";',
        "",
        f"export interface {token(ordinal, 1).capitalize()}Record{ordinal:03} {{",
        "  readonly key: string;",
        "  readonly weight: number;",
        "  readonly sealed: boolean;",
        "}",
        "",
        "/** Bounded accumulator over an ordered keyspace. */",
        f"export class {token(ordinal, 1).capitalize()}Store{ordinal:03} {{",
        f"  private readonly entries = new Map<string, {token(ordinal, 1).capitalize()}Record{ordinal:03}>();",
        "",
        "  private sealed = false;",
        "",
    ]
    for member in range(members(ordinal)):
        verb = token(ordinal, member + 2)
        lines += [
            f"  public {verb}{member}(key: string, weight: number): number {{",
            "    if (this.sealed) {",
            "      return 0;",
            "    }",
            "    const prior = this.entries.get(key);",
            f"    const next = (prior?.weight ?? 0) + weight + {member};",
            "    this.entries.set(key, { key, weight: next, sealed: false });",
            "    return next;",
            "  }",
            "",
        ]
    lines += [
        "  public seal(): number {",
        "    this.sealed = true;",
        "    return this.entries.size;",
        "  }",
        "}",
        "",
        f"export function join{name}(",
        f"  left: {token(ordinal, 1).capitalize()}Store{ordinal:03},",
        f"  right: readonly {token(peer, 1).capitalize()}Record{peer:03}[],",
        "): number {",
        "  return left.seal() + right.length;",
        "}",
        "",
    ]
    return "\n".join(lines)


def python_file(ordinal: int) -> str:
    name = f"{token(ordinal, 0)}_{ordinal:03}"
    peer = (ordinal + 5) % COUNTS["python"]
    lines = [
        '"""Deterministic indexing-benchmark fixture.',
        "",
        "Generated by ``scripts/generate-index-bench-corpus.py``; do not edit.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass, field",
        "",
        f"from .{token(peer, 0)}_{peer:03} import {token(peer, 1).capitalize()}State{peer:03}",
        "",
        "",
        "@dataclass",
        f"class {token(ordinal, 1).capitalize()}State{ordinal:03}:",
        '    """Bounded accumulator over an ordered keyspace."""',
        "",
        "    entries: dict[str, int] = field(default_factory=dict)",
        "    sealed: bool = False",
        "",
    ]
    for member in range(members(ordinal)):
        verb = token(ordinal, member + 2)
        lines += [
            f"    def {verb}_{member}(self, key: str, weight: int) -> int:",
            f'        """Fold ``{verb}`` evidence into the accumulator."""',
            "        if self.sealed:",
            "            return 0",
            f"        total = self.entries.get(key, 0) + weight + {member}",
            "        self.entries[key] = total",
            "        return total",
            "",
        ]
    lines += [
        "    def seal(self) -> int:",
        '        """Freeze the accumulator so later folds abstain."""',
        "        self.sealed = True",
        "        return len(self.entries)",
        "",
        "",
        f"def join_{name}(",
        f"    left: {token(ordinal, 1).capitalize()}State{ordinal:03},",
        f"    right: {token(peer, 1).capitalize()}State{peer:03},",
        ") -> int:",
        '    """Join two accumulators, preferring the left keyspace."""',
        "    return len(left.entries) + len(right.entries)",
        "",
    ]
    return "\n".join(lines)


def go_file(ordinal: int) -> str:
    name = f"{token(ordinal, 0).capitalize()}{ordinal:03}"
    lines = [
        "// Deterministic indexing-benchmark fixture.",
        "// Generated by scripts/generate-index-bench-corpus.py; do not edit.",
        "",
        "package corpus",
        "",
        'import "fmt"',
        "",
        "// State is a bounded accumulator over an ordered keyspace.",
        f"type {name}State struct {{",
        "\tentries map[string]uint64",
        "\tsealed  bool",
        "}",
        "",
        f"// New{name}State returns an empty accumulator.",
        f"func New{name}State() *{name}State {{",
        f"\treturn &{name}State{{entries: map[string]uint64{{}}}}",
        "}",
        "",
    ]
    for member in range(members(ordinal)):
        verb = token(ordinal, member + 2).capitalize()
        lines += [
            f"// {verb}{member} folds evidence into the accumulator.",
            f"func (s *{name}State) {verb}{member}(key string, weight uint64) uint64 {{",
            "\tif s.sealed {",
            "\t\treturn 0",
            "\t}",
            f"\ts.entries[key] += weight + {member}",
            "\treturn s.entries[key]",
            "}",
            "",
        ]
    lines += [
        "// Seal freezes the accumulator so later folds abstain.",
        f"func (s *{name}State) Seal() int {{",
        "\ts.sealed = true",
        "\treturn len(s.entries)",
        "}",
        "",
        f"// String renders the accumulator cardinality.",
        f"func (s *{name}State) String() string {{",
        f'\treturn fmt.Sprintf("{name}(%d)", len(s.entries))',
        "}",
        "",
    ]
    return "\n".join(lines)


def java_file(ordinal: int) -> str:
    name = f"{token(ordinal, 1).capitalize()}State{ordinal:03}"
    lines = [
        "// Deterministic indexing-benchmark fixture.",
        "// Generated by scripts/generate-index-bench-corpus.py; do not edit.",
        "",
        "package corpus;",
        "",
        "import java.util.LinkedHashMap;",
        "import java.util.Map;",
        "",
        "/** Bounded accumulator over an ordered keyspace. */",
        f"public final class {name} {{",
        "    private final Map<String, Long> entries = new LinkedHashMap<>();",
        "",
        "    private boolean sealed;",
        "",
    ]
    for member in range(members(ordinal)):
        verb = token(ordinal, member + 2)
        lines += [
            f"    /** Folds {verb} evidence into the accumulator. */",
            f"    public long {verb}{member}(String key, long weight) {{",
            "        if (sealed) {",
            "            return 0L;",
            "        }",
            f"        long next = entries.getOrDefault(key, 0L) + weight + {member}L;",
            "        entries.put(key, next);",
            "        return next;",
            "    }",
            "",
        ]
    lines += [
        "    /** Freezes the accumulator so later folds abstain. */",
        "    public int seal() {",
        "        sealed = true;",
        "        return entries.size();",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


EMITTERS = {
    "rust": (rust_file, "rs", lambda o: f"{token(o, 0)}_{o:03}.rs"),
    "typescript": (typescript_file, "ts", lambda o: f"{token(o, 0)}{o:03}.ts"),
    "python": (python_file, "py", lambda o: f"{token(o, 0)}_{o:03}.py"),
    "go": (go_file, "go", lambda o: f"{token(o, 0)}_{o:03}.go"),
    "java": (java_file, "java", lambda o: f"{token(o, 1).capitalize()}State{o:03}.java"),
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent.parent
        / "benchmark_data"
        / "index-bench"
        / "corpus",
    )
    parser.add_argument(
        "--scale",
        type=int,
        default=1,
        help=(
            "multiply every per-language count (default 1). Scaled corpora are "
            "still a pure function of the ordinal but are not the committed "
            "workload, so --scale > 1 requires an explicit --out"
        ),
    )
    arguments = parser.parse_args()
    root: pathlib.Path = arguments.out
    if arguments.scale < 1:
        parser.error("--scale must be a positive integer")
    if arguments.scale > 1:
        if arguments.out == parser.get_default("out"):
            parser.error("--scale > 1 requires --out outside the committed corpus")
        for language in COUNTS:
            COUNTS[language] *= arguments.scale

    if root.exists():
        shutil.rmtree(root)

    digest = hashlib.sha256()
    total_bytes = 0
    total_files = 0
    for language in sorted(COUNTS):
        emit, _extension, filename = EMITTERS[language]
        directory = root / language
        directory.mkdir(parents=True, exist_ok=True)
        for ordinal in range(COUNTS[language]):
            body = emit(ordinal).encode("utf-8")
            relative = f"{language}/{filename(ordinal)}"
            (root / relative).write_bytes(body)
            digest.update(relative.encode("utf-8"))
            digest.update(body)
            total_bytes += len(body)
            total_files += 1

    print(f"revision: {WORKLOAD_REVISION}")
    print(f"files: {total_files}")
    print(f"bytes: {total_bytes}")
    print(f"content_digest: sha256:{digest.hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
