#!/usr/bin/env bash
# End-to-end proof that `tracedecay install --agent hermes` works against
# STOCK (upstream NousResearch/hermes-agent) Hermes — not just customized
# forks. Used by the `hermes-integration` CI job and runnable locally:
#
#   git clone https://github.com/NousResearch/hermes-agent.git /tmp/hermes-upstream
#   git -C /tmp/hermes-upstream checkout <pinned ref>
#   cargo build --bin tracedecay
#   scripts/hermes_stock_integration.sh
#
# Environment:
#   TRACEDECAY_BIN        tracedecay binary to install/test (default: target/debug/tracedecay)
#   HERMES_UPSTREAM_DIR  stock hermes-agent checkout (default: /tmp/hermes-upstream)
#
# Everything is offline and deterministic: a throwaway user HOME (and its
# normal Hermes install) plus a throwaway initialized project, no model calls,
# no network beyond whatever
# `uv sync` needs the first time the upstream venv is created.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT_PATH="$REPO_ROOT/scripts/hermes_stock_integration.sh"
DAEMON_HARNESS="$REPO_ROOT/scripts/with-isolated-tracedecay-daemon.sh"
STAGE=""

run_integration() {
    local project="$1"
    local hermes_python="$HERMES_VENV/bin/python"
    local plugins_list doctor_out doctor_status

    (cd "$project" && "$TRACEDECAY_BIN" init)

    echo "== stock plugin manager / context engine / memory provider / dispatch checks"
    (
        cd "$project" &&
            PYTHONPATH="$HERMES_UPSTREAM_DIR" \
                "$hermes_python" "$REPO_ROOT/scripts/hermes_stock_check.py"
    )

    echo "== hermes plugins list"
    plugins_list="$(cd "$HERMES_UPSTREAM_DIR" && COLUMNS=200 \
        timeout 120 "$HERMES_VENV/bin/hermes" plugins list)"
    echo "$plugins_list" | grep tracedecay
    echo "$plugins_list" | grep tracedecay | grep -q enabled
    echo "ok - hermes plugins list shows tracedecay enabled"

    echo "== tracedecay doctor --agent hermes"
    set +e
    doctor_out="$(cd "$project" && "$TRACEDECAY_BIN" doctor --agent hermes 2>&1)"
    doctor_status=$?
    set -e
    if [[ $doctor_status -ne 0 ]]; then
        echo "error: tracedecay doctor exited with status $doctor_status:" >&2
        echo "$doctor_out" >&2
        return "$doctor_status"
    fi
    echo "$doctor_out" | grep -q "Hermes tracedecay plugin found"
    if echo "$doctor_out" | grep -q "was generated by tracedecay"; then
        echo "error: doctor reports a stale generated plugin:" >&2
        echo "$doctor_out" | grep "was generated by tracedecay" >&2
        return 1
    fi
    echo "ok - tracedecay doctor Hermes section is clean"

    echo "stock hermes integration: PASS"
}

main() {
    local tracedecay_bin hermes_upstream_dir hermes_venv
    local fake_home hermes_home profile socket project status

    tracedecay_bin="${TRACEDECAY_BIN:-$REPO_ROOT/target/debug/tracedecay}"
    tracedecay_bin="$(cd "$(dirname "$tracedecay_bin")" && pwd)/$(basename "$tracedecay_bin")"
    hermes_upstream_dir="${HERMES_UPSTREAM_DIR:-/tmp/hermes-upstream}"

    if [[ ! -x "$tracedecay_bin" ]]; then
        echo "error: tracedecay binary not found at $tracedecay_bin (build with: cargo build --bin tracedecay)" >&2
        return 1
    fi
    if [[ ! -f "$hermes_upstream_dir/pyproject.toml" ]]; then
        echo "error: stock hermes-agent checkout not found at $hermes_upstream_dir" >&2
        return 1
    fi

    echo "== stock hermes ref: $(git -C "$hermes_upstream_dir" rev-parse HEAD 2>/dev/null || echo unknown)"
    echo "== tracedecay binary: $tracedecay_bin ($("$tracedecay_bin" --version))"

    # Upstream source installs use either `.venv` (uv) or `venv` (Hermes installer).
    if [[ -x "$hermes_upstream_dir/.venv/bin/python" ]]; then
        hermes_venv="$hermes_upstream_dir/.venv"
    elif [[ -x "$hermes_upstream_dir/venv/bin/python" ]]; then
        hermes_venv="$hermes_upstream_dir/venv"
    else
        echo "== creating stock hermes venv (uv sync --frozen --no-dev)"
        (cd "$hermes_upstream_dir" && uv sync --frozen --no-dev)
        hermes_venv="$hermes_upstream_dir/.venv"
    fi

    STAGE="$(mktemp -d -t hermes-stock-XXXXXX)"
    fake_home="$STAGE/home"
    hermes_home="$fake_home/.hermes"
    profile="$fake_home/.tracedecay"
    socket="$profile/daemon.sock"
    project="$STAGE/project"
    mkdir -p "$fake_home" "$profile" "$project/src"
    trap 'rm -rf "$STAGE"' EXIT

    # Throwaway project so tool dispatch has a real .tracedecay graph to hit.
    printf 'pub fn add(a: i32, b: i32) -> i32 { a + b }\n\npub fn double(x: i32) -> i32 { add(x, x) }\n' > "$project/src/lib.rs"
    printf '[package]\nname = "throwaway"\nversion = "0.1.0"\nedition = "2021"\n' > "$project/Cargo.toml"
    git -C "$project" init -q
    git -C "$project" add -A
    git -C "$project" -c user.email=ci@tracedecay -c user.name=ci commit -qm init

    # Installation must precede the sole-owner daemon. Keep every user/profile
    # path inside the throwaway HOME.
    echo "== tracedecay install --agent hermes"
    HOME="$fake_home" \
        HERMES_HOME="$hermes_home" \
        TRACEDECAY_DATA_DIR="$profile" \
        TRACEDECAY_DAEMON_SOCKET="$socket" \
        "$tracedecay_bin" install --agent hermes
    test -f "$hermes_home/plugins/tracedecay/plugin.yaml"

    set +e
    HOME="$fake_home" \
        HERMES_HOME="$hermes_home" \
        TRACEDECAY_BIN="$tracedecay_bin" \
        HERMES_UPSTREAM_DIR="$hermes_upstream_dir" \
        HERMES_VENV="$hermes_venv" \
        "$DAEMON_HARNESS" --bin "$tracedecay_bin" --ready-timeout 30 \
        --lifecycle-label "temporary tracedecay daemon" -- \
        "$SCRIPT_PATH" --run "$project"
    status=$?
    set -e
    return "$status"
}

if [[ "${1:-}" == "--run" ]]; then
    shift
    run_integration "$@"
else
    main "$@"
fi
