#!/usr/bin/env python3
"""Prove Windows-style Git checkout preserves embedded and generated bytes."""

from __future__ import annotations

import os
from pathlib import Path
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parent.parent


class CheckoutBytesTests(unittest.TestCase):
    def test_autocrlf_preserves_text_binary_and_vendor_bytes(self):
        samples = {
            "scripts/entrypoint.sh": b"#!/bin/sh\nprintf 'ready\\n'\n",
            "dashboard/src/contracts/generated.ts": b"export const version = 1;\n",
            "dashboard/codegen/schemas/dashboard-contracts.schema.json": b'{"version":1}\n',
            "sdks/typescript/src/types.ts": b"export type Id = string;\n",
            "crates/example/src/template.rs": b'const TEMPLATE: &str = "hello";\n',
            "crates/example/schema.sql": b"CREATE TABLE example (id INTEGER);\n",
            "dashboard/public/image.png": b"\x89PNG\r\n\x1a\n\x00\x00\r\n",
            "crates/tracedecay-cli/tests/fixtures/source-provenance-cargo/vendor/example/data.txt": b"upstream\r\nbytes\r\n",
        }
        with tempfile.TemporaryDirectory(prefix="checkout-bytes-") as directory:
            root = Path(directory)
            repo = root / "repo"
            repo.mkdir()
            output = root / "checkout"
            output.mkdir()
            environment = os.environ.copy()
            for name in ("GIT_DIR", "GIT_WORK_TREE", "GIT_INDEX_FILE"):
                environment.pop(name, None)
            environment.update(GIT_CONFIG_NOSYSTEM="1", GIT_CONFIG_GLOBAL=os.devnull)

            def git(*args: str):
                subprocess.run(
                    ["git", "-c", "core.autocrlf=true", "-c", "core.attributesFile=", *args],
                    cwd=repo,
                    env=environment,
                    check=True,
                    capture_output=True,
                )

            git("init")
            (repo / ".gitattributes").write_bytes((ROOT / ".gitattributes").read_bytes())
            for name, contents in samples.items():
                path = repo / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(contents)
            git("add", ".")
            git("checkout-index", "--all", f"--prefix={output.as_posix()}/")
            for name, expected in samples.items():
                with self.subTest(path=name):
                    self.assertEqual((output / name).read_bytes(), expected)


if __name__ == "__main__":
    unittest.main()
