//! Hermes agent integration.
//!
//! Installs a Hermes profile plugin that exposes tracedecay tools as
//! Hermes-native plugin tools.

mod dashboard_wrapper;
mod lifecycle;
mod profile_config;

use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use crate::errors::{Result, TraceDecayError};
pub(crate) use profile_config::read_config_pinned_project_root;
use profile_config::{disable_plugin, enable_plugin};

use super::{
    AgentIntegration, DoctorCounters, HealthcheckContext, InstallContext, UpdatePluginOutcome,
};

mod templates;

/// Hermes agent.
pub struct HermesIntegration;

impl AgentIntegration for HermesIntegration {
    fn name(&self) -> &'static str {
        "Hermes"
    }

    fn id(&self) -> &'static str {
        "hermes"
    }

    fn install(&self, ctx: &InstallContext) -> Result<()> {
        lifecycle::install(ctx)?;
        Ok(())
    }

    fn update_plugin(&self, ctx: &InstallContext) -> Result<UpdatePluginOutcome> {
        lifecycle::update_plugin(ctx)
    }

    fn uninstall(&self, ctx: &InstallContext) -> Result<()> {
        lifecycle::uninstall(ctx)?;
        Ok(())
    }

    fn healthcheck(&self, dc: &mut DoctorCounters, ctx: &HealthcheckContext) {
        eprintln!("\n\x1b[1mHermes integration\x1b[0m");
        doctor_check_plugin(dc, &ctx.home);
    }

    fn is_detected(&self, home: &Path) -> bool {
        hermes_home(home).is_dir()
    }

    fn primary_config_path(&self, home: &Path) -> Option<PathBuf> {
        Some(hermes_home(home).join("config.yaml"))
    }

    fn has_tracedecay(&self, home: &Path) -> bool {
        default_plugin_dir(home).join("plugin.yaml").is_file()
    }
}

fn hermes_home(home: &Path) -> PathBuf {
    home.join(".hermes")
}

fn default_plugin_dir(home: &Path) -> PathBuf {
    hermes_home(home).join("plugins/tracedecay")
}

fn doctor_check_plugin(dc: &mut DoctorCounters, home: &Path) {
    let candidates = hermes_healthcheck_plugin_paths(home);
    let existing: Vec<&PathBuf> = candidates.iter().filter(|plugin| plugin.exists()).collect();
    let Some(first) = existing.first() else {
        if let Some(plugin) = candidates.first() {
            dc.warn(&format!(
                "{} not found — run `tracedecay install --agent hermes` if you use Hermes",
                plugin.display()
            ));
        } else {
            dc.warn("Hermes tracedecay plugin not found — run `tracedecay install --agent hermes` if you use Hermes");
        }
        return;
    };
    dc.pass(&format!(
        "Hermes tracedecay plugin found at {}",
        first.display()
    ));

    for manifest_path in &existing {
        // Stale generated plugins keep working but miss new tools/config
        // surfaces; `hermes plugins list` shows the same manifest version.
        match read_manifest_version(manifest_path) {
            Some(version) if version == env!("CARGO_PKG_VERSION") => {}
            Some(version) => dc.warn(&format!(
                "{} was generated by tracedecay {version} (installed binary is {}) — re-run `tracedecay install --agent hermes` to refresh it",
                manifest_path.display(),
                env!("CARGO_PKG_VERSION"),
            )),
            None => dc.warn(&format!(
                "{} has no manifest version — re-run `tracedecay install --agent hermes` to refresh it",
                manifest_path.display(),
            )),
        }
    }
}

fn hermes_healthcheck_plugin_paths(home: &Path) -> Vec<PathBuf> {
    vec![hermes_home(home).join("plugins/tracedecay/plugin.yaml")]
}

fn read_manifest_version(manifest_path: &Path) -> Option<String> {
    let manifest = std::fs::read_to_string(manifest_path).ok()?;
    manifest
        .lines()
        .find_map(|line| line.strip_prefix("version:"))
        .map(|version| version.trim().to_string())
        .filter(|version| !version.is_empty())
}

pub(super) fn install_plugin(
    plugin_dir: &Path,
    tracedecay_bin: &str,
    deploy_dashboard: bool,
) -> Result<()> {
    write_plugin_files(plugin_dir, tracedecay_bin)?;
    dashboard_wrapper::apply_install_policy(plugin_dir, tracedecay_bin, deploy_dashboard)?;
    if let Some(profile_dir) = plugin_dir.parent().and_then(Path::parent) {
        let config_path = profile_dir.join("config.yaml");
        enable_plugin(&config_path)?;
    }

    eprintln!(
        "\x1b[32m✔\x1b[0m Wrote Hermes tracedecay plugin to {}",
        plugin_dir.display()
    );
    Ok(())
}

/// Writes the generated agent-plugin files (manifest, schemas, tools,
/// entrypoint, skill). Shared by install and the config-preserving update
/// lifecycle path; never touches config.yaml.
pub(super) fn write_plugin_files(plugin_dir: &Path, tracedecay_bin: &str) -> Result<()> {
    std::fs::create_dir_all(plugin_dir).map_err(|e| TraceDecayError::Config {
        message: format!("failed to create {}: {e}", plugin_dir.display()),
    })?;
    std::fs::create_dir_all(plugin_dir.join("skills/tracedecay")).map_err(|e| {
        TraceDecayError::Config {
            message: format!(
                "failed to create {}: {e}",
                plugin_dir.join("skills/tracedecay").display()
            ),
        }
    })?;

    write_text_file(
        &plugin_dir.join("plugin.yaml"),
        &templates::plugin_manifest(),
    )?;
    write_text_file(&plugin_dir.join("schemas.py"), &templates::plugin_schemas())?;
    write_text_file(
        &plugin_dir.join("schemas.json"),
        &templates::plugin_schemas_json()?,
    )?;
    write_text_file(
        &plugin_dir.join("tools.py"),
        &templates::plugin_tools(tracedecay_bin),
    )?;
    write_text_file(&plugin_dir.join("__init__.py"), &templates::plugin_init())?;
    write_text_file(&plugin_dir.join("cli.py"), templates::PLUGIN_CLI_PY)?;
    write_text_file(
        &plugin_dir.join("skills/tracedecay/SKILL.md"),
        templates::HERMES_SKILL,
    )
}

/// The one supported user-level generated plugin directory, when installed.
pub(super) fn detected_plugin_dirs(home: &Path) -> Vec<PathBuf> {
    let plugin_dir = default_plugin_dir(home);
    plugin_dir
        .join("plugin.yaml")
        .is_file()
        .then_some(plugin_dir)
        .into_iter()
        .collect()
}

/// Historical generated plugin locations. These are consulted only during
/// the one-time cutover; they never select `TraceDecay` storage or a live Hermes
/// install target.
pub(super) fn legacy_plugin_dirs(home: &Path) -> Vec<PathBuf> {
    let default = default_plugin_dir(home);
    let roots = [hermes_home(home)];
    let mut profile_roots = Vec::new();
    for root in roots {
        profile_roots.push(root.clone());
        if let Ok(entries) = std::fs::read_dir(root.join("profiles")) {
            let mut profiles = entries
                .filter_map(|entry| {
                    let entry = entry.ok()?;
                    entry.file_type().ok()?.is_dir().then(|| entry.path())
                })
                .collect::<Vec<_>>();
            profiles.sort();
            profile_roots.extend(profiles);
        }
    }
    let mut seen = std::collections::BTreeSet::new();
    profile_roots
        .into_iter()
        .map(|root| root.join("plugins/tracedecay"))
        .filter(|plugin_dir| !paths_equal(plugin_dir, &default))
        .filter(|plugin_dir| plugin_dir.join("plugin.yaml").is_file())
        .filter(|plugin_dir| seen.insert(canonical_or_original(plugin_dir)))
        .collect()
}

#[doc(hidden)]
pub fn has_legacy_plugin_install(home: &Path) -> bool {
    !legacy_plugin_dirs(home).is_empty()
}

#[doc(hidden)]
pub fn cleanup_legacy_plugin_dirs(home: &Path) -> Result<Vec<PathBuf>> {
    let plugin_dirs = legacy_plugin_dirs(home);
    for plugin_dir in &plugin_dirs {
        uninstall_plugin(plugin_dir)?;
    }
    Ok(plugin_dirs)
}

fn paths_equal(left: &Path, right: &Path) -> bool {
    canonical_or_original(left) == canonical_or_original(right)
}

fn canonical_or_original(path: &Path) -> PathBuf {
    path.canonicalize().unwrap_or_else(|_| path.to_path_buf())
}

pub(super) fn uninstall_plugin(plugin_dir: &Path) -> Result<()> {
    if let Some(profile_dir) = plugin_dir.parent().and_then(Path::parent) {
        disable_plugin(&profile_dir.join("config.yaml"))?;
    }
    remove_generated_plugin_files(plugin_dir)
}

pub(super) fn remove_generated_plugin_files(plugin_dir: &Path) -> Result<()> {
    if !plugin_dir.exists() {
        eprintln!("  {} not found, skipping", plugin_dir.display());
        return Ok(());
    }

    remove_generated_file(&plugin_dir.join("plugin.yaml"))?;
    remove_generated_file(&plugin_dir.join("schemas.py"))?;
    remove_generated_file(&plugin_dir.join("schemas.json"))?;
    remove_generated_file(&plugin_dir.join("tools.py"))?;
    remove_generated_file(&plugin_dir.join("__init__.py"))?;
    remove_generated_file(&plugin_dir.join("cli.py"))?;
    remove_generated_file(&plugin_dir.join("skills/tracedecay/SKILL.md"))?;
    remove_empty_dir(&plugin_dir.join("skills/tracedecay"))?;
    remove_empty_dir(&plugin_dir.join("skills"))?;
    dashboard_wrapper::uninstall(plugin_dir)?;

    if remove_empty_dir(plugin_dir)? {
        eprintln!(
            "\x1b[32m✔\x1b[0m Removed Hermes tracedecay plugin from {}",
            plugin_dir.display()
        );
    } else {
        eprintln!(
            "  Left {} in place because it contains files not generated by tracedecay",
            plugin_dir.display()
        );
    }
    Ok(())
}

pub(super) fn write_text_file(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| TraceDecayError::Config {
            message: format!("failed to create {}: {e}", parent.display()),
        })?;
    }
    let current = std::fs::read_to_string(path).unwrap_or_default();
    if current == contents {
        return Ok(());
    }
    // Write-to-.new-then-rename so a mid-write crash can never leave a
    // truncated/corrupt generated file behind (same pattern as
    // write_config_file, minus the backup — these files are regenerable).
    let new_path = PathBuf::from(format!("{}.new", path.display()));
    if let Err(e) = std::fs::write(&new_path, contents) {
        std::fs::remove_file(&new_path).ok();
        return Err(TraceDecayError::Config {
            message: format!("failed to write {}: {e}", new_path.display()),
        });
    }
    if let Err(e) = std::fs::rename(&new_path, path) {
        std::fs::remove_file(&new_path).ok();
        return Err(TraceDecayError::Config {
            message: format!(
                "failed to replace {} with {}: {e}",
                path.display(),
                new_path.display()
            ),
        });
    }
    Ok(())
}

pub(super) fn remove_generated_file(path: &Path) -> Result<()> {
    match std::fs::remove_file(path) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == ErrorKind::NotFound => Ok(()),
        Err(e) => Err(TraceDecayError::Config {
            message: format!("failed to remove {}: {e}", path.display()),
        }),
    }
}

pub(super) fn remove_empty_dir(path: &Path) -> Result<bool> {
    match std::fs::remove_dir(path) {
        Ok(()) => Ok(true),
        Err(e) if matches!(e.kind(), ErrorKind::NotFound | ErrorKind::DirectoryNotEmpty) => {
            Ok(false)
        }
        Err(e) => Err(TraceDecayError::Config {
            message: format!("failed to remove {}: {e}", path.display()),
        }),
    }
}
