#!/usr/bin/env python3
"""Generate Bazel BUILD files for the Cargo workspace.

Reads `cargo metadata` for target shapes and `cargo tree` for Cargo's own
feature resolution, then emits one BUILD.bazel per member crate under
crates/. The lane resolves the Linux dependency graph only: member deps'
cfg() target gates are evaluated against a generic Linux host, and a gate
whose answer depends on the machine aborts the generator instead of
silently drifting (see cfg_applies_linux).

Filegroups for sources living outside a member's package land in the owning
package's BUILD.bazel. Member packages get them appended to their generated
rules; other packages keep handwritten content and carry the generated
rules inside a marked GEN_BEGIN/GEN_END block the generator re-renders, so
stale or obsolete groups are detectable drift rather than inherited bytes.

Feature model. Cargo compiles a member once per resolved feature set, and the
set depends on the consuming context (normal build vs dev/test resolution vs
required-features). Test contexts resolve once across the whole workspace,
as one `cargo test --workspace` does, so every member's tests share one
dependency build. Each member gets one rust_library per distinct feature set it is ever
built with. `<pkg>` covers its own build context and
`<pkg>__<extra-features>` names the variants. A variant's own member deps are the union
of the labels every producing context resolves for them. Dependents pick the
variant matching the feature set Cargo resolves in their context.

Outputs are deterministic. Rerun after any Cargo.toml change. `--check`
verifies the committed BUILD.bazel files match a fresh run without writing.
"""

import hashlib
import json
import re
import subprocess
import sys
import tomllib
from concurrent.futures import ThreadPoolExecutor
from functools import lru_cache
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent

BANNER = (
    "# Generated by scripts/bazel/gen_builds.py from Cargo.toml + Cargo.lock.\n"
    "# Regenerate instead of editing. bazel run //scripts:bazel/gen_builds.py\n"
)

# Generated filegroups embedded in a handwritten BUILD.bazel live inside
# this marked block so reruns re-render them in place: a stale or obsolete
# group is detectable drift, not bytes the generator inherited.
# The crate_universe hub repository (MODULE.bazel). Its name is spelled twice
# in every Windows build-script runfiles path
# (`rules_rust++crate+<hub>__<crate>-<version>/_bs.cargo_runfiles/` again), so
# it stays one letter to keep vendored C headers under MAX_PATH.
CRATE_HUB = "c"
# External crates the binaries must build with Cargo's target-side features.
# crate_universe folds a host triple's build-dependency features into that
# triple's normal build, so a build-dependency can widen the shipped crate:
# tree-sitter's build script enables serde_json/preserve_order, which turns
# every sorted JSON object (and the digests over it) into insertion order.
TARGET_FEATURE_CRATES = ("serde_json",)
TARGET_TRIPLE = "x86_64-unknown-linux-gnu"
GEN_BEGIN = "# BEGIN generated by scripts/bazel/gen_builds.py"
GEN_END = "# END generated by scripts/bazel/gen_builds.py"

# Files a build script READS at run time; sandboxing hides undeclared inputs.
BUILD_SCRIPT_DATA = {
    "tracedecay-agent-hosts": [
        "//plugin:sources",
        "//:version.txt",
        "//:Cargo.toml",
    ],
    "tracedecay-sdk": ["//:Cargo.toml"],
    "tracedecay-cli": [
        "//dashboard:dashboard_sources",
        "//dashboard:app_dist",
        "//dashboard:bundle_sha256",
        "//:version.txt",
        "//:product_git_sha",
    ],
}

# Extra data expressions (globs) appended to a build script's data. They name
# files the script reads under its own package, e.g. vendored C grammars.
BUILD_SCRIPT_DATA_EXTRA = {
    "tracedecay-code-extraction": ['glob(["vendor/**"])'],
}

# Extra compile-time data (include_str!/include_bytes! outside src/).
COMPILE_DATA_EXTRA = {
    "tracedecay-agent-hosts": [
        "//dashboard:hermes_wrapper",
        "//plugin:sources",
        "//plugin/chatgpt-extension:sources",
        "//plugin/cursor-native-extension:sources",
    ],
}

# #[path] modules a build script pulls in outside its own directory.
BUILD_SCRIPT_SRCS_EXTRA = {
    "tracedecay-cli": ['glob(["build-support/*.rs"])'],
    "tracedecay-agent-hosts": ["src/product_version/root_manifest.rs"],
    "tracedecay-sdk": ["src/codegen.rs"],
}

# build_script_env values keyed per member.
BUILD_SCRIPT_ENV = {
    "tracedecay-cli": {
        "TRACEDECAY_SKIP_DASHBOARD_BUILD": "1",
        "TRACEDECAY_DASHBOARD_DIST_DIR": "$(location //dashboard:app_dist)",
        "TRACEDECAY_DASHBOARD_BUNDLE_SHA256_FILE": "$(location //dashboard:bundle_sha256)",
        "TRACEDECAY_RELEASE_GIT_SHA_FILE": "$(location //:product_git_sha)",
    },
}


# Workspace binaries test suites resolve at run time, keyed by the override
# variable their helper reads (crates/tracedecay/tests/common, the SDK suite
# and the host-CLI fixture installer). Bazel hands each over as a runfiles
# path, so no suite depends on Cargo's target/<profile>/ layout. Binaries name
# their `__test` build, which carries the test run's features as Cargo's would.
RUNTIME_BINARIES = (
    (
        "TRACEDECAY_TYPESCRIPT_SDK_DIST",
        "//sdks/typescript:dist",
        r'var_os\("TRACEDECAY_TYPESCRIPT_SDK_DIST"\)',
    ),
    (
        "TRACEDECAY_TYPESCRIPT_SDK_RUNNER",
        "//sdks/typescript:typed_terminal_live",
        r'var_os\("TRACEDECAY_TYPESCRIPT_SDK_RUNNER"\)',
    ),
    (
        "TRACEDECAY_TEST_BIN",
        "//crates/tracedecay-cli:tracedecay__test",
        r'(?<!fn )\btracedecay_bin\(\)|var(?:_os)?\("TRACEDECAY_TEST_BIN"\)',
    ),
    (
        "TRACEDECAY_SEARCH_EVAL_TEST_BIN",
        "//crates/tracedecay-search-eval:tracedecay-search-eval_bin__test",
        r'search_eval_bin\("tracedecay-search-eval"\)',
    ),
    (
        "TRACEDECAY_SEARCH_EVAL_DIRECT_TEST_BIN",
        "//crates/tracedecay-search-eval:tracedecay-search-eval-direct__test",
        # Calls only: tests/common names the override inside search_eval_bin,
        # which every suite that includes common compiles.
        r'\bsearch_eval_direct_bin\(\)|search_eval_bin\("tracedecay-search-eval-direct"\)',
    ),
    (
        "TRACEDECAY_HOST_CLI_FIXTURE",
        "//crates/tracedecay-cli:tracedecay-host-cli-fixture",
        r'\bcompiled_host_cli_fixture\(\)',
    ),
)


# Marks a resolution context that Cargo builds with `--no-default-features`.
NO_DEFAULT_FEATURES = "!no-default-features"


_ANSI = re.compile(r"\x1b\[[0-9;]*m")


def run(cmd, cwd=REPO):
    out = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f"{' '.join(cmd)} failed:\n{out.stderr}")
    # CARGO_TERM_COLOR=always CI shells would otherwise bake color escapes
    # into parsed feature names; --color never covers Cargo, this covers the
    # rest.
    return _ANSI.sub("", out.stdout)


def perf_opt_levels():
    """Cargo `perf` opt-level per package name, the profile hosted CI tests
    with. `perf` inherits `dev`, so a package resolves to its perf override,
    then its dev override, then the perf and dev profile defaults."""
    profiles = tomllib.loads((REPO / "Cargo.toml").read_text())["profile"]
    perf = profiles.get("perf", {})
    dev = profiles.get("dev", {})
    default = perf.get("opt-level", dev.get("opt-level", 0))
    names = set(perf.get("package", {})) | set(dev.get("package", {}))
    levels = {}
    for name in names - {"*"}:
        for profile in (perf, dev):
            level = profile.get("package", {}).get(name, {}).get("opt-level")
            if level is not None:
                levels[name] = level
                break
    return default, levels


def cargo_metadata():
    return json.loads(
        run(["cargo", "metadata", "--format-version", "1", "--no-deps", "-q",
             "--color", "never"])
    )


_TREE_LINE = re.compile(
    r"^(?P<name>\S+) v(?P<ver>\S+)(?: \((?P<path>[^)]+)\))?\|(?P<feats>.*)$"
)


def feature_map(pkg_name, edges, features=()):
    """cargo tree resolution for one root context, or for the whole workspace
    when `pkg_name` is None (features then carry their `pkg/` prefix). Maps
    member -> feature set."""
    root = ["--workspace"] if pkg_name is None else ["-p", pkg_name]
    cmd = [
        "cargo", "tree", *root, "-e", edges,
        "-f", "{p}|{f}", "--prefix", "none", "--color", "never",
    ]
    features = set(features)
    if NO_DEFAULT_FEATURES in features:
        features.discard(NO_DEFAULT_FEATURES)
        cmd.append("--no-default-features")
    if features:
        cmd += ["--features", ",".join(sorted(features))]
    fmap = {}
    for line in run(cmd).splitlines():
        m = _TREE_LINE.match(line.strip())
        if not m or not m.group("path"):
            continue
        if "/crates/" not in m.group("path"):
            continue
        # cargo tree marks repeated subtrees by appending ' (*)' inside the
        # feature field; strip the marker before splitting.
        raw = m.group("feats").replace("(*)", "")
        feats = {f.strip() for f in raw.split(",") if f.strip()}
        fmap.setdefault(m.group("name"), set()).update(feats)
    return fmap


def target_feature_annotations(locked):
    """crate.annotation()s rebuilding each TARGET_FEATURE_CRATES library in
    its own repository from Cargo's target resolution. The override keeps the
    generated deps and build script; only the feature set narrows."""
    full = json.loads(
        run(["cargo", "metadata", "--format-version", "1", "-q", "--color", "never",
             "--filter-platform", TARGET_TRIPLE])
    )
    blocks = []
    for name in TARGET_FEATURE_CRATES:
        versions = sorted(p["version"] for p in locked if p["name"] == name)
        if len(versions) != 1:
            sys.exit(f"{name}: expected one locked version, found {versions}")
        version = versions[0]
        tree = [
            m for line in run([
                "cargo", "tree", "-p", f"{name}@{version}", "-e", "normal",
                "--depth", "1", "--target", TARGET_TRIPLE, "-f", "{p}|{f}",
                "--prefix", "none", "--color", "never",
            ]).splitlines()
            if (m := _TREE_LINE.match(line.strip()))
        ]
        root, deps = tree[0], tree[1:]
        features = sorted(f for f in root.group("feats").split(",") if f)
        package = next(
            p for p in full["packages"] if p["name"] == name and p["version"] == version
        )
        lib = next(t for t in package["targets"] if "lib" in t["kind"])
        has_build = any("custom-build" in t["kind"] for t in package["targets"])
        repo = f"{CRATE_HUB}__{name}-{version}"

        def lib_label(dep_name, dep_version):
            dep = next(
                p for p in full["packages"]
                if p["name"] == dep_name and p["version"] == dep_version
            )
            dep_lib = next(t for t in dep["targets"] if "lib" in t["kind"])
            return f"@{CRATE_HUB}__{dep_name}-{dep_version}//:{dep_lib['name'].replace('-', '_')}"

        dep_labels = sorted(lib_label(m.group("name"), m.group("ver")) for m in deps)
        if has_build:
            dep_labels.append(f"@{repo}//:build_script_build")
        crate_root = Path(lib["src_path"]).relative_to(Path(package["manifest_path"]).parent)
        target = f"{lib['name'].replace('-', '_')}_target"
        blocks.append(
            "crate.annotation(\n"
            '    additive_build_file_content = """\n'
            # The override replaces the generated library, and with it the
            # file's own rust_library load.
            'load("@rules_rust//rust:defs.bzl", _target_rust_library = "rust_library")\n'
            "\n"
            "_target_rust_library(\n"
            f'    name = "{target}",\n'
            '    srcs = glob(["**/*.rs"], allow_empty = True),\n'
            '    compile_data = glob(["**"], allow_empty = True, exclude = ["**/* *", ".tmp_git_root/**/*", "BUILD", "BUILD.bazel", "WORKSPACE", "WORKSPACE.bazel"]),\n'
            f'    crate_features = [{q(features)}],\n'
            f'    crate_name = "{lib["name"].replace("-", "_")}",\n'
            f'    crate_root = "{crate_root}",\n'
            f'    edition = "{package["edition"]}",\n'
            '    rustc_flags = ["--cap-lints=allow"],\n'
            f'    tags = ["cargo-bazel", "crate-name={name}", "manual", "noclippy", "norustfmt"],\n'
            f'    version = "{version}",\n'
            f"    deps = [{q(dep_labels)}],\n"
            ")\n"
            '""",\n'
            f'    crate = "{name}",\n'
            f'    override_target_lib = "@{repo}//:{target}",\n'
            f'    version = "{version}",\n'
            ")\n"
            # The root module resolves the override label, so it needs the
            # crate repository in view.
            f'use_repo(crate, "{repo}")'
        )
    return (
        GEN_BEGIN
        + "\n# Cargo's target features for crates a build-dependency widens\n"
        + "# (TARGET_FEATURE_CRATES in scripts/bazel/gen_builds.py).\n"
        + "\n".join(blocks)
        + "\n"
        + GEN_END
    )


_CFG_TOKEN = re.compile(r'"(?:[^"\\]|\\.)*"|[A-Za-z_][A-Za-z0-9_.]*|[(),=]')


def _cfg_parse(source):
    """Cargo cfg() expression -> ('all'|'any'|'not', [nodes]) | ('flag', name)
    | ('kv', key, value). Raises ValueError on any other shape."""
    tokens = []
    pos = 0
    while pos < len(source):
        if source[pos].isspace():
            pos += 1
            continue
        match = _CFG_TOKEN.match(source, pos)
        if not match:
            raise ValueError(source)
        tokens.append(match.group(0))
        pos = match.end()
    pos = 0

    def expression():
        nonlocal pos
        if pos >= len(tokens):
            raise ValueError(source)
        token = tokens[pos]
        pos += 1
        if token in ("all", "any", "not") and pos < len(tokens) and tokens[pos] == "(":
            pos += 1
            children = []
            while pos < len(tokens) and tokens[pos] != ")":
                children.append(expression())
                if pos < len(tokens) and tokens[pos] == ",":
                    pos += 1
                else:
                    break
            if pos >= len(tokens) or tokens[pos] != ")":
                raise ValueError(source)
            pos += 1
            if not children or (token == "not" and len(children) != 1):
                raise ValueError(source)
            return (token, children)
        if token in ("(", ")", ",", "=") or token.startswith('"'):
            raise ValueError(source)
        if pos < len(tokens) and tokens[pos] == "=":
            pos += 1
            if pos >= len(tokens) or not tokens[pos].startswith('"'):
                raise ValueError(source)
            try:
                value = json.loads(tokens[pos])
            except ValueError:
                raise ValueError(source) from None
            pos += 1
            return ("kv", token, value)
        return ("flag", token)

    tree = expression()
    if pos != len(tokens):
        raise ValueError(source)
    return tree


def _cfg_eval(node):
    """Tri-state Cargo cfg evaluation for a generic Linux host: True/False
    when the answer is platform-fixed, None when it depends on the machine
    (target_arch, target_env, target_abi, endian, pointer width, vendor,
    target_feature, panic, feature)."""
    op = node[0]
    if op == "flag":
        return {"unix": True, "windows": False}.get(node[1])
    if op == "kv":
        key, value = node[1], node[2]
        if key == "target_os":
            return value == "linux"
        if key == "target_family":
            # unix admits the lane; the other Cargo families never do.
            return {"unix": True, "windows": False, "wasm": False}.get(value)
        return None
    verdicts = [_cfg_eval(child) for child in node[1]]
    if op == "not":
        return None if verdicts[0] is None else not verdicts[0]
    if op == "any":
        if True in verdicts:
            return True
        return None if None in verdicts else False
    if False in verdicts:
        return False
    return None if None in verdicts else True


def cfg_applies_linux(target):
    """Whether a member dep's Cargo target gate admits it on Linux.

    The generated graph is the Linux resolution only: cfg() gates are
    evaluated as Cargo does — nested all/any/not included — and a gate whose
    answer depends on the host aborts the generator instead of baking one
    machine's graph into the tree."""
    if target is None:
        return True
    t = target.strip()
    if not t.startswith("cfg("):
        # A concrete target triple admits the dep only on a matching Linux.
        return "linux" in t
    verdict = None
    if t.endswith(")"):
        try:
            verdict = _cfg_eval(_cfg_parse(t[4:-1]))
        except ValueError:
            pass
    if verdict is None:
        sys.exit(
            f"gen_builds.py: member dependency target gate {target!r} is not "
            "resolvable for a generic Linux host; the Bazel lane resolves "
            "the Linux dependency graph only, so decide the mapping "
            "explicitly"
        )
    return verdict


def variant_name(pkg, feats, base):
    """Target name for a feature-set variant. `+feats`/`-feats` vs the
    member's own build-context set. `__bare` when nothing resolves."""
    if feats == base:
        return pkg
    if not feats:
        return f"{pkg}__bare"
    suffix = []
    plus = sorted(feats - base)
    minus = sorted(base - feats)
    if plus:
        suffix.extend(f"+{f}" for f in plus)
    if minus:
        suffix.extend(f"-{f}" for f in minus)
    name = f"{pkg}__{'_'.join(suffix)}"
    if len(name) > 120:
        name = f"{pkg}__cfg_{hashlib.sha1(','.join(sorted(feats)).encode()).hexdigest()[:8]}"
    return name


def q(items):
    return ", ".join(json.dumps(i) for i in items)


def env_dict(env):
    """A Starlark dict literal with sorted keys."""
    return "{" + ", ".join(
        f"{json.dumps(k)}: {json.dumps(v)}" for k, v in sorted(env.items())
    ) + "}"


@lru_cache(maxsize=None)
def rust_sources(roots):
    """(path, text) for every .rs file under `roots`, read once per run: the
    per-target scans below all walk the same test and #[path] trees."""
    seen = {}
    for root in roots:
        for f in root.rglob("*.rs"):
            seen.setdefault(f, f.read_text(errors="replace"))
    return tuple(seen.items())


def target_sources(t, extra_dirs=()):
    return rust_sources((Path(t["src_path"]).resolve().parent, *extra_dirs))


RE_PATH_ATTR = re.compile(r'^[ \t]*#\[\s*path\s*=\s*"([^"]+)"\]', re.M)
RE_BIN_EXE = re.compile(r'CARGO_BIN_EXE_([A-Za-z0-9_-]+)')
RE_INCLUDE = re.compile(r'include_(?:str|bytes)!\s*\(\s*"([^"]+)"')
RE_INCLUDE_MANIFEST = re.compile(
    r'include_(?:str|bytes)!\s*\(\s*concat!\s*\('
    r'\s*env!\s*\(\s*"CARGO_MANIFEST_DIR"\s*\)\s*,\s*"([^"]+)"'
)


def main():
    if sys.argv[1:] not in ([], ["--check"]):
        sys.exit("usage: gen_builds.py [--check]")
    check_only = sys.argv[1:] == ["--check"]
    meta = cargo_metadata()
    opt_default, opt_levels = perf_opt_levels()
    members = {p["name"]: p for p in meta["packages"]}
    dir_of = {
        p["name"]: str(Path(p["manifest_path"]).parent.relative_to(REPO))
        for p in meta["packages"]
    }
    rel_src = lambda p, t: str(Path(t["src_path"]).relative_to(Path(p["manifest_path"]).parent))
    member_deps_of = {}
    for p in meta["packages"]:
        by_kind = {"normal": [], "dev": [], "build": []}
        for d in p["dependencies"]:
            if d["name"] in members and cfg_applies_linux(d.get("target")):
                # cargo metadata 1.x reports normal deps as null, not "normal".
                by_kind[d["kind"] or "normal"].append(d["name"])
        member_deps_of[p["name"]] = by_kind

    # Every feature-resolution context a generated target needs.
    contexts = {}
    for p in meta["packages"]:
        name = p["name"]
        contexts[(name, "normal,build", frozenset())] = None
        contexts[(name, "normal,build,dev", frozenset())] = None
        reqs = set()
        for t in p["targets"]:
            req = t.get("required-features") or []
            if not req:
                continue
            edges = (
                "normal,build,dev"
                if {"test", "bench", "example"} & set(t["kind"])
                else "normal,build"
            )
            reqs.add((edges, frozenset(req)))
        for edges, req in reqs:
            contexts[(name, edges, req)] = None
    # The lean root build (`cargo check -p tracedecay --no-default-features`).
    contexts[("tracedecay", "normal,build", frozenset({NO_DEFAULT_FEATURES}))] = None

    # Every test context shares one workspace-wide resolution, as one `cargo
    # test --workspace` does, with every feature a test, bench or example
    # requires and each test-transport surface CI checks compiles (`cargo
    # check --workspace --all-targets --features test-transport`) enabled,
    # as the hosted CI test partitions enabled them. Resolving each member's
    # tests on their own, as `cargo test -p <member>` does, gave every member
    # its own featured copy of its dependency closure: 534 libraries for 50
    # crates. Feature-absence tests carry their own cfg gates.
    gated = frozenset(
        f"{p['name']}/{f}"
        for p in meta["packages"]
        for t in p["targets"]
        if {"test", "bench", "example"} & set(t["kind"])
        for f in t.get("required-features") or []
    ) | frozenset(
        f"{p['name']}/test-transport"
        for p in meta["packages"]
        if "test-transport" in p["features"]
    )

    def resolution(key):
        name, edges, req = key
        return (None, edges, gated) if "dev" in edges else key

    # Each distinct resolution is an independent `cargo tree` walk.
    walks = list(dict.fromkeys(resolution(key) for key in contexts))
    with ThreadPoolExecutor() as pool:
        walked = dict(zip(walks, pool.map(lambda key: feature_map(*key), walks)))
    contexts = {key: walked[resolution(key)] for key in contexts}

    base = {n: frozenset(contexts[(n, "normal,build", frozenset())][n]) for n in members}

    # Cargo resolves a member's member-deps inside the consuming build's own
    # graph, so a lib variant's identity is (edge-context kind, the member's
    # own feature set, and the member's whole transitive member-dep closure as
    # resolved in that context). Fingerprinting only direct pairs lets two
    # consumers share a variant whose deps were resolved differently, which
    # splits a crate's identity across one compile (rustc E0277/E0308) or
    # passes two rlibs of one crate (E0464).
    kind_of = lambda edges: "dev" if "dev" in edges else "norm"

    # Cargo dev-deps feed only the declaring crate's test/bench/example
    # targets; library variants never link them, which is why cargo permits
    # dev-dep cycles between members. Lib identity therefore closes over
    # normal member edges only.
    def pairs_of(member, fmap):
        return frozenset(
            (d, frozenset(fmap[d]))
            for d in member_deps_of[member]["normal"]
            if d in fmap
        )

    def closure_of(member, fmap):
        """{(dep, feature set, dep's own pairs)} across the transitive member
        closure of `member` under `fmap`."""
        seen = {}
        stack = [member]
        while stack:
            m = stack.pop()
            if m in seen or m not in fmap:
                continue
            pairs = pairs_of(m, fmap)
            seen[m] = (frozenset(fmap[m]), pairs)
            stack.extend(d for d, _ in pairs if d not in seen)
        return frozenset(
            (m, feats, frozenset((d, f) for d, f in pairs))
            for m, (feats, pairs) in seen.items()
        )

    canonical_closures = {
        n: {
            "norm": closure_of(n, contexts[(n, "normal,build", frozenset())]),
            "dev": closure_of(n, contexts[(n, "normal,build,dev", frozenset())]),
        }
        for n in members
    }

    def tname(member, kind, closure):
        feats = next(fs for m, fs, _ in closure if m == member)
        name = variant_name(member, frozenset(feats), base[member])
        if closure != canonical_closures[member][kind]:
            sig = hashlib.sha1(
                repr(
                    sorted(
                        (m, tuple(sorted(fs)), tuple(sorted((d, tuple(sorted(f))) for d, f in ps)))
                        for m, fs, ps in closure
                    )
                ).encode()
            ).hexdigest()[:10]
            name = f"{name}__d{sig}"
        return name if kind == "norm" else name + "__dev"

    # Variants map member -> (kind, closure) -> one producing context's fmap.
    # Dep labels inside the emitted rule come from that single fmap, so a rule
    # never sees two resolutions of one crate.
    variants = {n: {} for n in members}
    for (name, edges, req), fmap in contexts.items():
        kind = kind_of(edges)
        for member, feats in fmap.items():
            if member not in members:
                continue
            closure = closure_of(member, fmap)
            variants[member].setdefault((kind, closure), fmap)

    def label(member, fmap, kind="norm"):
        closure = closure_of(member, fmap)
        return f"//{dir_of[member]}:{tname(member, kind, closure)}"

    def dedup(seq):
        return list(dict.fromkeys(seq))

    def srcs_expr(fragments):
        """srcs attr from a mix of file paths and raw glob() expressions."""
        files = [f for f in fragments if not f.startswith("glob(")]
        expr = "[" + q(files) + "]"
        for g in fragments:
            if g.startswith("glob("):
                expr += " + " + g
        return expr

    # Sources that live outside the package dir (repo-root tests/ suites
    # shared between member crates) need a filegroup in their own package.
    out_of_pkg = {}  # (top_dir, group_dir) -> set of crate_root paths in package

    def owner_pkg(repo_rel):
        """Package dir that owns repo_rel plus the group dir inside it. Crates
        members own their subtree. Other top-level dirs own theirs."""
        parts = repo_rel.parts
        if parts[0] == "crates":
            return str(Path(*parts[:2])), str(Path(*parts[2:-1]))
        return parts[0], str(Path(*parts[1:-1]))

    def group_label(repo_rel, *, sources=False):
        """filegroup label + pkg-relative file label for an out-of-package
        file, registering the group for emission in the owning package."""
        pkg_dir, group_rel = owner_pkg(repo_rel)
        pkg_rel = str(Path(*repo_rel.parts[len(Path(pkg_dir).parts):]))
        gname = group_rel.replace("/", "_") or pkg_dir
        if (pkg_dir, gname) == ("tests", "fixtures"):
            gname = "shared_fixtures"
        entry = out_of_pkg.setdefault((pkg_dir, gname), {"files": set(), "glob": group_rel})
        entry["files"].add(pkg_rel)
        if sources:
            gname += "_sources"
            entry = out_of_pkg.setdefault(
                (pkg_dir, gname), {"files": set(), "glob": group_rel, "sources": True}
            )
            entry["files"].add(pkg_rel)
        return f"//{pkg_dir}:{gname}", pkg_dir, pkg_rel

    def srcs_for(p, t):
        """(srcs_expr, crate_root) for a target, crossing into another package
        when Cargo points outside the crate directory."""
        crate_dir = Path(p["manifest_path"]).parent
        rel = rel_src(p, t)
        if rel.startswith(".."):
            repo_rel = Path(t["src_path"]).resolve().relative_to(REPO)
            glabel, pkg_dir, pkg_rel = group_label(repo_rel, sources=True)
            return (f'["{glabel}"]', f'"//{pkg_dir}:{pkg_rel}"')
        d = Path(rel).parent
        # Package-root fixtures are data, including deliberately invalid or
        # vendored Rust. Nested support/fixtures modules remain source inputs.
        exclude = ', exclude = ["tests/fixtures/**"]' if d == Path("tests") else ""
        return (f'glob(["{d}/**/*.rs"]{exclude})', f'"{rel}"')

    def extra_mod_srcs(p, t, covered=()):
        """(pkg_relative_srcs, filegroup_labels) for `#[path = "..."]` modules
        a target's sources pull in. Inside the crate they become literal srcs
        entries, outside it they become //<pkg>:<group> labels. Paths under
        `covered` dirs are already matched by the target's srcs glob."""
        crate_dir = Path(p["manifest_path"]).parent
        base = Path(t["src_path"]).resolve().parent
        covered = tuple(covered) + (base,)
        local, labels, pulled_dirs = set(), set(), set()
        # Fixed point. Pulled-in files can carry their own #[path] escapes.
        seen, queue = set(), [base]
        while queue:
            root = queue.pop()
            for f in root.rglob("*.rs"):
                if f in seen:
                    continue
                seen.add(f)
                for m in RE_PATH_ATTR.finditer(f.read_text(errors="replace")):
                    resolved = (f.parent / m.group(1)).resolve()
                    try:
                        repo_rel = resolved.relative_to(REPO)
                    except ValueError:
                        continue
                    if resolved.parent not in pulled_dirs:
                        pulled_dirs.add(resolved.parent)
                        queue.append(resolved.parent)
                    if crate_dir in resolved.parents or resolved.parent == crate_dir:
                        if not any(d in resolved.parents for d in covered):
                            # The pulled-in file can declare its own `mod`
                            # children, which resolve beside it. Glob its dir.
                            local.add(
                                str(resolved.parent.relative_to(crate_dir))
                                + "/**/*.rs"
                            )
                        continue
                    glabel, _, _ = group_label(repo_rel, sources=True)
                    labels.add(glabel)
        return sorted(local), sorted(labels), sorted(pulled_dirs)

    RESOURCE_DIRS = (
        "src", "assets", "fixtures", "data", "resources", "vendor", "tests",
    )

    def extra_compile_data(p, t, extra_dirs=()):
        """(in_crate_globs, filegroup_labels) for include_str!/include_bytes!
        paths escaping the crate. `extra_dirs` are additional source dirs to
        scan (dirs of files pulled in via #[path]). Dirs already covered by
        the standard resource globs or //tests:fixtures are skipped."""
        crate_dir = Path(p["manifest_path"]).parent
        covered = tuple(crate_dir / d for d in RESOURCE_DIRS)
        local, labels = set(), set()
        for f, text in target_sources(t, tuple(extra_dirs)):
            include_hits = [
                (f.parent / m.group(1)).resolve()
                for m in RE_INCLUDE.finditer(text)
            ]
            include_hits += [
                (crate_dir / m.group(1).lstrip("/")).resolve()
                for m in RE_INCLUDE_MANIFEST.finditer(text)
            ]
            for resolved in include_hits:
                try:
                    repo_rel = resolved.relative_to(REPO)
                except ValueError:
                    continue
                if repo_rel.parts[0] == "tests":
                    continue  # covered by //tests:fixtures
                if crate_dir in resolved.parents or resolved.parent == crate_dir:
                    if not any(d in resolved.parents for d in covered):
                        local.add(
                            str(resolved.parent.relative_to(crate_dir))
                            + "/**"
                        )
                    continue
                glabel, _, _ = group_label(repo_rel)
                labels.add(glabel)
        return sorted(local), sorted(labels)

    def needed_bin_exes(p, t, extra_dirs=()):
        """CARGO_BIN_EXE_<name> literals a target's sources compile, mapped to
        that package's emitted bin target names."""
        return sorted(
            {name for _, text in target_sources(t, tuple(extra_dirs)) for name in RE_BIN_EXE.findall(text)}
        )

    def runtime_binaries(p, t, extra_dirs=()):
        """{env var: label} for workspace binaries a target's sources locate
        at run time through the shared test helpers, which read these
        overrides before falling back to Cargo's profile directory."""
        text = "".join(text for _, text in target_sources(t, tuple(extra_dirs)))
        return {
            variable: label
            for variable, label, pattern in RUNTIME_BINARIES
            if re.search(pattern, text)
        }

    def needs_env_tmpdir(p, t, extra_dirs=()):
        """True when a target's sources compile env!("CARGO_TARGET_TMPDIR"),
        which Cargo exports only for integration-test units."""
        return any(
            "CARGO_TARGET_TMPDIR" in text
            for _, text in target_sources(t, tuple(extra_dirs))
        )

    def render_build(p):
        name = p["name"]
        manifest = tomllib.loads(Path(p["manifest_path"]).read_text())
        test_sizes = (p.get("metadata") or {}).get("bazel", {}).get("test_sizes", {})
        if not isinstance(test_sizes, dict) or any(
            size not in ("small", "medium", "large", "enormous")
            for size in test_sizes.values()
        ):
            sys.exit(f"{name}: package.metadata.bazel.test_sizes must map targets to native Bazel sizes")
        test_sizes = dict(test_sizes)

        def test_size_attr(target):
            size = test_sizes.pop(target, None)
            return f'    size = "{size}",' if size else None

        # Mirror the Cargo `perf` profile hosted CI tests with: the package's
        # opt-level with debug assertions and overflow checks on. `-c opt`
        # (release) keeps the toolchain's own opt-level 3 without assertions.
        rustc_flags_attr = (
            f"    rustc_flags = perf_rustc_flags({opt_levels.get(name, opt_default)}),"
        )
        used_names = set()

        def unique_name(want):
            """Cargo allows a lib and a bin or a test and a bench to share a
            name; Bazel target names must be unique within the package."""
            if want not in used_names:
                used_names.add(want)
                return want
            for suffix in ("_bin", "_test", "_bench", "_fixture"):
                cand = want + suffix
                if cand not in used_names:
                    used_names.add(cand)
                    return cand
            i = 2
            while f"{want}_{i}" in used_names:
                i += 1
            cand = f"{want}_{i}"
            used_names.add(cand)
            return cand
        build_tree = contexts[(name, "normal,build", frozenset())]
        dev_tree = contexts[(name, "normal,build,dev", frozenset())]
        bin_target_names = {}  # cargo bin name -> target its tests spawn
        md = member_deps_of[name]
        lib_t = next((t for t in p["targets"] if "lib" in t["kind"]), None)
        has_build = any("custom-build" in t["kind"] for t in p["targets"])

        out = [BANNER]
        out.append('package(default_visibility = ["//visibility:public"])\n')
        out.append(
            f'load("@{CRATE_HUB}//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")\n'
            'load("@rules_rust//cargo:defs.bzl", "cargo_build_script")\n'
            'load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")\n'
            'load("//scripts:bazel/rust_test.bzl", "perf_rustc_flags", "rust_test")\n'
        )

        if lib_t:
            for (vkind, closure), vfmap in sorted(
                variants[name].items(),
                key=lambda kv: tname(name, kv[0][0], kv[0][1]),
            ):
                tgt = unique_name(tname(name, vkind, closure))
                deps = dedup(
                    sorted(
                        {
                            label(d, vfmap, vkind)
                            for d in md["normal"]
                            if d in vfmap
                        }
                    )
                )
                if has_build:
                    deps.append(":build_script_build")
                lib_extra, lib_mod_labels, lib_pulled = extra_mod_srcs(
                    p, lib_t, covered=(Path(p["manifest_path"]).parent / "src",)
                )
                inc_local, inc_labels = extra_compile_data(p, lib_t, lib_pulled)
                srcs_expr_lib = 'glob(["src/**/*.rs"])'
                if lib_extra:
                    srcs_expr_lib += " + glob([" + q(lib_extra) + "])"
                if lib_mod_labels:
                    srcs_expr_lib += " + [" + q(lib_mod_labels) + "]"
                out += [
                    "rust_library(",
                    f'    name = "{tgt}",',
                    "    srcs = " + srcs_expr_lib + ",",
                    f'    crate_root = "{rel_src(p, lib_t)}",',
                    f'    crate_name = "{lib_t["name"]}",',
                    '    edition = crate_edition(),',
                    '    compile_data = glob(["src/**/*"], exclude=["src/**/*.rs"], allow_empty = True)\n'
                    '        + glob(["assets/**","fixtures/**","data/**","resources/**","vendor/**"], allow_empty = True)\n'
                    '        + ["//tests:fixtures"]'
                    + (f" + [{q(COMPILE_DATA_EXTRA[name])}]" if COMPILE_DATA_EXTRA.get(name) else "")
                    + (f" + glob([{q(inc_local)}], allow_empty = True)" if inc_local else "")
                    + (f" + [{q(inc_labels)}]" if inc_labels else "")
                    + ",",
                    f'    version = "{p["version"]}",',
                    "    deps = all_crate_deps(normal = True) + [" + q(deps) + "],",
                    '    proc_macro_deps = all_crate_deps(proc_macro = True),',
                    '    aliases = aliases(normal = True),',
                    rustc_flags_attr,
                    "    crate_features = ["
                + q(sorted(next(fs for m, fs, _ in closure if m == name)))
                + "],",
                    ")\n",
                ]

        if has_build:
            srcs = srcs_expr(["build.rs"] + BUILD_SCRIPT_SRCS_EXTRA.get(name, []))
            build_edges = dedup(
                label(d, build_tree) for d in md["build"] if d in build_tree
            )
            out += [
                "cargo_build_script(",
                '    name = "build_script_build",',
                '    crate_name = "build_script_build",',
                '    crate_root = "build.rs",',
                "    srcs = " + srcs + ",",
                "    deps = all_crate_deps(build = True, build_proc_macro = True) + ["
                + q(build_edges) + "],",
                '    edition = crate_edition(),',
                f'    pkg_name = "{name}",',
                f'    version = "{p["version"]}",',
                f"    crate_features = [{q(sorted(build_tree[name]))}],",
            ]
            data_labels = q(BUILD_SCRIPT_DATA.get(name, []))
            data_expr = " + ".join([f"[{data_labels}]"] + BUILD_SCRIPT_DATA_EXTRA.get(name, []))
            if data_labels or BUILD_SCRIPT_DATA_EXTRA.get(name):
                out.append(f"    data = {data_expr},")
            if BUILD_SCRIPT_ENV.get(name):
                out.append(f"    build_script_env = {env_dict(BUILD_SCRIPT_ENV[name])},")
            out.append(")\n")

        for t in p["targets"]:
            kinds = t["kind"]
            if not ({"bin", "example"} & set(kinds)):
                continue
            srcs, crate_root = srcs_for(p, t)
            if not srcs.startswith("[") and rel_src(p, t).startswith("src/"):
                # In-package bins/tests resolve `mod` paths anywhere under
                # src/, not only beside their entry file.
                srcs = 'glob(["src/**/*.rs"])'
            bin_covered = (
                (Path(p["manifest_path"]).parent / "src",)
                if rel_src(p, t).startswith("src/")
                else ()
            )
            bin_local, bin_labels, bin_pulled = extra_mod_srcs(
                p, t, covered=bin_covered
            )
            inc_local_b, inc_labels_b = extra_compile_data(p, t, bin_pulled)
            if bin_local:
                srcs += " + glob([" + q(bin_local) + "])"
            if bin_labels:
                srcs += " + [" + q(bin_labels) + "]"
            req = frozenset(t.get("required-features") or [])
            # Cargo builds examples against the dev resolution, and builds the
            # binaries a test run spawns with that run's features too (test
            # hooks, test-transport). `<bin>__test` is that build; the plain
            # target is the shipped one.
            test_flavor = None
            if "example" in kinds:
                emitted = unique_name(t["name"])
                bin_target_names[t["name"]] = emitted
                flavors = [(emitted, contexts[(name, "normal,build,dev", req)], "dev", True)]
            else:
                emitted = unique_name(t["name"])
                test_flavor = unique_name(emitted + "__test")
                bin_target_names[t["name"]] = test_flavor
                flavors = [
                    (emitted, contexts[(name, "normal,build", req)], "norm", False),
                    (test_flavor, contexts[(name, "normal,build,dev", req)], "dev", False),
                ]
            for emitted, fmap, vkind, dev_args in flavors:
                edges = md["normal"] + (md["dev"] if dev_args else [])
                deps = dedup(
                    sorted({label(d, fmap, vkind) for d in edges if d in fmap})
                )
                if lib_t and name in fmap:
                    deps = dedup([label(name, fmap, vkind)] + deps)
                if has_build:
                    deps.append(":build_script_build")
                out += [
                    "rust_binary(",
                    f'    name = "{emitted}",',
                    # Suites check the spawned binary's own name, so the test
                    # build keeps the shipped file name in a directory of its own.
                    *([
                        "    testonly = True,",
                        f'    binary_name = "test/{t["name"]}",',
                        f'    crate_name = "{t["name"].replace("-", "_")}",',
                    ] if emitted == test_flavor else []),
                    "    srcs = " + srcs + ",",
                    f'    crate_root = {crate_root},',
                    '    edition = crate_edition(),',
                    '    compile_data = glob(["src/**/*"], exclude=["src/**/*.rs"], allow_empty = True)'
                    + ("\n        + glob([" + q(inc_local_b) + "], allow_empty = True)" if inc_local_b else "")
                    + ("\n        + [" + q(inc_labels_b) + "]" if inc_labels_b else "")
                    + ",",
                    f'    version = "{p["version"]}",',
                    "    deps = all_crate_deps(normal = True"
                    + (", normal_dev = True" if dev_args else "")
                    + ") + [" + q(deps) + "],",
                    "    proc_macro_deps = all_crate_deps(proc_macro = True"
                    + (", proc_macro_dev = True" if dev_args else "")
                    + "),",
                    "    aliases = aliases(normal = True"
                    + (", normal_dev = True" if dev_args else "")
                    + "),",
                    rustc_flags_attr,
                    f"    crate_features = [{q(sorted(fmap[name]))}],",
                    ")\n",
                ]
            # A binary's own #[cfg(test)] modules, as `cargo test --bins`
            # runs them, unless the manifest opts it out with `test = false`.
            if "bin" in kinds and t.get("test", True):
                fmap = contexts[(name, "normal,build,dev", req)]
                deps = dedup(
                    sorted(
                        {
                            label(d, fmap, "dev")
                            for d in md["normal"] + md["dev"]
                            if d in fmap
                        }
                    )
                )
                if lib_t and name in fmap:
                    deps = dedup([label(name, fmap, "dev")] + deps)
                if has_build:
                    deps.append(":build_script_build")
                runfiles_env = runtime_binaries(p, t, bin_pulled)
                test_name = unique_name(t["name"] + "_unit_test")
                out += [
                    "rust_test(",
                    f'    name = "{test_name}",',
                    test_size_attr(test_name),
                    f'    crate = ":{test_flavor}",',
                    f"    crate_features = [{q(sorted(fmap[name]))}],",
                    '    edition = crate_edition(),',
                    f'    version = "{p["version"]}",',
                    "    deps = all_crate_deps(normal = True, normal_dev = True) + ["
                    + q(deps) + "],",
                    '    proc_macro_deps = all_crate_deps('
                    "proc_macro = True, proc_macro_dev = True),",
                    '    aliases = aliases(normal = True, normal_dev = True),',
                    rustc_flags_attr,
                    '    compile_data = glob(["tests/**","assets/**","fixtures/**","data/**","resources/**","vendor/**"], allow_empty = True)\n'
                    '        + ["//tests:fixtures"],',
                    '    data = glob(["tests/**","assets/**","fixtures/**","data/**","resources/**","vendor/**"], allow_empty = True) + ["//tests:fixtures"],',
                    "    runfiles_env = " + env_dict(runfiles_env) + "," if runfiles_env else None,
                    ")\n",
                ]
                out = [l for l in out if l is not None]

        for t in p["targets"]:
            kinds = t["kind"]
            if not ({"test", "bench"} & set(kinds)):
                continue
            declared_target = next(
                (target for kind in kinds for target in manifest.get(kind, [])
                 if target.get("name") == t["name"]),
                {},
            )
            req = frozenset(t.get("required-features") or [])
            fmap = contexts[(name, "normal,build,dev", req)]
            deps = dedup(
                sorted(
                    {
                        label(d, fmap, "dev")
                        for d in md["normal"] + md["dev"]
                        if d in fmap
                    }
                )
            )
            if lib_t and name in fmap:
                deps = dedup([label(name, fmap, "dev")] + deps)
            if has_build:
                deps.append(":build_script_build")
            srcs, crate_root = srcs_for(p, t)
            mod_local, mod_labels, mod_pulled = extra_mod_srcs(p, t)
            inc_local_t, inc_labels_t = extra_compile_data(p, t, mod_pulled)
            if mod_local:
                srcs += " + glob([" + q(mod_local) + "])"
            if mod_labels:
                srcs += " + [" + q(mod_labels) + "]"
            runtime_globs = dedup([
                f"{Path(rel_src(p, t)).parent}/**",
                *[f"{directory}/**" for directory in RESOURCE_DIRS if directory != "src"],
            ])
            # Source groups keep separate full resource groups for runfiles.
            data = srcs.replace("_sources\"", "\"") if srcs.startswith("[") else (
                f"glob([{q(runtime_globs)}], allow_empty = True)"
                + (" + [" + q([label.removesuffix("_sources") for label in mod_labels]) + "]" if mod_labels else "")
            )
            # Suites read the shared fixtures as ../../tests/fixtures from the
            # crate directory, where the launcher starts them.
            data += ' + ["//tests:fixtures"]'
            if name == "tracedecay" and t["name"] == "memory_suite":
                data += ' + ["//evals/memory:scenarios"]'
            if name == "tracedecay" and t["name"] == "claude_observation_benchmark":
                data += ' + ["//benchmark_data:claude-observation"]'
            if name == "tracedecay" and t["name"] == "session_temporal":
                workload, _, _ = group_label(
                    Path("benchmark_data/session-temporal/workload-v1.json")
                )
                data += " + [" + q([workload]) + "]"
            # include_str!/include_bytes! are compile-time inputs. They cover crate-root
            # resource dirs beside tests/ and repo-root fixtures under //tests.
            compile_data = (
                'glob(["tests/**","assets/**","fixtures/**","data/**","resources/**","vendor/**"], allow_empty = True)'
                ' + ["//tests:fixtures"]'
            )
            if inc_local_t:
                compile_data += (
                    " + glob([" + q(inc_local_t) + "], allow_empty = True)"
                )
            if inc_labels_t:
                compile_data += " + [" + q(inc_labels_t) + "]"
            # env! needs compile-time values; the suites read the launcher's
            # runtime values first (scripts/bazel/rust_test.bzl), which stay
            # valid after a changed cwd and on every host.
            rustc_env = {}
            if needs_env_tmpdir(p, t, mod_pulled):
                rustc_env["CARGO_TARGET_TMPDIR"] = "/tmp"
            runfiles_env = {}
            for bin_name in needed_bin_exes(p, t, mod_pulled):
                emitted = bin_target_names.get(bin_name)
                if emitted is None:
                    continue
                rustc_env[f"CARGO_BIN_EXE_{bin_name}"] = f"$(rootpath :{emitted})"
                runfiles_env[f"CARGO_BIN_EXE_{bin_name}"] = f"//{dir_of[name]}:{emitted}"
            for variable, target in runtime_binaries(p, t, mod_pulled).items():
                runfiles_env.setdefault(variable, target)
            env_attr = "    rustc_env = " + env_dict(rustc_env) + "," if rustc_env else None
            test_name = unique_name(t["name"])
            out += [
                "rust_test(",
                f'    name = "{test_name}",',
                test_size_attr(test_name),
                "    use_libtest_harness = False,"
                if not declared_target.get("harness", True) else None,
                "    srcs = " + srcs + ",",
                f'    crate_root = {crate_root},',
                '    edition = crate_edition(),',
                f'    version = "{p["version"]}",',
                "    deps = all_crate_deps(normal = True, normal_dev = True) + ["
                + q(deps) + "],",
                '    proc_macro_deps = all_crate_deps('
                "proc_macro = True, proc_macro_dev = True),",
                '    aliases = aliases(normal = True, normal_dev = True),',
                rustc_flags_attr,
                f"    crate_features = [{q(sorted(fmap[name]))}],",
                f'    compile_data = {compile_data},',
                f'    data = {data},',
                env_attr,
                "    runfiles_env = " + env_dict(runfiles_env) + "," if runfiles_env else None,
                ")\n",
            ]
            out = [l for l in out if l is not None]

        if lib_t:
            lib_runfiles_env = runtime_binaries(p, lib_t, lib_pulled)
            dev_edges = md["normal"] + md["dev"]
            deps = dedup(
                sorted(
                    {label(d, dev_tree, "dev") for d in dev_edges if d in dev_tree}
                )
            )
            if has_build:
                deps.append(":build_script_build")
            out += [
                "rust_test(",
                '    name = "unit_test",',
                test_size_attr("unit_test"),
                f'    crate = ":{tname(name, "dev", closure_of(name, dev_tree))}",',
                # rust_test(crate=) takes its cfgs from its own
                # crate_features, not the library's.
                f"    crate_features = [{q(sorted(dev_tree[name]))}],",
                '    edition = crate_edition(),',
                f'    version = "{p["version"]}",',
                "    deps = all_crate_deps(normal = True, normal_dev = True) + ["
                + q(deps) + "],",
                '    proc_macro_deps = all_crate_deps('
                "proc_macro = True, proc_macro_dev = True),",
                '    aliases = aliases(normal = True, normal_dev = True),',
                rustc_flags_attr,
                '    compile_data = glob(["tests/**","assets/**","fixtures/**","data/**","resources/**","vendor/**"], allow_empty = True)\n'
                '        + ["//tests:fixtures"]'
                + (f"\n        + glob([{q(inc_local)}], allow_empty = True)" if inc_local else "")
                + (f"\n        + [{q(inc_labels)}]" if inc_labels else "")
                + ",",
                '    data = glob(["tests/**","assets/**","fixtures/**","data/**","resources/**","vendor/**"], allow_empty = True) + ["//tests:fixtures"],',
                "    runfiles_env = " + env_dict(lib_runfiles_env) + ","
                if lib_runfiles_env
                else None,
                ")\n",
            ]
            out = [l for l in out if l is not None]

        if test_sizes:
            sys.exit(f"{name}: test_sizes names unknown test targets: {', '.join(sorted(test_sizes))}")
        if name == "tracedecay-sdk":
            # The Bazel-only SDK generator reuses the canonical renderer and
            # compares its output with the checked-in Rust descriptors.
            out += [
                'exports_files(["src/bin/generate.rs", "src/codegen.rs", "src/operations.rs"],',
                '    visibility = ["//visibility:public"],',
                ')\n',
            ]
        return "\n".join(out)

    outputs = {}
    for p in meta["packages"]:
        outputs[Path(p["manifest_path"]).parent / "BUILD.bazel"] = render_build(p)

    def package_rules(pkg_dir, exports):
        """Generated rules for the out-of-package sources under pkg_dir,
        sorted by group name. `exports` names each referenced file for
        packages the generator owns outright (they have no handwritten
        package() visibility to rely on); shared handwritten packages never
        name member crate roots, so they need none."""
        rules = []
        for gname, entry in sorted(by_pkg.get(pkg_dir, {}).items()):
            pattern = f'{entry["glob"]}/**'
            exclude = ""
            if entry.get("sources"):
                pattern += "/*.rs"
                if entry["glob"] == "tests":
                    exclude = ', exclude = ["tests/fixtures/**"]'
            rules.append(
                f'filegroup(\n    name = "{gname}",\n'
                f'    srcs = glob(["{pattern}"]{exclude}),\n'
                '    visibility = ["//visibility:public"],\n)'
            )
            crate_roots = sorted(entry["files"])
            if exports and crate_roots and not entry.get("sources"):
                rules.append(
                    "exports_files([" + q(crate_roots) + "],\n"
                    '    visibility = ["//visibility:public"],\n)'
                )
        # Repo-root fixture trees members embed via include_str!/include_bytes!.
        if pkg_dir == "tests":
            rules.append(
                'filegroup(\n    name = "fixtures",\n'
                '    srcs = glob(["fixtures/**"]),\n'
                '    visibility = ["//visibility:public"],\n)'
            )
        return rules

    def generated_block(pkg_dir, exports):
        rules = package_rules(pkg_dir, exports)
        if not rules:
            return None
        return GEN_BEGIN + "\n" + "\n\n".join(rules) + "\n" + GEN_END

    def splice_generated(existing, block, path):
        """Expected content for a handwritten BUILD carrying a marked
        generated block: the block's contents are re-rendered in place (or
        appended when absent, or removed when the package no longer needs
        generated groups), so committed rules can never drift."""
        begin = existing.find(GEN_BEGIN)
        if begin == -1:
            if block is None:
                return existing
            return existing.rstrip("\n") + "\n\n" + block + "\n"
        end = existing.find(GEN_END, begin)
        if end == -1:
            sys.exit(f"{path.relative_to(REPO)}: unterminated {GEN_BEGIN!r} block")
        end += len(GEN_END)
        if existing[end : end + 1] == "\n":
            end += 1
        if block is not None:
            return existing[:begin] + block + "\n" + existing[end:]
        # The package's last generated group went away: drop the block and
        # one newline of the blank line that separated it.
        start = begin
        if existing[max(0, begin - 2) : begin] == "\n\n":
            start = begin - 1
        return existing[:start] + existing[end:]

    def render_shared(path, pkg_dir):
        """Expected content for a non-member BUILD the generator writes into:
        wholesale re-render when the generator owns the file outright (first
        line names it), otherwise just the marked generated block."""
        if path.exists():
            existing = path.read_text()
            if not existing.startswith("# Generated by scripts/bazel/gen_builds.py"):
                return splice_generated(existing, generated_block(pkg_dir, False), path)
        block = generated_block(pkg_dir, True)
        if block is None:
            # A fully generated file whose package lost every group is stale;
            # nothing renders, so flag it for removal rather than writing.
            return None
        return BANNER + "\n" + block + "\n"

    # External crates Cargo's perf profile optimizes past the dev default.
    # rules_rust matches per-crate flags on a prefix of the crate root's exec
    # path, which carries the canonical name of the crate_universe repository
    # (`rules_rust++crate+<hub>__<name>-<version>`).
    locked = tomllib.loads((REPO / "Cargo.lock").read_text())["package"]
    external_flags = []
    for package in sorted(locked, key=lambda pkg: (pkg["name"], pkg["version"])):
        level = opt_levels.get(package["name"])
        if package["name"] in members or level is None:
            continue
        prefix = f"external/rules_rust++crate+{CRATE_HUB}__{package['name']}-{package['version']}/"
        external_flags.append(
            f'build "--@rules_rust//rust/settings:per_crate_rustc_flag={prefix}@-Copt-level={level}"'
        )
    bazelrc = REPO / ".bazelrc"
    rc_block = (
        GEN_BEGIN
        + "\n# Cargo perf opt-levels for external crates (see [profile.perf]).\n"
        + "\n".join(external_flags)
        + "\n"
        + GEN_END
    )
    outputs[bazelrc] = splice_generated(bazelrc.read_text(), rc_block, bazelrc)
    module = REPO / "MODULE.bazel"
    outputs[module] = splice_generated(
        module.read_text(), target_feature_annotations(locked), module
    )

    by_pkg = {}
    for (pkg_dir, gname), entry in out_of_pkg.items():
        by_pkg.setdefault(pkg_dir, {})[gname] = entry
    member_dirs = set(dir_of.values())
    obsolete = []
    for pkg_dir in sorted(by_pkg):
        path = REPO / pkg_dir / "BUILD.bazel"
        if pkg_dir in member_dirs:
            # Member BUILDs are fully rendered above; append the filegroups
            # other members reach into this one's subtree for.
            outputs[path] += "\n" + "\n\n".join(package_rules(pkg_dir, False)) + "\n"
            continue
        rendered = render_shared(path, pkg_dir)
        if rendered is None:
            obsolete.append(path)
        else:
            outputs[path] = rendered
    # A generated block or fully generated file can also go stale when its
    # last Cargo reference disappears; re-render the marked ones too.
    for path in sorted(REPO.glob("*/BUILD.bazel")):
        if path in outputs or not path.exists():
            continue
        text = path.read_text()
        if (
            text.startswith("# Generated by scripts/bazel/gen_builds.py")
            or GEN_BEGIN in text
        ):
            rendered = render_shared(path, path.parent.name)
            if rendered is None:
                obsolete.append(path)
            elif rendered != text:
                outputs[path] = rendered

    if check_only:
        stale = [
            path for path in sorted(outputs)
            if not path.exists() or path.read_text() != outputs[path]
        ]
        # A removed member leaves its generated BUILD behind.
        stale += [
            path for path in sorted(REPO.glob("crates/*/BUILD.bazel"))
            if path not in outputs and path.read_text().startswith(BANNER)
        ]
        stale += sorted(obsolete)
        if stale:
            print("generated BUILD.bazel files are out of date:")
            for path in stale:
                print(f"  {path.relative_to(REPO)}")
            print("rerun: bazel run //scripts:bazel/gen_builds.py")
            # Show the first diffs so CI output explains the divergence.
            import difflib
            shown = 0
            for path in stale:
                if shown >= 60:
                    break
                if path not in outputs:
                    print(f"--- {path.relative_to(REPO)}: generated file with no source member")
                    continue
                diff = list(difflib.unified_diff(
                    path.read_text().splitlines(),
                    outputs[path].splitlines(),
                    str(path.relative_to(REPO)), "regenerated", lineterm="",
                ))
                for line in diff[:60 - shown]:
                    print(line)
                shown += len(diff[:60 - shown])
            sys.exit(1)
        print(f"all {len(outputs)} generated BUILD.bazel files are current")
        return

    for path, content in outputs.items():
        path.write_text(content)
    for path in obsolete:
        # Generator-owned files render to nothing once their last Cargo
        # reference is gone; remove them so --check stops flagging the same
        # stale file. Handwritten files keep their (now empty-free) content.
        path.unlink()
        print(f"removed obsolete generated {path.relative_to(REPO)}")

    counts = {
        m: sorted(tname(m, kind, c) for kind, c in v)
        for m, v in sorted(variants.items()) if len(v) > 1
    }
    print(f"wrote BUILD.bazel for {len(members)} members")
    print("members with feature variants:")
    print(json.dumps(counts, indent=2))


if __name__ == "__main__":
    main()
