#!/usr/bin/env python3
"""Generate Bazel BUILD files for the Cargo workspace.

Reads `cargo metadata` for target shapes and `cargo tree` for Cargo's own
feature resolution, then emits one BUILD.bazel per member crate under
crates/. The lane resolves the Linux dependency graph only: member deps
behind foreign-platform target gates are dropped, and an unrecognized gate
aborts the generator instead of silently drifting (see cfg_applies_linux).

Feature model. Cargo compiles a member once per resolved feature set, and the
set depends on the consuming context (normal build vs dev/test resolution vs
required-features). Each member therefore gets one rust_library per distinct
feature set it is ever built with. `<pkg>` covers its own build context and
`<pkg>__<extra-features>` names the variants. A variant's own member deps are the union
of the labels every producing context resolves for them. Dependents pick the
variant matching the feature set Cargo resolves in their context.

Outputs are deterministic. Rerun after any Cargo.toml change. `--check`
verifies the committed BUILD.bazel files match a fresh run without writing.
"""

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent

BANNER = (
    "# Generated by scripts/bazel/gen_builds.py from Cargo.toml + Cargo.lock.\n"
    "# Regenerate instead of editing. python3 scripts/bazel/gen_builds.py\n"
)

# Files a build script READS at run time; sandboxing hides undeclared inputs.
BUILD_SCRIPT_DATA = {
    "tracedecay-agent-hosts": [
        "//plugin:sources",
        "//:version.txt",
        "//:Cargo.toml",
    ],
    "tracedecay-sdk": ["//:Cargo.toml"],
    "tracedecay-cli": [
        "//dashboard:dashboard_sources",
        "//dashboard:app_dist",
        "//dashboard:bundle_sha256",
        "//:version.txt",
        "//:product_git_sha",
    ],
}

# Extra data expressions (globs) appended to a build script's data. They name
# files the script reads under its own package, e.g. vendored C grammars.
BUILD_SCRIPT_DATA_EXTRA = {
    "tracedecay-code-extraction": ['glob(["vendor/**"])'],
}

# Extra compile-time data (include_str!/include_bytes! outside src/).
COMPILE_DATA_EXTRA = {
    "tracedecay-agent-hosts": [
        "//dashboard:hermes_wrapper",
        "//plugin:sources",
        "//plugin/chatgpt-extension:sources",
        "//plugin/cursor-native-extension:sources",
    ],
}

# #[path] modules a build script pulls in outside its own directory.
BUILD_SCRIPT_SRCS_EXTRA = {
    "tracedecay-cli": ['glob(["build-support/*.rs"])'],
    "tracedecay-agent-hosts": ["src/product_version/root_manifest.rs"],
    "tracedecay-sdk": ["src/codegen.rs"],
}

# build_script_env values keyed per member.
BUILD_SCRIPT_ENV = {
    "tracedecay-cli": {
        "TRACEDECAY_SKIP_DASHBOARD_BUILD": "1",
        "TRACEDECAY_DASHBOARD_DIST_DIR": "$(location //dashboard:app_dist)",
        "TRACEDECAY_DASHBOARD_BUNDLE_SHA256_FILE": "$(location //dashboard:bundle_sha256)",
        "TRACEDECAY_RELEASE_GIT_SHA_FILE": "$(location //:product_git_sha)",
    },
}


def run(cmd, cwd=REPO):
    out = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f"{' '.join(cmd)} failed:\n{out.stderr}")
    return out.stdout


def cargo_metadata():
    return json.loads(
        run(["cargo", "metadata", "--format-version", "1", "--no-deps", "-q"])
    )


_TREE_LINE = re.compile(
    r"^(?P<name>\S+) v(?P<ver>\S+)(?: \((?P<path>[^)]+)\))?\|(?P<feats>.*)$"
)


def feature_map(pkg_name, edges, features=()):
    """cargo tree resolution for one root context. Maps member -> feature set."""
    cmd = [
        "cargo", "tree", "-p", pkg_name, "-e", edges,
        "-f", "{p}|{f}", "--prefix", "none",
    ]
    if features:
        cmd += ["--features", ",".join(sorted(features))]
    fmap = {}
    for line in run(cmd).splitlines():
        m = _TREE_LINE.match(line.strip())
        if not m or not m.group("path"):
            continue
        if "/crates/" not in m.group("path"):
            continue
        # cargo tree marks repeated subtrees by appending ' (*)' inside the
        # feature field; strip the marker before splitting.
        raw = m.group("feats").replace("(*)", "")
        feats = {f.strip() for f in raw.split(",") if f.strip()}
        fmap.setdefault(m.group("name"), set()).update(feats)
    return fmap


# Platform tokens that never admit a Linux resolution.
_FOREIGN_PLATFORM = (
    "windows", "macos", "apple", "darwin", "ios", "android", "wasm",
)


def cfg_applies_linux(target):
    """Whether a member dep's Cargo target gate admits it on Linux.

    The generated graph is the Linux resolution only: exact Linux gates keep
    the dep, foreign-platform gates drop it, and any other shape aborts so a
    newly gated member dep fails loudly instead of drifting the graph."""
    if target is None:
        return True
    t = target.replace(" ", "")
    if t in ('cfg(unix)', 'cfg(target_family="unix")', 'cfg(target_os="linux")'):
        return True
    if t.startswith("cfg(not(") and t.endswith("))"):
        inner = t[len("cfg(not("):-2]
        if any(k in inner for k in _FOREIGN_PLATFORM):
            return True
        if "linux" in inner or "unix" in inner:
            return False
    elif any(k in t for k in _FOREIGN_PLATFORM):
        return False
    elif "cfg(" not in t and "linux" in t:
        # Target triple, e.g. x86_64-unknown-linux-gnu.
        return True
    sys.exit(
        f"gen_builds.py: member dependency target gate {target!r} is not a "
        "recognized Linux form; the Bazel lane resolves the Linux dependency "
        "graph only, so decide the mapping explicitly"
    )


def variant_name(pkg, feats, base):
    """Target name for a feature-set variant. `+feats`/`-feats` vs the
    member's own build-context set. `__bare` when nothing resolves."""
    if feats == base:
        return pkg
    if not feats:
        return f"{pkg}__bare"
    suffix = []
    plus = sorted(feats - base)
    minus = sorted(base - feats)
    if plus:
        suffix.extend(f"+{f}" for f in plus)
    if minus:
        suffix.extend(f"-{f}" for f in minus)
    name = f"{pkg}__{'_'.join(suffix)}"
    if len(name) > 120:
        name = f"{pkg}__cfg_{hashlib.sha1(','.join(sorted(feats)).encode()).hexdigest()[:8]}"
    return name


def q(items):
    return ", ".join(json.dumps(i) for i in items)


RE_PATH_ATTR = re.compile(r'^[ \t]*#\[\s*path\s*=\s*"([^"]+)"\]', re.M)
RE_BIN_EXE = re.compile(r'CARGO_BIN_EXE_([A-Za-z0-9_-]+)')
RE_INCLUDE = re.compile(r'include_(?:str|bytes)!\s*\(\s*"([^"]+)"')
RE_INCLUDE_MANIFEST = re.compile(
    r'include_(?:str|bytes)!\s*\(\s*concat!\s*\('
    r'\s*env!\s*\(\s*"CARGO_MANIFEST_DIR"\s*\)\s*,\s*"([^"]+)"'
)


def main():
    if sys.argv[1:] not in ([], ["--check"]):
        sys.exit("usage: gen_builds.py [--check]")
    check_only = sys.argv[1:] == ["--check"]
    meta = cargo_metadata()
    members = {p["name"]: p for p in meta["packages"]}
    dir_of = {
        p["name"]: str(Path(p["manifest_path"]).parent.relative_to(REPO))
        for p in meta["packages"]
    }
    rel_src = lambda p, t: str(Path(t["src_path"]).relative_to(Path(p["manifest_path"]).parent))
    member_deps_of = {}
    for p in meta["packages"]:
        by_kind = {"normal": [], "dev": [], "build": []}
        for d in p["dependencies"]:
            if d["name"] in members and cfg_applies_linux(d.get("target")):
                # cargo metadata 1.x reports normal deps as null, not "normal".
                by_kind[d["kind"] or "normal"].append(d["name"])
        member_deps_of[p["name"]] = by_kind

    # Every feature-resolution context a generated target needs.
    contexts = {}
    for p in meta["packages"]:
        name = p["name"]
        contexts[(name, "normal,build", frozenset())] = None
        contexts[(name, "normal,build,dev", frozenset())] = None
        reqs = set()
        for t in p["targets"]:
            req = t.get("required-features") or []
            if not req:
                continue
            edges = (
                "normal,build,dev"
                if {"test", "bench", "example"} & set(t["kind"])
                else "normal,build"
            )
            reqs.add((edges, frozenset(req)))
        for edges, req in reqs:
            contexts[(name, edges, req)] = None

    for key in contexts:
        name, edges, feats = key
        contexts[key] = feature_map(name, edges, feats)

    base = {n: frozenset(contexts[(n, "normal,build", frozenset())][n]) for n in members}

    # Cargo resolves a member's member-deps inside the consuming build's own
    # graph, so a lib variant's identity is (edge-context kind, the member's
    # own feature set, and the member's whole transitive member-dep closure as
    # resolved in that context). Fingerprinting only direct pairs lets two
    # consumers share a variant whose deps were resolved differently, which
    # splits a crate's identity across one compile (rustc E0277/E0308) or
    # passes two rlibs of one crate (E0464).
    kind_of = lambda edges: "dev" if "dev" in edges else "norm"

    # Cargo dev-deps feed only the declaring crate's test/bench/example
    # targets; library variants never link them, which is why cargo permits
    # dev-dep cycles between members. Lib identity therefore closes over
    # normal member edges only.
    def pairs_of(member, fmap):
        return frozenset(
            (d, frozenset(fmap[d]))
            for d in member_deps_of[member]["normal"]
            if d in fmap
        )

    def closure_of(member, fmap):
        """{(dep, feature set, dep's own pairs)} across the transitive member
        closure of `member` under `fmap`."""
        seen = {}
        stack = [member]
        while stack:
            m = stack.pop()
            if m in seen or m not in fmap:
                continue
            pairs = pairs_of(m, fmap)
            seen[m] = (frozenset(fmap[m]), pairs)
            stack.extend(d for d, _ in pairs if d not in seen)
        return frozenset(
            (m, feats, frozenset((d, f) for d, f in pairs))
            for m, (feats, pairs) in seen.items()
        )

    canonical_closures = {
        n: {
            "norm": closure_of(n, contexts[(n, "normal,build", frozenset())]),
            "dev": closure_of(n, contexts[(n, "normal,build,dev", frozenset())]),
        }
        for n in members
    }

    def tname(member, kind, closure):
        feats = next(fs for m, fs, _ in closure if m == member)
        name = variant_name(member, frozenset(feats), base[member])
        if closure != canonical_closures[member][kind]:
            sig = hashlib.sha1(
                repr(
                    sorted(
                        (m, tuple(sorted(fs)), tuple(sorted((d, tuple(sorted(f))) for d, f in ps)))
                        for m, fs, ps in closure
                    )
                ).encode()
            ).hexdigest()[:10]
            name = f"{name}__d{sig}"
        return name if kind == "norm" else name + "__dev"

    # Variants map member -> (kind, closure) -> one producing context's fmap.
    # Dep labels inside the emitted rule come from that single fmap, so a rule
    # never sees two resolutions of one crate.
    variants = {n: {} for n in members}
    for (name, edges, req), fmap in contexts.items():
        kind = kind_of(edges)
        for member, feats in fmap.items():
            if member not in members:
                continue
            closure = closure_of(member, fmap)
            variants[member].setdefault((kind, closure), fmap)

    def label(member, fmap, kind="norm"):
        closure = closure_of(member, fmap)
        return f"//{dir_of[member]}:{tname(member, kind, closure)}"

    def dedup(seq):
        return list(dict.fromkeys(seq))

    def srcs_expr(fragments):
        """srcs attr from a mix of file paths and raw glob() expressions."""
        files = [f for f in fragments if not f.startswith("glob(")]
        expr = "[" + q(files) + "]"
        for g in fragments:
            if g.startswith("glob("):
                expr += " + " + g
        return expr

    # Sources that live outside the package dir (repo-root tests/ suites
    # shared between member crates) need a filegroup in their own package.
    out_of_pkg = {}  # (top_dir, group_dir) -> set of crate_root paths in package

    def owner_pkg(repo_rel):
        """Package dir that owns repo_rel plus the group dir inside it. Crates
        members own their subtree. Other top-level dirs own theirs."""
        parts = repo_rel.parts
        if parts[0] == "crates":
            return str(Path(*parts[:2])), str(Path(*parts[2:-1]))
        return parts[0], str(Path(*parts[1:-1]))

    def group_label(repo_rel):
        """filegroup label + pkg-relative file label for an out-of-package
        file, registering the group for emission in the owning package."""
        pkg_dir, group_rel = owner_pkg(repo_rel)
        pkg_rel = str(Path(*repo_rel.parts[len(Path(pkg_dir).parts):]))
        gname = group_rel.replace("/", "_") or pkg_dir
        if (pkg_dir, gname) == ("tests", "fixtures"):
            gname = "shared_fixtures"
        entry = out_of_pkg.setdefault((pkg_dir, gname), {"files": set(), "glob": group_rel})
        entry["files"].add(pkg_rel)
        return f"//{pkg_dir}:{gname}", pkg_dir, pkg_rel

    def srcs_for(p, t):
        """(srcs_expr, crate_root) for a target, crossing into another package
        when Cargo points outside the crate directory."""
        crate_dir = Path(p["manifest_path"]).parent
        rel = rel_src(p, t)
        if rel.startswith(".."):
            repo_rel = Path(t["src_path"]).resolve().relative_to(REPO)
            glabel, pkg_dir, pkg_rel = group_label(repo_rel)
            return (f'["{glabel}"]', f'"//{pkg_dir}:{pkg_rel}"')
        d = Path(rel).parent
        return (f'glob(["{d}/**/*.rs"])', f'"{rel}"')

    def extra_mod_srcs(p, t, covered=()):
        """(pkg_relative_srcs, filegroup_labels) for `#[path = "..."]` modules
        a target's sources pull in. Inside the crate they become literal srcs
        entries, outside it they become //<pkg>:<group> labels. Paths under
        `covered` dirs are already matched by the target's srcs glob."""
        crate_dir = Path(p["manifest_path"]).parent
        base = Path(t["src_path"]).resolve().parent
        covered = tuple(covered) + (base,)
        local, labels, pulled_dirs = set(), set(), set()
        # Fixed point. Pulled-in files can carry their own #[path] escapes.
        seen, queue = set(), [base]
        while queue:
            root = queue.pop()
            for f in root.rglob("*.rs"):
                if f in seen:
                    continue
                seen.add(f)
                for m in RE_PATH_ATTR.finditer(f.read_text(errors="replace")):
                    resolved = (f.parent / m.group(1)).resolve()
                    try:
                        repo_rel = resolved.relative_to(REPO)
                    except ValueError:
                        continue
                    if resolved.parent not in pulled_dirs:
                        pulled_dirs.add(resolved.parent)
                        queue.append(resolved.parent)
                    if crate_dir in resolved.parents or resolved.parent == crate_dir:
                        if not any(d in resolved.parents for d in covered):
                            # The pulled-in file can declare its own `mod`
                            # children, which resolve beside it. Glob its dir.
                            local.add(
                                str(resolved.parent.relative_to(crate_dir))
                                + "/**/*.rs"
                            )
                        continue
                    glabel, _, _ = group_label(repo_rel)
                    labels.add(glabel)
        return sorted(local), sorted(labels), sorted(pulled_dirs)

    RESOURCE_DIRS = (
        "src", "assets", "fixtures", "data", "resources", "vendor", "tests",
    )

    def extra_compile_data(p, t, extra_dirs=()):
        """(in_crate_globs, filegroup_labels) for include_str!/include_bytes!
        paths escaping the crate. `extra_dirs` are additional source dirs to
        scan (dirs of files pulled in via #[path]). Dirs already covered by
        the standard resource globs or //tests:fixtures are skipped."""
        crate_dir = Path(p["manifest_path"]).parent
        covered = tuple(crate_dir / d for d in RESOURCE_DIRS)
        base = Path(t["src_path"]).resolve().parent
        local, labels = set(), set()
        seen = set()
        for root in (base, *extra_dirs):
            for f in root.rglob("*.rs"):
                if f in seen:
                    continue
                seen.add(f)
                text = f.read_text(errors="replace")
                include_hits = [
                    (f.parent / m.group(1)).resolve()
                    for m in RE_INCLUDE.finditer(text)
                ]
                include_hits += [
                    (crate_dir / m.group(1).lstrip("/")).resolve()
                    for m in RE_INCLUDE_MANIFEST.finditer(text)
                ]
                for resolved in include_hits:
                    try:
                        repo_rel = resolved.relative_to(REPO)
                    except ValueError:
                        continue
                    if repo_rel.parts[0] == "tests":
                        continue  # covered by //tests:fixtures
                    if crate_dir in resolved.parents or resolved.parent == crate_dir:
                        if not any(d in resolved.parents for d in covered):
                            local.add(
                                str(resolved.parent.relative_to(crate_dir))
                                + "/**"
                            )
                        continue
                    glabel, _, _ = group_label(repo_rel)
                    labels.add(glabel)
        return sorted(local), sorted(labels)

    def needed_bin_exes(p, t, extra_dirs=()):
        """CARGO_BIN_EXE_<name> literals a target's sources compile, mapped to
        that package's emitted bin target names."""
        base = Path(t["src_path"]).resolve().parent
        names = set()
        for root in (base, *extra_dirs):
            for f in root.rglob("*.rs"):
                names.update(RE_BIN_EXE.findall(f.read_text(errors="replace")))
        return sorted(names)

    def needs_env_tmpdir(p, t, extra_dirs=()):
        """True when a target's sources compile env!("CARGO_TARGET_TMPDIR"),
        which Cargo exports only for integration-test units."""
        rel = rel_src(p, t)
        if rel.startswith(".."):
            base = Path(t["src_path"]).resolve().parent
        else:
            base = Path(p["manifest_path"]).parent / rel
            base = base.parent
        return any(
            "CARGO_TARGET_TMPDIR" in f.read_text(errors="replace")
            for root in (base, *extra_dirs)
            for f in root.rglob("*.rs")
        )

    def render_build(p):
        name = p["name"]
        used_names = set()

        def unique_name(want):
            """Cargo allows a lib and a bin or a test and a bench to share a
            name; Bazel target names must be unique within the package."""
            if want not in used_names:
                used_names.add(want)
                return want
            for suffix in ("_bin", "_test", "_bench", "_fixture"):
                cand = want + suffix
                if cand not in used_names:
                    used_names.add(cand)
                    return cand
            i = 2
            while f"{want}_{i}" in used_names:
                i += 1
            cand = f"{want}_{i}"
            used_names.add(cand)
            return cand
        build_tree = contexts[(name, "normal,build", frozenset())]
        dev_tree = contexts[(name, "normal,build,dev", frozenset())]
        bin_target_names = {}  # cargo bin name -> emitted Bazel target name
        md = member_deps_of[name]
        lib_t = next((t for t in p["targets"] if "lib" in t["kind"]), None)
        has_build = any("custom-build" in t["kind"] for t in p["targets"])

        out = [BANNER]
        out.append('package(default_visibility = ["//visibility:public"])\n')
        out.append(
            'load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")\n'
            'load("@rules_rust//cargo:defs.bzl", "cargo_build_script")\n'
            'load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library")\n'
            'load("//scripts:bazel/rust_test.bzl", "rust_test")\n'
        )

        if lib_t:
            for (vkind, closure), vfmap in sorted(
                variants[name].items(),
                key=lambda kv: tname(name, kv[0][0], kv[0][1]),
            ):
                tgt = unique_name(tname(name, vkind, closure))
                deps = dedup(
                    sorted(
                        {
                            label(d, vfmap, vkind)
                            for d in md["normal"]
                            if d in vfmap
                        }
                    )
                )
                if has_build:
                    deps.append(":build_script_build")
                lib_extra, lib_mod_labels, lib_pulled = extra_mod_srcs(
                    p, lib_t, covered=(Path(p["manifest_path"]).parent / "src",)
                )
                inc_local, inc_labels = extra_compile_data(p, lib_t, lib_pulled)
                srcs_expr_lib = 'glob(["src/**/*.rs"])'
                if lib_extra:
                    srcs_expr_lib += " + glob([" + q(lib_extra) + "])"
                if lib_mod_labels:
                    srcs_expr_lib += " + [" + q(lib_mod_labels) + "]"
                out += [
                    "rust_library(",
                    f'    name = "{tgt}",',
                    "    srcs = " + srcs_expr_lib + ",",
                    f'    crate_root = "{rel_src(p, lib_t)}",',
                    f'    crate_name = "{lib_t["name"]}",',
                    '    edition = crate_edition(),',
                    '    compile_data = glob(["src/**/*"], exclude=["src/**/*.rs"], allow_empty = True)\n'
                    '        + glob(["assets/**","fixtures/**","data/**","resources/**","vendor/**"], allow_empty = True)\n'
                    '        + ["//tests:fixtures"]'
                    + (f" + [{q(COMPILE_DATA_EXTRA[name])}]" if COMPILE_DATA_EXTRA.get(name) else "")
                    + (f" + glob([{q(inc_local)}], allow_empty = True)" if inc_local else "")
                    + (f" + [{q(inc_labels)}]" if inc_labels else "")
                    + ",",
                    f'    version = "{p["version"]}",',
                    "    deps = all_crate_deps(normal = True) + [" + q(deps) + "],",
                    '    proc_macro_deps = all_crate_deps(proc_macro = True),',
                    '    aliases = aliases(normal = True),',
                    "    crate_features = ["
                + q(sorted(next(fs for m, fs, _ in closure if m == name)))
                + "],",
                    ")\n",
                ]

        if has_build:
            srcs = srcs_expr(["build.rs"] + BUILD_SCRIPT_SRCS_EXTRA.get(name, []))
            build_edges = dedup(
                label(d, build_tree) for d in md["build"] if d in build_tree
            )
            out += [
                "cargo_build_script(",
                '    name = "build_script_build",',
                '    crate_name = "build_script_build",',
                '    crate_root = "build.rs",',
                "    srcs = " + srcs + ",",
                "    deps = all_crate_deps(build = True, build_proc_macro = True) + ["
                + q(build_edges) + "],",
                '    edition = crate_edition(),',
                f'    pkg_name = "{name}",',
                f'    version = "{p["version"]}",',
                f"    crate_features = [{q(sorted(build_tree[name]))}],",
            ]
            data_labels = q(BUILD_SCRIPT_DATA.get(name, []))
            data_expr = " + ".join([f"[{data_labels}]"] + BUILD_SCRIPT_DATA_EXTRA.get(name, []))
            if data_labels or BUILD_SCRIPT_DATA_EXTRA.get(name):
                out.append(f"    data = {data_expr},")
            if BUILD_SCRIPT_ENV.get(name):
                pairs = ", ".join(
                    f"{json.dumps(k)}: {json.dumps(v)}"
                    for k, v in BUILD_SCRIPT_ENV[name].items()
                )
                out.append(f"    build_script_env = {{{pairs}}},")
            out.append(")\n")

        for t in p["targets"]:
            kinds = t["kind"]
            if not ({"bin", "example"} & set(kinds)):
                continue
            req = frozenset(t.get("required-features") or [])
            if "example" in kinds:
                fmap = contexts[(name, "normal,build,dev", req)]
                edges = md["normal"] + md["dev"]
            else:
                fmap = contexts[(name, "normal,build", req)]
                edges = md["normal"]
            vkind = "dev" if "example" in kinds else "norm"
            deps = dedup(
                sorted({label(d, fmap, vkind) for d in edges if d in fmap})
            )
            if lib_t and name in fmap:
                deps = dedup([label(name, fmap, vkind)] + deps)
            if has_build:
                deps.append(":build_script_build")
            srcs, crate_root = srcs_for(p, t)
            if not srcs.startswith("[") and rel_src(p, t).startswith("src/"):
                # In-package bins/tests resolve `mod` paths anywhere under
                # src/, not only beside their entry file.
                srcs = 'glob(["src/**/*.rs"])'
            bin_covered = (
                (Path(p["manifest_path"]).parent / "src",)
                if rel_src(p, t).startswith("src/")
                else ()
            )
            bin_local, bin_labels, bin_pulled = extra_mod_srcs(
                p, t, covered=bin_covered
            )
            inc_local_b, inc_labels_b = extra_compile_data(p, t, bin_pulled)
            if bin_local:
                srcs += " + glob([" + q(bin_local) + "])"
            if bin_labels:
                srcs += " + [" + q(bin_labels) + "]"
            # Cargo builds examples against the dev resolution.
            dev_args = "example" in kinds
            emitted = unique_name(t["name"])
            bin_target_names[t["name"]] = emitted
            out += [
                "rust_binary(",
                f'    name = "{emitted}",',
                "    srcs = " + srcs + ",",
                f'    crate_root = {crate_root},',
                '    edition = crate_edition(),',
                '    compile_data = glob(["src/**/*"], exclude=["src/**/*.rs"], allow_empty = True)'
                + ("\n        + glob([" + q(inc_local_b) + "], allow_empty = True)" if inc_local_b else "")
                + ("\n        + [" + q(inc_labels_b) + "]" if inc_labels_b else "")
                + ",",
                f'    version = "{p["version"]}",',
                "    deps = all_crate_deps(normal = True"
                + (", normal_dev = True" if dev_args else "")
                + ") + [" + q(deps) + "],",
                "    proc_macro_deps = all_crate_deps(proc_macro = True"
                + (", proc_macro_dev = True" if dev_args else "")
                + "),",
                "    aliases = aliases(normal = True"
                + (", normal_dev = True" if dev_args else "")
                + "),",
                f"    crate_features = [{q(sorted(fmap[name]))}],",
                ")\n",
            ]

        for t in p["targets"]:
            kinds = t["kind"]
            if not ({"test", "bench"} & set(kinds)):
                continue
            req = frozenset(t.get("required-features") or [])
            fmap = contexts[(name, "normal,build,dev", req)]
            deps = dedup(
                sorted(
                    {
                        label(d, fmap, "dev")
                        for d in md["normal"] + md["dev"]
                        if d in fmap
                    }
                )
            )
            if lib_t and name in fmap:
                deps = dedup([label(name, fmap, "dev")] + deps)
            if has_build:
                deps.append(":build_script_build")
            srcs, crate_root = srcs_for(p, t)
            mod_local, mod_labels, mod_pulled = extra_mod_srcs(p, t)
            inc_local_t, inc_labels_t = extra_compile_data(p, t, mod_pulled)
            if mod_local:
                srcs += " + glob([" + q(mod_local) + "])"
            if mod_labels:
                srcs += " + [" + q(mod_labels) + "]"
            data = srcs if srcs.startswith("[") else f'glob(["{str(Path(rel_src(p, t)).parent)}/**"])' +                 (" + [" + q(mod_labels) + "]" if mod_labels else "")
            if not data.startswith("["):
                data += ' + glob(["assets/**","fixtures/**","data/**","resources/**","vendor/**"], allow_empty = True)'
            # include_str!/include_bytes! are compile-time inputs. They cover crate-root
            # resource dirs beside tests/ and repo-root fixtures under //tests.
            compile_data = (
                'glob(["tests/**","assets/**","fixtures/**","data/**","resources/**","vendor/**"], allow_empty = True)'
                ' + ["//tests:fixtures"]'
            )
            if inc_local_t:
                compile_data += (
                    " + glob([" + q(inc_local_t) + "], allow_empty = True)"
                )
            if inc_labels_t:
                compile_data += " + [" + q(inc_labels_t) + "]"
            rustc_env = {}
            if needs_env_tmpdir(p, t, mod_pulled):
                rustc_env["CARGO_TARGET_TMPDIR"] = "/tmp"
            bin_data = []
            for bin_name in needed_bin_exes(p, t, mod_pulled):
                emitted = bin_target_names.get(bin_name)
                if emitted is None:
                    continue
                rustc_env[f"CARGO_BIN_EXE_{bin_name}"] = (
                    f"$(location :{emitted})"
                )
                bin_data.append(f":{emitted}")
            env_attr = (
                "    rustc_env = {"
                + ", ".join(
                    f"{json.dumps(k)}: {json.dumps(v)}"
                    for k, v in sorted(rustc_env.items())
                )
                + "},"
                if rustc_env
                else None
            )
            if bin_data:
                data += " + [" + q(bin_data) + "]"
            out += [
                "rust_test(",
                f'    name = "{unique_name(t["name"])}",',
                "    srcs = " + srcs + ",",
                f'    crate_root = {crate_root},',
                '    edition = crate_edition(),',
                f'    version = "{p["version"]}",',
                "    deps = all_crate_deps(normal = True, normal_dev = True) + ["
                + q(deps) + "],",
                '    proc_macro_deps = all_crate_deps('
                "proc_macro = True, proc_macro_dev = True),",
                '    aliases = aliases(normal = True, normal_dev = True),',
                f"    crate_features = [{q(sorted(fmap[name]))}],",
                f'    compile_data = {compile_data},',
                f'    data = {data},',
                env_attr,
                ")\n",
            ]
            out = [l for l in out if l is not None]

        if lib_t:
            dev_edges = md["normal"] + md["dev"]
            deps = dedup(
                sorted(
                    {label(d, dev_tree, "dev") for d in dev_edges if d in dev_tree}
                )
            )
            if has_build:
                deps.append(":build_script_build")
            out += [
                "rust_test(",
                '    name = "unit_test",',
                f'    crate = ":{tname(name, "dev", closure_of(name, dev_tree))}",',
                '    edition = crate_edition(),',
                f'    version = "{p["version"]}",',
                "    deps = all_crate_deps(normal = True, normal_dev = True) + ["
                + q(deps) + "],",
                '    proc_macro_deps = all_crate_deps('
                "proc_macro = True, proc_macro_dev = True),",
                '    aliases = aliases(normal = True, normal_dev = True),',
                '    compile_data = glob(["tests/**","assets/**","fixtures/**","data/**","resources/**","vendor/**"], allow_empty = True)\n'
                '        + ["//tests:fixtures"]'
                + (f"\n        + glob([{q(inc_local)}], allow_empty = True)" if inc_local else "")
                + (f"\n        + [{q(inc_labels)}]" if inc_labels else "")
                + ",",
                '    data = glob(["tests/**"], allow_empty = True),',
                ")\n",
            ]

        return "\n".join(out)

    outputs = {}
    for p in meta["packages"]:
        outputs[Path(p["manifest_path"]).parent / "BUILD.bazel"] = render_build(p)

    by_pkg = {}
    for (pkg_dir, gname), entry in out_of_pkg.items():
        by_pkg.setdefault(pkg_dir, {})[gname] = entry
    for pkg_dir, groups in by_pkg.items():
        path = REPO / pkg_dir / "BUILD.bazel"
        if path.exists():
            # Append shared-dir filegroups to an existing BUILD instead of
            # clobbering it; skip groups already declared (idempotent).
            existing = path.read_text()
            extra = []
            for gname, entry in sorted(groups.items()):
                if f'name = "{gname}"' in existing:
                    continue
                extra.append(
                    f'filegroup(\n    name = "{gname}",\n'
                    f'    srcs = glob(["{entry["glob"]}/**"]),\n'
                    '    visibility = ["//visibility:public"],\n)\n'
                )
            if extra:
                existing += "\n" + "\n".join(extra)
            outputs[path] = existing
            continue
        lines = [BANNER]
        for gname, entry in sorted(groups.items()):
            lines.append(
                f'filegroup(\n    name = "{gname}",\n'
                f'    srcs = glob(["{entry["glob"]}/**"]),\n'
                '    visibility = ["//visibility:public"],\n)\n'
            )
            crate_roots = sorted(entry["files"])
            if crate_roots:
                lines.append(
                    "exports_files(["
                    + q(crate_roots)
                    + '],\n    visibility = ["//visibility:public"],\n)\n'
                )
        # Repo-root fixture trees members embed via include_str!/include_bytes!.
        if pkg_dir == "tests":
            lines.append(
                'filegroup(\n    name = "fixtures",\n'
                '    srcs = glob(["fixtures/**"]),\n'
                '    visibility = ["//visibility:public"],\n)\n'
            )
        outputs[path] = "\n".join(lines)

    if check_only:
        stale = [
            path for path in sorted(outputs)
            if not path.exists() or path.read_text() != outputs[path]
        ]
        # A removed member leaves its generated BUILD behind.
        stale += [
            path for path in sorted(REPO.glob("crates/*/BUILD.bazel"))
            if path not in outputs and path.read_text().startswith(BANNER)
        ]
        if stale:
            print("generated BUILD.bazel files are out of date:")
            for path in stale:
                print(f"  {path.relative_to(REPO)}")
            print("rerun: python3 scripts/bazel/gen_builds.py")
            # Show the first diffs so CI output explains the divergence.
            import difflib
            shown = 0
            for path in stale:
                if shown >= 60:
                    break
                if path not in outputs:
                    print(f"--- {path.relative_to(REPO)}: generated file with no source member")
                    continue
                diff = list(difflib.unified_diff(
                    path.read_text().splitlines(),
                    outputs[path].splitlines(),
                    str(path.relative_to(REPO)), "regenerated", lineterm="",
                ))
                for line in diff[:60 - shown]:
                    print(line)
                shown += len(diff[:60 - shown])
            sys.exit(1)
        print(f"all {len(outputs)} generated BUILD.bazel files are current")
        return

    for path, content in outputs.items():
        path.write_text(content)

    counts = {
        m: sorted(tname(m, kind, c) for kind, c in v)
        for m, v in sorted(variants.items()) if len(v) > 1
    }
    print(f"wrote BUILD.bazel for {len(members)} members")
    print("members with feature variants:")
    print(json.dumps(counts, indent=2))


if __name__ == "__main__":
    main()
