//! Root-side shim for the dashboard HTTP surface.
//!
//! The dashboard API — routes, read models, services and their tests — lives
//! in `crates/tracedecay-dashboard-api`. Everything that used to be reachable
//! at `crate::dashboard::…` is re-exported here so existing root modules,
//! command adapters and integration tests keep compiling unchanged.
//!
//! [`assets`] deliberately stays in the root crate: the embedded single-app
//! dist is generated by the root `build.rs` into `OUT_DIR` and included via
//! `env!("OUT_DIR")`, which only resolves inside the crate whose build script
//! produced it.

pub(crate) use tracedecay_dashboard_api::*;

pub(crate) mod assets;
